import type { ResonanceConnection } from "./types";

const connection = (
  sourceId: string,
  targetId: string,
  resonanceType: ResonanceConnection["resonanceType"],
  title: string,
  shortResonance: string,
  explanation: string,
  strength: number,
  scriptureAnchors: string[] = [],
  hebrewAnchors: string[] = [],
): ResonanceConnection => ({
  id: `resonance-phase36a-${sourceId}-${targetId}`,
  sourceId,
  targetId,
  resonanceType,
  title,
  shortResonance,
  explanation,
  strength,
  scriptureAnchors,
  hebrewAnchors,
});

export const phase36AResonanceConnections: ResonanceConnection[] = [
  connection("bara", "schamajim", "meaning", "Schaffen oeffnet Himmel", "Bara gibt Schamajim den ersten Raum.", "Das Schoepfungswort bringt den oberen Raum der Welt in den Bedeutungsbogen.", 0.88, ["genesis-1-1"], ["\u05d1\u05e8\u05d0", "\u05e9\u05de\u05d9\u05dd"]),
  connection("bara", "erez", "meaning", "Schaffen erdet sich", "Bara ruft auch Erez hervor.", "Himmel und Erde bilden zusammen den ersten Resonanzraum des Anfangs.", 0.86, ["genesis-1-1"], ["\u05d1\u05e8\u05d0", "\u05d0\u05e8\u05e5"]),
  connection("schamajim", "majim", "hebrew", "Himmel mit Wasserspur", "Schamajim traegt Majim im Klang.", "Der Himmel bleibt im Codex mit Wasser, Scheidung und Ordnung verbunden.", 0.9, ["genesis-1-8"], ["\u05e9\u05de\u05d9\u05dd", "\u05de\u05d9\u05dd"]),
  connection("erez", "adam", "story", "Erde und Mensch", "Adam kommt aus dem Boden.", "Erez wird nicht nur Ort, sondern Stoff und Auftrag des Menschen.", 0.86, ["genesis-2-7"], ["\u05d0\u05e8\u05e5", "\u05d0\u05d3\u05dd"]),
  connection("adam", "chava", "meaning", "Mensch wird Beziehung", "Adam und Chava lassen Leben antworten.", "Im Anfangsraum verdichtet sich Menschsein als Beziehung, Atem und Geburt.", 0.84, ["genesis-3-20"], ["\u05d0\u05d3\u05dd", "\u05d7\u05d5\u05d4"]),
  connection("gan", "nahar", "story", "Garten und Strom", "Nahar naehert Gan.", "Der Garten ist lebendig, weil Wasser als gerichteter Strom durch ihn geht.", 0.9, ["genesis-2-10"], ["\u05d2\u05df", "\u05e0\u05d4\u05e8"]),
  connection("nahar", "jordan", "threshold", "Strom wird Schwelle", "Nahar verdichtet sich im Jordan.", "Der Fluss wird am Jordan zur Grenze, zum Durchgang und zur Tauferinnerung.", 0.88, ["joshua-3", "matthew-3-13-17"], ["\u05e0\u05d4\u05e8", "\u05d9\u05e8\u05d3\u05df"]),
  connection("mikwe", "tahor", "meaning", "Eintauchen klaert", "Mikwe oeffnet Tahor.", "Gesammeltes Wasser wird zum Raum ritueller Reinigung und Rueckkehr.", 0.92, ["leviticus-15"], ["\u05de\u05e7\u05d5\u05d4", "\u05d8\u05d4\u05d5\u05e8"]),
  connection("jordan", "mikwe", "hebrew", "Fluss und Reinigungsraum", "Jordan klingt mit Mikwe.", "Taufe, Eintauchen und Reinigung werden als ein Wasserbogen lesbar.", 0.86, ["matthew-3-13-17"], ["\u05d9\u05e8\u05d3\u05df", "\u05de\u05e7\u05d5\u05d4"]),
  connection("jam", "tehom", "meaning", "Meer und Tiefe", "Jam erinnert die Anfangstiefe.", "Das Meer traegt die ungezähmte Tiefe, die Tehom am Anfang bezeichnet.", 0.88, ["genesis-1-2", "exodus-14"], ["\u05d9\u05dd", "\u05ea\u05d4\u05d5\u05dd"]),
  connection("or", "panim", "revelation", "Licht wird Angesicht", "Or wird in Panim persoenlich.", "Licht ist nicht nur Helligkeit; im Angesicht wird es Begegnung.", 0.9, ["numbers-6-25"], ["\u05d0\u05d5\u05e8", "\u05e4\u05e0\u05d9\u05dd"]),
  connection("panim", "kavod", "revelation", "Angesicht und Herrlichkeit", "Panim und Kavod tragen Gegenwart.", "Das Angesicht gibt Herrlichkeit Zuwendung; Kavod gibt dem Angesicht Gewicht.", 0.86, [], ["\u05e4\u05e0\u05d9\u05dd", "\u05db\u05d1\u05d5\u05d3"]),
  connection("kavod", "sinai", "story", "Herrlichkeit am Sinai", "Kavod erscheint in Wolke und Feuer.", "Am Sinai wird Herrlichkeit als gewichtige, furchtbare und leuchtende Gegenwart erzaehlt.", 0.9, ["exodus-24"], ["\u05db\u05d1\u05d5\u05d3", "\u05e1\u05d9\u05e0\u05d9"]),
  connection("chokma", "bina", "meaning", "Weisheit versteht", "Chokma braucht Bina.", "Weisheit wird durch unterscheidendes Verstehen tragfaehig.", 0.88, ["proverbs-2"], ["\u05d7\u05db\u05de\u05d4", "\u05d1\u05d9\u05e0\u05d4"]),
  connection("chokma", "or", "revelation", "Weisheit leuchtet", "Chokma macht Wege sichtbar.", "Weisheit ist im Lichtfeld nicht Information, sondern Orientierung.", 0.84, ["proverbs-8"], ["\u05d7\u05db\u05de\u05d4", "\u05d0\u05d5\u05e8"]),
  connection("esch", "mizbeach", "story", "Feuer am Altar", "Mizbeach ordnet Esch.", "Das Feuer wird am Altar zum Ort der Gabe, nicht bloss zur zerstoerenden Kraft.", 0.9, ["exodus-27"], ["\u05d0\u05e9", "\u05de\u05d6\u05d1\u05d7"]),
  connection("mizbeach", "korban", "meaning", "Altar und Nahgabe", "Korban findet am Mizbeach Ort.", "Die Gabe wird im Altarraum zur Bewegung des Herantretens.", 0.88, ["leviticus-1"], ["\u05de\u05d6\u05d1\u05d7", "\u05e7\u05e8\u05d1\u05df"]),
  connection("korban", "lechem", "meaning", "Gabe und Brot", "Korban und Lechem teilen Empfang.", "Brot und Opfergabe beruehren sich dort, wo Nahrung als Gabe vor Gott lesbar wird.", 0.78, [], ["\u05e7\u05e8\u05d1\u05df", "\u05dc\u05d7\u05dd"]),
  connection("midbar", "derech", "journey", "Weg durch die Wueste", "Derech geht durch Midbar.", "Die Wueste ist nicht nur Ort des Mangels, sondern Raum, in dem der Weg Gestalt annimmt.", 0.92, ["deuteronomy-8"], ["\u05de\u05d3\u05d1\u05e8", "\u05d3\u05e8\u05da"]),
  connection("derech", "nes", "threshold", "Zeichen auf dem Weg", "Nes sammelt Derech.", "Ein Zeichen gibt dem offenen Weg Richtung, ohne ihn abzukuerzen.", 0.82, ["exodus-17"], ["\u05d3\u05e8\u05da", "\u05e0\u05e1"]),
  connection("derech", "sinai", "journey", "Weg zum Sinai", "Derech fuehrt zur Offenbarung.", "Der Wuestenweg verdichtet sich am Sinai zu Stimme, Feuer und Bund.", 0.88, ["exodus-19"], ["\u05d3\u05e8\u05da", "\u05e1\u05d9\u05e0\u05d9"]),
  connection("sinai", "qol", "revelation", "Sinai wird Stimme", "Qol hallt am Sinai.", "Der Berg wird zum Resonanzkoerper des gehoerten Wortes.", 0.86, ["exodus-19"], ["\u05e1\u05d9\u05e0\u05d9", "\u05e7\u05d5\u05dc"]),
  connection("lechem", "manna", "meaning", "Brot als Wuestengabe", "Manna ist Lechem im Mangel.", "Brot erscheint in der Wueste nicht als Besitz, sondern als taeglicher Empfang.", 0.94, ["exodus-16"], ["\u05dc\u05d7\u05dd", "\u05de\u05df"]),
  connection("manna", "dagan", "polarity", "Himmelgabe und Korn", "Manna faellt, Dagan waechst.", "Beide naehren, aber sie zeigen zwei Weisen von Gabe: taeglichen Empfang und verborgenes Wachstum.", 0.84, [], ["\u05de\u05df", "\u05d3\u05d2\u05df"]),
  connection("dagan", "shever", "story", "Korn im Bruch", "Dagan wird in Shever gesucht.", "Im Hunger wird Korn zur Spur von Rettung, Bruch und spaeterer Versoehnung.", 0.82, ["genesis-42"], ["\u05d3\u05d2\u05df", "\u05e9\u05d1\u05e8"]),
  connection("shever", "seudah", "meaning", "Bruch wird Mahl", "Aus Shever kann Seudah werden.", "Der Bruch findet eine andere Gestalt, wenn Nahrung geteilt und Gemeinschaft erneuert wird.", 0.78, [], ["\u05e9\u05d1\u05e8", "\u05e1\u05e2\u05d5\u05d3\u05d4"]),
  connection("noach", "jam", "story", "Noah und Wasserweite", "Noach geht durch bedrohliche Tiefe.", "Die Flut verbindet Noach mit Wasser als Gericht, Bewahrung und Neubeginn.", 0.84, ["genesis-6-9"], ["\u05e0\u05d7", "\u05d9\u05dd"]),
  connection("noach", "majim", "threshold", "Wasser zum Neubeginn", "Noach zeigt Majim als Schwelle.", "Wasser trennt alte und neue Welt und traegt Bewahrung hindurch.", 0.86, ["genesis-6-9"], ["\u05e0\u05d7", "\u05de\u05d9\u05dd"]),
  connection("tahor", "or", "revelation", "Reinheit wird Licht", "Tahor fuehrt zu klarer Sichtbarkeit.", "Geklaerte Ordnung kann im Licht erscheinen.", 0.78, [], ["\u05d8\u05d4\u05d5\u05e8", "\u05d0\u05d5\u05e8"]),
  connection("tahor", "esch", "meaning", "Reinigung und Feuer", "Tahor klingt auch mit Laeuterung.", "Wasser und Feuer tragen zwei Wege der Klaerung.", 0.76, [], ["\u05d8\u05d4\u05d5\u05e8", "\u05d0\u05e9"]),
];
