import type { ResonanceConnection, ResonanceRegistry } from "./types";
import { phase36AResonanceConnections } from "./phase36AConnections";

export const resonanceConnections: ResonanceConnection[] = [
  {
    id: "resonance-genesis-1-1-genesis-1-2",
    sourceId: "genesis-1-1",
    targetId: "genesis-1-2",
    resonanceType: "journey",
    title: "Vom gesetzten Ursprung in die Tiefe",
    shortResonance: "Himmel und Erde sind gesetzt; die Erde erscheint noch ungeordnet.",
    explanation: "Genesis 1,1 oeffnet den Ursprung. Genesis 1,2 zeigt diesen Ursprung als noch ungeformte Tiefe, ueber der Gottes Geist nicht fehlt.",
    strength: 0.96,
    scriptureAnchors: ["genesis-1-1", "genesis-1-2"],
    hebrewAnchors: ["\u05d1\u05e8\u05d0\u05e9\u05d9\u05ea", "\u05ea\u05d4\u05d5\u05dd"],
  },
  {
    id: "resonance-genesis-1-2-wasser",
    sourceId: "genesis-1-2",
    targetId: "wasser",
    resonanceType: "story",
    title: "Wasser entsteht als Tiefenraum",
    shortResonance: "Wasser wird der erste grosse Erfahrungsraum des Anfangs.",
    explanation: "Tehom, Ruach und Majim machen Genesis 1,2 zum Ursprungsknoten des Wasserraums.",
    strength: 0.95,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05e8\u05d5\u05d7", "\u05de\u05d9\u05dd"],
  },
  {
    id: "resonance-genesis-1-2-genesis-1-3",
    sourceId: "genesis-1-2",
    targetId: "genesis-1-3",
    resonanceType: "journey",
    title: "Aus Tiefe und Ruach zum Wort",
    shortResonance: "Die bewegte Tiefe fuehrt zum gesprochenen Licht.",
    explanation: "Die Ruach ueber den Wassern bereitet die Szene vor, in der Gottes Sprechen Sichtbarkeit oeffnet.",
    strength: 0.97,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05d0\u05de\u05e8", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-genesis-1-3-licht",
    sourceId: "genesis-1-3",
    targetId: "licht",
    resonanceType: "story",
    title: "Licht entsteht als Sichtbarkeitsraum",
    shortResonance: "Or oeffnet die erste lesbare Ordnung.",
    explanation: "Genesis 1,3 macht Licht nicht nur hell, sondern zum Raum von Offenbarung, Unterscheidung und Orientierung.",
    strength: 0.95,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05d0\u05de\u05e8", "\u05d0\u05d5\u05e8", "\u05d5\u05d9\u05d4\u05d9"],
  },
  {
    id: "resonance-genesis-1-1-bereschit",
    sourceId: "genesis-1-1",
    targetId: "bereschit",
    resonanceType: "hebrew",
    title: "Genesis 1,1 beginnt mit Bereschit",
    shortResonance: "Der Anfang wird als Wortschwelle betreten.",
    explanation: "Bereschit bindet Ursprung, Anfang und verborgene Ordnung an den ersten Vers.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-1"],
    hebrewAnchors: ["\u05d1\u05e8\u05d0\u05e9\u05d9\u05ea"],
  },
  {
    id: "resonance-genesis-1-1-bara",
    sourceId: "genesis-1-1",
    targetId: "bara",
    resonanceType: "hebrew",
    title: "Bara setzt den Schöpfungsakt",
    shortResonance: "Schaffen erscheint als Setzung von Wirklichkeit.",
    explanation: "Bara verbindet Genesis 1,1 mit Schoepfung, Wort, Himmel und Erde.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-1"],
    hebrewAnchors: ["\u05d1\u05e8\u05d0"],
  },
  {
    id: "resonance-genesis-1-2-tehom",
    sourceId: "genesis-1-2",
    targetId: "tehom",
    resonanceType: "hebrew",
    title: "Tehom verankert die Tiefe",
    shortResonance: "Die Anfangstiefe ist ungeordnet, aber nicht gottleer.",
    explanation: "Genesis 1,2 sammelt Tiefe, Finsternis, Wasser und Ruach in einem Ursprungsknoten.",
    strength: 0.92,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd"],
  },
  {
    id: "resonance-genesis-1-3-or",
    sourceId: "genesis-1-3",
    targetId: "or",
    resonanceType: "hebrew",
    title: "Or öffnet Sichtbarkeit",
    shortResonance: "Das gesprochene Licht macht Ordnung lesbar.",
    explanation: "Or verbindet Genesis 1,3 mit Licht, Offenbarung und erster Unterscheidbarkeit.",
    strength: 0.92,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-tehom-majim",
    sourceId: "tehom",
    targetId: "majim",
    resonanceType: "meaning",
    title: "Tiefe vor dem Wasser",
    shortResonance: "Wasser trägt jetzt Ursprung und Tiefe.",
    explanation: "Tehom ist nicht einfach Wasser, sondern die uranfängliche Tiefe, aus der das Wasserfeld seine Ursprungsschwere empfängt.",
    strength: 0.96,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05de\u05d9\u05dd"],
  },
  {
    id: "resonance-tehom-davar",
    sourceId: "tehom",
    targetId: "davar",
    resonanceType: "expression",
    title: "Aus Tiefe wird Wort",
    shortResonance: "Aus der Verborgenheit erhebt sich Davar.",
    explanation: "Tehom bildet den verborgenen Ursprungsraum; Davar ist das Wort, das aus diesem Raum Richtung und Wirklichkeit hervorbringt.",
    strength: 0.95,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05d3\u05d1\u05e8"],
  },
  {
    id: "resonance-tehom-ruach",
    sourceId: "tehom",
    targetId: "ruach",
    resonanceType: "meaning",
    title: "Tiefe wird bewegt",
    shortResonance: "Ruach berührt die Tiefe vor dem Wort.",
    explanation: "Tehom bleibt nicht statische Tiefe: Ruach markiert die unsichtbare Bewegung über dem Ursprung.",
    strength: 0.97,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05e8\u05d5\u05d7"],
  },
  {
    id: "resonance-majim-ruach",
    sourceId: "majim",
    targetId: "ruach",
    resonanceType: "meaning",
    title: "Geist über den Wassern",
    shortResonance: "Majim wird vom Atem der Ruach berührt.",
    explanation: "Genesis 1,2 verbindet die Wasser des Anfangs mit der Ruach, die über ihnen schwebt.",
    strength: 0.98,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05de\u05d9\u05dd", "\u05e8\u05d5\u05d7"],
  },
  {
    id: "resonance-bereschit-tehom",
    sourceId: "bereschit",
    targetId: "tehom",
    resonanceType: "threshold",
    title: "Anfang öffnet Tiefe",
    shortResonance: "Genesis 1,1 setzt die Schwelle, an der Tehom erzählbar wird.",
    explanation: "Bereschit ist kein fertiger Raum, sondern die Schwelle zwischen Nicht-Erzähltem und dem Anfangsbild von Tiefe, Wasser und Geist.",
    strength: 0.91,
    scriptureAnchors: ["genesis-1-1", "genesis-1-2"],
    hebrewAnchors: ["\u05d1\u05e8\u05d0\u05e9\u05d9\u05ea", "\u05ea\u05d4\u05d5\u05dd"],
  },
  {
    id: "resonance-tohu-vohu-tehom",
    sourceId: "tohu",
    targetId: "tehom",
    resonanceType: "meaning",
    title: "Ungeformte Tiefe",
    shortResonance: "Tohu wa-vohu beschreibt die offene Möglichkeit vor der Form.",
    explanation: "Das Ungeformte von Genesis 1,2 steht nicht neben der Tiefe, sondern macht ihren Zustand vor Ordnung und Sichtbarkeit lesbar.",
    strength: 0.88,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5", "\u05d5\u05d1\u05d4\u05d5", "\u05ea\u05d4\u05d5\u05dd"],
  },
  {
    id: "resonance-ruach-merachefet",
    sourceId: "ruach",
    targetId: "merachefet",
    resonanceType: "expression",
    title: "Geist schwebt",
    shortResonance: "Merachefet macht die Bewegung der Ruach über den Wassern spürbar.",
    explanation: "Genesis 1,2 beschreibt die Ruach nicht abstrakt: Ihr Schweben hält Nähe, Bewegung und schöpferische Möglichkeit über der Tiefe zusammen.",
    strength: 0.93,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05de\u05e8\u05d7\u05e4\u05ea"],
  },
  {
    id: "resonance-ruach-davar",
    sourceId: "ruach",
    targetId: "davar",
    resonanceType: "expression",
    title: "Atem trägt Wort",
    shortResonance: "Davar bewegt sich durch Ruach.",
    explanation: "Ruach ist die unsichtbare Atem- und Geistbrücke, durch die Davar vom verborgenen Ursprung in die Sprache treten kann.",
    strength: 0.93,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05d3\u05d1\u05e8"],
  },
  {
    id: "resonance-ruach-qol",
    sourceId: "ruach",
    targetId: "qol",
    resonanceType: "expression",
    title: "Atem wird Stimme",
    shortResonance: "Ruach gibt Qol bewegte Gegenwart.",
    explanation: "Qol wird hörbar, weil Stimme Atem braucht; Ruach verbindet Atem, Geist und Bewegung.",
    strength: 0.92,
    scriptureAnchors: [],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05e7\u05d5\u05dc"],
  },
  {
    id: "resonance-ruach-or",
    sourceId: "ruach",
    targetId: "or",
    resonanceType: "revelation",
    title: "Bewegung öffnet Licht",
    shortResonance: "Die Bewegung des Geistes öffnet zur Sichtbarkeit.",
    explanation: "Ruach steht vor dem ausgesprochenen Licht als Bewegung, die Offenbarung vorbereitet.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-tehom-midbar",
    sourceId: "tehom",
    targetId: "midbar",
    resonanceType: "meaning",
    title: "Tiefe im leeren Raum",
    shortResonance: "Tehom hallt im Midbar nach.",
    explanation: "Midbar trägt die Leere, in der das Wort hörbar wird; Tehom trägt die verborgene Tiefe vor diesem Hervortreten.",
    strength: 0.86,
    scriptureAnchors: [],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05de\u05d3\u05d1\u05e8"],
  },
  {
    id: "resonance-tehom-or",
    sourceId: "tehom",
    targetId: "or",
    resonanceType: "revelation",
    title: "Vor dem Licht",
    shortResonance: "Die Tiefe geht dem Licht voraus.",
    explanation: "Bevor Or sichtbar wird, steht Tehom als verborgener Anfangsraum der Offenbarung.",
    strength: 0.94,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-majim-midbar",
    sourceId: "majim",
    targetId: "midbar",
    resonanceType: "story",
    title: "Weg der Prüfung",
    shortResonance: "Erst die Leere zeigt, wonach die Tiefe sucht.",
    explanation: "",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: [],
  },
  {
    id: "resonance-majim-lechem",
    sourceId: "majim",
    targetId: "lechem",
    resonanceType: "meaning",
    title: "Von der Quelle zur Nahrung",
    shortResonance: "Was aus der Tiefe kommt, wird zur Gabe.",
    explanation: "",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: [],
  },
  {
    id: "resonance-midbar-lechem",
    sourceId: "midbar",
    targetId: "lechem",
    resonanceType: "story",
    title: "Manna",
    shortResonance: "Im Mangel wird Versorgung als Gabe sichtbar.",
    explanation: "",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: [],
  },
  {
    id: "resonance-or-esch",
    sourceId: "or",
    targetId: "esch",
    resonanceType: "meaning",
    title: "Licht und Feuer",
    shortResonance: "Licht offenbart. Feuer verwandelt.",
    explanation: "Licht macht sichtbar, was verborgen war. Feuer führt das Sichtbare durch Wandlung.",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: [],
  },
  {
    id: "resonance-esch-davar",
    sourceId: "esch",
    targetId: "davar",
    resonanceType: "story",
    title: "Feuer und Wort",
    shortResonance: "Im Feuer wird das Wort hörbar.",
    explanation: "Am Dornbusch erscheint das Feuer nicht als Vernichtung, sondern als Ort der Stimme.",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: [],
  },
  {
    id: "resonance-or-davar",
    sourceId: "or",
    targetId: "davar",
    resonanceType: "meaning",
    title: "Licht und Wort",
    shortResonance: "Das Wort spricht. Das Licht macht sichtbar.",
    explanation: "In der Schöpfung steht das Wort am Anfang der Sichtbarkeit.",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: [],
  },
  {
    id: "resonance-amar-or",
    sourceId: "amar",
    targetId: "or",
    resonanceType: "revelation",
    title: "Sprechen öffnet Licht",
    shortResonance: "Amar ruft Or in die Sichtbarkeit.",
    explanation: "Genesis 1,3 liest Licht nicht nur als Helligkeit, sondern als gesprochenes Hervortreten aus der Tiefe.",
    strength: 0.94,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05d0\u05de\u05e8", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-wajehi-or",
    sourceId: "wajehi",
    targetId: "or",
    resonanceType: "expression",
    title: "Licht geschieht",
    shortResonance: "Wajehi verbindet den Ruf mit dem Ereignis des Lichts.",
    explanation: "Das Licht bleibt nicht Idee: Wajehi bestätigt, dass das gesprochene Werden in sichtbare Wirklichkeit tritt.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05d5\u05d9\u05d4\u05d9", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-or-ordnung",
    sourceId: "or",
    targetId: "ordnung",
    resonanceType: "revelation",
    title: "Licht beginnt Ordnung",
    shortResonance: "Or macht den ersten Unterschied lesbar.",
    explanation: "In Genesis 1,3 ist Licht der Beginn von Sichtbarkeit und damit die Vorbereitung der ersten Ordnung.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-davar-qol",
    sourceId: "davar",
    targetId: "qol",
    resonanceType: "expression",
    title: "Wort wird Stimme",
    shortResonance: "Das Wort wird hörbar.",
    explanation: "Davar beschreibt das Wort; Qol beschreibt das Wort, das als Stimme in den Raum tritt.",
    strength: 1,
    scriptureAnchors: [],
    hebrewAnchors: ["\u05d3\u05d1\u05e8", "\u05e7\u05d5\u05dc"],
  },
  {
    id: "resonance-qol-or",
    sourceId: "qol",
    targetId: "or",
    resonanceType: "revelation",
    title: "Stimme führt zum Licht",
    shortResonance: "Die Stimme öffnet Sichtbarkeit.",
    explanation: "Qol führt vom gehörten Ruf zur sichtbaren Orientierung von Or.",
    strength: 0.95,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05e7\u05d5\u05dc", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "resonance-qol-midbar",
    sourceId: "qol",
    targetId: "midbar",
    resonanceType: "story",
    title: "Stimme in der Wüste",
    shortResonance: "Im leeren Raum wird die Stimme hörbar.",
    explanation: "Midbar ist nicht nur Ort des Mangels; die Wüste wird zum Raum des Hörens.",
    strength: 0.9,
    scriptureAnchors: [],
    hebrewAnchors: ["\u05e7\u05d5\u05dc", "\u05de\u05d3\u05d1\u05e8"],
  },
  {
    id: "resonance-midbar-davar",
    sourceId: "midbar",
    targetId: "davar",
    resonanceType: "expression",
    title: "Wort in der Wüste",
    shortResonance: "Im Midbar wird Davar empfangbar.",
    explanation: "Der reduzierte Raum des Midbar öffnet die Wahrnehmung für Davar als Wort, das Richtung gibt.",
    strength: 0.86,
    scriptureAnchors: [],
    hebrewAnchors: ["\u05de\u05d3\u05d1\u05e8", "\u05d3\u05d1\u05e8"],
  },
  ...phase36AResonanceConnections,
];

let registry: ResonanceRegistry | null = null;

function createRegistry(): ResonanceRegistry {
  const byId = new Map<string, ResonanceConnection>();
  const bySource = new Map<string, ResonanceConnection[]>();
  const byTarget = new Map<string, ResonanceConnection[]>();

  resonanceConnections.forEach((connection) => {
    byId.set(connection.id, connection);

    const sourceConnections = bySource.get(connection.sourceId) ?? [];
    sourceConnections.push(connection);
    bySource.set(connection.sourceId, sourceConnections);

    const targetConnections = byTarget.get(connection.targetId) ?? [];
    targetConnections.push(connection);
    byTarget.set(connection.targetId, targetConnections);
  });

  return {
    connections: resonanceConnections,
    byId,
    bySource,
    byTarget,
  };
}

export function getResonanceRegistry(): ResonanceRegistry {
  registry ??= createRegistry();
  return registry;
}

export function getAllResonanceConnections(): ResonanceConnection[] {
  return getResonanceRegistry().connections;
}

export function getResonanceConnectionById(id: string): ResonanceConnection | undefined {
  return getResonanceRegistry().byId.get(id);
}

export function getResonanceConnectionsFromSource(sourceId: string): ResonanceConnection[] {
  return getResonanceRegistry().bySource.get(sourceId) ?? [];
}

export function getResonanceConnectionsToTarget(targetId: string): ResonanceConnection[] {
  return getResonanceRegistry().byTarget.get(targetId) ?? [];
}

export function getResonanceConnectionsForNode(nodeId: string): ResonanceConnection[] {
  const registry = getResonanceRegistry();
  return [
    ...(registry.bySource.get(nodeId) ?? []),
    ...(registry.byTarget.get(nodeId) ?? []),
  ];
}
