import type { SymbolRoomDefinition } from "@/components/rooms/types";
import type {
  ExperienceTraits,
  MeaningQuality,
  SymbolGraph,
  VisualTraits,
} from "@/lib/symbolism";
import { visualAssets } from "@/lib/visualAssets";

const fireVisuals: VisualTraits = {
  material: "gold-thread",
  accent: "gold",
  glow: 0.96,
  opacity: 0.94,
  motion: "spark",
};

const fireExperience: ExperienceTraits = {
  camera: "draw-near",
  tone: "awakening",
  tempo: "measured",
  depth: 0.38,
};

const meaningQualityLabels: Record<MeaningQuality, string> = {
  origin: "Glut",
  depth: "verborgene Waerme",
  chaos: "Unruhe",
  birth: "Entzuendung",
  transition: "Verwandlung",
  purification: "Laeuterung",
  "hidden-source": "verborgene Kraft",
  lack: "Erloeschen",
  revelation: "Offenbarung",
  life: "Lebendigkeit",
  impulse: "Funke",
  movement: "Aufstieg",
  resistance: "Widerstand",
};

const fireSymbolGraph: SymbolGraph = {
  id: "fire-symbol-engine",
  title: "Fire Symbol Engine",
  centerId: "fire",
  nodes: [
    {
      id: "fire",
      type: "core-symbol",
      label: "Feuer",
      hebrew: "\u05d0\u05e9",
      transliteration: "Esh",
      shortMeaning: "Feuer entzuendet, verwandelt, offenbart und sendet.",
      importance: 1,
      depthLevel: 0,
      visuals: fireVisuals,
      experience: fireExperience,
      roomHref: "/raeume/feuer",
    },
    {
      id: "embers",
      type: "natural-symbol",
      label: "Glut",
      shortMeaning: "In der Glut liegt eine Kraft, die noch keine Flamme braucht.",
      importance: 0.84,
      depthLevel: 1,
      visuals: { material: "black-stone", accent: "gold", glow: 0.48, opacity: 0.88, motion: "breathing" },
      experience: { camera: "draw-near", tone: "still", tempo: "very-slow", depth: 0.62 },
    },
    {
      id: "spark",
      type: "natural-symbol",
      label: "Funke",
      shortMeaning: "Ein kleiner Impuls ueberspringt die Schwelle zur Entzuendung.",
      importance: 0.9,
      depthLevel: 1,
      visuals: { material: "gold-thread", accent: "gold", glow: 0.92, opacity: 0.9, motion: "spark" },
      experience: { camera: "draw-near", tone: "awakening", tempo: "measured", depth: 0.42 },
    },
    {
      id: "flame",
      type: "natural-symbol",
      label: "Flamme",
      shortMeaning: "Die Flamme verwandelt Stoff in Waerme, Bewegung und neue Gestalt.",
      importance: 0.96,
      depthLevel: 1,
      visuals: { material: "gold-thread", accent: "gold", glow: 1, opacity: 0.96, motion: "emerging" },
      experience: { camera: "reveal", tone: "awe", tempo: "measured", depth: 0.3 },
    },
    {
      id: "light",
      type: "spiritual-symbol",
      label: "Licht",
      shortMeaning: "Feuer wird sichtbar als Licht und macht den Raum lesbar.",
      importance: 0.9,
      depthLevel: 1,
      visuals: { material: "script-light", accent: "gold", glow: 0.94, opacity: 0.92, motion: "breathing" },
      experience: { camera: "reveal", tone: "awe", tempo: "slow", depth: 0.26 },
    },
    {
      id: "sending",
      type: "spiritual-symbol",
      label: "Sendung",
      shortMeaning: "Was empfangen wurde, wird zur Bewegung nach aussen.",
      importance: 0.88,
      depthLevel: 1,
      visuals: { material: "gold-thread", accent: "gold", glow: 0.82, opacity: 0.88, motion: "emerging" },
      experience: { camera: "wide-threshold", tone: "hope", tempo: "measured", depth: 0.34 },
    },
  ],
  edges: [
    {
      source: "fire",
      target: "embers",
      relation: "contains",
      weight: 0.88,
      layer: "surface",
      meaningQuality: "origin",
      emotionalTone: "still",
      visualBehavior: "breathing",
      explanation: "Glut bewahrt Waerme, bevor eine sichtbare Flamme entsteht.",
    },
    {
      source: "fire",
      target: "spark",
      relation: "breaks-through",
      weight: 0.94,
      layer: "visual",
      meaningQuality: "impulse",
      emotionalTone: "awakening",
      visualBehavior: "spark",
      explanation: "Der Funke ist klein und doch genuegt er, damit Feuer beginnt.",
    },
    {
      source: "fire",
      target: "flame",
      relation: "transforms",
      weight: 0.98,
      layer: "existential",
      meaningQuality: "transition",
      emotionalTone: "awe",
      visualBehavior: "emerging",
      explanation: "Die Flamme macht Verwandlung sichtbar: nichts bleibt ganz, wie es war.",
    },
    {
      source: "fire",
      target: "light",
      relation: "reveals",
      weight: 0.92,
      layer: "spiritual",
      meaningQuality: "revelation",
      emotionalTone: "awe",
      visualBehavior: "breathing",
      explanation: "Im Licht des Feuers tritt hervor, was zuvor im Dunkel lag.",
    },
    {
      source: "fire",
      target: "sending",
      relation: "unfolds-into",
      weight: 0.9,
      layer: "existential",
      meaningQuality: "movement",
      emotionalTone: "hope",
      visualBehavior: "emerging",
      explanation: "Feuer bleibt nicht stehen: Seine Waerme und sein Licht greifen weiter.",
    },
  ],
  primaryPaths: {
    fire: ["fire", "embers", "spark", "flame", "light", "sending"],
    embers: ["embers", "fire", "spark"],
    spark: ["spark", "fire", "flame"],
    flame: ["flame", "fire", "light"],
    light: ["light", "fire", "sending"],
    sending: ["sending", "fire", "light"],
  },
};

export const fireRoomDefinition: SymbolRoomDefinition = {
  id: "fire-room",
  slug: "feuer",
  graph: fireSymbolGraph,
  centerNodeId: "fire",
  entrance: {
    symbolNodeId: "fire",
    kickerPrefix: "Raum",
    statement: "Feuer entzuendet. Feuer verwandelt. Feuer sendet.",
    ctaLabel: "Der Waerme folgen",
    ctaHref: "#symbolreise",
    heroImage: {
      src: visualAssets.feuerHero,
      alt: "Dunkler Raum mit warmen goldenen Lichtachsen",
    },
    backgroundImage: {
      src: visualAssets.feuerHero,
      alt: "Atmosphaerischer Raum mit warmem Licht",
    },
  },
  encounters: [
    {
      id: "potential",
      symbolNodeId: "embers",
      state: "potential",
      impulse: "Waerme wartet unter der Oberflaeche.",
      experienceState: { mood: "expectant", motion: "glowing", light: "deep-amber", density: 0.62, transition: "gather" },
    },
    {
      id: "ignition",
      symbolNodeId: "spark",
      state: "ignition",
      impulse: "Ein Funke genuegt.",
      experienceState: { mood: "awakening", motion: "sparking", light: "bright-gold", density: 0.4, transition: "ignite" },
    },
    {
      id: "transformation",
      symbolNodeId: "flame",
      state: "transformation",
      impulse: "Die Flamme gibt allem eine neue Gestalt.",
      experienceState: { mood: "awe", motion: "rising", light: "amber-gold", density: 0.34, transition: "transform" },
    },
    {
      id: "revelation",
      symbolNodeId: "light",
      state: "revelation",
      impulse: "Im Licht wird der Raum lesbar.",
      experienceState: { mood: "clarity", motion: "radiating", light: "warm-gold", density: 0.28, transition: "reveal" },
    },
    {
      id: "radiance",
      symbolNodeId: "sending",
      state: "radiance",
      impulse: "Was brennt, traegt Waerme weiter.",
      experienceState: { mood: "resolve", motion: "ascending", light: "living-gold", density: 0.3, transition: "send" },
    },
  ],
  decision: {
    kicker: "Reflexionsraum",
    reflectionQuestion: "Was will in dir nicht nur glimmen, sondern zur Sendung werden?",
    textareaLabel: "Reflexion zum Feuerraum",
    placeholder: "Still notieren...",
    storageNotice: "Deine Reflexion bleibt nur auf diesem Geraet gespeichert.",
    saveLabel: "Reflexion speichern",
    savedMessage: "Gespeichert. Du findest den Gedanken unter Mein Pfad.",
    emptyMessage: "Schreibe zuerst eine kurze Reflexion.",
  },
  transition: {
    symbolNodeId: "fire",
  },
  theme: {
    id: "fire",
    colors: {
      background: "#100603",
      accentRgb: "232, 178, 82",
      ambientRgb: "217, 119, 42",
      shadowRgb: "8, 2, 1",
      veilRgb: "24, 8, 3",
      depthRgb: "42, 16, 5",
    },
    atmosphereProfile: {
      id: "warm-light-particles",
      motion: "ascending",
      particles: "sparks",
      light: "emission",
      materiality: "warm-ash",
      rhythm: "pulsing",
    },
    overlayStyle: {
      background:
        "radial-gradient(circle at 50% 78%, rgba(var(--symbol-room-ambient-rgb), 0.16), transparent 34%), radial-gradient(circle at 52% 42%, rgba(var(--symbol-room-accent-rgb), 0.1), transparent 28%), linear-gradient(180deg, rgba(var(--symbol-room-shadow-rgb), 0.96), var(--symbol-room-background))",
    },
    encounterImage: {
      src: visualAssets.feuerHero,
      alt: "Dunkler Raum mit warmen goldenen Lichtachsen",
    },
    journeyKicker: "Symbolreise",
    journeyStatement: "Fuenf Bewegungen des Feuers: Glut, Funke, Flamme, Licht, Sendung.",
    meaningQualityLabels,
    primaryMeaningQualities: ["impulse", "transition", "revelation", "movement"],
    fallbackQualities: ["Glut", "Verwandlung", "Sendung"],
  },
};
