import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const fireEngineData: SymbolEngineData = {
  id: "fire-engine",
  slug: "feuer",
  title: "Feuerraum",
  symbolLabel: "Feuer",
  hebrew: {
    hebrewWordId: "esch",
    hebrewLetterIds: ["aleph", "shin"],
    hebrewMeaningFieldIds: ["esh-fire", "esh-transformation", "esh-presence", "esh-purification", "esh-calling"],
    word: "\u05d0\u05e9",
    transliteration: "esch",
    translation: "Feuer",
    summary: "Esch verbindet verborgene Gegenwart und verwandelnde Kraft: vom stillen Aleph zur bewegten Energie des Shin.",
    letters: [
      {
        id: "aleph",
        hebrewLetterId: "aleph",
        letter: "\u05d0",
        name: "Aleph",
        position: "Anfang",
        meaning: "Ursprung, Stille, verborgene Gegenwart",
        detail: "Aleph steht am Anfang des Wortes: Feuer beginnt als Gegenwart, noch bevor eine Flamme sichtbar wird.",
      },
      {
        id: "shin",
        hebrewLetterId: "shin",
        letter: "\u05e9",
        name: "Shin",
        position: "Ende",
        meaning: "Feuer, Energie, Verwandlung",
        detail: "Shin gibt dem Feuer Bewegung. Was verborgen glimmt, kann sichtbar werden, rufen und verwandeln.",
      },
    ],
  },
  scenes: [
    {
      id: "exodus-3-2",
      reference: "Exodus 3,2",
      title: "Der brennende Dornbusch",
      text: "Der Dornbusch brennt und verbrennt nicht. Mose tritt näher und hört seinen Namen.",
      meaning: "Feuer wird zur Gegenwart, die nicht verzehrt, sondern ruft.",
    },
    {
      id: "exodus-13-21",
      reference: "Exodus 13,21",
      title: "Die Feuersäule",
      text: "In der Nacht begleitet eine Feuersäule Israel auf dem Weg.",
      meaning: "Feuer wird zur Führung: genug Licht für den gegenwärtigen Augenblick.",
    },
    {
      id: "malachi-3-2-3",
      reference: "Maleachi 3,2-3",
      title: "Das läuternde Feuer",
      text: "Das Feuer des Schmelzers klärt, was kostbar ist.",
      meaning: "Läuterung meint keine Auslöschung, sondern eine Verwandlung, die Wesentliches freilegt.",
    },
  ],
  connections: [
    { id: "spark", label: "Funke", relation: "Möglichkeit", detail: "In der Glut liegt eine Kraft, die noch keine sichtbare Flamme braucht." },
    { id: "presence", label: "Gegenwart", relation: "Offenbarung", detail: "Der Dornbusch brennt, ohne zu verbrennen: Feuer wird zum Zeichen tragender Nähe." },
    { id: "calling", label: "Ruf", relation: "Berufung", detail: "Mose wird beim Namen gerufen und aus der Distanz in Gegenwart geführt." },
    { id: "guidance", label: "Führung", relation: "Weg", detail: "Die Feuersäule gibt Richtung, ohne den ganzen Weg vorwegzunehmen." },
    { id: "purification", label: "Reinigung", relation: "Läuterung", detail: "Feuer kann klären, was bleiben soll, und lösen, was seine Gestalt verloren hat." },
    { id: "transformation", label: "Verwandlung", relation: "Neue Gestalt", detail: "Was dem Feuer begegnet, bleibt nicht ganz, wie es war." },
  ],
  states: [
    {
      id: "hidden-fire",
      navigationLabel: "Verborgenes Feuer",
      eyebrow: "\u05d0\u05e9 / Möglichkeit",
      title: "Verborgenes Feuer",
      text: "Wärme wartet unter der Oberfläche. Ein Funke genügt, damit sichtbar wird, was bereits in Bewegung ist.",
      inscription: "Möglichkeit / Glut / Funke",
      visual: {
        image: visualAssets.feuerGlut,
        backgroundImage: visualAssets.feuerAsh,
        alt: "Verborgene warme Glut in einem dunklen Raum",
        atmosphere: { id: "hidden-fire", mood: "erwartend", motion: "glimmend", light: "tiefes amber", density: 0.68 },
        veilOpacity: 0.72,
      },
      hebrewLetterIds: ["aleph"],
      hebrewCodexLetterIds: ["aleph"],
      hebrewMeaningFieldIds: ["esh-fire", "esh-presence"],
      hebrewSummary: "Aleph bewahrt den stillen Anfang: Feuer ist schon gegenwärtig, bevor es sichtbar hervortritt.",
      biblicalSceneIds: [],
      connectionIds: ["spark", "presence"],
      reflection: { kicker: "Innere Erfahrung", question: "Was glimmt bereits in dir?" },
    },
    {
      id: "burning-bush",
      navigationLabel: "Dornbusch",
      eyebrow: "Exodus 3,2",
      title: "Der brennende Dornbusch",
      text: "Der Dornbusch brennt und wird nicht verzehrt. Feuer wird zur Offenbarung: Eine Gegenwart tritt hervor und ruft Mose beim Namen.",
      inscription: "Offenbarung / Gegenwart / Ruf",
      visual: {
        image: visualAssets.feuerHero,
        backgroundImage: visualAssets.feuerGlut,
        alt: "Warme goldene Lichtachsen erinnern an einen brennenden Dornbusch",
        atmosphere: { id: "burning-bush", mood: "wach", motion: "aufflammend", light: "warmes gold", density: 0.54 },
        veilOpacity: 0.56,
      },
      hebrewLetterIds: ["aleph", "shin"],
      hebrewCodexLetterIds: ["aleph", "shin"],
      hebrewMeaningFieldIds: ["esh-presence", "esh-calling"],
      hebrewSummary: "Aleph und Shin verbinden stille Gegenwart mit bewegtem Feuer: Aus dem Zeichen wird ein Ruf.",
      biblicalSceneIds: ["exodus-3-2"],
      connectionIds: ["presence", "calling"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo ruft dich etwas beim Namen?" },
    },
    {
      id: "pillar-of-fire",
      navigationLabel: "Feuersäule",
      eyebrow: "Exodus 13,21",
      title: "Feuersäule",
      text: "In der Nacht wird Feuer zum Wegzeichen. Es nimmt die Unsicherheit nicht fort, aber es lässt Richtung sichtbar werden.",
      inscription: "Führung / Nacht / Weg",
      visual: {
        image: visualAssets.feuerSmoke,
        backgroundImage: visualAssets.feuerHero,
        alt: "Rauch und warmer Feuerschein steigen wie eine Spur durch einen dunklen Raum",
        atmosphere: { id: "pillar-of-fire", mood: "entschieden", motion: "weisend", light: "goldene säule", density: 0.48 },
        veilOpacity: 0.5,
      },
      hebrewLetterIds: ["shin"],
      hebrewCodexLetterIds: ["shin"],
      hebrewMeaningFieldIds: ["esh-fire", "esh-presence"],
      hebrewSummary: "Shin trägt die bewegte Energie des Feuers: Die Flamme bleibt nicht stehen, sondern weist weiter.",
      biblicalSceneIds: ["exodus-13-21"],
      connectionIds: ["guidance", "presence"],
      reflection: { kicker: "Innere Erfahrung", question: "Was weist dir den Weg?" },
    },
    {
      id: "refining-fire",
      navigationLabel: "Läuterndes Feuer",
      eyebrow: "Maleachi 3,2-3",
      title: "Läuterndes Feuer",
      text: "Feuer kann klären, ohne das Wesentliche auszulöschen. In der Läuterung bekommt Verwandlung eine neue Gestalt.",
      inscription: "Läuterung / Reinigung / Verwandlung",
      visual: {
        image: visualAssets.feuerMacro,
        backgroundImage: visualAssets.feuerAsh,
        alt: "Warmer goldener Feuerschein sammelt sich in einem tiefen Raum",
        atmosphere: { id: "refining-fire", mood: "klärend", motion: "sammelnd", light: "lebendiges gold", density: 0.4 },
        veilOpacity: 0.48,
      },
      hebrewLetterIds: ["aleph", "shin"],
      hebrewCodexLetterIds: ["aleph", "shin"],
      hebrewMeaningFieldIds: ["esh-transformation", "esh-purification"],
      hebrewSummary: "Aleph und Shin bilden eine Bewegung vom verborgenen Ursprung zur verwandelnden Kraft.",
      biblicalSceneIds: ["malachi-3-2-3"],
      connectionIds: ["purification", "transformation"],
      reflection: { kicker: "Innere Erfahrung", question: "Was darf gereinigt werden?" },
    },
  ],
};
