import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const wuesteEngineData: SymbolEngineData = {
  id: "desert-engine",
  slug: "wueste",
  title: "Wüstenraum",
  symbolLabel: "Wüste",
  hebrew: {
    hebrewWordId: "midbar",
    hebrewLetterIds: ["mem", "dalet", "bet", "resh"],
    hebrewMeaningFieldIds: ["midbar-desert", "midbar-reduction", "midbar-listening", "midbar-testing", "midbar-guidance", "midbar-word"],
    word: "\u05de\u05d3\u05d1\u05e8",
    transliteration: "midbar",
    translation: "Wüste",
    summary:
      "Midbar bezeichnet die Wüste als Raum von Leere, Weg und Hören. Die Nähe zum Bedeutungsfeld von davar / Wort bleibt eine behutsame Spur, keine Gleichsetzung.",
    letters: [
      {
        id: "mem",
        hebrewLetterId: "mem",
        letter: "\u05de",
        name: "Mem",
        position: "Anfang",
        meaning: "Tiefe, Leere, offener Raum",
        detail: "Mem öffnet den Eintritt in einen Raum, in dem äußere Sicherheiten fehlen und Tiefe spürbar wird.",
      },
      {
        id: "dalet",
        hebrewLetterId: "dalet",
        letter: "\u05d3",
        name: "Dalet",
        position: "Zweite Stelle",
        meaning: "Tür, Schwelle, Übergang",
        detail: "Dalet markiert eine Schwelle: Die Wüste ist kein Endpunkt, sondern ein Raum des Hindurchgehens.",
      },
      {
        id: "bet",
        hebrewLetterId: "bet",
        letter: "\u05d1",
        name: "Bet",
        position: "Dritte Stelle",
        meaning: "Innenraum, Sammlung, Hören",
        detail: "Bet sammelt die Aufmerksamkeit nach innen. In der Leere kann eine Stimme hörbar werden.",
      },
      {
        id: "resh",
        hebrewLetterId: "resh",
        letter: "\u05e8",
        name: "Resh",
        position: "Ende",
        meaning: "Ausrichtung, Wahrnehmung, Weg",
        detail: "Resh schließt das Wort mit einer neuen Ausrichtung: Eine Spur wird lesbar.",
      },
    ],
  },
  scenes: [
    {
      id: "exodus-wilderness",
      reference: "Exodus 16",
      title: "Israel in der Wüste",
      text: "Nach dem Auszug führt der Weg durch einen Raum ohne vertraute Sicherheiten. Hunger und Durst machen Abhängigkeit spürbar.",
      meaning: "Die Wüste zeigt Mangel nicht als Endpunkt, sondern als Ort, an dem Vertrauen neu gelernt wird.",
    },
    {
      id: "deuteronomy-8",
      reference: "Deuteronomium 8",
      title: "Der Weg der Prüfung",
      text: "Der lange Weg durch die Wüste wird als Prüfung erinnert. Sichtbar wird, was im Herzen verborgen liegt.",
      meaning: "Die Prüfung legt frei, worauf ein Mensch vertraut, wenn Ablenkung und Kontrolle schwinden.",
    },
    {
      id: "exodus-13-21",
      reference: "Exodus 13,21",
      title: "Die Feuersäule",
      text: "In der Nacht begleitet eine Feuersäule Israel auf dem Weg. Sie zeigt nicht die ganze Strecke, aber eine Spur im Dunkel.",
      meaning: "In der dunklen Weite werden Licht und Feuer zu Zeichen von Führung und Gegenwart.",
    },
    {
      id: "sinai-word",
      reference: "Exodus 19",
      title: "Die Stimme am Sinai",
      text: "In der Wüste wird der Berg zum Ort des Hörens. Aus der Stille tritt ein Wort hervor, das Richtung gibt.",
      meaning: "Midbar kann als Raum des Hörens gelesen werden. Die Nähe zu davar / Wort bleibt eine offene Bedeutungsnähe.",
    },
  ],
  connections: [
    { id: "water", label: "Wasser", relation: "Mangel und Quelle", detail: "Wo Wasser fehlt, werden Durst, Abhängigkeit und die Gabe einer Quelle sichtbar." },
    { id: "light", label: "Licht", relation: "Orientierung", detail: "In der Nacht gibt Licht genug Richtung für den Augenblick." },
    { id: "fire", label: "Feuer", relation: "Gegenwart", detail: "Die Feuersäule verbindet die dunkle Weite mit tragender Gegenwart." },
    { id: "word", label: "Wort", relation: "Stimme", detail: "In der Stille kann eine leise Stimme als Wort und Ausrichtung hörbar werden." },
  ],
  states: [
    {
      id: "emptiness",
      navigationLabel: "Die Leere",
      eyebrow: "Exodus / Eintritt",
      title: "Alles Vertraute fällt weg.",
      text: "Kein Wasser. Keine Sicherheit. Die Wüste nimmt nicht nur etwas fort, sie macht sichtbar, worauf Vertrauen bisher geruht hat.",
      inscription: "Leere / Mangel / Abhängigkeit",
      visual: {
        image: visualAssets.wuesteHero,
        backgroundImage: visualAssets.wuesteDust,
        alt: "Weite dunkle Wüste in Nachtblau mit kaum sichtbarem Licht",
        atmosphere: { id: "desert-emptiness", mood: "still", motion: "verlangsamend", light: "nachtblau", density: 0.84 },
        veilOpacity: 0.78,
        imageOpacity: 0.72,
      },
      hebrewLetterIds: ["mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["midbar-desert", "midbar-reduction"],
      hebrewSummary: "Mem öffnet die Tiefe der Leere: einen Raum, in dem Mangel nicht überdeckt werden kann.",
      biblicalSceneIds: ["exodus-wilderness"],
      connectionIds: ["water"],
      reflection: { kicker: "Innere Erfahrung", question: "Was fehlt dir gerade so sehr, dass du merkst, worauf du wirklich vertraust?" },
    },
    {
      id: "testing",
      navigationLabel: "Die Prüfung",
      eyebrow: "Deuteronomium 8",
      title: "Die Wüste zeigt, was verborgen ist.",
      text: "Hunger, Durst, Angst und der Wunsch nach Kontrolle treten in der Leere deutlicher hervor. Ohne Ablenkung bekommt das Innere Kontur.",
      inscription: "Prüfung / Verborgenheit / Vertrauen",
      visual: {
        image: visualAssets.wuesteDust,
        backgroundImage: visualAssets.wuesteMacro,
        alt: "Trockener dunkler Raum mit feinem Staub und einer fernen Lichtachse",
        atmosphere: { id: "desert-testing", mood: "gespannt", motion: "staubend", light: "ferne Achse", density: 0.72 },
        veilOpacity: 0.74,
        imageOpacity: 0.7,
      },
      hebrewLetterIds: ["dalet"],
      hebrewCodexLetterIds: ["dalet"],
      hebrewMeaningFieldIds: ["midbar-testing"],
      hebrewSummary: "Dalet markiert die Schwelle: Prüfung ist ein Übergang, an dem Verborgenes hervortritt.",
      biblicalSceneIds: ["deuteronomy-8"],
      connectionIds: ["water"],
      reflection: { kicker: "Innere Erfahrung", question: "Was kommt in dir zum Vorschein, wenn nichts dich ablenkt?" },
    },
    {
      id: "guidance",
      navigationLabel: "Die Führung",
      eyebrow: "Exodus 13,21",
      title: "In der Nacht wird Führung sichtbar.",
      text: "Die Feuersäule nimmt die Wüste nicht fort. Sie macht in der dunklen Weite eine Richtung sichtbar und trägt die Spur.",
      inscription: "Feuersäule / Licht / Gegenwart",
      visual: {
        image: visualAssets.wuestePath,
        alt: "Ruhige goldene Lichtsäule in einer weiten dunklen Landschaft",
        atmosphere: { id: "desert-guidance", mood: "gesammelt", motion: "weisend", light: "goldene Säule", density: 0.52 },
        veilOpacity: 0.58,
        imageOpacity: 0.7,
      },
      hebrewLetterIds: ["resh"],
      hebrewCodexLetterIds: ["resh"],
      hebrewMeaningFieldIds: ["midbar-guidance"],
      hebrewSummary: "Resh richtet die Wahrnehmung neu aus: Der ganze Weg bleibt verborgen, aber eine Spur wird lesbar.",
      biblicalSceneIds: ["exodus-13-21"],
      connectionIds: ["light", "fire"],
      reflection: { kicker: "Innere Erfahrung", question: "Welchem Licht folgst du, wenn der Weg nicht sichtbar ist?" },
    },
    {
      id: "voice",
      navigationLabel: "Die Stimme",
      eyebrow: "\u05de\u05d3\u05d1\u05e8 / midbar",
      title: "In der Stille wird eine Stimme hörbar.",
      text: "Nicht die Fülle spricht, sondern die Stille. Die Wüste wird zum Ort des Wortes, ohne dass sich ihr Geheimnis in einer einfachen Gleichung auflöst.",
      inscription: "Stille / Stimme / Wort",
      visual: {
        image: visualAssets.wuesteHebrew,
        backgroundImage: visualAssets.wuestePath,
        alt: "Warme hebräische Spuren in einem dunklen stillen Archivraum",
        atmosphere: { id: "desert-voice", mood: "lauschend", motion: "sammelnd", light: "warmes Gold", density: 0.42 },
        veilOpacity: 0.64,
        imageOpacity: 0.68,
      },
      hebrewLetterIds: ["bet", "resh"],
      hebrewCodexLetterIds: ["bet", "resh"],
      hebrewMeaningFieldIds: ["midbar-listening", "midbar-word"],
      hebrewSummary: "Bet und Resh führen vom inneren Hören zur Ausrichtung. Midbar steht in behutsamer Bedeutungsnähe zu davar / Wort.",
      biblicalSceneIds: ["sinai-word"],
      connectionIds: ["word", "light"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche leise Stimme wird hörbar, wenn alles andere schweigt?" },
    },
  ],
};
