import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const wuesteEngineData: SymbolEngineData = {
  id: "desert-engine",
  slug: "wueste",
  title: "Wüstenraum",
  symbolLabel: "Wüste",
  hebrew: {
    hebrewWordId: "midbar",
    hebrewLetterIds: ["mem", "dalet", "bet", "resh"],
    hebrewMeaningFieldIds: ["midbar-desert", "midbar-reduction", "midbar-listening", "midbar-testing", "midbar-guidance", "midbar-word"],
    word: "\u05de\u05d3\u05d1\u05e8",
    transliteration: "midbar",
    translation: "Wüste",
    summary:
      "Midbar bezeichnet die Wueste als Raum von Leere, Weg und Hoeren. Die Naehe zum Bedeutungsfeld von davar / Wort bleibt eine behutsame Spur, keine Gleichsetzung.",
    letters: [
      {
        id: "mem",
        hebrewLetterId: "mem",
        letter: "\u05de",
        name: "Mem",
        position: "Anfang",
        meaning: "Tiefe, Leere, offener Raum",
        detail: "Mem oeffnet den Eintritt in einen Raum, in dem aeussere Sicherheiten fehlen und Tiefe spuerbar wird.",
      },
      {
        id: "dalet",
        hebrewLetterId: "dalet",
        letter: "\u05d3",
        name: "Dalet",
        position: "Zweite Stelle",
        meaning: "Tuer, Schwelle, Uebergang",
        detail: "Dalet markiert eine Schwelle: Die Wueste ist kein Endpunkt, sondern ein Raum des Hindurchgehens.",
      },
      {
        id: "bet",
        hebrewLetterId: "bet",
        letter: "\u05d1",
        name: "Bet",
        position: "Dritte Stelle",
        meaning: "Innenraum, Sammlung, Hoeren",
        detail: "Bet sammelt die Aufmerksamkeit nach innen. In der Leere kann eine Stimme hoerbar werden.",
      },
      {
        id: "resh",
        hebrewLetterId: "resh",
        letter: "\u05e8",
        name: "Resh",
        position: "Ende",
        meaning: "Ausrichtung, Wahrnehmung, Weg",
        detail: "Resh schliesst das Wort mit einer neuen Ausrichtung: Eine Spur wird lesbar.",
      },
    ],
  },
  scenes: [
    {
      id: "exodus-wilderness",
      reference: "Exodus 16",
      title: "Israel in der Wueste",
      text: "Nach dem Auszug fuehrt der Weg durch einen Raum ohne vertraute Sicherheiten. Hunger und Durst machen Abhaengigkeit spuerbar.",
      meaning: "Die Wueste zeigt Mangel nicht als Endpunkt, sondern als Ort, an dem Vertrauen neu gelernt wird.",
    },
    {
      id: "deuteronomy-8",
      reference: "Deuteronomium 8",
      title: "Der Weg der Pruefung",
      text: "Der lange Weg durch die Wueste wird als Pruefung erinnert. Sichtbar wird, was im Herzen verborgen liegt.",
      meaning: "Die Pruefung legt frei, worauf ein Mensch vertraut, wenn Ablenkung und Kontrolle schwinden.",
    },
    {
      id: "exodus-13-21",
      reference: "Exodus 13,21",
      title: "Die Feuersaeule",
      text: "In der Nacht begleitet eine Feuersaeule Israel auf dem Weg. Sie zeigt nicht die ganze Strecke, aber eine Spur im Dunkel.",
      meaning: "In der dunklen Weite werden Licht und Feuer zu Zeichen von Fuehrung und Gegenwart.",
    },
    {
      id: "sinai-word",
      reference: "Exodus 19",
      title: "Die Stimme am Sinai",
      text: "In der Wueste wird der Berg zum Ort des Hoerens. Aus der Stille tritt ein Wort hervor, das Richtung gibt.",
      meaning: "Midbar kann als Raum des Hoerens gelesen werden. Die Naehe zu davar / Wort bleibt eine offene Bedeutungsnaehe.",
    },
  ],
  connections: [
    { id: "water", label: "Wasser", relation: "Mangel und Quelle", detail: "Wo Wasser fehlt, werden Durst, Abhaengigkeit und die Gabe einer Quelle sichtbar." },
    { id: "light", label: "Licht", relation: "Orientierung", detail: "In der Nacht gibt Licht genug Richtung fuer den Augenblick." },
    { id: "fire", label: "Feuer", relation: "Gegenwart", detail: "Die Feuersaeule verbindet die dunkle Weite mit tragender Gegenwart." },
    { id: "word", label: "Wort", relation: "Stimme", detail: "In der Stille kann eine leise Stimme als Wort und Ausrichtung hoerbar werden." },
  ],
  states: [
    {
      id: "emptiness",
      navigationLabel: "Die Leere",
      eyebrow: "Exodus / Eintritt",
      title: "Alles Vertraute faellt weg.",
      text: "Kein Wasser. Keine Sicherheit. Die Wueste nimmt nicht nur etwas fort, sie macht sichtbar, worauf Vertrauen bisher geruht hat.",
      inscription: "Leere / Mangel / Abhaengigkeit",
      visual: {
        image: visualAssets.wuesteHero,
        alt: "Weite dunkle Wueste in Nachtblau mit kaum sichtbarem Licht",
        atmosphere: { id: "desert-emptiness", mood: "still", motion: "verlangsamend", light: "nachtblau", density: 0.84 },
        veilOpacity: 0.78,
        imageOpacity: 0.72,
      },
      hebrewLetterIds: ["mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["midbar-desert", "midbar-reduction"],
      hebrewSummary: "Mem oeffnet die Tiefe der Leere: einen Raum, in dem Mangel nicht ueberdeckt werden kann.",
      biblicalSceneIds: ["exodus-wilderness"],
      connectionIds: ["water"],
      reflection: { kicker: "Innere Erfahrung", question: "Was fehlt dir gerade so sehr, dass du merkst, worauf du wirklich vertraust?" },
    },
    {
      id: "testing",
      navigationLabel: "Die Pruefung",
      eyebrow: "Deuteronomium 8",
      title: "Die Wueste zeigt, was verborgen ist.",
      text: "Hunger, Durst, Angst und der Wunsch nach Kontrolle treten in der Leere deutlicher hervor. Ohne Ablenkung bekommt das Innere Kontur.",
      inscription: "Pruefung / Verborgenheit / Vertrauen",
      visual: {
        image: visualAssets.wuesteHero,
        backgroundImage: visualAssets.wuesteHero,
        alt: "Trockener dunkler Raum mit feinem Staub und einer fernen Lichtachse",
        atmosphere: { id: "desert-testing", mood: "gespannt", motion: "staubend", light: "ferne Achse", density: 0.72 },
        veilOpacity: 0.74,
        imageOpacity: 0.7,
      },
      hebrewLetterIds: ["dalet"],
      hebrewCodexLetterIds: ["dalet"],
      hebrewMeaningFieldIds: ["midbar-testing"],
      hebrewSummary: "Dalet markiert die Schwelle: Pruefung ist ein Uebergang, an dem Verborgenes hervortritt.",
      biblicalSceneIds: ["deuteronomy-8"],
      connectionIds: ["water"],
      reflection: { kicker: "Innere Erfahrung", question: "Was kommt in dir zum Vorschein, wenn nichts dich ablenkt?" },
    },
    {
      id: "guidance",
      navigationLabel: "Die Fuehrung",
      eyebrow: "Exodus 13,21",
      title: "In der Nacht wird Fuehrung sichtbar.",
      text: "Die Feuersaeule nimmt die Wueste nicht fort. Sie macht in der dunklen Weite eine Richtung sichtbar und traegt die Spur.",
      inscription: "Feuersaeule / Licht / Gegenwart",
      visual: {
        image: visualAssets.lichtHero,
        alt: "Ruhige goldene Lichtsaeule in einer weiten dunklen Landschaft",
        atmosphere: { id: "desert-guidance", mood: "gesammelt", motion: "weisend", light: "goldene Saeule", density: 0.52 },
        veilOpacity: 0.58,
        imageOpacity: 0.7,
      },
      hebrewLetterIds: ["resh"],
      hebrewCodexLetterIds: ["resh"],
      hebrewMeaningFieldIds: ["midbar-guidance"],
      hebrewSummary: "Resh richtet die Wahrnehmung neu aus: Der ganze Weg bleibt verborgen, aber eine Spur wird lesbar.",
      biblicalSceneIds: ["exodus-13-21"],
      connectionIds: ["light", "fire"],
      reflection: { kicker: "Innere Erfahrung", question: "Welchem Licht folgst du, wenn der Weg nicht sichtbar ist?" },
    },
    {
      id: "voice",
      navigationLabel: "Die Stimme",
      eyebrow: "\u05de\u05d3\u05d1\u05e8 / midbar",
      title: "In der Stille wird eine Stimme hoerbar.",
      text: "Nicht die Fuelle spricht, sondern die Stille. Die Wueste wird zum Ort des Wortes, ohne dass sich ihr Geheimnis in einer einfachen Gleichung aufloest.",
      inscription: "Stille / Stimme / Wort",
      visual: {
        image: visualAssets.wuesteHero,
        backgroundImage: visualAssets.lichtHero,
        alt: "Warme hebraeische Spuren in einem dunklen stillen Archivraum",
        atmosphere: { id: "desert-voice", mood: "lauschend", motion: "sammelnd", light: "warmes Gold", density: 0.42 },
        veilOpacity: 0.64,
        imageOpacity: 0.68,
      },
      hebrewLetterIds: ["bet", "resh"],
      hebrewCodexLetterIds: ["bet", "resh"],
      hebrewMeaningFieldIds: ["midbar-listening", "midbar-word"],
      hebrewSummary: "Bet und Resh fuehren vom inneren Hoeren zur Ausrichtung. Midbar steht in behutsamer Bedeutungsnaehe zu davar / Wort.",
      biblicalSceneIds: ["sinai-word"],
      connectionIds: ["word", "light"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche leise Stimme wird hoerbar, wenn alles andere schweigt?" },
    },
  ],
};
