import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const breadEngineData: SymbolEngineData = {
  id: "bread-engine",
  slug: "brot",
  title: "Brotraum",
  symbolLabel: "Brot",
  hebrew: {
    hebrewWordId: "lechem",
    hebrewLetterIds: ["lamed", "chet", "mem"],
    hebrewMeaningFieldIds: ["lechem-nourishment", "lechem-gift", "lechem-community", "lechem-breaking", "lechem-life", "lechem-word"],
    word: "\u05dc\u05d7\u05dd",
    transliteration: "lechem",
    translation: "Brot",
    summary: "Lechem verbindet Nahrung, Gabe und Gemeinschaft: vom verborgenen Korn über die tägliche Versorgung bis zum geteilten Brot des Lebens.",
    letters: [
      {
        id: "lamed",
        hebrewLetterId: "lamed",
        letter: "\u05dc",
        name: "Lamed",
        position: "Anfang",
        meaning: "Lernen, Ausrichtung, Wachstum",
        detail: "Lamed richtet den Blick auf das Werden: Korn wächst, reift und wird zur Nahrung, die empfangen werden kann.",
      },
      {
        id: "chet",
        hebrewLetterId: "chet",
        letter: "\u05d7",
        name: "Chet",
        position: "Mitte",
        meaning: "Leben, Innenraum, Gemeinschaft",
        detail: "Chet sammelt das Brot in der Mitte des Wortes als Zeichen des Lebens, das nicht für sich allein bleibt.",
      },
      {
        id: "mem",
        hebrewLetterId: "mem",
        letter: "\u05dd",
        name: "Mem",
        position: "Ende",
        meaning: "Wasser, Verborgenheit, empfangene Gabe",
        detail: "Das finale Mem bewahrt eine verborgene Innenseite: Nahrung bleibt Gabe und verweist über sich hinaus.",
      },
    ],
  },
  scenes: [
    {
      id: "mark-4-grain",
      reference: "Markus 4,26-29",
      title: "Das verborgene Korn",
      text: "Ein Same liegt in der Erde und wächst, ohne dass sein Werden ganz verfügbar wäre. Aus dem verborgenen Leben reift Korn.",
      meaning: "Brot beginnt lange vor dem Laib: als verborgenes Leben, das Wasser und Licht empfängt.",
    },
    {
      id: "exodus-16-manna",
      reference: "Exodus 16,4",
      title: "Manna in der Wüste",
      text: "In der Wüste fällt Brot vom Himmel. Es kann nicht gehortet werden, sondern wird Tag für Tag empfangen.",
      meaning: "Manna macht Versorgung als Gabe sichtbar: genug für den heutigen Weg.",
    },
    {
      id: "luke-24-breaking",
      reference: "Lukas 24,30-31",
      title: "Erkannt im Brechen",
      text: "Am Tisch wird das Brot genommen, gesegnet und gebrochen. Im Teilen öffnet sich den Jüngern eine neue Sicht.",
      meaning: "Brot stiftet Gemeinschaft gerade dort, wo es gebrochen und geteilt wird.",
    },
    {
      id: "john-6-life",
      reference: "Johannes 6,35",
      title: "Brot des Lebens",
      text: "Jesus spricht vom Brot des Lebens. Die tägliche Nahrung wird zum Zeichen einer inneren Versorgung, die tiefer reicht als Saettigung.",
      meaning: "Brot verweist auf Christus als Nahrung für das innere Leben und auf das Wort, von dem der Mensch lebt.",
    },
  ],
  connections: [
    { id: "desert", label: "Wüste", relation: "Manna", detail: "In der Wüste wird Brot zur täglichen Gabe mitten im Mangel." },
    { id: "fire", label: "Feuer", relation: "Backen und Verwandlung", detail: "Im Feuer wird aus dem Gewachsenen eine neue Gestalt, die Nahrung werden kann." },
    { id: "water", label: "Wasser", relation: "Wachstum", detail: "Wasser trägt das verborgene Wachstum des Korns und macht Nahrung möglich." },
    { id: "light", label: "Licht", relation: "Reifung und Offenbarung", detail: "Im Licht reift das Korn. Im geteilten Brot kann zugleich Verborgenes sichtbar werden." },
    { id: "word", label: "Wort", relation: "Innere Nahrung", detail: "Der Mensch lebt nicht vom Brot allein, sondern auch von dem Wort, das Leben ausrichtet." },
    { id: "community", label: "Gemeinschaft", relation: "Brechen und Teilen", detail: "Brot wird im Brechen nicht weniger bedeutend, sondern zur geteilten Gabe." },
  ],
  states: [
    {
      id: "grain",
      navigationLabel: "Korn",
      eyebrow: "Markus 4,26-29",
      title: "Im Korn liegt verborgenes Leben.",
      text: "Brot beginnt unscheinbar. Wasser trägt das Wachstum, Licht lässt das Korn reifen, und lange bleibt verborgen, was einmal Nahrung werden kann.",
      inscription: "Korn / Wachstum / Verborgenheit",
      visual: {
        image: visualAssets.brotGrain,
        backgroundImage: visualAssets.brotDew,
        alt: "Nahaufnahme einer dunklen, organischen Struktur mit feinem Licht als Bild für verborgenes Korn",
        atmosphere: { id: "bread-grain", mood: "erwartend", motion: "keimend", light: "sanftes morgenlicht", density: 0.64 },
        veilOpacity: 0.7,
        imageOpacity: 0.72,
      },
      hebrewLetterIds: ["lamed"],
      hebrewCodexLetterIds: ["lamed"],
      hebrewMeaningFieldIds: ["lechem-life", "lechem-nourishment"],
      hebrewSummary: "Lamed richtet den Blick auf Lernen und Wachstum: Das Korn trägt Nahrung zunächst als verborgenes Werden.",
      biblicalSceneIds: ["mark-4-grain"],
      connectionIds: ["water", "light"],
      reflection: { kicker: "Innere Erfahrung", question: "Welches verborgene Leben braucht gerade Zeit zum Reifen?" },
    },
    {
      id: "manna",
      navigationLabel: "Manna",
      eyebrow: "Exodus 16,4",
      title: "In der Wüste wird Nahrung zur Gabe.",
      text: "Manna fällt nicht auf Vorrat, sondern für den heutigen Tag. Im Mangel wird sichtbar, dass Leben nicht allein aus eigener Verfügbarkeit getragen wird.",
      inscription: "Manna / Gabe / Vertrauen",
      visual: {
        image: visualAssets.brotManna,
        alt: "Dunkler weiter Raum mit feinen hellen Spuren als Bild für Manna in der Wüste",
        atmosphere: { id: "bread-manna", mood: "still", motion: "fallend", light: "feines gold", density: 0.56 },
        veilOpacity: 0.68,
        imageOpacity: 0.7,
      },
      hebrewLetterIds: ["mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["lechem-gift", "lechem-nourishment"],
      hebrewSummary: "Das finale Mem bewahrt die verborgene Innenseite der Gabe: Versorgung wird empfangen und nicht vollständig kontrolliert.",
      biblicalSceneIds: ["exodus-16-manna"],
      connectionIds: ["desert", "word"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche Gabe reicht für den heutigen Tag?" },
    },
    {
      id: "breaking",
      navigationLabel: "Brechen",
      eyebrow: "Lukas 24,30-31",
      title: "Im Brechen entsteht Gemeinschaft.",
      text: "Das Brot bleibt nicht unberührt auf dem Tisch. Es wird genommen, gebrochen und geteilt; gerade darin wird aus Nahrung eine gemeinsame Gabe.",
      inscription: "Brechen / Teilen / Gemeinschaft",
      visual: {
        image: visualAssets.brotPath,
        alt: "Warme Lichtspuren in einem dunklen Raum als Bild für geteiltes Brot am Tisch",
        atmosphere: { id: "bread-breaking", mood: "warm", motion: "teilend", light: "tischgold", density: 0.46 },
        veilOpacity: 0.6,
        imageOpacity: 0.66,
      },
      hebrewLetterIds: ["chet"],
      hebrewCodexLetterIds: ["chet"],
      hebrewMeaningFieldIds: ["lechem-breaking", "lechem-community"],
      hebrewSummary: "Chet sammelt das Motiv des Lebens in der Mitte des Wortes: Brot wird im Teilen zum Zeichen von Gemeinschaft.",
      biblicalSceneIds: ["luke-24-breaking"],
      connectionIds: ["community", "light"],
      reflection: { kicker: "Innere Erfahrung", question: "Was wird tragender, wenn du es teilst?" },
    },
    {
      id: "bread-of-life",
      navigationLabel: "Brot des Lebens",
      eyebrow: "Johannes 6,35",
      title: "Nahrung reicht bis ins Innere.",
      text: "Christus spricht vom Brot des Lebens. Das einfache Brot bleibt alltägliche Nahrung und öffnet zugleich einen tieferen Raum: Leben wird empfangen, geteilt und vom Wort getragen.",
      inscription: "Christus / Leben / Wort",
      visual: {
        image: visualAssets.brotHero,
        alt: "Warmer heller Lichtschein in einem tiefen Raum als Bild für das Brot des Lebens",
        atmosphere: { id: "bread-of-life", mood: "gesammelt", motion: "öffnend", light: "warmes gold", density: 0.38 },
        veilOpacity: 0.54,
        imageOpacity: 0.68,
      },
      hebrewLetterIds: ["lamed", "chet", "mem"],
      hebrewCodexLetterIds: ["lamed", "chet", "mem"],
      hebrewMeaningFieldIds: ["lechem-life", "lechem-word", "lechem-community"],
      hebrewSummary: "Lamed, Chet und Mem verbinden Wachstum, Leben und verborgene Gabe. Lechem wird zum Zeichen einer Nahrung, die den ganzen Menschen meint.",
      biblicalSceneIds: ["john-6-life"],
      connectionIds: ["word", "community"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche Nahrung stärkt nicht nur deinen Alltag, sondern auch dein Inneres?" },
    },
  ],
};
