import type { OntologyEntity, OntologyRelation, OntologyRelationType } from "./types";

type Phase36AEntityInput = {
  id: string;
  title: string;
  hebrew: string;
  transliteration: string;
  gematria: number;
  summary: string;
  tags: string[];
  clusterId: string;
  domain?: OntologyEntity["domain"];
  aliases?: string[];
};

const uniqueAliases = (values: string[]) => {
  const seen = new Set<string>();

  return values.filter((value) => {
    const normalized = value.toLocaleLowerCase("de");

    if (seen.has(normalized)) return false;
    seen.add(normalized);

    return true;
  });
};

const entity = ({
  id,
  title,
  hebrew,
  transliteration,
  gematria,
  summary,
  tags,
  clusterId,
  domain = "word",
  aliases = [],
}: Phase36AEntityInput): OntologyEntity => ({
  id,
  type: "hebrew_word",
  title,
  hebrew,
  transliteration,
  gematria,
  summary,
  domain,
  aliases: uniqueAliases([title, transliteration, hebrew, ...aliases]),
  archetypalRole: summary,
  clusterId,
  tags: ["hebrew", "phase-36a", ...tags],
});

const relation = (
  sourceId: string,
  targetId: string,
  type: OntologyRelationType,
  title: string,
  shortResonance: string,
  explanation: string,
  strength: number,
  hebrewAnchors: string[] = [],
  scriptureAnchors: string[] = [],
): OntologyRelation => ({
  id: `phase36a-${sourceId}-${type}-${targetId}`,
  sourceId,
  targetId,
  type,
  title,
  shortResonance,
  explanation,
  strength,
  hebrewAnchors,
  scriptureAnchors,
});

export const phase36AOntologyEntities: OntologyEntity[] = [
  entity({
    id: "bara",
    title: "Bara",
    hebrew: "\u05d1\u05e8\u05d0",
    transliteration: "bara",
    gematria: 203,
    summary: "Bara verdichtet Schoepfung als wirksames Hervorrufen von Wirklichkeit.",
    tags: ["schoepfung", "wort", "anfang", "licht"],
    clusterId: "cluster-schoepfung-anfang",
  }),
  entity({
    id: "schamajim",
    title: "Schamajim",
    hebrew: "\u05e9\u05de\u05d9\u05dd",
    transliteration: "schamajim",
    gematria: 390,
    summary: "Schamajim oeffnet den oberen Schoepfungsraum von Himmel, Wassertrennung und Licht.",
    tags: ["schoepfung", "wasser", "licht", "himmel"],
    clusterId: "cluster-schoepfung-anfang",
    aliases: ["Himmel"],
  }),
  entity({
    id: "erez",
    title: "Erez",
    hebrew: "\u05d0\u05e8\u05e5",
    transliteration: "erez",
    gematria: 291,
    summary: "Erez ist Erde und Land: Boden, Bewohnbarkeit und Verheissungsraum.",
    tags: ["schoepfung", "erde", "land", "brot"],
    clusterId: "cluster-schoepfung-anfang",
    aliases: ["Erde", "Land"],
  }),
  entity({
    id: "adam",
    title: "Adam",
    hebrew: "\u05d0\u05d3\u05dd",
    transliteration: "adam",
    gematria: 45,
    summary: "Adam zeigt den Menschen als Erdgestalt, Atemwesen und Antwortenden.",
    tags: ["schoepfung", "mensch", "atem", "erde"],
    clusterId: "cluster-schoepfung-anfang",
    aliases: ["Mensch"],
  }),
  entity({
    id: "chava",
    title: "Chava",
    hebrew: "\u05d7\u05d5\u05d4",
    transliteration: "chava",
    gematria: 19,
    summary: "Chava traegt Leben, Geburt und Beziehung im Anfangsraum.",
    tags: ["schoepfung", "leben", "geburt", "gemeinschaft"],
    clusterId: "cluster-schoepfung-anfang",
    aliases: ["Eva", "Leben"],
  }),
  entity({
    id: "gan",
    title: "Gan",
    hebrew: "\u05d2\u05df",
    transliteration: "gan",
    gematria: 53,
    summary: "Gan ist Garten als geschuetzter Lebensraum, Fuelle und Gegenwart.",
    tags: ["schoepfung", "garten", "leben", "brot"],
    clusterId: "cluster-schoepfung-anfang",
    aliases: ["Garten"],
  }),
  entity({
    id: "nahar",
    title: "Nahar",
    hebrew: "\u05e0\u05d4\u05e8",
    transliteration: "nahar",
    gematria: 255,
    summary: "Nahar fuehrt Wasser als Strom, Richtung und Bewaesserung in den Garten.",
    tags: ["wasser", "fluss", "garten", "leben"],
    clusterId: "cluster-wasser-ursprung",
    aliases: ["Fluss"],
  }),
  entity({
    id: "mikwe",
    title: "Mikwe",
    hebrew: "\u05de\u05e7\u05d5\u05d4",
    transliteration: "mikwe",
    gematria: 151,
    summary: "Mikwe sammelt Wasser zu einem Raum von Ordnung, Reinigung und Neuwerden.",
    tags: ["wasser", "reinigung", "geburt", "ritual"],
    clusterId: "cluster-wasser-ursprung",
    domain: "ritual",
    aliases: ["Reinigungsbad"],
  }),
  entity({
    id: "jordan",
    title: "Jordan",
    hebrew: "\u05d9\u05e8\u05d3\u05df",
    transliteration: "jarden",
    gematria: 264,
    summary: "Jordan ist Wassergrenze, Taufraum und Schwelle ins Land.",
    tags: ["wasser", "taufe", "uebergang", "land"],
    clusterId: "cluster-wasser-ursprung",
    domain: "place",
    aliases: ["Jarden"],
  }),
  entity({
    id: "jam",
    title: "Jam",
    hebrew: "\u05d9\u05dd",
    transliteration: "jam",
    gematria: 50,
    summary: "Jam zeigt Meer als Tiefe, Grenze, Chaos und moeglichen Durchgang.",
    tags: ["wasser", "meer", "tiefe", "uebergang"],
    clusterId: "cluster-wasser-ursprung",
    aliases: ["Meer"],
  }),
  entity({
    id: "panim",
    title: "Panim",
    hebrew: "\u05e4\u05e0\u05d9\u05dd",
    transliteration: "panim",
    gematria: 180,
    summary: "Panim verbindet Licht mit Angesicht, Gegenwart und zugewandter Offenbarung.",
    tags: ["licht", "angesicht", "gegenwart", "offenbarung"],
    clusterId: "cluster-licht-offenbarung",
    aliases: ["Angesicht"],
  }),
  entity({
    id: "kavod",
    title: "Kavod",
    hebrew: "\u05db\u05d1\u05d5\u05d3",
    transliteration: "kavod",
    gematria: 32,
    summary: "Kavod ist Herrlichkeit als Gewicht, Glanz und spuerbare Gegenwart.",
    tags: ["licht", "feuer", "herrlichkeit", "gegenwart"],
    clusterId: "cluster-licht-offenbarung",
    aliases: ["Herrlichkeit", "Gewicht"],
  }),
  entity({
    id: "chokma",
    title: "Chokma",
    hebrew: "\u05d7\u05db\u05de\u05d4",
    transliteration: "chokma",
    gematria: 73,
    summary: "Chokma ist Weisheit als Schoepfungsordnung, Einsicht und Wegwissen.",
    tags: ["licht", "weisheit", "erkenntnis", "schoepfung"],
    clusterId: "cluster-licht-offenbarung",
    aliases: ["Weisheit"],
  }),
  entity({
    id: "bina",
    title: "Bina",
    hebrew: "\u05d1\u05d9\u05e0\u05d4",
    transliteration: "bina",
    gematria: 67,
    summary: "Bina ist Verstehen als unterscheidendes Hoeren und geordnete Einsicht.",
    tags: ["licht", "verstehen", "hoeren", "wort"],
    clusterId: "cluster-licht-offenbarung",
    aliases: ["Verstehen", "Einsicht"],
  }),
  entity({
    id: "mizbeach",
    title: "Mizbeach",
    hebrew: "\u05de\u05d6\u05d1\u05d7",
    transliteration: "mizbeach",
    gematria: 57,
    summary: "Mizbeach ist Altar als Ort von Feuer, Gabe und Begegnung.",
    tags: ["feuer", "altar", "gabe", "opfer"],
    clusterId: "cluster-feuer-offenbarung",
    domain: "ritual",
    aliases: ["Altar"],
  }),
  entity({
    id: "korban",
    title: "Korban",
    hebrew: "\u05e7\u05e8\u05d1\u05df",
    transliteration: "korban",
    gematria: 352,
    summary: "Korban ist Gabe als Herantreten, Naehe und verwandelte Beziehung.",
    tags: ["feuer", "gabe", "naehe", "opfer"],
    clusterId: "cluster-feuer-offenbarung",
    domain: "ritual",
    aliases: ["Opfergabe", "Nahgabe"],
  }),
  entity({
    id: "derech",
    title: "Derech",
    hebrew: "\u05d3\u05e8\u05da",
    transliteration: "derech",
    gematria: 224,
    summary: "Derech ist Weg, Richtung und Pruefungsraum durch die Wueste.",
    tags: ["wueste", "weg", "pruefung", "orientierung"],
    clusterId: "cluster-wueste-pruefung",
    aliases: ["Weg"],
  }),
  entity({
    id: "nes",
    title: "Nes",
    hebrew: "\u05e0\u05e1",
    transliteration: "nes",
    gematria: 110,
    summary: "Nes ist Zeichen und Banner, das im offenen Raum Orientierung sammelt.",
    tags: ["wueste", "zeichen", "orientierung", "vertrauen"],
    clusterId: "cluster-wueste-pruefung",
    aliases: ["Zeichen", "Banner"],
  }),
  entity({
    id: "sinai",
    title: "Sinai",
    hebrew: "\u05e1\u05d9\u05e0\u05d9",
    transliteration: "sinai",
    gematria: 130,
    summary: "Sinai verdichtet Wueste, Feuer, Stimme und Offenbarung zum Bundesraum.",
    tags: ["wueste", "feuer", "stimme", "offenbarung"],
    clusterId: "cluster-wueste-pruefung",
    domain: "place",
  }),
  entity({
    id: "dagan",
    title: "Dagan",
    hebrew: "\u05d3\u05d2\u05df",
    transliteration: "dagan",
    gematria: 57,
    summary: "Dagan ist Korn als verborgenes Lebenspotential, Ernte und Nahrung.",
    tags: ["brot", "korn", "erde", "nahrung"],
    clusterId: "cluster-brot-nahrung",
    aliases: ["Korn"],
  }),
  entity({
    id: "shever",
    title: "Shever",
    hebrew: "\u05e9\u05d1\u05e8",
    transliteration: "shever",
    gematria: 502,
    summary: "Shever verbindet Bruch, Hunger, Getreide und die Wendung zur Versorgung.",
    tags: ["brot", "bruch", "mangel", "versorgung"],
    clusterId: "cluster-brot-nahrung",
    aliases: ["Bruch", "Getreidekauf"],
  }),
  entity({
    id: "seudah",
    title: "Seudah",
    hebrew: "\u05e1\u05e2\u05d5\u05d3\u05d4",
    transliteration: "seudah",
    gematria: 145,
    summary: "Seudah ist Mahl als geteilte Gabe, Staerkung und Tischgemeinschaft.",
    tags: ["brot", "mahl", "gemeinschaft", "gabe"],
    clusterId: "cluster-brot-nahrung",
    aliases: ["Mahl"],
  }),
  entity({
    id: "noach",
    title: "Noach",
    hebrew: "\u05e0\u05d7",
    transliteration: "noach",
    gematria: 58,
    summary: "Noach traegt Ruhe, Bewahrung durch Wasser und Neubeginn nach der Flut.",
    tags: ["wasser", "noah", "flut", "bund"],
    clusterId: "cluster-wasser-ursprung",
    aliases: ["Noah", "Ruhe"],
  }),
  entity({
    id: "tahor",
    title: "Tahor",
    hebrew: "\u05d8\u05d4\u05d5\u05e8",
    transliteration: "tahor",
    gematria: 220,
    summary: "Tahor benennt Reinheit als geklaerte Ordnung, Rueckkehr und Licht.",
    tags: ["wasser", "feuer", "licht", "reinigung"],
    clusterId: "cluster-wasser-ursprung",
    aliases: ["rein"],
  }),
];

export const phase36AOntologyRelations: OntologyRelation[] = [
  relation("bara", "tehom", "emerges_from", "Bara ruft aus der Tiefe", "Schoepfung hebt aus verborgener Tiefe an.", "Bara steht als wirksames Hervorrufen gegenueber Tehom, dem noch ungeformten Anfangsraum.", 0.9, ["\u05d1\u05e8\u05d0", "\u05ea\u05d4\u05d5\u05dd"], ["genesis-1-1", "genesis-1-2"]),
  relation("bara", "or", "reveals", "Bara oeffnet Licht", "Schaffen fuehrt in Sichtbarkeit.", "Das Schoepfungswort fuehrt vom verborgenen Anfang zur ersten Unterscheidung des Lichts.", 0.91, ["\u05d1\u05e8\u05d0", "\u05d0\u05d5\u05e8"], ["genesis-1-3"]),
  relation("bara", "davar", "expressed_through", "Bara geschieht als Davar", "Schaffen und Wort klingen zusammen.", "Im Anfang erscheint Schoepfung nicht als stumme Materie, sondern als wirksames Wortgeschehen.", 0.88, ["\u05d1\u05e8\u05d0", "\u05d3\u05d1\u05e8"]),
  relation("bara", "schamajim", "gives_rise_to", "Bara bringt Schamajim hervor", "Himmel wird als Schoepfungsraum lesbar.", "Der Himmel gehoert zum ersten Bogen der geschaffenen Welt.", 0.84, ["\u05d1\u05e8\u05d0", "\u05e9\u05de\u05d9\u05dd"], ["genesis-1-1"]),
  relation("schamajim", "majim", "resonates_with", "Schamajim klingt mit Majim", "Himmel und Wasser beruehren sich im Anfang.", "Schamajim traegt im Klang die Wasserspur und steht in Genesis im Raum der Wassertrennung.", 0.9, ["\u05e9\u05de\u05d9\u05dd", "\u05de\u05d9\u05dd"], ["genesis-1-8"]),
  relation("schamajim", "or", "opens_into", "Himmel oeffnet Lichtzeichen", "Der obere Raum wird zum Ort der Orientierung.", "Im Himmel erscheinen Licht, Zeichen und Zeiten als geordnete Orientierung.", 0.82, ["\u05e9\u05de\u05d9\u05dd", "\u05d0\u05d5\u05e8"]),
  relation("schamajim", "ruach", "resonates_with", "Schamajim und Ruach", "Der Himmel ist Raum von Atem, Wind und Weite.", "Ruach bewegt im Anfang ueber den Wassern; Schamajim weitet diesen Bewegungsraum nach oben.", 0.78, ["\u05e9\u05de\u05d9\u05dd", "\u05e8\u05d5\u05d7"]),
  relation("schamajim", "erez", "contrasts_with", "Himmel und Erde", "Schamajim steht Erez als oberer Raum gegenueber.", "Himmel und Erde bilden die erste umfassende Polaritaet des Schoepfungsraums.", 0.89, ["\u05e9\u05de\u05d9\u05dd", "\u05d0\u05e8\u05e5"], ["genesis-1-1"]),
  relation("erez", "schamajim", "contrasts_with", "Erde unter dem Himmel", "Erez macht den unteren Raum bewohnbar.", "Erez steht nicht isoliert, sondern im Bogen mit Schamajim als sichtbarer Lebensboden.", 0.84, ["\u05d0\u05e8\u05e5", "\u05e9\u05de\u05d9\u05dd"]),
  relation("erez", "adam", "gives_rise_to", "Erez traegt Adam", "Der Mensch ist Erdling und Atemwesen.", "Adam wird aus Erde geformt und bleibt an den Boden der geschaffenen Welt gebunden.", 0.87, ["\u05d0\u05e8\u05e5", "\u05d0\u05d3\u05dd"]),
  relation("erez", "dagan", "nourishes", "Erez bringt Dagan", "Korn waechst aus Erde und Gabe.", "Dagan bindet Brot an Erde, Regen, Licht und verborgenes Wachstum.", 0.86, ["\u05d0\u05e8\u05e5", "\u05d3\u05d2\u05df"]),
  relation("erez", "midbar", "contrasts_with", "Land und Wueste", "Erez steht im Gegenueber zur Wueste.", "Das Land ist bewonbarer Boden; Midbar zeigt Entzug, Weg und Pruefung.", 0.78, ["\u05d0\u05e8\u05e5", "\u05de\u05d3\u05d1\u05e8"]),
  relation("adam", "erez", "emerges_from", "Adam aus Erde", "Der Mensch kommt aus dem Boden.", "Adam ist nicht losgeloeste Geistigkeit, sondern geformtes Leben aus Erde und Atem.", 0.9, ["\u05d0\u05d3\u05dd", "\u05d0\u05e8\u05e5"]),
  relation("adam", "ruach", "resonates_with", "Adam empfaengt Atem", "Menschsein wird durch Atem lebendig.", "Ruach verbindet die Erdgestalt mit unsichtbarer Lebenskraft.", 0.86, ["\u05d0\u05d3\u05dd", "\u05e8\u05d5\u05d7"]),
  relation("adam", "chava", "resonates_with", "Adam und Chava", "Menschsein wird Beziehung.", "Adam und Chava bilden im Anfangsraum eine Beziehung, in der Leben weitergegeben wird.", 0.82, ["\u05d0\u05d3\u05dd", "\u05d7\u05d5\u05d4"]),
  relation("adam", "gan", "belongs_to", "Adam im Gan", "Der Mensch wird in den Garten gestellt.", "Gan ist der erste Raum von Auftrag, Grenze, Fuelle und Gegenwart fuer Adam.", 0.8, ["\u05d0\u05d3\u05dd", "\u05d2\u05df"]),
  relation("chava", "adam", "resonates_with", "Chava klingt mit Adam", "Leben erscheint in Beziehung.", "Chava ist nicht Nebenmotiv, sondern verdichtet Leben, Geburt und Antwort im menschlichen Anfang.", 0.82, ["\u05d7\u05d5\u05d4", "\u05d0\u05d3\u05dd"]),
  relation("chava", "gan", "belongs_to", "Chava im Garten", "Leben steht im Raum von Fuelle und Grenze.", "Der Garten ist der Ort, an dem Leben, Beziehung und Verantwortung zugleich sichtbar werden.", 0.78, ["\u05d7\u05d5\u05d4", "\u05d2\u05df"]),
  relation("chava", "majim", "resonates_with", "Chava und Wassergeburt", "Leben beruehrt das Wasserfeld der Geburt.", "Chava traegt das Lebensmotiv, das im Wasser als Geburt und Neuwerden mitschwingt.", 0.74, ["\u05d7\u05d5\u05d4", "\u05de\u05d9\u05dd"]),
  relation("chava", "lechem", "nourishes", "Leben braucht Brot", "Geburt fuehrt in Nahrung und Gemeinschaft.", "Chava verbindet lebendigen Anfang mit der spaeteren Brotspur von Nahrung und Tisch.", 0.72, ["\u05d7\u05d5\u05d4", "\u05dc\u05d7\u05dd"]),
  relation("gan", "nahar", "nourishes", "Der Fluss bewaessert den Garten", "Gan lebt aus Nahar.", "Der Garten ist kein isolierter Ort; ein Strom gibt ihm Bewegung und Versorgung.", 0.9, ["\u05d2\u05df", "\u05e0\u05d4\u05e8"], ["genesis-2-10"]),
  relation("gan", "adam", "opens_into", "Gan oeffnet Adam den Auftrag", "Der Garten wird Lebens- und Verantwortungsraum.", "Im Gan wird Adam in Arbeit, Bewahrung und Grenze gestellt.", 0.82, ["\u05d2\u05df", "\u05d0\u05d3\u05dd"]),
  relation("gan", "chava", "resonates_with", "Gan und Chava", "Der Garten traegt Lebensfuelle.", "Chava und Gan verdichten Leben als Geburt, Beziehung und bewohnbare Fuelle.", 0.78, ["\u05d2\u05df", "\u05d7\u05d5\u05d4"]),
  relation("gan", "dagan", "gives_rise_to", "Garten und Korn", "Fuelle wird zu Nahrung.", "Der Gartenraum bereitet die Brotspur vor, in der verborgenes Wachstum Nahrung wird.", 0.74, ["\u05d2\u05df", "\u05d3\u05d2\u05df"]),
  relation("nahar", "gan", "nourishes", "Nahar naehert Gan", "Der Strom macht den Garten fruchtbar.", "Nahar zeigt Wasser nicht nur als Tiefe, sondern als gerichteten Lebensstrom.", 0.9, ["\u05e0\u05d4\u05e8", "\u05d2\u05df"]),
  relation("nahar", "majim", "is_expression_of", "Nahar ist bewegtes Wasser", "Der Fluss ist Majim in Richtung.", "Nahar macht aus dem Wasserfeld eine Weg- und Lebensbewegung.", 0.88, ["\u05e0\u05d4\u05e8", "\u05de\u05d9\u05dd"]),
  relation("nahar", "jordan", "resonates_with", "Nahar klingt im Jordan", "Der Strom wird zur Schwelle.", "Jordan ist ein konkreter Fluss, in dem Nahar als Grenze und Uebergang erzaehlt wird.", 0.84, ["\u05e0\u05d4\u05e8", "\u05d9\u05e8\u05d3\u05df"]),
  relation("nahar", "dagan", "nourishes", "Fluss naehert Korn", "Wasser fuehrt zur Brotspur.", "Ohne Wasser bleibt Dagan verborgen; Nahar verbindet Wasser mit Nahrung.", 0.8, ["\u05e0\u05d4\u05e8", "\u05d3\u05d2\u05df"]),
  relation("mikwe", "majim", "belongs_to", "Mikwe sammelt Majim", "Wasser wird Ort und Ordnung.", "Mikwe ist nicht nur Wasser, sondern gesammeltes Wasser mit reinigender Schwellenkraft.", 0.9, ["\u05de\u05e7\u05d5\u05d4", "\u05de\u05d9\u05dd"]),
  relation("mikwe", "tahor", "opens_into", "Mikwe oeffnet Tahor", "Eintauchen fuehrt in Klaerung.", "Die Mikwe macht Reinheit als Rueckkehr und Neuordnung leiblich erfahrbar.", 0.92, ["\u05de\u05e7\u05d5\u05d4", "\u05d8\u05d4\u05d5\u05e8"]),
  relation("mikwe", "jordan", "resonates_with", "Mikwe und Jordan", "Reinigung wird zur Flussschwelle.", "Der Jordan traegt die Taufspur; Mikwe gibt ihr die rituelle Wasserresonanz.", 0.86, ["\u05de\u05e7\u05d5\u05d4", "\u05d9\u05e8\u05d3\u05df"]),
  relation("mikwe", "tehom", "echoes_within", "Mikwe erinnert Tehom", "Jedes Eintauchen beruehrt Tiefe.", "Der reinigende Wasserraum bewahrt ein Echo der Anfangstiefe und des Neuwerdens.", 0.8, ["\u05de\u05e7\u05d5\u05d4", "\u05ea\u05d4\u05d5\u05dd"]),
  relation("jordan", "majim", "is_expression_of", "Jordan ist Schwellenwasser", "Majim wird am Jordan zum Durchgang.", "Der Jordan verdichtet Wasser als Grenze, Reinigung und Neubeginn.", 0.9, ["\u05d9\u05e8\u05d3\u05df", "\u05de\u05d9\u05dd"]),
  relation("jordan", "mikwe", "resonates_with", "Jordan klingt mit Mikwe", "Fluss und Reinigungsbad teilen die Schwelle.", "Beide Wasserraeume tragen Reinigen, Eintauchen und Heraustreten.", 0.84, ["\u05d9\u05e8\u05d3\u05df", "\u05de\u05e7\u05d5\u05d4"]),
  relation("jordan", "derech", "is_threshold_to", "Jordan ist Schwelle des Weges", "Der Weg geht durch Wasser ins Land.", "Am Jordan wird Derech zur Uebergangsbewegung zwischen Wueste und Land.", 0.88, ["\u05d9\u05e8\u05d3\u05df", "\u05d3\u05e8\u05da"]),
  relation("jordan", "noach", "resonates_with", "Jordan und Noah", "Wasser fuehrt durch Gericht und Neubeginn.", "Noach und Jordan teilen die Wasserlogik von Bewahrung, Schwelle und neuer Ordnung.", 0.76, ["\u05d9\u05e8\u05d3\u05df", "\u05e0\u05d7"]),
  relation("jam", "majim", "belongs_to", "Jam gehoert zu Majim", "Meer ist Weite des Wassers.", "Jam zeigt Majim als Grenze, Tiefe und unkontrollierbare Macht.", 0.9, ["\u05d9\u05dd", "\u05de\u05d9\u05dd"]),
  relation("jam", "tehom", "resonates_with", "Jam klingt mit Tehom", "Meer und Tiefe beruehren das Chaosfeld.", "Jam traegt im Erzaehlraum die dunkle Tiefe, die Tehom am Anfang bezeichnet.", 0.88, ["\u05d9\u05dd", "\u05ea\u05d4\u05d5\u05dd"]),
  relation("jam", "jordan", "contrasts_with", "Meer und Jordan", "Wasser wird einmal Weite, einmal Schwelle.", "Jam ist die grosse Grenze; Jordan ist der konkrete Durchgang ins Land.", 0.78, ["\u05d9\u05dd", "\u05d9\u05e8\u05d3\u05df"]),
  relation("jam", "noach", "echoes_within", "Jam hallt in Noahs Wasser", "Wasser kann bewahren und bedrohen.", "Die Fluterzaehlung laesst das Meermotiv von Tiefe, Gericht und Neubeginn nachklingen.", 0.76, ["\u05d9\u05dd", "\u05e0\u05d7"]),
  relation("panim", "or", "reveals", "Panim leuchtet", "Das Angesicht macht Licht persoenlich.", "Panim fuehrt Or aus blosser Helligkeit in zugewandte Gegenwart.", 0.9, ["\u05e4\u05e0\u05d9\u05dd", "\u05d0\u05d5\u05e8"]),
  relation("panim", "kavod", "resonates_with", "Panim und Kavod", "Angesicht und Herrlichkeit teilen Gegenwart.", "Kavod gibt Panim Gewicht und Glanz; Panim gibt Kavod Zuwendung.", 0.86, ["\u05e4\u05e0\u05d9\u05dd", "\u05db\u05d1\u05d5\u05d3"]),
  relation("panim", "ruach", "resonates_with", "Panim und Ruach", "Gegenwart wird Atem und Angesicht.", "Ruach ist unsichtbare Bewegung; Panim ist zugewandte Sichtbarkeit.", 0.78, ["\u05e4\u05e0\u05d9\u05dd", "\u05e8\u05d5\u05d7"]),
  relation("panim", "qol", "opens_into", "Panim antwortet Qol", "Stimme sucht Angesicht.", "Der gehoerte Ruf zielt auf Begegnung, nicht nur auf Information.", 0.76, ["\u05e4\u05e0\u05d9\u05dd", "\u05e7\u05d5\u05dc"]),
  relation("kavod", "or", "is_expression_of", "Kavod glaenzt als Licht", "Herrlichkeit wird sichtbar.", "Kavod macht Licht gewichtig: Glanz als spuerbare Gegenwart.", 0.9, ["\u05db\u05d1\u05d5\u05d3", "\u05d0\u05d5\u05e8"]),
  relation("kavod", "esch", "resonates_with", "Kavod und Feuer", "Herrlichkeit erscheint als brennende Gegenwart.", "Am Sinai und im Heiligtum verbindet sich Kavod mit Feuer, Wolke und Furcht.", 0.88, ["\u05db\u05d1\u05d5\u05d3", "\u05d0\u05e9"]),
  relation("kavod", "panim", "reveals", "Kavod sucht Angesicht", "Glanz wird Beziehung.", "Herrlichkeit bleibt nicht abstrakt, sondern wird als zugewandte Gegenwart lesbar.", 0.78, ["\u05db\u05d1\u05d5\u05d3", "\u05e4\u05e0\u05d9\u05dd"]),
  relation("kavod", "sinai", "appears_in_story", "Kavod am Sinai", "Herrlichkeit steht im Feuerraum des Bundes.", "Am Sinai verdichtet sich Kavod mit Wolke, Feuer und Stimme.", 0.9, ["\u05db\u05d1\u05d5\u05d3", "\u05e1\u05d9\u05e0\u05d9"], ["exodus-24"]),
  relation("chokma", "or", "opens_into", "Chokma oeffnet Licht", "Weisheit macht Wege sichtbar.", "Chokma verbindet Erkenntnis mit Licht, das nicht blendet, sondern ordnet.", 0.84, ["\u05d7\u05db\u05de\u05d4", "\u05d0\u05d5\u05e8"]),
  relation("chokma", "bina", "resonates_with", "Weisheit und Verstehen", "Chokma braucht Bina.", "Weisheit wird tragfaehig, wenn sie in unterscheidendes Verstehen eintritt.", 0.88, ["\u05d7\u05db\u05de\u05d4", "\u05d1\u05d9\u05e0\u05d4"]),
  relation("chokma", "bara", "resonates_with", "Schoepfung in Weisheit", "Die Welt wird als weise Ordnung lesbar.", "Chokma klingt mit Bara, weil Schoepfung im Codex als geordnete Wirklichkeit erscheint.", 0.82, ["\u05d7\u05db\u05de\u05d4", "\u05d1\u05e8\u05d0"]),
  relation("chokma", "davar", "expressed_through", "Chokma spricht Davar", "Weisheit wird Wort fuer den Weg.", "Weisheit bleibt nicht Idee, sondern wird als Weisung, Wort und Orientierung hoerbar.", 0.78, ["\u05d7\u05db\u05de\u05d4", "\u05d3\u05d1\u05e8"]),
  relation("bina", "chokma", "resonates_with", "Bina empfaengt Chokma", "Verstehen ordnet Weisheit.", "Bina gibt der Weisheit unterscheidende Form und praktische Lesbarkeit.", 0.86, ["\u05d1\u05d9\u05e0\u05d4", "\u05d7\u05db\u05de\u05d4"]),
  relation("bina", "qol", "opens_into", "Bina hoert Qol", "Verstehen beginnt im Hoeren.", "Qol wird erst durch empfangendes Verstehen zur Orientierung.", 0.8, ["\u05d1\u05d9\u05e0\u05d4", "\u05e7\u05d5\u05dc"]),
  relation("bina", "davar", "reveals", "Bina deutet Davar", "Das Wort wird verstanden.", "Bina macht Davar nicht nur hoerbar, sondern einsichtig und geordnet.", 0.82, ["\u05d1\u05d9\u05e0\u05d4", "\u05d3\u05d1\u05e8"]),
  relation("bina", "derech", "structures_journey", "Bina ordnet Derech", "Verstehen gibt dem Weg Richtung.", "Auf dem Weg durch die Wueste braucht Orientierung ein verstehendes Herz.", 0.76, ["\u05d1\u05d9\u05e0\u05d4", "\u05d3\u05e8\u05da"]),
  relation("mizbeach", "esch", "belongs_to", "Mizbeach traegt Feuer", "Der Altar ist Feuerort der Gabe.", "Am Mizbeach wird Feuer kultisch geordnet und zur Schwelle von Gabe und Gegenwart.", 0.9, ["\u05de\u05d6\u05d1\u05d7", "\u05d0\u05e9"]),
  relation("mizbeach", "korban", "opens_into", "Altar oeffnet Korban", "Die Gabe findet ihren Ort.", "Korban wird am Mizbeach zur sichtbaren Bewegung des Herantretens.", 0.88, ["\u05de\u05d6\u05d1\u05d7", "\u05e7\u05e8\u05d1\u05df"]),
  relation("mizbeach", "kavod", "is_threshold_to", "Altar als Schwelle zu Kavod", "Gabe oeffnet Gegenwart.", "Der Altar markiert einen Ort, an dem Feuer, Gabe und Herrlichkeit einander beruehren.", 0.8, ["\u05de\u05d6\u05d1\u05d7", "\u05db\u05d1\u05d5\u05d3"]),
  relation("mizbeach", "sinai", "appears_in_story", "Mizbeach am Sinai", "Bund und Gabe werden geerdet.", "Am Sinai gehoeren Offenbarung, Altar und Bundesantwort zusammen.", 0.78, ["\u05de\u05d6\u05d1\u05d7", "\u05e1\u05d9\u05e0\u05d9"]),
  relation("korban", "mizbeach", "belongs_to", "Korban gehoert zum Mizbeach", "Die Gabe sucht den Feuerort.", "Korban ist Gabe in Bewegung; Mizbeach ist der Ort ihrer kultischen Verdichtung.", 0.88, ["\u05e7\u05e8\u05d1\u05df", "\u05de\u05d6\u05d1\u05d7"]),
  relation("korban", "esch", "transforms_into", "Korban geht durchs Feuer", "Gabe wird verwandelt.", "Im Feuer wird die Gabe nicht bloss vernichtet, sondern als Naehe- und Hingabegeste lesbar.", 0.84, ["\u05e7\u05e8\u05d1\u05df", "\u05d0\u05e9"]),
  relation("korban", "lechem", "resonates_with", "Korban und Brot", "Gabe und Nahrung beruehren sich.", "Brot kann Gabe sein; Korban macht diese Gabe zur bewussten Naehebewegung.", 0.76, ["\u05e7\u05e8\u05d1\u05df", "\u05dc\u05d7\u05dd"]),
  relation("korban", "panim", "opens_into", "Korban sucht Panim", "Gabe zielt auf Angesicht.", "Die Opfergabe ist im Codex nicht Besitzverlust, sondern Herantreten vor das Angesicht.", 0.74, ["\u05e7\u05e8\u05d1\u05df", "\u05e4\u05e0\u05d9\u05dd"]),
  relation("derech", "midbar", "passes_through", "Derech geht durch Midbar", "Der Weg wird in der Wueste geformt.", "Midbar ist kein Umweg, sondern der Raum, in dem Derech Pruefung und Vertrauen lernt.", 0.92, ["\u05d3\u05e8\u05da", "\u05de\u05d3\u05d1\u05e8"]),
  relation("derech", "sinai", "opens_into", "Derech fuehrt zum Sinai", "Der Weg fuehrt zur Offenbarung.", "Die Wuestenroute findet am Sinai eine Verdichtung in Wort, Stimme und Bund.", 0.88, ["\u05d3\u05e8\u05da", "\u05e1\u05d9\u05e0\u05d9"]),
  relation("derech", "jordan", "is_threshold_to", "Derech erreicht Jordan", "Der Weg endet nicht vor dem Wasser.", "Jordan wird zur Schwelle, an der der Wuestenweg in Land und Auftrag uebergeht.", 0.86, ["\u05d3\u05e8\u05da", "\u05d9\u05e8\u05d3\u05df"]),
  relation("derech", "nes", "resonates_with", "Derech braucht Nes", "Der Weg braucht Zeichen.", "Nes sammelt Orientierung, wo Derech durch offenen Raum fuehrt.", 0.8, ["\u05d3\u05e8\u05da", "\u05e0\u05e1"]),
  relation("nes", "derech", "structures_journey", "Nes ordnet den Weg", "Das Zeichen gibt Richtung.", "Im offenen Raum wird Nes zum sichtbaren Marker fuer Vertrauen und Bewegung.", 0.82, ["\u05e0\u05e1", "\u05d3\u05e8\u05da"]),
  relation("nes", "midbar", "appears_in_story", "Nes in der Wueste", "Das Banner steht im Pruefungsraum.", "Die Wueste braucht Zeichen, die nicht besitzen, sondern ausrichten.", 0.78, ["\u05e0\u05e1", "\u05de\u05d3\u05d1\u05e8"]),
  relation("nes", "or", "reveals", "Nes macht sichtbar", "Das Zeichen faengt Licht fuer den Weg.", "Ein Zeichen wird nur hilfreich, wenn es Wahrnehmung sammelt und Richtung zeigt.", 0.74, ["\u05e0\u05e1", "\u05d0\u05d5\u05e8"]),
  relation("nes", "mizbeach", "resonates_with", "Nes und Altar", "Zeichen und Gabe stehen im Bund.", "Exodus 17 verbindet Bannername und Altar: Orientierung wird zur Antwort.", 0.72, ["\u05e0\u05e1", "\u05de\u05d6\u05d1\u05d7"]),
  relation("sinai", "midbar", "belongs_to", "Sinai steht im Midbar", "Offenbarung geschieht in der Wueste.", "Sinai zeigt, dass der leere Raum zum Ort der Stimme und des Bundes werden kann.", 0.92, ["\u05e1\u05d9\u05e0\u05d9", "\u05de\u05d3\u05d1\u05e8"]),
  relation("sinai", "esch", "reveals", "Sinai brennt", "Feuer macht Offenbarung sichtbar.", "Am Sinai erscheinen Feuer, Wolke und Stimme als verdichtete Gegenwart.", 0.9, ["\u05e1\u05d9\u05e0\u05d9", "\u05d0\u05e9"]),
  relation("sinai", "qol", "opens_into", "Sinai laesst Qol hoeren", "Die Stimme wird im Bergraum hoerbar.", "Sinai ist nicht nur Ort, sondern Resonanzkoerper der Stimme.", 0.86, ["\u05e1\u05d9\u05e0\u05d9", "\u05e7\u05d5\u05dc"]),
  relation("sinai", "kavod", "reveals", "Sinai offenbart Kavod", "Herrlichkeit erscheint in Wolke und Feuer.", "Kavod bekommt am Sinai Gewicht, Licht und Furcht.", 0.88, ["\u05e1\u05d9\u05e0\u05d9", "\u05db\u05d1\u05d5\u05d3"]),
  relation("dagan", "lechem", "gives_rise_to", "Dagan wird Lechem", "Korn wird Brot.", "Dagan ist die verborgene Vorform, aus der Brot als Nahrung hervorgeht.", 0.9, ["\u05d3\u05d2\u05df", "\u05dc\u05d7\u05dd"]),
  relation("dagan", "manna", "contrasts_with", "Korn und Manna", "Einmal waechst Nahrung, einmal faellt sie als Gabe.", "Dagan bindet Brot an Erde und Wachstum; Manna zeigt Versorgung ohne Besitzsicherheit.", 0.84, ["\u05d3\u05d2\u05df", "\u05de\u05df"]),
  relation("dagan", "erez", "emerges_from", "Dagan aus Erez", "Korn gehoert zur Erde.", "Das Korn macht die Erde als tragenden Nahrungsraum sichtbar.", 0.82, ["\u05d3\u05d2\u05df", "\u05d0\u05e8\u05e5"]),
  relation("dagan", "nahar", "resonates_with", "Dagan braucht Nahar", "Korn braucht Wasser.", "Die Brotspur bleibt mit der Wasserbewegung verbunden: Wachstum braucht Strom und Regen.", 0.78, ["\u05d3\u05d2\u05df", "\u05e0\u05d4\u05e8"]),
  relation("shever", "lechem", "resonates_with", "Shever und Brot", "Bruch fuehrt zur Nahrung.", "Shever laesst das Brot nicht als glatte Fuelle, sondern als Gabe im Mangel lesen.", 0.84, ["\u05e9\u05d1\u05e8", "\u05dc\u05d7\u05dd"]),
  relation("shever", "dagan", "resonates_with", "Shever sucht Dagan", "Hunger sucht Korn.", "In der Josefgeschichte wird Getreide im Mangel zur Spur von Rettung und Versoehnung.", 0.82, ["\u05e9\u05d1\u05e8", "\u05d3\u05d2\u05df"]),
  relation("shever", "seudah", "opens_into", "Bruch wird Mahl", "Aus Mangel kann Tischgemeinschaft werden.", "Shever oeffnet die Brotspur zur Seudah, wenn Bruch in geteilte Gabe verwandelt wird.", 0.78, ["\u05e9\u05d1\u05e8", "\u05e1\u05e2\u05d5\u05d3\u05d4"]),
  relation("shever", "midbar", "resonates_with", "Shever und Midbar", "Bruch und Wueste teilen Mangel.", "Beide Raeume entziehen Sicherheit und koennen dadurch Empfang sichtbar machen.", 0.74, ["\u05e9\u05d1\u05e8", "\u05de\u05d3\u05d1\u05e8"]),
  relation("seudah", "lechem", "belongs_to", "Seudah teilt Lechem", "Brot wird Mahl.", "Im Mahl wird Brot nicht nur Nahrung, sondern Beziehung und gemeinsamer Empfang.", 0.88, ["\u05e1\u05e2\u05d5\u05d3\u05d4", "\u05dc\u05d7\u05dd"]),
  relation("seudah", "shever", "transforms_into", "Seudah verwandelt Bruch", "Gemeinschaft antwortet auf Mangel.", "Das Mahl kann den Bruch nicht leugnen, aber in Teilen und Staerkung wandeln.", 0.78, ["\u05e1\u05e2\u05d5\u05d3\u05d4", "\u05e9\u05d1\u05e8"]),
  relation("seudah", "korban", "resonates_with", "Mahl und Gabe", "Tisch und Altar beruehren sich.", "Seudah und Korban verbinden Essen, Gabe und Naehe in unterschiedlicher Gestalt.", 0.76, ["\u05e1\u05e2\u05d5\u05d3\u05d4", "\u05e7\u05e8\u05d1\u05df"]),
  relation("seudah", "chava", "nourishes", "Seudah naehert Leben", "Das Mahl staerkt lebendige Gemeinschaft.", "Chava traegt Leben; Seudah macht dieses Leben am Tisch geteilt und gestaerkt.", 0.72, ["\u05e1\u05e2\u05d5\u05d3\u05d4", "\u05d7\u05d5\u05d4"]),
  relation("manna", "lechem", "is_expression_of", "Manna ist Brot als Gabe", "Brot faellt im Mangel vom Himmel.", "Manna zeigt Lechem als empfangene Versorgung ohne Vorratssicherheit.", 0.94, ["\u05de\u05df", "\u05dc\u05d7\u05dd"], ["exodus-16"]),
  relation("manna", "midbar", "appears_in_story", "Manna in der Wueste", "Im Mangel wird Gabe sichtbar.", "Midbar macht Manna lesbar: Nahrung wird gerade dort Gabe, wo Besitz nicht traegt.", 0.92, ["\u05de\u05df", "\u05de\u05d3\u05d1\u05e8"], ["exodus-16"]),
  relation("manna", "dagan", "contrasts_with", "Manna und Dagan", "Himmelsgabe und Kornspur stehen nebeneinander.", "Dagan waechst aus Erde; Manna erscheint im Entzug als taegliche Gabe.", 0.82, ["\u05de\u05df", "\u05d3\u05d2\u05df"]),
  relation("manna", "majim", "resonates_with", "Manna und Tau", "Brot beruehrt Wasser.", "Die Mannaspur ist mit Tau und Morgen verbunden und haelt Wasser im Brotpfad wach.", 0.76, ["\u05de\u05df", "\u05de\u05d9\u05dd"]),
  relation("noach", "majim", "passes_through", "Noach geht durch Wasser", "Wasser wird Gericht und Bewahrung.", "Noach zeigt, dass Majim nicht nur Reinigung, sondern auch bedrohliche Schwelle sein kann.", 0.88, ["\u05e0\u05d7", "\u05de\u05d9\u05dd"]),
  relation("noach", "jam", "resonates_with", "Noach und Jam", "Flut und Meer teilen Tiefe.", "Die Flut laesst das Meermotiv von Chaos, Grenze und Neubeginn mitschwingen.", 0.82, ["\u05e0\u05d7", "\u05d9\u05dd"]),
  relation("noach", "tahor", "opens_into", "Noach oeffnet Reinheit", "Nach den Wassern entsteht neue Ordnung.", "Die Fluterzaehlung fuehrt von Verderben durch Wasser in einen geordneten Neuanfang.", 0.78, ["\u05e0\u05d7", "\u05d8\u05d4\u05d5\u05e8"]),
  relation("noach", "nes", "resonates_with", "Noach und Zeichen", "Der Bund braucht ein sichtbares Zeichen.", "Nach der Flut wird Bewahrung durch ein Zeichen erinnert und ausgerichtet.", 0.74, ["\u05e0\u05d7", "\u05e0\u05e1"]),
  relation("tahor", "mikwe", "emerges_from", "Tahor aus der Mikwe", "Reinheit steigt aus dem Wasserraum.", "Mikwe macht Tahor als leiblichen Uebergang von Unordnung zu Klaerung erfahrbar.", 0.9, ["\u05d8\u05d4\u05d5\u05e8", "\u05de\u05e7\u05d5\u05d4"]),
  relation("tahor", "majim", "resonates_with", "Tahor klingt mit Majim", "Reinigung bleibt an Wasser gebunden.", "Majim traegt die Reinigungsspur, in der Tahor als geordnete Rueckkehr erscheint.", 0.86, ["\u05d8\u05d4\u05d5\u05e8", "\u05de\u05d9\u05dd"]),
  relation("tahor", "or", "reveals", "Reinheit wird licht", "Klaerung fuehrt zu Sichtbarkeit.", "Tahor kann als lichte Ordnung gelesen werden: was geklaert ist, kann erscheinen.", 0.78, ["\u05d8\u05d4\u05d5\u05e8", "\u05d0\u05d5\u05e8"]),
  relation("tahor", "esch", "resonates_with", "Tahor und Feuer", "Reinigung kann auch durch Laeuterung gehen.", "Feuer und Wasser tragen verschiedene Wege der Klaerung und Rueckkehr.", 0.76, ["\u05d8\u05d4\u05d5\u05e8", "\u05d0\u05e9"]),
];
