import type {
  OntologyEntity,
  OntologyNeighbor,
  OntologyRegistry,
  OntologyRelation,
  OntologyRelationType,
} from "./types";
import { phase36AOntologyEntities, phase36AOntologyRelations } from "./phase36AHebrewResonance";

export const ONTOLOGY_RELATION_LABELS: Record<OntologyRelationType, string> = {
  belongs_to: "Gehört zu",
  resonates_with: "Klingt mit",
  emerges_from: "Entsteht aus",
  transforms_into: "Wandelt sich zu",
  opposes: "Steht in Spannung zu",
  fulfills: "Erfüllt",
  reveals: "Macht sichtbar",
  opens_into: "Öffnet Raum",
  source_of: "Ist Ursprung von",
  gives_rise_to: "Bringt hervor",
  echoes_within: "Hallt nach in",
  precedes: "Bereitet vor",
  expressed_through: "Drückt sich aus durch",
  is_expression_of: "Ist Ausdruck von",
  is_threshold_to: "Öffnet Schwelle zu",
  contrasts_with: "Steht im Gegenüber zu",
  contains_pattern: "Trägt Muster",
  fulfills_pattern_of: "Erfüllt Muster",
  has_polarity: "Trägt Spannung",
  structures_journey: "Ordnet Bewegung",
  passes_through: "Geht hindurch durch",
  nourishes: "Nährt",
  tests: "Prüft",
  shares_letter: "Teilt Buchstaben",
  shares_number: "Teilt Zahl",
  appears_in_story: "Erscheint in",
};

const ONTOLOGY_RELATION_MARKER_LABELS: Record<OntologyRelationType, string> = {
  is_expression_of: "Ausdruck",
  is_threshold_to: "Schwelle",
  opens_into: "Schwelle",
  source_of: "Ursprung",
  gives_rise_to: "Ursprung",
  echoes_within: "Resonanz",
  precedes: "Vorbereitung",
  expressed_through: "Hebräisch",
  contrasts_with: "Spannung",
  contains_pattern: "Muster",
  fulfills_pattern_of: "Muster",
  has_polarity: "Spannung",
  structures_journey: "Bewegung",
  passes_through: "Durchgang",
  emerges_from: "Herkunft",
  transforms_into: "Wandlung",
  reveals: "Offenbarung",
  nourishes: "Nahrung",
  tests: "Prüfung",
  shares_letter: "Hebräisch",
  shares_number: "Zahl",
  appears_in_story: "Biblischer Anker",
  belongs_to: "Zugehörigkeit",
  resonates_with: "Resonanz",
  opposes: "Spannung",
  fulfills: "Erfüllung",
};

const ONTOLOGY_RELATION_PRIORITY: Partial<Record<OntologyRelationType, number>> = {
  opens_into: 1,
  reveals: 2,
  is_threshold_to: 3,
  is_expression_of: 4,
  contains_pattern: 5,
  contrasts_with: 6,
  emerges_from: 7,
  structures_journey: 8,
  shares_letter: 9,
  shares_number: 10,
  appears_in_story: 11,
  passes_through: 12,
  resonates_with: 13,
  belongs_to: 14,
};

const CANONICAL_ONTOLOGY_ENTITY_IDS: Record<string, string> = {
  wasser: "majim",
  licht: "or",
  feuer: "esch",
  esh: "esch",
  wueste: "midbar",
  brot: "lechem",
  tiefe: "tehom",
  geist: "ruach",
  wind: "ruach",
  atem: "ruach",
  wort: "davar",
  stimme: "qol",
};

function canonicalOntologyEntityId(id: string) {
  return CANONICAL_ONTOLOGY_ENTITY_IDS[id] ?? id;
}

export const ontologyEntities: OntologyEntity[] = [
  {
    id: "quelle",
    type: "symbol",
    title: "Quelle",
    summary: "Die Quelle zeigt Wasser als Ursprung, Hervortreten und erste Gabe.",
    primaryHierarchyId: "quelle",
    domain: "place",
    archetypalRole: "Ursprung, Hervortreten und Gabe des Anfangs",
    aliases: ["Quelle", "Ursprung", "Wasserquelle"],
    imageSymbol: "dunkle Quelle mit feiner Lichtachse",
    clusterId: "cluster-wasser-ursprung",
    tags: ["wasser", "ursprung", "quelle", "anfang"],
  },
  {
    id: "brunnen",
    type: "symbol",
    title: "Brunnen",
    primaryHierarchyId: "brunnen",
    tags: ["wasser", "unterraum", "tiefe", "begegnung"],
    summary: "Brunnen bindet Wasser an verborgene Tiefe, Schöpfen und Begegnung.",
    aliases: ["Brunnen", "Quelle in der Tiefe", "Wasserstelle"],
    archetypalRole: "Zugang zur Tiefe und Ort der Begegnung",
    domain: "place",
    imageSymbol: "tiefer Brunnen im Halbdunkel mit Licht über dem Wasser",
    polarity: {
      axis: "Tiefe und Begegnung",
      visiblePole: "Wasserstelle",
      hiddenPole: "verborgene Tiefe",
      note: "Der Brunnen macht das Verborgene erreichbar und wird zum Ort der Begegnung.",
    },
    clusterId: "cluster-wasser-ursprung",
  },
  {
    id: "meer",
    type: "symbol",
    title: "Meer",
    summary: "Das Meer zeigt Wasser als Grenze, Tiefe, Chaos und Durchgang.",
    primaryHierarchyId: "meer",
    domain: "element",
    archetypalRole: "Grenze, Tiefe, Gefahr und Übergang",
    aliases: ["Meer", "See", "Wasserweite", "Tiefe"],
    imageSymbol: "weite dunkle Wasserfläche mit fernem Licht",
    polarity: {
      axis: "Chaos und Durchgang",
      visiblePole: "Gefahr und Grenze",
      hiddenPole: "Weg in Freiheit",
      note: "Das Meer erscheint als bedrohliche Tiefe und zugleich als Schwelle zu neuem Leben.",
    },
    clusterId: "cluster-wasser-ursprung",
    tags: ["wasser", "meer", "tiefe", "grenze", "durchgang"],
  },
  {
    id: "fluss",
    type: "symbol",
    title: "Fluss",
    summary: "Der Fluss zeigt Wasser als Bewegung, Richtung und lebendigen Strom.",
    primaryHierarchyId: "fluss",
    domain: "element",
    archetypalRole: "Bewegung, Richtung und lebendiger Strom",
    aliases: ["Fluss", "Strom", "Wasserlauf"],
    imageSymbol: "dunkler Strom mit leuchtender Bewegung",
    clusterId: "cluster-wasser-ursprung",
    tags: ["wasser", "fluss", "bewegung", "leben", "strom"],
  },
  {
    id: "manna",
    type: "symbol",
    title: "Manna",
    primaryHierarchyId: "manna",
    tags: ["brot", "wueste", "wasser", "gabe", "versorgung"],
    summary: "Manna liest Brot als tägliche Gabe im Raum der Wüste: Im Mangel wird Empfang sichtbar.",
    hebrew: "מן",
    transliteration: "man",
    gematria: 90,
    aliases: ["Manna", "Man", "מן", "Himmelsbrot"],
    archetypalRole: "Gabe im Mangel, tägliche Nahrung und Vertrauen",
    domain: "word",
    imageSymbol: "helle Körner auf Tau in dunkler Wüste",
    firstMention: {
      ref: "Exodus 16",
      role: "Manna erscheint als Gabe im Mangel der Wüste.",
    },
    polarity: {
      axis: "Mangel und Gabe",
      visiblePole: "Nahrung",
      hiddenPole: "Vertrauen",
      note: "Manna nährt nur im täglichen Empfangen; im Zahlkörper 90 berührt es die Wasserspur von majim.",
    },
    clusterId: "cluster-wueste-pruefung",
  },
  {
    id: "leere",
    type: "concept",
    title: "Leere",
    summary: "Die Leere ist der Raum des Entzugs, in dem Hören und Prüfung möglich werden.",
    primaryHierarchyId: "leere",
    domain: "concept",
    archetypalRole: "Entzug, Offenheit und Vorbereitung des Hörens",
    aliases: ["Leere", "Entzug", "Raum ohne Sicherheiten"],
    imageSymbol: "weite dunkle Fläche mit fernem Lichtpunkt",
    polarity: {
      axis: "Entzug und Offenheit",
      visiblePole: "Mangel",
      hiddenPole: "Bereitschaft",
      note: "Die Leere nimmt Fülle weg, damit Empfang möglich wird.",
    },
    clusterId: "cluster-wueste-pruefung",
    tags: ["wueste", "leere", "entzug", "hoeren"],
  },
  {
    id: "dornbusch",
    type: "symbol",
    title: "Dornbusch",
    primaryHierarchyId: "dornbusch",
    tags: ["feuer", "wueste", "ruf", "offenbarung"],
    summary: "Dornbusch verbindet Feuer, Stimme und Gegenwart ohne Verzehrung.",
    aliases: ["Dornbusch", "brennender Dornbusch", "סנה"],
    archetypalRole: "Ort der Offenbarung, an dem Feuer nicht verzehrt",
    domain: "place",
    imageSymbol: "brennender Dornbusch in dunkler Wüste",
    firstMention: {
      ref: "Exodus 3:2",
      role: "Der Dornbusch brennt und wird doch nicht verzehrt.",
    },
    polarity: {
      axis: "Brennen und Nicht-Verzehren",
      visiblePole: "Feuer",
      hiddenPole: "Gegenwart ohne Vernichtung",
      note: "Der Dornbusch zeigt Feuer als Offenbarung, nicht als blosse Zerstörung.",
    },
    clusterId: "cluster-feuer-offenbarung",
  },
  {
    id: "flamme",
    type: "symbol",
    title: "Flamme",
    summary: "Die Flamme zeigt Feuer als sichtbare Bewegung, Nähe und aufsteigende Gegenwart.",
    primaryHierarchyId: "flamme",
    domain: "element",
    archetypalRole: "sichtbare Bewegung des Feuers und Zeichen der Gegenwart",
    aliases: ["Flamme", "Feuerzunge", "brennendes Licht"],
    imageSymbol: "schmale goldene Flamme in dunklem Raum",
    clusterId: "cluster-feuer-offenbarung",
    tags: ["feuer", "flamme", "licht", "bewegung"],
  },
  {
    id: "glut",
    type: "symbol",
    title: "Glut",
    summary: "Die Glut zeigt Feuer als verborgene Wärme und innere Wandlungskraft.",
    primaryHierarchyId: "glut",
    domain: "element",
    archetypalRole: "verborgenes Feuer, Wärme und Wandlung im Inneren",
    aliases: ["Glut", "Kohle", "verborgenes Feuer"],
    imageSymbol: "dunkle Glut mit rotem Kernlicht",
    clusterId: "cluster-feuer-offenbarung",
    tags: ["feuer", "glut", "innenraum", "wandlung"],
  },
  {
    id: "altar",
    type: "symbol",
    title: "Altarfeuer",
    summary: "Das Altarfeuer zeigt Feuer als Hingabe, Annäherung und geordnete Schwelle.",
    primaryHierarchyId: "altar",
    domain: "ritual",
    archetypalRole: "Hingabe, Annäherung und rituelle Schwelle",
    aliases: ["Altarfeuer", "Altar", "Feuer der Hingabe"],
    imageSymbol: "ruhiges Feuer auf einem dunklen Altarstein",
    clusterId: "cluster-feuer-offenbarung",
    tags: ["feuer", "altar", "ritual", "hingabe"],
  },
  {
    id: "laeuterung",
    type: "concept",
    title: "Läuterung",
    summary: "Läuterung zeigt Feuer als innere Klärung, Prüfung und Verwandlung.",
    primaryHierarchyId: "laeuterung",
    domain: "concept",
    archetypalRole: "Klärung, Prüfung und Verwandlung durch Feuer",
    aliases: ["Läuterung", "Reinigung durch Feuer", "Klärung"],
    imageSymbol: "helles Feuer, das dunkles Metall klärt",
    polarity: {
      axis: "Schmerz und Klärung",
      visiblePole: "Brennen",
      hiddenPole: "Reinigung",
      note: "Läuterung ist Feuer als Verwandlung, nicht als blosse Vernichtung.",
    },
    clusterId: "cluster-feuer-offenbarung",
    tags: ["feuer", "laeuterung", "pruefung", "wandlung"],
  },
  {
    id: "weg",
    type: "symbol",
    title: "Weg",
    primaryHierarchyId: "weg",
    tags: ["wueste", "bewegung", "pruefung", "erzaehlung"],
    summary: "Weg macht Bewegung durch das Unbekannte als Prüfung und Erzählung sichtbar.",
    aliases: ["Weg", "Pfad", "Gang", "Reise"],
    archetypalRole: "Bewegung durch Prüfung zur Verwandlung",
    domain: "threshold",
    imageSymbol: "schmaler Pfad durch dunkle Weite",
    polarity: {
      axis: "Aufbruch und Prüfung",
      visiblePole: "Bewegung",
      hiddenPole: "Verwandlung",
      note: "Der Weg ist nicht nur Strecke, sondern innere Reifung.",
    },
    clusterId: "cluster-wueste-pruefung",
  },
  {
    id: "majim",
    type: "archetype",
    title: "Wasser",
    primaryHierarchyId: "wasser",
    tags: ["archetyp", "tiefe", "leben", "reinigung"],
    summary: "Wasser trägt Tiefe, Leben, Reinigung, Grenze und Übergang.",
    hebrew: "מים",
    transliteration: "majim",
    gematria: 90,
    aliases: ["Wasser", "Majim", "מים"],
    archetypalRole: "Ursprung, Tiefe, Reinigung und Schwelle",
    domain: "element",
    imageSymbol: "dunkles Wasser mit warmer Lichtachse",
    visibleHidden: {
      visible: "Wasser als Element",
      hidden: "Ursprung, Tiefe und Übergang",
    },
    firstMention: {
      ref: "Genesis 1:2",
      role: "Wasser erscheint als Tiefe unter dem Geist.",
    },
    polarity: {
      axis: "Tiefe und Reinigung",
      visiblePole: "Reinigung",
      hiddenPole: "Chaos, Ursprung und Mutterleib",
      note: "Wasser trägt zugleich Geborgenheit, Gefahr und neues Werden.",
    },
    clusterId: "cluster-wasser-ursprung",
  },
  {
    id: "midbar",
    type: "archetype",
    title: "Wüste",
    primaryHierarchyId: "wueste",
    tags: ["archetyp", "mangel", "pruefung", "hoeren"],
    summary: "Wüste ist der Bedeutungsraum von Reduktion, Mangel, Stille und Prüfung; als midbar wird sie zum Ort, an dem das Wort hörbar wird.",
    hebrew: "מדבר",
    transliteration: "midbar",
    gematria: 246,
    aliases: ["Wüste", "Midbar", "מדבר", "Wildnis"],
    archetypalRole: "Entzug, Prüfung, Weg und Ort der Stimme",
    domain: "place",
    imageSymbol: "weite dunkle Leere mit fernem Licht",
    visibleHidden: {
      visible: "Leere",
      hidden: "Ort der Stimme",
    },
    firstMention: {
      ref: "Exodus",
      role: "Die Wüste wird zum Raum der Prüfung, Führung und Offenbarung.",
    },
    polarity: {
      axis: "Leere und Stimme",
      visiblePole: "Mangel und Entzug",
      hiddenPole: "Führung und Offenbarung",
      note: "Die Wüste nimmt Sicherheiten, damit das Hören entstehen kann: Midbar ist nicht nur Leere, sondern Raum des Wortes.",
    },
    clusterId: "cluster-wueste-pruefung",
  },
  {
    id: "lechem",
    type: "archetype",
    title: "Brot",
    primaryHierarchyId: "brot",
    tags: ["archetyp", "nahrung", "gabe", "gemeinschaft"],
    summary: "Brot deutet Nahrung, Gabe, Alltag, Teilung und Gemeinschaft.",
    hebrew: "לחם",
    transliteration: "lechem",
    gematria: 78,
    aliases: ["Brot", "Lechem", "לחם", "Nahrung"],
    archetypalRole: "Nahrung, Gabe, Teilung und Wort",
    domain: "ritual",
    imageSymbol: "einfaches Brot im warmen Licht",
    polarity: {
      axis: "Mangel und Gabe",
      visiblePole: "Nahrung",
      hiddenPole: "Abhängigkeit und Vertrauen",
      note: "Brot zeigt Leben als empfangene Gabe.",
    },
    clusterId: "cluster-brot-nahrung",
  },
  {
    id: "esch",
    type: "archetype",
    title: "Feuer",
    primaryHierarchyId: "feuer",
    tags: ["archetyp", "gegenwart", "ruf", "wandlung"],
    summary: "Feuer sammelt Gegenwart, Ruf, Führung, Läuterung und Verwandlung.",
    hebrew: "אש",
    transliteration: "esch",
    gematria: 301,
    aliases: ["Feuer", "Esch", "אש", "Flamme"],
    archetypalRole: "Gegenwart, Läuterung und verzehrende Nähe",
    domain: "element",
    imageSymbol: "ruhiges goldenes Feuer in dunkler Tiefe",
    visibleHidden: {
      visible: "Brennen",
      hidden: "Offenbarung und Läuterung",
    },
    polarity: {
      axis: "Gegenwart und Verzehrung",
      visiblePole: "Licht und Wärme",
      hiddenPole: "Gericht und Läuterung",
      note: "Feuer ist Nähe, die offenbart und verwandelt.",
    },
    clusterId: "cluster-feuer-offenbarung",
  },
  {
    id: "or",
    type: "archetype",
    title: "Licht",
    primaryHierarchyId: "licht",
    tags: ["archetyp", "offenbarung", "orientierung", "klarheit"],
    summary: "Licht macht Klarheit, Offenbarung, Orientierung und Schöpfungsanfang lesbar.",
    hebrew: "אור",
    transliteration: "or",
    gematria: 207,
    aliases: ["Licht", "Or", "אור"],
    archetypalRole: "Offenbarung, Bewusstsein und Orientierung",
    domain: "element",
    imageSymbol: "warme Lichtachse im dunklen Raum",
    firstMention: {
      ref: "Genesis 1:3",
      role: "Licht erscheint als erstes gesprochenes Werden.",
    },
    polarity: {
      axis: "Offenbarung und Verborgenheit",
      visiblePole: "Erkenntnis",
      hiddenPole: "Ursprung im Unsichtbaren",
      note: "Licht macht sichtbar, kommt aber selbst aus dem verborgenen Wort.",
    },
    clusterId: "cluster-genesis-1",
  },
  {
    id: "ursprung",
    type: "concept",
    title: "Ursprung",
    summary: "Ursprung bezeichnet den verborgenen Anfang, aus dem Bewegung, Leben und Bedeutung hervortreten.",
    domain: "concept",
    archetypalRole: "verborgener Anfang, Quelle und erstes Hervortreten",
    aliases: ["Ursprung", "Anfang", "Quelle", "Hervortreten"],
    imageSymbol: "dunkler Anfangspunkt, aus dem eine feine Lichtachse hervortritt",
    polarity: {
      axis: "Verborgenheit und Hervortreten",
      visiblePole: "Hervortreten",
      hiddenPole: "verborgener Anfang",
      note: "Der Ursprung ist nicht bloss Beginn, sondern das Unsichtbare, aus dem Sichtbares wird.",
    },
    clusterId: "cluster-wasser-ursprung",
    tags: ["ursprung", "anfang", "quelle", "wasser", "schoepfung"],
  },
  {
    id: "offenbarung",
    type: "concept",
    title: "Offenbarung",
    summary: "Offenbarung bezeichnet das Sichtbarwerden des Verborgenen durch Licht, Stimme, Feuer oder Wort.",
    domain: "divine",
    archetypalRole: "Sichtbarwerden des Verborgenen",
    aliases: ["Offenbarung", "Enthüllung", "Sichtbarwerden", "Erscheinen"],
    imageSymbol: "warme Lichtachse, die aus dunkler Tiefe hervortritt",
    polarity: {
      axis: "Verborgenheit und Sichtbarwerden",
      visiblePole: "Erscheinung",
      hiddenPole: "verborgene Gegenwart",
      note: "Offenbarung hebt das Verborgene nicht auf, sondern macht es erfahrbar.",
    },
    clusterId: "cluster-offenbarung",
    tags: ["offenbarung", "licht", "feuer", "stimme", "wort"],
  },
  {
    id: "ordnung",
    type: "concept",
    title: "Ordnung",
    summary: "Ordnung bezeichnet die sinnvolle Gestalt, die aus Trennung, Mass und Zuordnung entsteht.",
    domain: "concept",
    archetypalRole: "Gestalt, Mass und sinnvolle Zuordnung",
    aliases: ["Ordnung", "Mass", "Gestalt", "Struktur"],
    imageSymbol: "feine goldene Linien, die sich im dunklen Raum zu einer ruhigen Struktur fügen",
    polarity: {
      axis: "Chaos und Gestalt",
      visiblePole: "Gestalt",
      hiddenPole: "ungeformte Tiefe",
      note: "Ordnung entsteht nicht als Kontrolle, sondern als sinnvolle Unterscheidung.",
    },
    clusterId: "cluster-genesis-1",
    tags: ["ordnung", "gestalt", "mass", "trennung", "schoepfung"],
  },
  {
    id: "erkenntnis",
    type: "concept",
    title: "Erkenntnis",
    summary: "Erkenntnis bezeichnet ein Sehen, das nicht nur äußere Form wahrnimmt, sondern Bedeutung erkennt.",
    domain: "concept",
    archetypalRole: "inneres Sehen und bedeutendes Wahrnehmen",
    aliases: ["Erkenntnis", "Sehen", "Einsicht", "Wahrnehmung"],
    imageSymbol: "ruhiges Auge, in dem sich eine warme Lichtspur spiegelt",
    polarity: {
      axis: "Sehen und Verstehen",
      visiblePole: "Wahrnehmung",
      hiddenPole: "Bedeutung",
      note: "Erkenntnis entsteht, wenn das Sichtbare als Träger von Sinn wahrgenommen wird.",
    },
    clusterId: "cluster-genesis-1",
    tags: ["erkenntnis", "sehen", "auge", "licht", "wahrnehmung"],
  },
  {
    id: "raah",
    type: "hebrew_word",
    title: "Raah",
    primaryHierarchyId: "auge",
    tags: ["raah", "sehen", "licht", "erkenntnis", "offenbarung", "genesis"],
    summary: "Raah bezeichnet Sehen als Wahrnehmung, in der Licht nicht nur erscheint, sondern erkannt wird.",
    hebrew: "\u05e8\u05d0\u05d4",
    transliteration: "raah",
    aliases: ["Raah", "\u05e8\u05d0\u05d4", "sehen", "sah", "wahrnehmen"],
    archetypalRole: "Sehen als Schwelle zwischen Licht und Erkenntnis",
    domain: "word",
    firstMention: {
      ref: "Genesis 1:4",
      role: "Gott sieht das Licht.",
    },
    clusterId: "cluster-genesis-1",
  },
  {
    id: "tov",
    type: "hebrew_word",
    title: "Tov",
    tags: ["tov", "gut", "guete", "licht", "ordnung", "leben", "genesis"],
    summary: "Tov bezeichnet das Gute als stimmige, lebensfaehige und erkannte Qualitaet der geschaffenen Ordnung.",
    hebrew: "\u05d8\u05d5\u05d1",
    transliteration: "tov",
    gematria: 17,
    aliases: ["Tov", "\u05d8\u05d5\u05d1", "gut", "Guete", "lebensfaehig"],
    archetypalRole: "erkannte Guete und tragfaehige Ordnung",
    domain: "word",
    firstMention: {
      ref: "Genesis 1:4",
      role: "Das Licht wird als gut erkannt.",
    },
    clusterId: "cluster-genesis-1",
  },
  {
    id: "leben",
    type: "concept",
    title: "Leben",
    summary: "Leben bezeichnet Bewegung, Atem, Fruchtbarkeit und die Gabe des Daseins.",
    domain: "concept",
    archetypalRole: "Bewegung, Atem, Fruchtbarkeit und Gabe",
    aliases: ["Leben", "Lebendigkeit", "Atem", "Fruchtbarkeit"],
    imageSymbol: "feiner Strom von Licht und Wasser, der aus dunkler Tiefe hervortritt",
    polarity: {
      axis: "Empfang und Bewegung",
      visiblePole: "Lebendigkeit",
      hiddenPole: "empfangene Gabe",
      note: "Leben ist nicht Besitz, sondern empfangene Bewegung.",
    },
    clusterId: "cluster-wasser-ursprung",
    tags: ["leben", "wasser", "atem", "bewegung", "gabe"],
  },
  {
    id: "ruach",
    type: "hebrew_word",
    title: "Ruach",
    summary: "Ruach bezeichnet Geist, Wind und Atem: unsichtbare Bewegung zwischen Ursprung, Wasser, Wort, Stimme und Licht.",
    domain: "word",
    archetypalRole: "Atem- und Geistbrücke zwischen Tiefe und Offenbarung",
    hebrew: "\u05e8\u05d5\u05d7",
    transliteration: "ruach",
    gematria: 214,
    aliases: ["Ruach", "\u05e8\u05d5\u05d7", "Geist", "Wind", "Atem", "bewegte Gegenwart"],
    imageSymbol: "unsichtbare Bewegung über dunklem Wasser",
    polarity: {
      axis: "Unsichtbarkeit und Wirkung",
      visiblePole: "bewegte Wirkung",
      hiddenPole: "unsichtbare Gegenwart",
      note: "Ruach wird nicht als Objekt gesehen, sondern an Bewegung, Atem und Stimme erkannt.",
    },
    clusterId: "cluster-wasser-ursprung",
    tags: ["ruach", "geist", "wind", "atem", "bewegung", "gegenwart", "offenbarung", "leben", "wasser", "tehom"],
  },
  {
    id: "himmel",
    type: "concept",
    title: "Himmel",
    summary: "Himmel bezeichnet die obere Weite, den Raum der Zeichen, der Ordnung und der Herkunft des Lichts.",
    domain: "place",
    archetypalRole: "obere Weite, Zeichenraum und Herkunft des Lichts",
    aliases: ["Himmel", "Himmelsraum", "obere Weite", "Zeichenraum"],
    imageSymbol: "tiefer Nachthimmel mit wenigen ruhigen Lichtpunkten",
    polarity: {
      axis: "Oben und Unten",
      visiblePole: "Weite und Zeichen",
      hiddenPole: "verborgene Herkunft",
      note: "Der Himmel ist nicht nur Raum über der Erde, sondern ein Bedeutungsraum der Orientierung.",
    },
    clusterId: "cluster-genesis-1",
    tags: ["himmel", "licht", "stern", "zeichen", "ordnung"],
  },
  {
    id: "tau",
    type: "symbol",
    title: "Tau",
    primaryHierarchyId: "tau",
    tags: ["wasser", "himmel", "manna", "gabe"],
    summary: "Tau ist Wasser des Himmels und Schwelle, aus der Manna sichtbar wird.",
    hebrew: "טל",
    transliteration: "tal",
    gematria: 39,
    aliases: ["Tau", "Tal", "טל", "Morgentau"],
    archetypalRole: "feine Gabe des Morgens und Übergang zwischen Himmel und Erde",
    domain: "element",
    imageSymbol: "leuchtender Tau auf dunklem Grund",
    polarity: {
      axis: "Himmel und Erde",
      visiblePole: "Feuchtigkeit",
      hiddenPole: "leise Gabe von oben",
      note: "Tau erscheint ungreifbar und doch nährend.",
    },
    clusterId: "cluster-wasser-ursprung",
  },
  {
    id: "morgenlicht",
    type: "symbol",
    title: "Morgenlicht",
    summary: "Morgenlicht zeigt Licht als Beginn, Erwachen und erste Orientierung.",
    primaryHierarchyId: "morgenlicht",
    domain: "time",
    archetypalRole: "Erwachen, Beginn und erste Orientierung",
    aliases: ["Morgenlicht", "Morgen", "Frühes Licht"],
    imageSymbol: "erste warme Lichtachse in dunklem Blau",
    clusterId: "cluster-genesis-1",
    tags: ["licht", "morgen", "anfang", "orientierung"],
  },
  {
    id: "leuchte",
    type: "symbol",
    title: "Leuchte",
    summary: "Die Leuchte zeigt Licht als getragenes, geordnetes und weitergegebenes Licht.",
    primaryHierarchyId: "leuchte",
    domain: "ritual",
    archetypalRole: "getragenes Licht, Ordnung und Dienst",
    aliases: ["Leuchte", "Lampe", "Lichtträger"],
    imageSymbol: "kleine goldene Leuchte im dunklen Raum",
    clusterId: "cluster-genesis-1",
    tags: ["licht", "leuchte", "ordnung", "dienst"],
  },
  {
    id: "stern",
    type: "symbol",
    title: "Stern",
    summary: "Der Stern zeigt Licht als Orientierung in der Nacht und als Zeichen am Himmel.",
    primaryHierarchyId: "stern",
    domain: "element",
    archetypalRole: "Orientierung, Zeichen und himmlische Ordnung",
    aliases: ["Stern", "Himmelslicht", "Zeichen am Himmel"],
    imageSymbol: "ferner Stern im tiefen Nachtblau",
    clusterId: "cluster-genesis-1",
    tags: ["licht", "stern", "himmel", "orientierung"],
  },
  {
    id: "glanz",
    type: "concept",
    title: "Glanz",
    summary: "Glanz zeigt Licht als Ausstrahlung, Würde und sichtbare Gegenwart.",
    primaryHierarchyId: "glanz",
    domain: "concept",
    archetypalRole: "Ausstrahlung, Würde und sichtbare Gegenwart",
    aliases: ["Glanz", "Strahlen", "Herrlichkeit"],
    imageSymbol: "sanfter goldener Schimmer in dunkler Tiefe",
    clusterId: "cluster-genesis-1",
    tags: ["licht", "glanz", "herrlichkeit", "gegenwart"],
  },
  {
    id: "auge",
    type: "symbol",
    title: "Auge",
    summary: "Das Auge verbindet Licht mit Wahrnehmung, Erkenntnis und innerer Ausrichtung.",
    primaryHierarchyId: "auge",
    domain: "body",
    archetypalRole: "Wahrnehmung, Erkenntnis und innere Ausrichtung",
    aliases: ["Auge", "Sehen", "Blick"],
    imageSymbol: "ruhiges Auge als dunkle Spiegelung von Licht",
    clusterId: "cluster-genesis-1",
    tags: ["licht", "auge", "sehen", "erkenntnis"],
  },
  {
    id: "davar",
    type: "hebrew_word",
    title: "Davar",
    primaryHierarchyId: "wort",
    tags: ["davar", "wort", "sprache", "ruf", "offenbarung", "ordnung", "licht", "wueste"],
    summary: "Davar bezeichnet Wort, Sache, Ereignis und wirksame Wirklichkeit: das Wort, das aus der Tiefe Richtung hervorbringt.",
    hebrew: "\u05d3\u05d1\u05e8",
    transliteration: "davar",
    gematria: 206,
    aliases: ["Davar", "\u05d3\u05d1\u05e8", "Wort", "Sache", "Ereignis", "Wirklichkeit"],
    archetypalRole: "Wirksames Wort zwischen verborgener Tiefe und hörbarer Stimme",
    domain: "word",
    imageSymbol: "feine Wortlinie, die aus dunkler Tiefe in Stimme übergeht",
    polarity: {
      axis: "Verborgenes und ausgesprochenes Wort",
      visiblePole: "gesprochenes Wort",
      hiddenPole: "wirksame Wirklichkeit",
      note: "Davar ist nicht nur Information, sondern Wort, das Wirklichkeit ordnet und hervorruft.",
    },
    clusterId: "cluster-offenbarung",
  },
  {
    id: "stimme",
    type: "symbol",
    title: "Stimme",
    primaryHierarchyId: "stimme",
    tags: ["wueste", "wort", "ruf", "offenbarung"],
    summary: "Stimme macht das Wort im stillen Raum hörbar.",
    aliases: ["Stimme", "Ruf", "Sprechen", "Wort"],
    archetypalRole: "Ruf aus dem Verborgenen und Ursprung von Orientierung",
    domain: "divine",
    imageSymbol: "unsichtbare Stimme als Lichtwelle im dunklen Raum",
    polarity: {
      axis: "Schweigen und Ruf",
      visiblePole: "hörbares Wort",
      hiddenPole: "verborgener Ursprung",
      note: "Die Stimme kommt aus dem Unsichtbaren und ruft in eine Richtung.",
    },
    clusterId: "cluster-offenbarung",
  },
  {
    id: "qol",
    type: "hebrew_word",
    title: "Qol",
    primaryHierarchyId: "stimme",
    tags: ["qol", "stimme", "ruf", "hoeren", "offenbarung", "wueste", "wort", "licht"],
    summary: "Qol bezeichnet Stimme, Klang, Ruf und hörbare Gegenwart: das Wort, das im Raum des Hörens wahrnehmbar wird.",
    hebrew: "קול",
    transliteration: "qol",
    gematria: 136,
    aliases: ["Qol", "קול", "Stimme", "Klang", "Ruf", "hörbare Gegenwart"],
    archetypalRole: "Hörbar gewordenes Wort zwischen Verborgenheit und Offenbarung",
    domain: "word",
    imageSymbol: "unsichtbare Stimme als feine Lichtlinie in der Wüste",
    polarity: {
      axis: "Verborgenes Wort und hörbare Gegenwart",
      visiblePole: "Stimme",
      hiddenPole: "Wort vor dem Verstehen",
      note: "Qol macht nicht zuerst sichtbar, sondern hörbar: Offenbarung beginnt als Ruf.",
    },
    clusterId: "cluster-offenbarung",
  },
  {
    id: "pruefung",
    type: "symbol",
    title: "Prüfung",
    primaryHierarchyId: "pruefung",
    tags: ["wueste", "weg", "mensch", "innenraum"],
    summary: "Prüfung ist der Weg, auf dem das Innere sichtbar wird.",
    aliases: ["Prüfung", "Bewährung", "Test", "Erprobung"],
    archetypalRole: "Raum der Klärung, in dem Verborgenes sichtbar wird",
    domain: "concept",
    imageSymbol: "enge Schwelle zwischen Dunkelheit und Licht",
    polarity: {
      axis: "Entzug und Bewährung",
      visiblePole: "Mangel",
      hiddenPole: "Reifung",
      note: "Prüfung nimmt nicht nur weg, sondern macht die innere Gestalt sichtbar.",
    },
    clusterId: "cluster-wueste-pruefung",
  },
  {
    id: "tiefe",
    type: "concept",
    title: "Tiefe",
    tags: ["wasser", "verborgenheit", "anfang", "unterraum"],
    summary: "Tiefe bezeichnet den verborgenen Raum unter der Oberfläche, in dem Ursprung und Wandlung liegen.",
    aliases: ["Tiefe", "Urtiefe"],
    archetypalRole: "Verborgenes Anfangsfeld unter dem Sichtbaren",
    domain: "concept",
    imageSymbol: "dunkle Wassertiefe unter einer ruhigen Oberfläche",
    firstMention: {
      ref: "Genesis 1:2",
      role: "Die Tiefe erscheint als ungeformter Anfangsraum.",
    },
    polarity: {
      axis: "Verborgenheit und Ursprung",
      visiblePole: "Dunkelheit unter der Oberfläche",
      hiddenPole: "ungeformter Anfang",
      note: "Tiefe ist nicht Leere, sondern verborgene Möglichkeit.",
    },
    clusterId: "cluster-wasser-ursprung",
  },
  {
    id: "tehom",
    type: "hebrew_word",
    title: "Tehom",
    tags: ["tehom", "ursprung", "tiefe", "verborgenheit", "wasser", "geburt", "offenbarung", "wort", "licht"],
    summary:
      "Tehom bezeichnet die uranfängliche Tiefe vor Ordnung, Trennung und Licht: den verborgenen Raum des Ursprungs, aus dem Wort, Stimme und Licht hervorgehen.",
    hebrew: "\u05ea\u05d4\u05d5\u05dd",
    transliteration: "tehom",
    gematria: 451,
    aliases: ["Tehom", "Tiefe", "Urtiefe", "\u05ea\u05d4\u05d5\u05dd"],
    archetypalRole: "Ursprungsknoten der Tiefe vor Ordnung und Offenbarung",
    domain: "word",
    imageSymbol: "dunkle Tiefe vor der ersten Lichtlinie",
    firstMention: {
      ref: "Genesis 1:2",
      role: "Die Tiefe erscheint vor Ordnung, Trennung und Licht.",
    },
    movementSteps: [
      "Tiefe vor der Ordnung",
      "verborgener Ursprung",
      "Wort erhebt sich",
      "Stimme wird hörbar",
      "Licht tritt hervor",
    ],
    leadsTo: ["davar", "qol", "licht"],
    visibleHidden: {
      visible: "Finsternis über der Tiefe",
      hidden: "verborgener Ursprung der Offenbarung",
    },
    polarity: {
      axis: "Verborgenheit und Offenbarung",
      visiblePole: "Tiefe und Finsternis",
      hiddenPole: "Ursprung des Wortes",
      note: "Tehom ist nicht Chaos im modernen Sinn, sondern der verborgene Raum vor Licht und Ordnung.",
    },
    clusterId: "cluster-wasser-ursprung",
  },
  {
    id: "begegnung",
    type: "concept",
    title: "Begegnung",
    tags: ["brunnen", "weg", "ruf", "schwelle"],
    summary: "Begegnung beschreibt den Moment, in dem Wege, Mangel und Ruf an einer Schwelle zusammenkommen.",
    aliases: ["Begegnung", "Treffpunkt", "Zusammentreffen"],
    archetypalRole: "Schwellenmoment, in dem getrennte Wege Bedeutung gewinnen",
    domain: "concept",
    imageSymbol: "zwei Wege treffen sich an einer Wasserstelle",
    polarity: {
      axis: "Fremdheit und Erkennen",
      visiblePole: "Zusammentreffen",
      hiddenPole: "Ruf und Entscheidung",
      note: "Begegnung ist mehr als Kontakt: Sie kann Richtung und Berufung sichtbar machen.",
    },
    clusterId: "cluster-wasser-ursprung",
  },
  {
    id: "exodus-wilderness",
    type: "story_anchor",
    title: "Exodus 16",
    tags: ["exodus", "wueste", "manna", "versorgung"],
    summary: "Exodus 16 verankert Manna als Gabe im Raum der Wüste.",
    aliases: ["Exodus 16", "Israel in der Wüste", "Manna in der Wüste"],
    domain: "story",
    clusterId: "cluster-wueste-pruefung",
  },
  {
    id: "exodus-3-2",
    type: "verse_anchor",
    title: "Exodus 3:2",
    primaryHierarchyId: "exodus-3-2",
    tags: ["exodus", "dornbusch", "feuer", "offenbarung"],
    summary: "Exodus 3:2 verankert den brennenden Dornbusch als Feuer, das nicht verzehrt.",
    aliases: ["Exodus 3:2", "Exodus 3,2", "Brennender Dornbusch"],
    domain: "story",
    clusterId: "cluster-feuer-offenbarung",
  },
  {
    id: "pattern-gabe-im-mangel",
    type: "concept",
    title: "Gabe im Mangel",
    summary: "Ein Muster, in dem Nahrung, Hilfe oder Leben gerade im Raum des Mangels erscheint.",
    domain: "pattern",
    aliases: ["Gabe im Mangel", "Versorgung im Entzug", "Himmelsgabe"],
    archetypalRole: "Empfangen statt Besitzen",
    imageSymbol: "helle Gabe in dunkler Leere",
    movementSteps: ["Mangel", "Schwelle", "Empfangen", "Gabe"],
    leadsTo: ["Leben", "Vertrauen", "Gabe"],
    polarity: {
      axis: "Mangel und Gabe",
      visiblePole: "Mangel",
      hiddenPole: "Gabe",
      note: "Der Mangel wird zum Ort, an dem Empfang sichtbar wird.",
    },
    clusterId: "cluster-brot-nahrung",
    tags: ["pattern", "mangel", "gabe", "brot", "manna", "wueste"],
  },
  {
    id: "pattern-pruefung-durch-entzug",
    type: "concept",
    title: "Prüfung durch Entzug",
    summary: "Ein Muster, in dem äußere Sicherheiten weggenommen werden, damit innere Wahrheit sichtbar wird.",
    domain: "pattern",
    aliases: ["Prüfung durch Entzug", "Bewährung im Mangel", "Wüstenprüfung"],
    archetypalRole: "Klärung durch Leere",
    imageSymbol: "enge Schwelle zwischen Dunkelheit und Licht",
    movementSteps: ["Gewohntes", "Mangel", "Prüfung", "Reifung"],
    leadsTo: ["Erkenntnis", "Vertrauen"],
    polarity: {
      axis: "Entzug und Bewährung",
      visiblePole: "Entzug",
      hiddenPole: "Reifung",
      note: "Der Entzug ist nicht nur Verlust, sondern ein Raum der Offenlegung.",
    },
    clusterId: "cluster-wueste-pruefung",
    tags: ["pattern", "pruefung", "wueste", "weg", "mangel"],
  },
  {
    id: "pattern-schwelle-durch-wasser",
    type: "concept",
    title: "Schwelle durch Wasser",
    summary: "Ein Muster, in dem Wasser Grenze, Durchgang, Reinigung und Neuwerdung zugleich ist.",
    domain: "pattern",
    aliases: ["Schwelle durch Wasser", "Durchgang durch Wasser", "Wasser als Übergang"],
    archetypalRole: "Übergang durch Tiefe",
    imageSymbol: "dunkles Wasser als Grenze mit Licht jenseits davon",
    movementSteps: ["Chaos", "Schwelle", "Durchgang", "Ordnung"],
    leadsTo: ["Ordnung", "Ursprung", "Leben"],
    polarity: {
      axis: "Grenze und Geburt",
      visiblePole: "Gefahr und Grenze",
      hiddenPole: "Neuwerdung",
      note: "Wasser trennt und trägt zugleich in einen neuen Zustand.",
    },
    clusterId: "cluster-wasser-ursprung",
    tags: ["pattern", "wasser", "schwelle", "reinigung", "geburt"],
  },
  {
    id: "pattern-offenbarung-im-feuer",
    type: "concept",
    title: "Offenbarung im Feuer",
    summary: "Ein Muster, in dem Feuer nicht nur verzehrt, sondern Gegenwart und Stimme sichtbar macht.",
    domain: "pattern",
    aliases: ["Offenbarung im Feuer", "Feuer als Gegenwart", "brennende Offenbarung"],
    archetypalRole: "Gegenwart, die verwandelt",
    imageSymbol: "ruhiges goldenes Feuer in dunklem Raum",
    movementSteps: ["Verborgenheit", "Brennen", "Offenbarung", "Sendung"],
    leadsTo: ["Offenbarung", "Erkenntnis"],
    polarity: {
      axis: "Verzehrung und Gegenwart",
      visiblePole: "Brennen",
      hiddenPole: "Offenbarung",
      note: "Feuer ist nicht bloss Zerstörung, sondern Nähe, die das Verborgene zeigt.",
    },
    clusterId: "cluster-feuer-offenbarung",
    tags: ["pattern", "feuer", "offenbarung", "stimme", "dornbusch"],
  },
  {
    id: "pattern-weg-der-reifung",
    type: "concept",
    title: "Weg der Reifung",
    summary: "Ein Muster, in dem Bewegung, Prüfung und Führung zu innerer Verwandlung werden.",
    domain: "pattern",
    aliases: ["Weg der Reifung", "Reifungsweg", "innerer Weg"],
    archetypalRole: "Verwandlung durch Gang",
    imageSymbol: "schmaler Pfad durch dunkle Weite",
    movementSteps: ["Ruf", "Weg", "Prüfung", "Gestalt"],
    leadsTo: ["Erkenntnis", "Leben"],
    polarity: {
      axis: "Aufbruch und Verwandlung",
      visiblePole: "Weg",
      hiddenPole: "Reifung",
      note: "Der Weg ist nicht nur Strecke, sondern Wandlung des Gehenden.",
    },
    clusterId: "cluster-wueste-pruefung",
    tags: ["pattern", "weg", "wueste", "pruefung", "verwandlung"],
  },
  {
    id: "pattern-chaos-ordnung-offenbarung",
    type: "concept",
    title: "Chaos, Ordnung, Offenbarung",
    summary: "Ein Muster, in dem ungeformte Tiefe nicht uebersprungen wird: Aus Ursprung und Chaos wird Ordnung, und Ordnung oeffnet Sichtbarkeit.",
    domain: "pattern",
    aliases: ["Chaos Ordnung Offenbarung", "Von der Tiefe zum Licht", "Genesis-Ursprungsmuster"],
    archetypalRole: "Ursprung wird bewegt, geordnet und sichtbar",
    imageSymbol: "dunkle Tiefe, geordnete Linie und erstes Licht",
    movementSteps: ["Ursprung", "Tiefe", "Wort", "Licht"],
    leadsTo: ["Ordnung", "Offenbarung", "Erkenntnis"],
    polarity: {
      axis: "Verborgenheit und Sichtbarkeit",
      visiblePole: "Licht",
      hiddenPole: "Tiefe",
      note: "Das Muster liest Ordnung nicht als Kontrolle, sondern als erste lesbare Gestalt aus der Tiefe.",
    },
    clusterId: "cluster-genesis-1",
    tags: ["pattern", "genesis", "chaos", "ordnung", "offenbarung", "tiefe", "licht"],
  },
  ...phase36AOntologyEntities,
];

export const ontologyRelations: OntologyRelation[] = [
  {
    id: "ontology-tehom-source-of-wasser",
    sourceId: "tehom",
    targetId: "majim",
    type: "source_of",
    title: "Tehom ist Ursprungstiefe des Wassers",
    shortResonance: "Wasser trägt jetzt auch Ursprung und Tiefe.",
    explanation: "Tehom ist nicht einfach Wasser, aber im Anfangsraum wird Wasser aus der uranfänglichen Tiefe lesbar.",
    strength: 0.95,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05de\u05d9\u05dd"],
  },
  {
    id: "ontology-ruach-resonates-with-tehom",
    sourceId: "ruach",
    targetId: "tehom",
    type: "resonates_with",
    title: "Ruach bewegt sich über Tehom",
    shortResonance: "Die Tiefe wird durch unsichtbare Bewegung berührt.",
    explanation: "Ruach steht zwischen der uranfänglichen Tiefe und dem Hervortreten der Offenbarung: nicht sichtbar, aber wirksam.",
    strength: 0.97,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05ea\u05d4\u05d5\u05dd"],
  },
  {
    id: "ontology-ruach-resonates-with-majim",
    sourceId: "ruach",
    targetId: "majim",
    type: "resonates_with",
    title: "Ruach schwebt über Majim",
    shortResonance: "Wasser und Geist bilden den Anfangskorridor.",
    explanation: "Genesis 1,2 verbindet Ruach mit den Wassern; Majim wird dadurch nicht nur Tiefe, sondern bewegter Ursprungsraum.",
    strength: 0.98,
    scriptureAnchors: ["genesis-1-2"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05de\u05d9\u05dd"],
  },
  {
    id: "ontology-ruach-expressed-through-davar",
    sourceId: "ruach",
    targetId: "davar",
    type: "expressed_through",
    title: "Ruach trägt Davar",
    shortResonance: "Das Wort wird durch Atem und Bewegung getragen.",
    explanation: "Ruach ist die unsichtbare Bewegung, durch die Davar nicht abstrakt bleibt, sondern in den Raum des Hörens gelangen kann.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05d3\u05d1\u05e8"],
  },
  {
    id: "ontology-ruach-gives-rise-to-qol",
    sourceId: "ruach",
    targetId: "qol",
    type: "gives_rise_to",
    title: "Ruach gibt Qol Atem",
    shortResonance: "Die Stimme wird durch Atem hörbar.",
    explanation: "Qol wird als Stimme erfahrbar, weil Ruach Atem, Bewegung und Gegenwart in das Wort bringt.",
    strength: 0.91,
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05e7\u05d5\u05dc"],
  },
  {
    id: "ontology-ruach-opens-into-or",
    sourceId: "ruach",
    targetId: "or",
    type: "opens_into",
    title: "Ruach öffnet zum Licht",
    shortResonance: "Die Bewegung des Geistes führt zur Sichtbarkeit.",
    explanation: "Ruach trägt die Bewegung vom verborgenen Anfang zur Offenbarung, in der Or sichtbar wird.",
    strength: 0.88,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05e8\u05d5\u05d7", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "ontology-ruach-source-of-leben",
    sourceId: "ruach",
    targetId: "leben",
    type: "source_of",
    title: "Ruach ist Atem des Lebens",
    shortResonance: "Leben wird als Atem und Bewegung lesbar.",
    explanation: "Ruach verbindet Geist, Wind und Atem mit Leben: nicht als sichtbares Objekt, sondern als tragende Wirkung.",
    strength: 0.9,
    hebrewAnchors: ["\u05e8\u05d5\u05d7"],
  },
  {
    id: "ontology-tehom-gives-rise-to-davar",
    sourceId: "tehom",
    targetId: "davar",
    type: "gives_rise_to",
    title: "Aus Tehom erhebt sich Davar",
    shortResonance: "Aus der Tiefe erhebt sich das Wort.",
    explanation: "Die grosse Achse beginnt in der Verborgenheit: Aus Tehom erhebt sich Davar als wirksames Wort, bevor es in Qol hörbar wird.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05d3\u05d1\u05e8"],
  },
  {
    id: "ontology-davar-gives-rise-to-qol",
    sourceId: "davar",
    targetId: "qol",
    type: "gives_rise_to",
    title: "Davar wird Qol",
    shortResonance: "Das Wort wird als Stimme hörbar.",
    explanation: "Davar trägt die wirksame Wirklichkeit des Wortes; in Qol tritt dieses Wort als Stimme in den Raum des Hörens.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-3"],
    hebrewAnchors: ["\u05d3\u05d1\u05e8", "\u05e7\u05d5\u05dc"],
  },
  {
    id: "ontology-tehom-echoes-within-wueste",
    sourceId: "tehom",
    targetId: "midbar",
    type: "echoes_within",
    title: "Tehom hallt im Midbar nach",
    shortResonance: "Tiefe und Wüste teilen verborgenen Raum.",
    explanation: "Im Midbar wird leer, was in Tehom verborgen ist: ein Raum vor der sichtbaren Gestalt, in dem Hören beginnen kann.",
    strength: 0.82,
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05de\u05d3\u05d1\u05e8"],
  },
  {
    id: "ontology-tehom-precedes-licht",
    sourceId: "tehom",
    targetId: "or",
    type: "precedes",
    title: "Tehom geht dem Licht voraus",
    shortResonance: "Vor dem Licht steht die Tiefe.",
    explanation: "Genesis 1,2 verankert die Tiefe vor Genesis 1,3: Licht wird sichtbar, nachdem die Verborgenheit als Ursprung genannt ist.",
    strength: 0.95,
    scriptureAnchors: ["genesis-1-2", "genesis-1-3"],
    hebrewAnchors: ["\u05ea\u05d4\u05d5\u05dd", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "ontology-quelle-is-expression-of-wasser",
    sourceId: "quelle",
    targetId: "majim",
    type: "is_expression_of",
    title: "Quelle ist Ausdruck von Wasser",
    shortResonance: "In der Quelle tritt Wasser als Ursprung hervor.",
    explanation: "Die Quelle zeigt Wasser nicht als Fläche, sondern als ersten Austritt und Gabe.",
    strength: 0.9,
  },
  {
    id: "ontology-quelle-contains-pattern-schwelle-durch-wasser",
    sourceId: "quelle",
    targetId: "pattern-schwelle-durch-wasser",
    type: "contains_pattern",
    title: "Quelle enthält das Muster der Schwelle durch Wasser",
    shortResonance: "Die Quelle macht Wasser als Anfang einer Schwelle sichtbar.",
    explanation: "Wo Wasser hervortritt, beginnt ein Übergang vom Verborgenen ins Sichtbare.",
    strength: 0.75,
  },
  {
    id: "rel-quelle-opens-ursprung",
    sourceId: "quelle",
    targetId: "ursprung",
    type: "opens_into",
    title: "Quelle öffnet Ursprung",
    shortResonance: "Die Quelle zeigt den Ursprung als erstes Hervortreten.",
    explanation: "In der Quelle wird der verborgene Anfang berührbar: Wasser erscheint nicht als Vorrat, sondern als Beginn.",
    strength: 0.86,
  },
  {
    id: "ontology-brunnen-is-expression-of-wasser",
    sourceId: "brunnen",
    targetId: "majim",
    type: "is_expression_of",
    title: "Brunnen ist Ausdruck von Wasser",
    shortResonance: "Die Tiefe des Brunnens ist ein Wasserraum.",
    explanation: "Im Brunnen sammelt sich Wasser als verborgene Tiefe.",
    strength: 1,
  },
  {
    id: "ontology-brunnen-is-threshold-to-begegnung",
    sourceId: "brunnen",
    targetId: "begegnung",
    type: "is_threshold_to",
    title: "Brunnen ist Schwelle zur Begegnung",
    shortResonance: "Am Brunnen wird Tiefe zum Ort der Begegnung.",
    explanation: "Wo Wasser geschöpft wird, können Wege einander begegnen.",
    strength: 0.75,
  },
  {
    id: "ontology-brunnen-opens-into-tiefe",
    sourceId: "brunnen",
    targetId: "tehom",
    type: "opens_into",
    title: "Brunnen öffnet in die Tiefe",
    shortResonance: "Der Brunnen macht verborgene Tiefe erreichbar.",
    explanation: "Der Brunnen führt unter die Oberfläche.",
    strength: 0.9,
  },
  {
    id: "ontology-meer-is-expression-of-wasser",
    sourceId: "meer",
    targetId: "majim",
    type: "is_expression_of",
    title: "Meer ist Ausdruck von Wasser",
    shortResonance: "Im Meer wird Wasser zu Grenze, Tiefe und Weite.",
    explanation: "Das Meer zeigt Wasser als überwältigende Tiefe und als Schwelle des Durchgangs.",
    strength: 0.9,
  },
  {
    id: "ontology-meer-opens-into-tiefe",
    sourceId: "meer",
    targetId: "tehom",
    type: "opens_into",
    title: "Meer öffnet in die Tiefe",
    shortResonance: "Das Meer führt in die unermessliche Tiefe.",
    explanation: "Die Weite des Meeres macht die verborgene Tiefe des Wassers spürbar.",
    strength: 0.85,
  },
  {
    id: "ontology-meer-contains-pattern-schwelle-durch-wasser",
    sourceId: "meer",
    targetId: "pattern-schwelle-durch-wasser",
    type: "contains_pattern",
    title: "Meer enthält das Muster der Schwelle durch Wasser",
    shortResonance: "Das Meer ist Grenze und Durchgang zugleich.",
    explanation: "Am Meer wird Wasser zur gefährlichen Grenze und zum möglichen Weg in Freiheit.",
    strength: 0.8,
  },
  {
    id: "ontology-meer-contrasts-with-wueste",
    sourceId: "meer",
    targetId: "midbar",
    type: "contrasts_with",
    title: "Meer steht in Spannung zur Wüste",
    shortResonance: "Wasserfülle und Wasserentzug spiegeln einander.",
    explanation: "Meer und Wüste markieren gegensätzliche Erfahrungsräume von Wasser: Übermaß und Mangel.",
    strength: 0.7,
  },
  {
    id: "ontology-fluss-is-expression-of-wasser",
    sourceId: "fluss",
    targetId: "majim",
    type: "is_expression_of",
    title: "Fluss ist Ausdruck von Wasser",
    shortResonance: "Im Fluss wird Wasser zu Bewegung und Richtung.",
    explanation: "Der Fluss zeigt Wasser als lebendigen Strom, der einen Weg bildet.",
    strength: 0.85,
  },
  {
    id: "ontology-fluss-structures-journey-weg",
    sourceId: "fluss",
    targetId: "weg",
    type: "structures_journey",
    title: "Fluss strukturiert den Weg",
    shortResonance: "Der Fluss gibt Bewegung eine Richtung.",
    explanation: "Ein Fluss ist Wasser, das nicht steht, sondern einen Weg durch den Raum zeichnet.",
    strength: 0.75,
  },
  {
    id: "rel-fluss-opens-leben",
    sourceId: "fluss",
    targetId: "leben",
    type: "opens_into",
    title: "Fluss öffnet Leben",
    shortResonance: "Der Fluss zeigt Leben als Bewegung.",
    explanation: "Im Fluss wird Wasser zur Richtung: Leben erscheint als empfangene Bewegung, nicht als Stillstand.",
    strength: 0.82,
  },
  {
    id: "ontology-manna-is-expression-of-brot",
    sourceId: "manna",
    targetId: "lechem",
    type: "is_expression_of",
    title: "Manna ist Ausdruck von Brot",
    shortResonance: "Manna ist Brot als Gabe im Mangel.",
    explanation: "Manna zeigt Brot als tägliche Gabe auf dem Weg.",
    strength: 1,
  },
  {
    id: "ontology-manna-is-threshold-to-wueste",
    sourceId: "manna",
    targetId: "midbar",
    type: "is_threshold_to",
    title: "Manna ist Schwelle zur Wüste",
    shortResonance: "Im Mangel wird Versorgung als Gabe sichtbar.",
    explanation: "Die Wüste macht Manna als unerwartete Versorgung lesbar.",
    strength: 0.95,
  },
  {
    id: "ontology-manna-emerges-from-tau",
    sourceId: "manna",
    targetId: "tau",
    type: "emerges_from",
    title: "Manna aus dem Tau",
    shortResonance: "Die Gabe erscheint auf der Schwelle des Taus.",
    explanation: "Aus der feinen Feuchte des Morgens tritt die Gabe hervor.",
    strength: 0.85,
  },
  {
    id: "ontology-manna-shares-number-wasser-90",
    sourceId: "manna",
    targetId: "majim",
    type: "shares_number",
    title: "Manna und Wasser teilen den Zahlkörper 90",
    shortResonance: "Wasser und Manna teilen die Spur der 90: Gabe und Tiefe berühren sich.",
    explanation: "Majim und man führen beide in den Zahlkörper 90; so wird Manna als Gabe im Mangel neben der Tiefe des Wassers lesbar.",
    strength: 0.78,
    hebrewAnchors: ["\u05de\u05d9\u05dd", "\u05de\u05df"],
  },
  {
    id: "ontology-manna-appears-in-exodus-16",
    sourceId: "manna",
    targetId: "exodus-wilderness",
    type: "appears_in_story",
    title: "Manna in Exodus 16",
    shortResonance: "Exodus 16 verankert Manna als Gabe in der Wüste.",
    explanation: "Die Erzählung der Wüste gibt Manna seinen Ort.",
    scriptureAnchors: ["exodus-wilderness"],
  },
  {
    id: "ontology-tau-is-expression-of-wasser",
    sourceId: "tau",
    targetId: "majim",
    type: "is_expression_of",
    title: "Tau ist Ausdruck von Wasser",
    shortResonance: "Tau zeigt Wasser als leise Gabe von oben.",
    explanation: "Im Tau erscheint Wasser fein, morgendlich und empfangen.",
    strength: 0.85,
  },
  {
    id: "ontology-tau-is-threshold-to-manna",
    sourceId: "tau",
    targetId: "manna",
    type: "is_threshold_to",
    title: "Tau ist Schwelle zu Manna",
    shortResonance: "Aus dem Tau wird die Gabe sichtbar.",
    explanation: "Der Tau bildet die morgendliche Schwelle, auf der Manna hervortritt.",
    strength: 0.8,
  },
  {
    id: "ontology-tau-contains-pattern-gabe-im-mangel",
    sourceId: "tau",
    targetId: "pattern-gabe-im-mangel",
    type: "contains_pattern",
    title: "Tau enthält das Muster der Gabe im Mangel",
    shortResonance: "Tau bereitet die Gabe im Mangel vor.",
    explanation: "In der Wüste wird die feine Feuchte des Taus zum Vorraum unerwarteter Versorgung.",
    strength: 0.7,
  },
  {
    id: "ontology-dornbusch-is-expression-of-feuer",
    sourceId: "dornbusch",
    targetId: "esch",
    type: "is_expression_of",
    title: "Dornbusch ist Ausdruck von Feuer",
    shortResonance: "Der Dornbusch ist Feuer als rufende Gegenwart.",
    explanation: "Im Dornbusch brennt Feuer als Gegenwart, die ruft.",
    strength: 1,
  },
  {
    id: "ontology-dornbusch-reveals-stimme",
    sourceId: "dornbusch",
    targetId: "qol",
    type: "reveals",
    title: "Dornbusch offenbart Stimme",
    shortResonance: "Im Feuer wird die Stimme hörbar.",
    explanation: "Im Feuer wird die Stimme hörbar.",
    strength: 0.9,
  },
  {
    id: "ontology-dornbusch-appears-in-exodus-3-2",
    sourceId: "dornbusch",
    targetId: "exodus-3-2",
    type: "appears_in_story",
    title: "Dornbusch in Exodus 3:2",
    shortResonance: "Der brennende Dornbusch verankert Feuer als nicht verzehrende Gegenwart.",
    explanation: "Exodus 3:2 zeigt Feuer als Gegenwart, die brennt und nicht verzehrt.",
    scriptureAnchors: ["exodus-3-2"],
    strength: 1,
  },
  {
    id: "ontology-dornbusch-contains-pattern-offenbarung-im-feuer",
    sourceId: "dornbusch",
    targetId: "pattern-offenbarung-im-feuer",
    type: "contains_pattern",
    title: "Dornbusch enthält das Muster der Offenbarung im Feuer",
    shortResonance: "Im Dornbusch wird Feuer zur Offenbarung ohne Verzehrung.",
    explanation: "Der Dornbusch trägt das Muster, in dem Feuer Gegenwart und Stimme sichtbar macht.",
    strength: 0.95,
  },
  {
    id: "ontology-flamme-is-expression-of-feuer",
    sourceId: "flamme",
    targetId: "esch",
    type: "is_expression_of",
    title: "Flamme ist Ausdruck von Feuer",
    shortResonance: "Die Flamme macht Feuer sichtbar und beweglich.",
    explanation: "In der Flamme erscheint Feuer als aufsteigende, lebendige Bewegung.",
    strength: 0.9,
  },
  {
    id: "ontology-flamme-reveals-licht",
    sourceId: "flamme",
    targetId: "or",
    type: "reveals",
    title: "Flamme offenbart Licht",
    shortResonance: "Die Flamme lässt Feuer als Licht erscheinen.",
    explanation: "In der Flamme wird die leuchtende Seite des Feuers sichtbar.",
    strength: 0.75,
  },
  {
    id: "ontology-glut-is-expression-of-feuer",
    sourceId: "glut",
    targetId: "esch",
    type: "is_expression_of",
    title: "Glut ist Ausdruck von Feuer",
    shortResonance: "Glut ist Feuer als verborgene Wärme.",
    explanation: "Die Glut zeigt, dass Feuer auch verborgen weiterwirken kann.",
    strength: 0.85,
  },
  {
    id: "ontology-glut-opens-into-laeuterung",
    sourceId: "glut",
    targetId: "laeuterung",
    type: "opens_into",
    title: "Glut öffnet in Läuterung",
    shortResonance: "Verborgene Hitze wird zur inneren Klärung.",
    explanation: "Glut trägt die stille Kraft des Feuers, die verwandeln und klären kann.",
    strength: 0.75,
  },
  {
    id: "ontology-altar-is-expression-of-feuer",
    sourceId: "altar",
    targetId: "esch",
    type: "is_expression_of",
    title: "Altarfeuer ist Ausdruck von Feuer",
    shortResonance: "Am Altar wird Feuer zur geordneten Hingabe.",
    explanation: "Das Altarfeuer bindet die Energie des Feuers an Ritual, Nähe und Gabe.",
    strength: 0.85,
  },
  {
    id: "ontology-altar-is-threshold-to-dornbusch",
    sourceId: "altar",
    targetId: "dornbusch",
    type: "is_threshold_to",
    title: "Altarfeuer ist Schwelle zum Dornbusch",
    shortResonance: "Rituelles Feuer bereitet die Lesbarkeit heiliger Gegenwart vor.",
    explanation: "Altarfeuer und Dornbusch teilen Feuer als Ort der Annäherung an Gegenwart.",
    strength: 0.7,
  },
  {
    id: "ontology-laeuterung-is-expression-of-feuer",
    sourceId: "laeuterung",
    targetId: "esch",
    type: "is_expression_of",
    title: "Läuterung ist Ausdruck von Feuer",
    shortResonance: "Läuterung zeigt Feuer als klärende Verwandlung.",
    explanation: "In der Läuterung brennt Feuer nicht nur, sondern macht das Innere klarer.",
    strength: 0.85,
  },
  {
    id: "ontology-laeuterung-passes-through-pruefung",
    sourceId: "laeuterung",
    targetId: "pruefung",
    type: "passes_through",
    title: "Läuterung führt durch Prüfung",
    shortResonance: "Klärung geschieht durch Erprobung.",
    explanation: "Läuterung ist eine Form der Prüfung, in der Verborgenes sichtbar und verwandelt wird.",
    strength: 0.75,
  },
  {
    id: "ontology-weg-is-threshold-to-wueste",
    sourceId: "weg",
    targetId: "midbar",
    type: "is_threshold_to",
    title: "Weg ist Schwelle zur Wüste",
    shortResonance: "Der Weg führt durch den Raum der Reduktion.",
    explanation: "In der Wüste wird der Weg zur Prüfung und Erzählung.",
    strength: 1,
  },
  {
    id: "ontology-weg-contains-pattern-weg-der-reifung",
    sourceId: "weg",
    targetId: "pattern-weg-der-reifung",
    type: "contains_pattern",
    title: "Weg enthält das Muster der Reifung",
    shortResonance: "Der Weg wird zur Form innerer Reifung.",
    explanation: "Auf dem Weg werden Bewegung, Prüfung und Führung zu innerer Verwandlung.",
    strength: 0.8,
  },
  {
    id: "ontology-weg-passes-through-pruefung",
    sourceId: "weg",
    targetId: "pruefung",
    type: "passes_through",
    title: "Weg führt durch Prüfung",
    shortResonance: "Der Weg macht sichtbar, was im Inneren trägt.",
    explanation: "Auf dem Weg zeigt sich, was im Inneren trägt.",
    strength: 0.85,
  },
  {
    id: "ontology-manna-contains-pattern-gabe-im-mangel",
    sourceId: "manna",
    targetId: "pattern-gabe-im-mangel",
    type: "contains_pattern",
    title: "Manna enthält das Muster der Gabe im Mangel",
    shortResonance: "Manna macht Gabe im Raum des Mangels sichtbar.",
    explanation: "Im Manna erscheint Nahrung nicht aus Vorrat, sondern als täglich empfangene Gabe.",
    strength: 1,
  },
  {
    id: "ontology-leere-is-expression-of-wueste",
    sourceId: "leere",
    targetId: "midbar",
    type: "is_expression_of",
    title: "Leere ist Ausdruck von Wüste",
    shortResonance: "Leere zeigt die Wüste als Raum des Entzugs.",
    explanation: "In der Leere wird der Wüstenraum als Verlust von Sicherheiten erfahrbar.",
    strength: 0.9,
  },
  {
    id: "ontology-leere-contains-pattern-pruefung-durch-entzug",
    sourceId: "leere",
    targetId: "pattern-pruefung-durch-entzug",
    type: "contains_pattern",
    title: "Leere enthält das Muster der Prüfung durch Entzug",
    shortResonance: "Leere prüft durch das Wegnehmen von Sicherheiten.",
    explanation: "Die Leere macht Entzug zu einem Raum, in dem innere Wahrheit sichtbar wird.",
    strength: 0.8,
  },
  {
    id: "ontology-leere-opens-into-stimme",
    sourceId: "leere",
    targetId: "qol",
    type: "opens_into",
    title: "Leere öffnet in Stimme",
    shortResonance: "Im entleerten Raum kann Stimme hörbar werden.",
    explanation: "Wo äußere Sicherheiten schweigen, entsteht Raum für den Ruf.",
    strength: 0.75,
  },
  {
    id: "ontology-pruefung-contains-pattern-pruefung-durch-entzug",
    sourceId: "pruefung",
    targetId: "pattern-pruefung-durch-entzug",
    type: "contains_pattern",
    title: "Prüfung enthält das Muster der Prüfung durch Entzug",
    shortResonance: "Prüfung klärt durch Entzug.",
    explanation: "Prüfung wird in der Wüste als Weg erfahrbar, auf dem Sicherheiten wegfallen.",
    strength: 0.85,
  },
  {
    id: "ontology-stimme-emerges-from-leere",
    sourceId: "qol",
    targetId: "leere",
    type: "emerges_from",
    title: "Stimme entsteht aus Leere",
    shortResonance: "Aus der Stille der Leere wird der Ruf hörbar.",
    explanation: "Die Stimme braucht den entleerten Raum, in dem sie nicht von anderen Sicherheiten verdeckt wird.",
    strength: 0.75,
  },
  {
    id: "ontology-stimme-reveals-licht",
    sourceId: "qol",
    targetId: "or",
    type: "reveals",
    title: "Stimme offenbart Licht",
    shortResonance: "Die Stimme gibt Orientierung wie Licht.",
    explanation: "Der Ruf aus der Wüste macht Richtung und Erkenntnis sichtbar.",
    strength: 0.7,
  },
  {
    id: "ontology-qol-reveals-licht",
    sourceId: "qol",
    targetId: "or",
    type: "reveals",
    title: "Qol offenbart Licht",
    shortResonance: "Die Stimme führt in sichtbare Orientierung.",
    explanation: "Qol öffnet den Weg von gehörtem Ruf zu Licht, Klarheit und Wahrnehmung.",
    strength: 0.86,
    hebrewAnchors: ["\u05e7\u05d5\u05dc", "\u05d0\u05d5\u05e8"],
  },
  {
    id: "ontology-qol-emerges-from-wueste",
    sourceId: "qol",
    targetId: "midbar",
    type: "emerges_from",
    title: "Qol steigt aus der Wüste hervor",
    shortResonance: "In der Wüste wird die Stimme hörbar.",
    explanation: "Der reduzierte Raum des Midbar macht Qol als Ruf und Führung wahrnehmbar.",
    strength: 0.86,
    hebrewAnchors: ["\u05e7\u05d5\u05dc", "\u05de\u05d3\u05d1\u05e8"],
  },
  {
    id: "ontology-qol-opens-offenbarung",
    sourceId: "qol",
    targetId: "offenbarung",
    type: "opens_into",
    title: "Qol öffnet Offenbarung",
    shortResonance: "Die Stimme verbindet das Verborgene mit dem Offenbaren.",
    explanation: "Qol wird zur Schwelle, an der Gegenwart zuerst gehört wird, bevor sie verstanden oder gesehen wird.",
    strength: 0.82,
  },
  {
    id: "ontology-qol-opens-begegnung",
    sourceId: "qol",
    targetId: "begegnung",
    type: "opens_into",
    title: "Qol öffnet Begegnung",
    shortResonance: "Der Ruf macht Begegnung möglich.",
    explanation: "Wo Qol gehört wird, entsteht Antwort: Stimme und Hören werden zum Raum der Begegnung.",
    strength: 0.76,
  },
  {
    id: "ontology-wueste-contains-pattern-pruefung-durch-entzug",
    sourceId: "midbar",
    targetId: "pattern-pruefung-durch-entzug",
    type: "contains_pattern",
    title: "Wüste enthält das Muster der Prüfung durch Entzug",
    shortResonance: "Die Wüste prüft durch Reduktion und Mangel.",
    explanation: "In der Wüste werden äußere Sicherheiten entzogen, damit innere Wahrheit sichtbar wird.",
    strength: 1,
  },
  {
    id: "ontology-wueste-opens-into-stimme",
    sourceId: "midbar",
    targetId: "qol",
    type: "opens_into",
    title: "Midbar öffnet Qol",
    shortResonance: "In der Wüste wird das Wort hörbar, weil das Andere schweigt.",
    explanation: "Midbar ist nicht nur Leere: Der entleerte Raum lässt Stimme und Ruf als Orientierung hervortreten.",
    strength: 0.86,
    hebrewAnchors: ["\u05de\u05d3\u05d1\u05e8"],
  },
  {
    id: "ontology-midbar-opens-into-davar",
    sourceId: "midbar",
    targetId: "davar",
    type: "opens_into",
    title: "Midbar öffnet Davar",
    shortResonance: "Im leeren Raum wird das Wort empfangbar.",
    explanation: "Midbar steht in behutsamer Nähe zu Davar: Die Reduktion der Wüste macht das Wort nicht sichtbar, sondern zuerst empfangbar.",
    strength: 0.84,
    hebrewAnchors: ["\u05de\u05d3\u05d1\u05e8", "\u05d3\u05d1\u05e8"],
  },
  {
    id: "ontology-wasser-contains-pattern-schwelle-durch-wasser",
    sourceId: "majim",
    targetId: "pattern-schwelle-durch-wasser",
    type: "contains_pattern",
    title: "Wasser enthält das Muster der Schwelle",
    shortResonance: "Wasser wird Grenze, Durchgang und Neuwerdung.",
    explanation: "Wasser trennt und trägt zugleich: Es markiert Gefahr, Reinigung und Geburt.",
    strength: 1,
  },
  {
    id: "ontology-feuer-contains-pattern-offenbarung-im-feuer",
    sourceId: "esch",
    targetId: "pattern-offenbarung-im-feuer",
    type: "contains_pattern",
    title: "Feuer enthält das Muster der Offenbarung",
    shortResonance: "Feuer macht Gegenwart und Stimme sichtbar.",
    explanation: "Feuer erscheint nicht nur als Verzehrung, sondern als Nähe, die das Verborgene zeigt.",
    strength: 0.95,
  },
  {
    id: "rel-pattern-gabe-im-mangel-opens-leben",
    sourceId: "pattern-gabe-im-mangel",
    targetId: "leben",
    type: "opens_into",
    title: "Gabe im Mangel öffnet Leben",
    shortResonance: "Empfang im Mangel führt zur Lebensgabe.",
    explanation: "Dieses Muster läuft auf Leben zu, weil Versorgung nicht Besitz bleibt, sondern empfangene Bewegung wird.",
    strength: 0.82,
  },
  {
    id: "rel-pattern-pruefung-durch-entzug-opens-erkenntnis",
    sourceId: "pattern-pruefung-durch-entzug",
    targetId: "erkenntnis",
    type: "opens_into",
    title: "Prüfung durch Entzug öffnet Erkenntnis",
    shortResonance: "Im Entzug wird sichtbar, was trägt.",
    explanation: "Die Prüfung führt zur Erkenntnis, weil wegfallende Sicherheiten innere Wahrheit freilegen.",
    strength: 0.78,
  },
  {
    id: "rel-pattern-schwelle-durch-wasser-opens-ordnung",
    sourceId: "pattern-schwelle-durch-wasser",
    targetId: "ordnung",
    type: "opens_into",
    title: "Schwelle durch Wasser öffnet Ordnung",
    shortResonance: "Der Durchgang durch Wasser führt in neue Ordnung.",
    explanation: "Wasser bleibt Schwelle: Aus Chaos, Grenze und Durchgang entsteht eine lesbare Gestalt.",
    strength: 0.8,
  },
  {
    id: "rel-pattern-offenbarung-im-feuer-opens-offenbarung",
    sourceId: "pattern-offenbarung-im-feuer",
    targetId: "offenbarung",
    type: "opens_into",
    title: "Offenbarung im Feuer öffnet Offenbarung",
    shortResonance: "Feuer führt vom Verborgenen ins Sichtbare.",
    explanation: "Dieses Muster sammelt Brennen, Stimme und Gegenwart in der Achse der Offenbarung.",
    strength: 0.84,
  },
  {
    id: "rel-pattern-weg-der-reifung-opens-erkenntnis",
    sourceId: "pattern-weg-der-reifung",
    targetId: "erkenntnis",
    type: "opens_into",
    title: "Weg der Reifung öffnet Erkenntnis",
    shortResonance: "Der Weg formt Wahrnehmung zu Erkenntnis.",
    explanation: "Reifung läuft auf Erkenntnis zu, weil Prüfung und Führung den Weg innerlich lesbar machen.",
    strength: 0.78,
  },
  {
    id: "rel-pattern-chaos-ordnung-offenbarung-emerges-tehom",
    sourceId: "pattern-chaos-ordnung-offenbarung",
    targetId: "tehom",
    type: "emerges_from",
    title: "Das Muster beginnt in Tehom",
    shortResonance: "Die Ordnung wird aus der Tiefe heraus lesbar.",
    explanation: "Genesis 1,1-3 ueberspringt die Tiefe nicht: Tehom bleibt der verborgene Anfangsraum vor Licht und Unterscheidung.",
    strength: 0.88,
  },
  {
    id: "rel-pattern-chaos-ordnung-offenbarung-opens-ordnung",
    sourceId: "pattern-chaos-ordnung-offenbarung",
    targetId: "ordnung",
    type: "opens_into",
    title: "Chaos, Ordnung, Offenbarung oeffnet Ordnung",
    shortResonance: "Aus dem Ungeformten entsteht lesbare Gestalt.",
    explanation: "Ordnung erscheint hier nicht als starre Kontrolle, sondern als erste Unterscheidung, die das Licht vorbereitet.",
    strength: 0.86,
  },
  {
    id: "rel-pattern-chaos-ordnung-offenbarung-opens-offenbarung",
    sourceId: "pattern-chaos-ordnung-offenbarung",
    targetId: "offenbarung",
    type: "opens_into",
    title: "Chaos, Ordnung, Offenbarung oeffnet Offenbarung",
    shortResonance: "Das Verborgene tritt in Sichtbarkeit.",
    explanation: "Die Bewegung von Anfang, Tiefe und Wort fuehrt zur Offenbarung des Lichts.",
    strength: 0.86,
  },
  {
    id: "ontology-morgenlicht-is-expression-of-licht",
    sourceId: "morgenlicht",
    targetId: "or",
    type: "is_expression_of",
    title: "Morgenlicht ist Ausdruck von Licht",
    shortResonance: "Morgenlicht zeigt Licht als Anfang und Erwachen.",
    explanation: "Im Morgenlicht wird Licht zur ersten Orientierung nach der Dunkelheit.",
    strength: 0.85,
  },
  {
    id: "rel-morgenlicht-opens-offenbarung",
    sourceId: "morgenlicht",
    targetId: "offenbarung",
    type: "opens_into",
    title: "Morgenlicht öffnet Offenbarung",
    shortResonance: "Im Morgenlicht beginnt das Verborgene sichtbar zu werden.",
    explanation: "Morgenlicht ist nicht nur Helligkeit, sondern der erste Übergang aus der Nacht in Orientierung.",
    strength: 0.84,
  },
  {
    id: "ontology-leuchte-is-expression-of-licht",
    sourceId: "leuchte",
    targetId: "or",
    type: "is_expression_of",
    title: "Leuchte ist Ausdruck von Licht",
    shortResonance: "Die Leuchte trägt Licht im Raum.",
    explanation: "In der Leuchte wird Licht geordnet, bewahrt und weitergegeben.",
    strength: 0.85,
  },
  {
    id: "rel-leuchte-reveals-ordnung",
    sourceId: "leuchte",
    targetId: "ordnung",
    type: "reveals",
    title: "Leuchte offenbart Ordnung",
    shortResonance: "Die Leuchte trägt Licht in geordneter Form.",
    explanation: "Die Leuchte zeigt Licht als Dienst, Mass und verlässliche Orientierung im Raum.",
    strength: 0.8,
  },
  {
    id: "ontology-stern-is-expression-of-licht",
    sourceId: "stern",
    targetId: "or",
    type: "is_expression_of",
    title: "Stern ist Ausdruck von Licht",
    shortResonance: "Der Stern zeigt Licht als Orientierung in der Nacht.",
    explanation: "Der Stern macht Licht als fernes Zeichen und himmlische Ordnung lesbar.",
    strength: 0.85,
  },
  {
    id: "rel-stern-threshold-himmel",
    sourceId: "stern",
    targetId: "himmel",
    type: "is_threshold_to",
    title: "Stern ist Schwelle zum Himmel",
    shortResonance: "Der Stern öffnet den Blick in die obere Ordnung.",
    explanation: "Der Stern steht am Himmel als Zeichen: klein sichtbar und doch Hinweis auf eine größere Weite.",
    strength: 0.8,
  },
  {
    id: "ontology-glanz-is-expression-of-licht",
    sourceId: "glanz",
    targetId: "or",
    type: "is_expression_of",
    title: "Glanz ist Ausdruck von Licht",
    shortResonance: "Glanz zeigt Licht als Ausstrahlung.",
    explanation: "Im Glanz wird Licht zu sichtbarer Gegenwart und Würde.",
    strength: 0.8,
  },
  {
    id: "rel-glanz-reveals-offenbarung",
    sourceId: "glanz",
    targetId: "offenbarung",
    type: "reveals",
    title: "Glanz offenbart Gegenwart",
    shortResonance: "Glanz macht Gegenwart sichtbar.",
    explanation: "Im Glanz erscheint Licht als Würde und Ausstrahlung, nicht nur als Beleuchtung.",
    strength: 0.82,
  },
  {
    id: "ontology-auge-is-threshold-to-licht",
    sourceId: "auge",
    targetId: "or",
    type: "is_threshold_to",
    title: "Auge ist Schwelle zum Licht",
    shortResonance: "Das Auge macht Licht zur Wahrnehmung.",
    explanation: "Durch das Auge wird Licht nicht nur hell, sondern gesehen und gedeutet.",
    strength: 0.8,
  },
  {
    id: "rel-auge-opens-erkenntnis",
    sourceId: "auge",
    targetId: "erkenntnis",
    type: "opens_into",
    title: "Auge öffnet Erkenntnis",
    shortResonance: "Das Auge wird zur Schwelle inneren Sehens.",
    explanation: "Sehen wird zur Erkenntnis, wenn Licht nicht nur Dinge zeigt, sondern Bedeutung öffnet.",
    strength: 0.84,
  },
  {
    id: "rel-or-is-threshold-to-raah",
    sourceId: "or",
    targetId: "raah",
    type: "is_threshold_to",
    title: "Licht wird gesehen",
    shortResonance: "Licht oeffnet die Schwelle des Sehens.",
    explanation: "Genesis 1,4 fuehrt das gerufene Licht in Wahrnehmung: Es wird nicht nur erschaffen, sondern gesehen.",
    strength: 0.88,
    scriptureAnchors: ["genesis-1-4"],
    hebrewAnchors: ["\u05d0\u05d5\u05e8", "\u05e8\u05d0\u05d4"],
  },
  {
    id: "rel-raah-opens-erkenntnis",
    sourceId: "raah",
    targetId: "erkenntnis",
    type: "opens_into",
    title: "Sehen oeffnet Erkenntnis",
    shortResonance: "Gesehenes Licht wird deutbar.",
    explanation: "Raah verbindet Sichtbarkeit mit Erkenntnis: Licht wird wahrgenommen und als Bedeutung erkannt.",
    strength: 0.86,
    scriptureAnchors: ["genesis-1-4"],
    hebrewAnchors: ["\u05e8\u05d0\u05d4"],
  },
  {
    id: "rel-raah-reveals-tov",
    sourceId: "raah",
    targetId: "tov",
    type: "reveals",
    title: "Sehen erkennt das Gute",
    shortResonance: "Das Gute erscheint als erkannte Qualitaet.",
    explanation: "In Genesis 1,4 folgt auf das Sehen die Benennung des Guten: Tov wird nicht flach behauptet, sondern am Licht erkannt.",
    strength: 0.9,
    scriptureAnchors: ["genesis-1-4"],
    hebrewAnchors: ["\u05e8\u05d0\u05d4", "\u05d8\u05d5\u05d1"],
  },
  {
    id: "rel-tov-opens-leben",
    sourceId: "tov",
    targetId: "leben",
    type: "opens_into",
    title: "Tov oeffnet Leben",
    shortResonance: "Gut ist lebensfaehige Ordnung.",
    explanation: "Tov bezeichnet eine tragende Qualitaet: stimmig, geordnet und lebensdienlich.",
    strength: 0.82,
    scriptureAnchors: ["genesis-1-4"],
    hebrewAnchors: ["\u05d8\u05d5\u05d1"],
  },
  ...phase36AOntologyRelations,
];

let registry: OntologyRegistry | null = null;

const technicalOntologyTextPatterns = [
  /existiert bereits/i,
  /als Unterraum/i,
  /semantisch erreicht/i,
  /\btarget\b/i,
  /Ontology/i,
  /CodexEntry/i,
  /\bID\b/,
  /Fallback/i,
  /extern/i,
  /interner/i,
  /modelliert/i,
  /TODO/i,
  /Semantic Zoom/i,
];

function normalizeOntologyText(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function normalizeOntologyTextForComparison(value: string) {
  return normalizeOntologyText(value)
    .toLocaleLowerCase("de")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\p{L}\p{N}\s]/gu, "")
    .trim();
}

function isUserFacingOntologyText(value: string) {
  const text = normalizeOntologyText(value);

  return text.length > 0 && !technicalOntologyTextPatterns.some((pattern) => pattern.test(text));
}

function areOntologyTextsNearDuplicate(left: string, right: string) {
  const normalizedLeft = normalizeOntologyTextForComparison(left);
  const normalizedRight = normalizeOntologyTextForComparison(right);

  if (!normalizedLeft || !normalizedRight) return false;
  if (normalizedLeft === normalizedRight) return true;
  if (normalizedLeft.includes(normalizedRight) || normalizedRight.includes(normalizedLeft)) return true;

  const leftWords = new Set(normalizedLeft.split(/\s+/));
  const rightWords = new Set(normalizedRight.split(/\s+/));
  const sharedWords = Array.from(leftWords).filter((word) => rightWords.has(word)).length;
  const unionSize = new Set([...leftWords, ...rightWords]).size;

  return unionSize > 0 && sharedWords / unionSize >= 0.82;
}

function formatOntologyExternalLabel(id: string) {
  const scriptureLikeId = id.match(/^([a-z]+)-(\d+)(?:-(\d+))?$/);

  if (scriptureLikeId) {
    const [, book, chapter, verse] = scriptureLikeId;
    const bookLabel = book.charAt(0).toUpperCase() + book.slice(1);

    return verse ? `${bookLabel} ${chapter}:${verse}` : `${bookLabel} ${chapter}`;
  }

  return id
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function getOntologyRelationLabel(type: OntologyRelationType): string {
  return ONTOLOGY_RELATION_LABELS[type];
}

export function getOntologyRelationMarkerLabel(type: OntologyRelationType): string {
  return ONTOLOGY_RELATION_MARKER_LABELS[type];
}

export function getOntologyEntityTitle(id: string): string {
  return getOntologyEntity(id)?.title ?? formatOntologyExternalLabel(id);
}

export function normalizeOntologyStrength(strength?: number): number {
  if (!strength) return 0;
  return strength <= 1 ? strength * 100 : strength;
}

export function sortOntologyRelations(relations: OntologyRelation[]): OntologyRelation[] {
  return [...relations].sort((left, right) => {
    const leftPriority = ONTOLOGY_RELATION_PRIORITY[left.type] ?? 99;
    const rightPriority = ONTOLOGY_RELATION_PRIORITY[right.type] ?? 99;

    return leftPriority - rightPriority
      || normalizeOntologyStrength(right.strength) - normalizeOntologyStrength(left.strength)
      || left.id.localeCompare(right.id, "de-DE");
  });
}

export function shouldShowOntologyExplanation(
  shortResonance?: string,
  explanation?: string,
): boolean {
  const shortText = normalizeOntologyText(shortResonance ?? "");
  const explanationText = normalizeOntologyText(explanation ?? "");

  if (!isUserFacingOntologyText(explanationText)) return false;
  if (!shortText) return true;
  if (areOntologyTextsNearDuplicate(shortText, explanationText)) return false;
  if (explanationText.length <= shortText.length + 18 && areOntologyTextsNearDuplicate(shortText, explanationText)) return false;

  return true;
}

export function getOntologyDisplayText(relation: OntologyRelation): string {
  const shortResonance = normalizeOntologyText(relation.shortResonance);
  const explanation = normalizeOntologyText(relation.explanation);
  const hasShortResonance = isUserFacingOntologyText(shortResonance);
  const hasExplanation = isUserFacingOntologyText(explanation);

  if (hasShortResonance) {
    return shortResonance;
  }

  if (hasExplanation && !areOntologyTextsNearDuplicate(shortResonance, explanation)) {
    return explanation;
  }

  return "";
}

function createRegistry(): OntologyRegistry {
  const byId = new Map<string, OntologyEntity>();
  const relationsBySource = new Map<string, OntologyRelation[]>();
  const relationsByTarget = new Map<string, OntologyRelation[]>();
  const relationsByType = new Map<OntologyRelationType, OntologyRelation[]>();
  const entitiesByTag = new Map<string, OntologyEntity[]>();

  ontologyEntities.forEach((entity) => {
    byId.set(entity.id, entity);

    entity.tags.forEach((tag) => {
      const taggedEntities = entitiesByTag.get(tag) ?? [];
      taggedEntities.push(entity);
      entitiesByTag.set(tag, taggedEntities);
    });
  });

  ontologyRelations.forEach((relation) => {
    const sourceRelations = relationsBySource.get(relation.sourceId) ?? [];
    sourceRelations.push(relation);
    relationsBySource.set(relation.sourceId, sourceRelations);

    const targetRelations = relationsByTarget.get(relation.targetId) ?? [];
    targetRelations.push(relation);
    relationsByTarget.set(relation.targetId, targetRelations);

    const typeRelations = relationsByType.get(relation.type) ?? [];
    typeRelations.push(relation);
    relationsByType.set(relation.type, typeRelations);
  });

  return {
    entities: ontologyEntities,
    relations: ontologyRelations,
    byId,
    relationsBySource,
    relationsByTarget,
    relationsByType,
    entitiesByTag,
  };
}

export function getOntologyRegistry(): OntologyRegistry {
  registry ??= createRegistry();
  return registry;
}

export function getOntologyEntity(id: string): OntologyEntity | undefined {
  return getOntologyRegistry().byId.get(canonicalOntologyEntityId(id));
}

export function getOntologyRelationsForEntity(id: string): OntologyRelation[] {
  const registry = getOntologyRegistry();
  const entityId = canonicalOntologyEntityId(id);

  return [
    ...(registry.relationsBySource.get(entityId) ?? []),
    ...(registry.relationsByTarget.get(entityId) ?? []),
  ];
}

export function getOntologyRelationsByType(type: OntologyRelationType): OntologyRelation[] {
  return getOntologyRegistry().relationsByType.get(type) ?? [];
}

export function getOntologyNeighbors(id: string): OntologyNeighbor[] {
  const registry = getOntologyRegistry();
  const sourceNeighbors = (registry.relationsBySource.get(id) ?? [])
    .flatMap((relation): OntologyNeighbor[] => {
      const entity = registry.byId.get(relation.targetId);

      return entity ? [{ entity, relation, direction: "target" }] : [];
    });
  const targetNeighbors = (registry.relationsByTarget.get(id) ?? [])
    .flatMap((relation): OntologyNeighbor[] => {
      const entity = registry.byId.get(relation.sourceId);

      return entity ? [{ entity, relation, direction: "source" }] : [];
    });

  return [...sourceNeighbors, ...targetNeighbors];
}

export function getOntologyEntitiesByTag(tag: string): OntologyEntity[] {
  return getOntologyRegistry().entitiesByTag.get(tag) ?? [];
}
