import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const waterEngineData: SymbolEngineData = {
  id: "water-engine",
  slug: "wasser",
  title: "Wasserraum",
  symbolLabel: "Wasser",
  hebrew: {
    hebrewWordId: "majim",
    hebrewLetterIds: ["mem", "jod", "mem"],
    hebrewMeaningFieldIds: ["majim-depth", "majim-transition", "majim-new-birth"],
    word: "\u05de\u05d9\u05dd",
    transliteration: "majim",
    translation: "Wasser",
    summary:
      "Majim steht in Genesis 1,2 nicht nur als Element, sondern als Tiefe vor der Form: vom offenen Mem über den Impuls des Jod zum geschlossenen Mem.",
    letters: [
      {
        id: "open-mem",
        hebrewLetterId: "mem",
        letter: "\u05de",
        name: "Offenes Mem",
        position: "Anfang",
        meaning: "Tiefe, Ursprung, noch offene Möglichkeit",
        detail: "Das Wasser beginnt offen: empfangend, unruhig und noch nicht geordnet.",
      },
      {
        id: "yod",
        hebrewLetterId: "jod",
        letter: "\u05d9",
        name: "Jod",
        position: "Mitte",
        meaning: "Punkt, Hand, Impuls",
        detail: "Im Inneren des Wortes liegt ein kleiner Impuls: ein Anfang von Form und Handlung.",
      },
      {
        id: "closed-mem",
        hebrewLetterId: "mem",
        letter: "\u05dd",
        name: "Geschlossenes Mem",
        position: "Ende",
        meaning: "Grenze, Sammlung, verborgene Quelle",
        detail: "Das Wasser schliesst sich zur Gestalt. Die Tiefe wird nicht aufgehoben, sondern gehalten.",
      },
    ],
  },
  scenes: [
    {
      id: "genesis-1-1",
      reference: "Genesis 1,1",
      title: "Der Anfang ist beruehrt.",
      text: "Im Anfang werden Himmel und Erde genannt. Noch ist die Geschichte kaum geoeffnet, aber der Raum ist gesetzt.",
      meaning: "Genesis 1,1 bleibt die Schwelle, aus der die Tiefe von Genesis 1,2 hervortritt.",
    },
    {
      id: "genesis-1-2",
      reference: "Genesis 1,2",
      title: "Die Tiefe ist nicht leer.",
      text: "Die Erde ist tohu wa-vohu. Finsternis liegt auf Tehom, und die Ruach Gottes schwebt über den Wassern.",
      meaning: "Wasser ist hier kein fertiges Element. Es ist Tiefe vor der Form, von Geist berührt und noch ungeordnet offen.",
    },
    {
      id: "noah",
      reference: "Genesis 6-9",
      title: "Noah",
      text: "Die Flut löst eine gewordene Welt auf. Danach erscheint wieder Boden unter den Füßen.",
      meaning: "Wasser kann Ende und Neubeginn zugleich tragen.",
    },
    {
      id: "exodus-14",
      reference: "Exodus 14",
      title: "Der Weg durch das Meer",
      text: "Das Meer verschwindet nicht. Es teilt sich, und mitten in der Grenze entsteht ein Weg.",
      meaning: "Befreiung führt nicht am Wasser vorbei, sondern durch es hindurch.",
    },
    {
      id: "jordan-baptism",
      reference: "Matthaeus 3,13-17",
      title: "Jordan und Taufe",
      text: "Jesus steigt in den Jordan. Beim Auftauchen öffnet sich der Himmel.",
      meaning: "Untertauchen markiert keinen Verlust, sondern einen neuen Anfang.",
    },
    {
      id: "john-4-14",
      reference: "Johannes 4,14",
      title: "Lebendiges Wasser",
      text: "Das gegebene Wasser wird im Menschen zu einer Quelle, die ins ewige Leben quillt.",
      meaning: "Die Quelle liegt nicht mehr nur ausserhalb. Sie beginnt im Inneren zu strömen.",
    },
  ],
  connections: [
    { id: "origin-threshold", label: "Bereschit", relation: "Schwelle", detail: "Genesis 1,1 setzt den Raum, bevor Tiefe und Wasser erzählbar werden." },
    { id: "creation", label: "Schöpfung", relation: "Ursprung", detail: "Aus ungeordneter Tiefe tritt Gestalt hervor." },
    { id: "tehom", label: "Tehom", relation: "Urtiefe", detail: "Die Tiefe ist nicht Wasser allein, sondern der verborgene Raum vor Form und Licht." },
    { id: "tohu-vohu", label: "Tohu wa-vohu", relation: "Möglichkeit", detail: "Das Ungeformte ist noch nicht bewohnbar, aber nicht bedeutungslos leer." },
    { id: "chaos", label: "Chaos", relation: "Tiefe", detail: "Das Wasser bewahrt, was noch keine Form gefunden hat." },
    { id: "boundary", label: "Grenze", relation: "Sammlung", detail: "Wasser trennt Ufer, Zeiten und Zustände voneinander." },
    { id: "freedom", label: "Befreiung", relation: "Durchgang", detail: "Die Grenze wird zum Weg, als Israel hindurchgeht." },
    { id: "cleansing", label: "Reinigung", relation: "Neubeginn", detail: "Wasser löst, wäscht und eröffnet einen neuen Zustand." },
    { id: "baptism", label: "Taufe", relation: "Verwandlung", detail: "Untertauchen und Auftauchen werden zu einer inneren Bewegung." },
    { id: "life", label: "Leben", relation: "Quelle", detail: "Lebendiges Wasser strömt aus verborgener Tiefe." },
    { id: "spirit", label: "Ruach", relation: "Bewegung", detail: "Der Geist schwebt über dem Wasser und setzt Möglichkeit in Bewegung." },
    { id: "merachefet", label: "Merachefet", relation: "Schweben", detail: "Das Schweben hält Nähe ohne Zugriff: Bewegung über der Tiefe, bevor Licht gesprochen wird." },
  ],
  states: [
    {
      id: "before-order",
      navigationLabel: "Tiefe",
      eyebrow: "Genesis 1,1-2",
      title: "Der Weg beginnt nicht oben, sondern in der Tiefe.",
      text: "Wasser traegt, bevor Form erscheint. Unter dem ersten Anfang liegt Tehom: dunkel, offen, noch nicht sichtbar geordnet.",
      inscription: "Anfang / Tiefe / Wasser",
      visual: {
        image: visualAssets.wasserCinema,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Weiter dunkler Wasserraum vor der Ordnung",
        atmosphere: { id: "origin", mood: "erwartend", motion: "schwebend", light: "untergetaucht", density: 0.64 },
        veilOpacity: 0.74,
      },
      hebrewLetterIds: ["open-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-depth"],
      biblicalSceneIds: ["genesis-1-1", "genesis-1-2"],
      hebrewSummary: "Majim bleibt hier nah an Tehom: Wasser als getragene Tiefe, bevor Gestalt hervortritt.",
      connectionIds: ["origin-threshold", "tehom", "tohu-vohu"],
      reflection: { kicker: "Innere Erfahrung", question: "Was liegt in deiner Tiefe, bevor es Form bekommt?" },
    },
    {
      id: "depth",
      navigationLabel: "Atem",
      eyebrow: "Ruach ueber den Wassern",
      title: "Ueber der Tiefe bewegt sich Atem.",
      text: "Die Tiefe bleibt dunkel, aber nicht starr. Ruach schwebt ueber den Wassern; aus dieser Bewegung oeffnet sich das Wort.",
      inscription: "Ruach / Bewegung / Wort / Licht",
      visual: {
        image: visualAssets.wasserDepth,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Tiefer Wasserraum mit Lichtstrahl und hebräischem Zeichen",
        atmosphere: { id: "depth", mood: "still", motion: "schwebend", light: "Licht von oben", density: 0.82 },
        veilOpacity: 0.76,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-depth", "majim-transition"],
      hebrewSummary: "Offenes Mem, Jod und geschlossenes Mem halten Tiefe, Impuls und Sammlung zusammen.",
      biblicalSceneIds: ["genesis-1-2"],
      connectionIds: ["spirit", "merachefet", "creation"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo spuerst du Bewegung, obwohl noch nichts sichtbar ist?" },
    },
    {
      id: "boundary",
      navigationLabel: "Grenze",
      eyebrow: "Geschlossenes Mem",
      title: "Das Wasser sammelt sich zur Grenze.",
      text: "Wasser ist nicht nur Weite. Es bekommt Ufer, Gewicht und Widerstand. Gerade die Grenze macht einen Übergang sichtbar.",
      inscription: "Geschlossenes Mem / Ufer / Sammlung",
      visual: {
        image: visualAssets.wasserMacro,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Nahaufnahme einer bewegten Wasseroberfläche",
        atmosphere: { id: "boundary", mood: "konzentriert", motion: "kreisend", light: "gebrochen", density: 0.68 },
        veilOpacity: 0.66,
      },
      hebrewLetterIds: ["closed-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-transition"],
      hebrewSummary: "Das geschlossene Mem sammelt die Tiefe. Es gibt dem Wasser eine Grenze, ohne sein Geheimnis aufzulösen.",
      biblicalSceneIds: ["noah"],
      connectionIds: ["boundary", "chaos", "cleansing"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche Grenze hält dich gerade fest, und welche Form gibt sie dir?" },
    },
    {
      id: "exodus",
      navigationLabel: "Exodus",
      eyebrow: "Exodus 14",
      title: "Die Grenze wird zum Weg.",
      text: "Das Meer verschwindet nicht. Es teilt sich. Befreiung beginnt dort, wo der erste Schritt mitten durch die Grenze führt.",
      inscription: "Grenze / Durchzug / Befreiung",
      visual: {
        image: visualAssets.wasserScene,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Der Weg durch das geteilte Meer im Exodus",
        atmosphere: { id: "exodus", mood: "entschieden", motion: "teilend", light: "goldene Passage", density: 0.74 },
        veilOpacity: 0.52,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-transition"],
      hebrewSummary: "Zwischen offenem und geschlossenem Mem liegt Jod: ein kleiner Impuls, der den Durchgang eröffnet.",
      biblicalSceneIds: ["exodus-14"],
      connectionIds: ["boundary", "freedom", "spirit"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo wird ein Weg erst sichtbar, wenn du dich der Schwelle anvertraust?" },
    },
    {
      id: "cleansing",
      navigationLabel: "Reinigung",
      eyebrow: "Noah",
      title: "Wasser löst und lässt neu beginnen.",
      text: "In der Flut liegt eine harte Ambivalenz: Was geworden ist, wird aufgelöst. Danach muss Leben wieder Boden finden.",
      inscription: "Flut / Lösung / Neubeginn",
      visual: {
        image: visualAssets.wasserMap,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Wasser in dichter Bewegung",
        atmosphere: { id: "cleansing", mood: "klärend", motion: "spülend", light: "silbrig", density: 0.62 },
        veilOpacity: 0.58,
      },
      hebrewLetterIds: ["closed-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-new-birth"],
      hebrewSummary: "Das geschlossene Mem erinnert daran, dass Reinigung nicht endlos bleibt: Das Wasser sammelt sich wieder.",
      biblicalSceneIds: ["noah"],
      connectionIds: ["cleansing", "creation", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Was darf sich lösen, damit unter deinen Füßen wieder Boden entsteht?" },
    },
    {
      id: "baptism",
      navigationLabel: "Taufe",
      eyebrow: "Jordan",
      title: "Untertauchen wird Neubeginn.",
      text: "Am Jordan wird Wasser zur Schwelle. Der Weg führt hinab und wieder hinauf: dieselbe Person, und doch ein neuer Anfang.",
      inscription: "Jordan / Taufe / Verwandlung",
      visual: {
        image: visualAssets.wasserHebrew,
        backgroundImage: visualAssets.wasserHebrew,
        alt: "Hebräisches Wassersymbol in einem dunklen Raum",
        atmosphere: { id: "baptism", mood: "offen", motion: "auftauchend", light: "weichgold", density: 0.48 },
        veilOpacity: 0.56,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-transition", "majim-new-birth"],
      hebrewSummary: "Majim beschreibt eine ganze Bewegung: offen werden, einen Impuls empfangen, verwandelt gesammelt werden.",
      biblicalSceneIds: ["jordan-baptism"],
      connectionIds: ["baptism", "cleansing", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Was möchte in dir nicht nur gereinigt, sondern neu begonnen werden?" },
    },
    {
      id: "living-water",
      navigationLabel: "Lebendiges Wasser",
      eyebrow: "Johannes 4,14",
      title: "Die Quelle rückt ins Innere.",
      text: "Lebendiges Wasser wird nicht nur gereicht. Es beginnt im Menschen selbst zu quellen und verwandelt Durst in Bewegung.",
      inscription: "Durst / Quelle / Leben",
      visual: {
        image: visualAssets.wasserInterface,
        backgroundImage: visualAssets.wasserMacro,
        alt: "Leuchtender Wasserraum mit aufsteigender Bewegung",
        atmosphere: { id: "living-water", mood: "lebendig", motion: "stroemend", light: "cyan und gold", density: 0.42 },
        veilOpacity: 0.48,
      },
      hebrewLetterIds: ["yod"],
      hebrewCodexLetterIds: ["jod"],
      hebrewSummary: "Jod ist der kleine lebendige Impuls in der Mitte: der Punkt, aus dem Bewegung hervorgeht.",
      biblicalSceneIds: ["john-4-14"],
      connectionIds: ["life", "spirit", "baptism"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo spürst du Durst, und wo vielleicht schon eine verborgene Quelle?" },
    },
    {
      id: "source",
      navigationLabel: "Quelle",
      eyebrow: "Majim",
      title: "Die Tiefe ist zur Quelle geworden.",
      text: "Die Reise endet nicht an der Oberfläche. Wasser bleibt Tiefe, Grenze und Durchgang. Doch nun ist auch die Quelle sichtbar.",
      inscription: "Majim / Quelle / Leben",
      visual: {
        image: visualAssets.wasserRoomHero,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Wasserraum zwischen Tiefe und Licht",
        atmosphere: { id: "source", mood: "gesammelt", motion: "aufsteigend", light: "offen", density: 0.34 },
        veilOpacity: 0.46,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-depth", "majim-transition", "majim-new-birth"],
      hebrewSummary: "Offenes Mem, Jod und geschlossenes Mem bilden eine Reise: Tiefe vor der Form, Impuls und gesammelte Quelle.",
      biblicalSceneIds: ["genesis-1-1", "genesis-1-2", "exodus-14", "jordan-baptism", "john-4-14"],
      connectionIds: ["tehom", "merachefet", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Was nimmst du aus der Tiefe mit zurück an die Oberfläche?" },
    },
  ].slice(0, 4),
};
