import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const waterEngineData: SymbolEngineData = {
  id: "water-engine",
  slug: "wasser",
  title: "Wasserraum",
  symbolLabel: "Wasser",
  hebrew: {
    hebrewWordId: "majim",
    hebrewLetterIds: ["mem", "jod", "mem"],
    hebrewMeaningFieldIds: ["majim-depth", "majim-transition", "majim-new-birth"],
    word: "\u05de\u05d9\u05dd",
    transliteration: "majim",
    translation: "Wasser",
    summary:
      "Majim traegt eine Bewegung zwischen Tiefe und Gestalt: vom offenen Mem ueber den Impuls des Jod zum geschlossenen Mem.",
    letters: [
      {
        id: "open-mem",
        hebrewLetterId: "mem",
        letter: "\u05de",
        name: "Offenes Mem",
        position: "Anfang",
        meaning: "Tiefe, Ursprung, noch offene Moeglichkeit",
        detail: "Das Wasser beginnt offen: empfangend, unruhig und noch nicht geordnet.",
      },
      {
        id: "yod",
        hebrewLetterId: "jod",
        letter: "\u05d9",
        name: "Jod",
        position: "Mitte",
        meaning: "Punkt, Hand, Impuls",
        detail: "Im Inneren des Wortes liegt ein kleiner Impuls: ein Anfang von Form und Handlung.",
      },
      {
        id: "closed-mem",
        hebrewLetterId: "mem",
        letter: "\u05dd",
        name: "Geschlossenes Mem",
        position: "Ende",
        meaning: "Grenze, Sammlung, verborgene Quelle",
        detail: "Das Wasser schliesst sich zur Gestalt. Die Tiefe wird nicht aufgehoben, sondern gehalten.",
      },
    ],
  },
  scenes: [
    {
      id: "genesis-1-2",
      reference: "Genesis 1,2",
      title: "Vor der Ordnung",
      text: "Finsternis liegt ueber der Tiefe, und der Geist Gottes schwebt ueber dem Wasser.",
      meaning: "Wasser ist hier kein fertiges Bild. Es ist der Raum, in dem Schoepfung beginnen kann.",
    },
    {
      id: "noah",
      reference: "Genesis 6-9",
      title: "Noah",
      text: "Die Flut loest eine gewordene Welt auf. Danach erscheint wieder Boden unter den Fuessen.",
      meaning: "Wasser kann Ende und Neubeginn zugleich tragen.",
    },
    {
      id: "exodus-14",
      reference: "Exodus 14",
      title: "Der Weg durch das Meer",
      text: "Das Meer verschwindet nicht. Es teilt sich, und mitten in der Grenze entsteht ein Weg.",
      meaning: "Befreiung fuehrt nicht am Wasser vorbei, sondern durch es hindurch.",
    },
    {
      id: "jordan-baptism",
      reference: "Matthaeus 3,13-17",
      title: "Jordan und Taufe",
      text: "Jesus steigt in den Jordan. Beim Auftauchen oeffnet sich der Himmel.",
      meaning: "Untertauchen markiert keinen Verlust, sondern einen neuen Anfang.",
    },
    {
      id: "john-4-14",
      reference: "Johannes 4,14",
      title: "Lebendiges Wasser",
      text: "Das gegebene Wasser wird im Menschen zu einer Quelle, die ins ewige Leben quillt.",
      meaning: "Die Quelle liegt nicht mehr nur ausserhalb. Sie beginnt im Inneren zu stroemen.",
    },
  ],
  connections: [
    { id: "creation", label: "Schoepfung", relation: "Ursprung", detail: "Aus ungeordneter Tiefe tritt Gestalt hervor." },
    { id: "chaos", label: "Chaos", relation: "Tiefe", detail: "Das Wasser bewahrt, was noch keine Form gefunden hat." },
    { id: "boundary", label: "Grenze", relation: "Sammlung", detail: "Wasser trennt Ufer, Zeiten und Zustaende voneinander." },
    { id: "freedom", label: "Befreiung", relation: "Durchgang", detail: "Die Grenze wird zum Weg, als Israel hindurchgeht." },
    { id: "cleansing", label: "Reinigung", relation: "Neubeginn", detail: "Wasser loest, waescht und eroeffnet einen neuen Zustand." },
    { id: "baptism", label: "Taufe", relation: "Verwandlung", detail: "Untertauchen und Auftauchen werden zu einer inneren Bewegung." },
    { id: "life", label: "Leben", relation: "Quelle", detail: "Lebendiges Wasser stroemt aus verborgener Tiefe." },
    { id: "spirit", label: "Geist", relation: "Bewegung", detail: "Der Geist schwebt ueber dem Wasser und setzt Moeglichkeit in Bewegung." },
  ],
  states: [
    {
      id: "before-order",
      navigationLabel: "Vor der Ordnung",
      eyebrow: "Genesis 1,2",
      title: "Noch ist nichts getrennt.",
      text: "Wasser erscheint vor jeder klaren Grenze. Die Tiefe ist dunkel, aber nicht leer: Ueber ihr schwebt bereits Bewegung.",
      inscription: "Tiefe / Geist / Moeglichkeit",
      visual: {
        image: visualAssets.wasserDepth,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Weiter dunkler Wasserraum vor der Ordnung",
        atmosphere: { id: "origin", mood: "erwartend", motion: "schwebend", light: "untergetaucht", density: 0.54 },
        veilOpacity: 0.72,
      },
      hebrewLetterIds: ["open-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-depth"],
      hebrewSummary: "Das offene Mem fuehrt in die unbestimmte Tiefe des Anfangs.",
      biblicalSceneIds: ["genesis-1-2"],
      connectionIds: ["creation", "chaos", "spirit"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo ist in deinem Leben etwas noch ungeordnet, aber bereits in Bewegung?" },
    },
    {
      id: "depth",
      navigationLabel: "Tiefe",
      eyebrow: "Offenes Mem",
      title: "Die Tiefe oeffnet sich.",
      text: "Das offene Mem ist keine Antwort. Es ist ein Raum, in dem Ursprung, Unsicherheit und Geburt nebeneinander liegen duerfen.",
      inscription: "Offenes Mem / Ursprung / Tiefe",
      visual: {
        image: visualAssets.wasserDepth,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Tiefer Wasserraum mit Lichtstrahl und hebraeischem Zeichen",
        atmosphere: { id: "depth", mood: "still", motion: "sinkend", light: "tiefblau", density: 0.88 },
        veilOpacity: 0.78,
      },
      hebrewLetterIds: ["open-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-depth"],
      hebrewSummary: "Mem beginnt offen. Die Tiefe ist zugaenglich, aber nicht kontrollierbar.",
      biblicalSceneIds: ["genesis-1-2", "noah"],
      connectionIds: ["chaos", "creation", "cleansing"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche Tiefe vermeidest du, obwohl in ihr auch ein Anfang liegen koennte?" },
    },
    {
      id: "boundary",
      navigationLabel: "Grenze",
      eyebrow: "Geschlossenes Mem",
      title: "Das Wasser sammelt sich zur Grenze.",
      text: "Wasser ist nicht nur Weite. Es bekommt Ufer, Gewicht und Widerstand. Gerade die Grenze macht einen Uebergang sichtbar.",
      inscription: "Geschlossenes Mem / Ufer / Sammlung",
      visual: {
        image: visualAssets.wasserMacro,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Nahaufnahme einer bewegten Wasseroberflaeche",
        atmosphere: { id: "boundary", mood: "konzentriert", motion: "kreisend", light: "gebrochen", density: 0.68 },
        veilOpacity: 0.66,
      },
      hebrewLetterIds: ["closed-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-transition"],
      hebrewSummary: "Das geschlossene Mem sammelt die Tiefe. Es gibt dem Wasser eine Grenze, ohne sein Geheimnis aufzuloesen.",
      biblicalSceneIds: ["noah"],
      connectionIds: ["boundary", "chaos", "cleansing"],
      reflection: { kicker: "Innere Erfahrung", question: "Welche Grenze haelt dich gerade fest, und welche Form gibt sie dir?" },
    },
    {
      id: "exodus",
      navigationLabel: "Exodus",
      eyebrow: "Exodus 14",
      title: "Die Grenze wird zum Weg.",
      text: "Das Meer verschwindet nicht. Es teilt sich. Befreiung beginnt dort, wo der erste Schritt mitten durch die Grenze fuehrt.",
      inscription: "Grenze / Durchzug / Befreiung",
      visual: {
        image: visualAssets.wasserScene,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Der Weg durch das geteilte Meer im Exodus",
        atmosphere: { id: "exodus", mood: "entschieden", motion: "teilend", light: "goldene Passage", density: 0.74 },
        veilOpacity: 0.52,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-transition"],
      hebrewSummary: "Zwischen offenem und geschlossenem Mem liegt Jod: ein kleiner Impuls, der den Durchgang eroeffnet.",
      biblicalSceneIds: ["exodus-14"],
      connectionIds: ["boundary", "freedom", "spirit"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo wird ein Weg erst sichtbar, wenn du dich der Schwelle anvertraust?" },
    },
    {
      id: "cleansing",
      navigationLabel: "Reinigung",
      eyebrow: "Noah",
      title: "Wasser loest und laesst neu beginnen.",
      text: "In der Flut liegt eine harte Ambivalenz: Was geworden ist, wird aufgeloest. Danach muss Leben wieder Boden finden.",
      inscription: "Flut / Loesung / Neubeginn",
      visual: {
        image: visualAssets.wasserMacro,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Wasser in dichter Bewegung",
        atmosphere: { id: "cleansing", mood: "klaerend", motion: "spuelend", light: "silbrig", density: 0.62 },
        veilOpacity: 0.58,
      },
      hebrewLetterIds: ["closed-mem"],
      hebrewCodexLetterIds: ["mem"],
      hebrewMeaningFieldIds: ["majim-new-birth"],
      hebrewSummary: "Das geschlossene Mem erinnert daran, dass Reinigung nicht endlos bleibt: Das Wasser sammelt sich wieder.",
      biblicalSceneIds: ["noah"],
      connectionIds: ["cleansing", "creation", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Was darf sich loesen, damit unter deinen Fuessen wieder Boden entsteht?" },
    },
    {
      id: "baptism",
      navigationLabel: "Taufe",
      eyebrow: "Jordan",
      title: "Untertauchen wird Neubeginn.",
      text: "Am Jordan wird Wasser zur Schwelle. Der Weg fuehrt hinab und wieder hinauf: dieselbe Person, und doch ein neuer Anfang.",
      inscription: "Jordan / Taufe / Verwandlung",
      visual: {
        image: visualAssets.wasserHebrew,
        backgroundImage: visualAssets.wasserHebrew,
        alt: "Hebraeisches Wassersymbol in einem dunklen Raum",
        atmosphere: { id: "baptism", mood: "offen", motion: "auftauchend", light: "weichgold", density: 0.48 },
        veilOpacity: 0.56,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-transition", "majim-new-birth"],
      hebrewSummary: "Majim beschreibt eine ganze Bewegung: offen werden, einen Impuls empfangen, verwandelt gesammelt werden.",
      biblicalSceneIds: ["jordan-baptism"],
      connectionIds: ["baptism", "cleansing", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Was moechte in dir nicht nur gereinigt, sondern neu begonnen werden?" },
    },
    {
      id: "living-water",
      navigationLabel: "Lebendiges Wasser",
      eyebrow: "Johannes 4,14",
      title: "Die Quelle rueckt ins Innere.",
      text: "Lebendiges Wasser wird nicht nur gereicht. Es beginnt im Menschen selbst zu quellen und verwandelt Durst in Bewegung.",
      inscription: "Durst / Quelle / Leben",
      visual: {
        image: visualAssets.wasserInterface,
        backgroundImage: visualAssets.wasserMacro,
        alt: "Leuchtender Wasserraum mit aufsteigender Bewegung",
        atmosphere: { id: "living-water", mood: "lebendig", motion: "stroemend", light: "cyan und gold", density: 0.42 },
        veilOpacity: 0.48,
      },
      hebrewLetterIds: ["yod"],
      hebrewCodexLetterIds: ["jod"],
      hebrewSummary: "Jod ist der kleine lebendige Impuls in der Mitte: der Punkt, aus dem Bewegung hervorgeht.",
      biblicalSceneIds: ["john-4-14"],
      connectionIds: ["life", "spirit", "baptism"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo spuerst du Durst, und wo vielleicht schon eine verborgene Quelle?" },
    },
    {
      id: "source",
      navigationLabel: "Quelle",
      eyebrow: "Majim",
      title: "Die Tiefe ist zur Quelle geworden.",
      text: "Die Reise endet nicht an der Oberflaeche. Wasser bleibt Tiefe, Grenze und Durchgang. Doch nun ist auch die Quelle sichtbar.",
      inscription: "Majim / Quelle / Leben",
      visual: {
        image: visualAssets.wasserDepth,
        backgroundImage: visualAssets.wasserInterface,
        alt: "Wasserraum zwischen Tiefe und Licht",
        atmosphere: { id: "source", mood: "gesammelt", motion: "aufsteigend", light: "offen", density: 0.34 },
        veilOpacity: 0.46,
      },
      hebrewLetterIds: ["open-mem", "yod", "closed-mem"],
      hebrewCodexLetterIds: ["mem", "jod", "mem"],
      hebrewMeaningFieldIds: ["majim-depth", "majim-transition", "majim-new-birth"],
      hebrewSummary: "Offenes Mem, Jod und geschlossenes Mem bilden eine Reise: Tiefe, Impuls und gesammelte Quelle.",
      biblicalSceneIds: ["genesis-1-2", "exodus-14", "jordan-baptism", "john-4-14"],
      connectionIds: ["creation", "freedom", "baptism", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Was nimmst du aus der Tiefe mit zurueck an die Oberflaeche?" },
    },
  ],
};
