import type { SymbolEngineData } from "@/types/engine";
import { visualAssets } from "@/lib/visualAssets";

export const lightEngineData: SymbolEngineData = {
  id: "light-engine",
  slug: "licht",
  title: "Lichtraum",
  symbolLabel: "Licht",
  hebrew: {
    hebrewWordId: "or",
    hebrewLetterIds: ["aleph", "vav", "resh"],
    hebrewMeaningFieldIds: ["or-light", "or-revelation", "or-awareness", "or-orientation", "or-presence", "or-visibility", "or-life"],
    word: "\u05d0\u05d5\u05e8",
    transliteration: "or",
    translation: "Licht",
    summary: "Or verbindet Genesis 1,3 mit Sichtbarkeit, Erkenntnis und Ordnung: vom stillen Ursprung ueber die Verbindung bis zur sichtbaren Gegenwart.",
    letters: [
      {
        id: "aleph",
        hebrewLetterId: "aleph",
        letter: "\u05d0",
        name: "Aleph",
        position: "Anfang",
        meaning: "Ursprung, Stille, verborgene Gegenwart",
        detail: "Aleph steht am Anfang des Wortes: ein stiller Ursprung, bevor etwas sichtbar hervortritt.",
      },
      {
        id: "vav",
        hebrewLetterId: "vav",
        letter: "\u05d5",
        name: "Vav",
        position: "Mitte",
        meaning: "Verbindung, Achse, Weg",
        detail: "Vav verbindet Anfang und Sichtbarkeit. Im Licht wird aus dem Ursprung eine Richtung.",
      },
      {
        id: "resh",
        hebrewLetterId: "resh",
        letter: "\u05e8",
        name: "Resh",
        position: "Ende",
        meaning: "Haupt, Wahrnehmung, Sichtbarkeit",
        detail: "Resh schliesst das Wort mit einer sichtbaren Ausrichtung: Licht wird wahrnehmbar und lesbar.",
      },
    ],
  },
  scenes: [
    {
      id: "genesis-origin",
      reference: "Genesis 1,1",
      title: "Vor der Erzaehlung",
      text: "Bereschit setzt den Anfang. Himmel und Erde stehen als erste Spannung, bevor Licht benannt wird.",
      meaning: "Der Lichtraum beginnt nicht bei Helligkeit, sondern an der Schwelle, an der Erzaehlung Raum bekommt.",
    },
    {
      id: "genesis-darkness",
      reference: "Genesis 1,2",
      title: "Vor dem Licht",
      text: "Finsternis liegt ueber der Tiefe. Noch ist keine Kontur sichtbar.",
      meaning: "Die Dunkelheit ist ein erwartender Raum vor der ersten Unterscheidung.",
    },
    {
      id: "genesis-light",
      reference: "Genesis 1,3",
      title: "Es werde Licht",
      text: "Gott spricht: Es werde Licht. Und es wurde Licht.",
      meaning: "Amar und Wajehi halten Ruf und Ereignis zusammen: Licht wird erste Sichtbarkeit und Beginn von Ordnung.",
    },
    {
      id: "genesis-light-seen",
      reference: "Genesis 1,4",
      title: "Leise Folgeschwelle",
      text: "Gott sieht das Licht. Das Gute wird als Qualitaet erkannt.",
      meaning: "Genesis 1,4 bleibt knapp: or fuehrt zu raah, und tov erscheint als erkannte, lebensfaehige Qualitaet.",
    },
    {
      id: "exodus-pillar",
      reference: "Exodus 13,21",
      title: "Licht auf dem Weg",
      text: "Die Saeule begleitet Israel durch die Nacht und macht den Weg begehbar.",
      meaning: "Licht wird zur Orientierung: nicht als ganze Karte, sondern als leise Richtung im Dunkel.",
    },
    {
      id: "john-light",
      reference: "Johannes 1,4-5",
      title: "Licht in dir",
      text: "Das Leben ist das Licht der Menschen. Das Licht leuchtet in der Finsternis.",
      meaning: "Licht rueckt ins Innere: als Bewusstsein, Leben und Gegenwart.",
    },
  ],
  connections: [
    { id: "origin-threshold", label: "Bereschit", relation: "Schwelle", detail: "Genesis 1,1 setzt Himmel und Erde als erste Spannung vor dem Licht." },
    { id: "darkness", label: "Dunkelheit", relation: "Tiefe", detail: "Vor der Sichtbarkeit liegt ein Raum der Erwartung." },
    { id: "amar", label: "Amar", relation: "Sprechen", detail: "Das Licht beginnt als gesprochenes Werden, nicht als blosse Helligkeit." },
    { id: "wajehi", label: "Wajehi", relation: "Ereignis", detail: "Was gesprochen wird, geschieht: Sichtbarkeit tritt in Wirklichkeit." },
    { id: "revelation", label: "Offenbarung", relation: "Durchbruch", detail: "Licht laesst hervortreten, was zuvor verborgen blieb." },
    { id: "order", label: "Ordnung", relation: "Unterscheidung", detail: "Licht macht den ersten Unterschied lesbar und bereitet Ordnung vor." },
    { id: "or-raah", label: "or -> raah", relation: "Licht -> Sehen", detail: "Licht macht nicht nur hell. Es macht sichtbar und fuehrt in Wahrnehmung." },
    { id: "seeing", label: "Sehen", relation: "Wahrnehmung", detail: "Licht wird in Genesis 1,4 gesehen, bevor es gut genannt wird." },
    { id: "raah-tov", label: "raah -> tov", relation: "Sehen -> Gut", detail: "Was sichtbar wird, kann erkannt werden; das Gute erscheint als stimmige Qualitaet des Lebens." },
    { id: "goodness", label: "Gut", relation: "Guete", detail: "Tov bezeichnet die erkannte, lebensfaehige Qualitaet des Lichts." },
    { id: "awareness", label: "Erkenntnis", relation: "Bewusstsein", detail: "Sichtbarkeit kann zur inneren Wahrnehmung werden." },
    { id: "guidance", label: "Orientierung", relation: "Fuehrung", detail: "Licht zeigt genug Richtung fuer den Augenblick." },
    { id: "presence", label: "Gegenwart", relation: "Naehe", detail: "Licht macht eine tragende Gegenwart erfahrbar." },
    { id: "life", label: "Leben", relation: "Leuchten", detail: "Johannes verbindet Leben und Licht im Inneren." },
  ],
  states: [
    {
      id: "before-light",
      navigationLabel: "Vor dem Licht",
      eyebrow: "Genesis 1,2",
      title: "Noch liegt alles in der Tiefe.",
      text: "Bereschit hat den Raum gesetzt, doch noch liegt alles in der Tiefe. Licht ist vorbereitet, aber noch nicht gesprochen.",
      inscription: "Bereschit / Tiefe / Erwartung",
      visual: {
        image: visualAssets.lichtCinema,
        alt: "Dunkler Raum aus Tiefe und Nebel vor dem ersten Licht",
        atmosphere: { id: "before-light", mood: "erwartend", motion: "schwebend", light: "verborgen", density: 0.82 },
        veilOpacity: 0.78,
        imageOpacity: 0.76,
      },
      hebrewLetterIds: ["aleph"],
      hebrewCodexLetterIds: ["aleph"],
      hebrewMeaningFieldIds: ["or-presence"],
      hebrewSummary: "Aleph steht am Anfang: still, verborgen und noch vor jeder sichtbaren Kontur.",
      biblicalSceneIds: ["genesis-origin", "genesis-darkness"],
      connectionIds: ["origin-threshold", "darkness", "presence"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo fehlt dir gerade Klarheit?" },
    },
    {
      id: "let-there-be-light",
      navigationLabel: "Es werde Licht",
      eyebrow: "Genesis 1,3",
      title: "Licht macht nicht nur hell. Es macht sichtbar.",
      text: "Amar ruft Or. Wajehi bestaetigt das Geschehen. Licht ueberstrahlt die Tiefe nicht; es macht sichtbar, was erkannt werden kann.",
      inscription: "Amar / Or / Wajehi",
      visual: {
        image: visualAssets.lichtHero,
        backgroundImage: visualAssets.lichtOrderLine,
        alt: "Goldene Lichtachsen brechen ruhig durch einen tiefen nebligen Raum",
        atmosphere: { id: "revelation", mood: "offen", motion: "durchbrechend", light: "goldene Achse", density: 0.58 },
        veilOpacity: 0.56,
      },
      hebrewLetterIds: ["aleph", "vav"],
      hebrewCodexLetterIds: ["aleph", "vav"],
      hebrewMeaningFieldIds: ["or-light", "or-revelation", "or-visibility"],
      hebrewSummary: "Aus dem stillen Aleph fuehrt Vav in die Sichtbarkeit: Or wird Offenbarung und Anfang von Ordnung.",
      biblicalSceneIds: ["genesis-light"],
      connectionIds: ["amar", "wajehi", "order", "or-raah"],
      reflection: { kicker: "Innere Erfahrung", question: "Was wird sichtbar, wenn Licht auf deine Tiefe faellt?" },
    },
    {
      id: "light-seen-as-good",
      navigationLabel: "Sehen / Gut",
      eyebrow: "Genesis 1,4 / Folgeschwelle",
      title: "Hier beginnt das Sehen.",
      text: "Was sichtbar wird, kann erkannt werden. Genesis 1,4 bleibt eine leise Folgeschwelle: Licht wird gesehen, und Gut erscheint als Qualitaet, die Leben traegt.",
      inscription: "or / raah / tov",
      visual: {
        image: visualAssets.lichtOrderLine,
        backgroundImage: visualAssets.lichtReflection,
        alt: "Warme goldene Lichtachse macht Konturen in einem tiefen blauen Raum sichtbar",
        atmosphere: { id: "recognized-light", mood: "erkennend", motion: "klaerend", light: "warme Lichtachse", density: 0.48 },
        veilOpacity: 0.54,
      },
      hebrewLetterIds: ["resh"],
      hebrewCodexLetterIds: ["resh"],
      hebrewMeaningFieldIds: ["or-visibility", "or-awareness", "or-life"],
      hebrewSummary: "Resh schliesst Or als bewusste Sichtbarkeit: Das Licht tritt vor den Blick und bereitet raah und tov vor.",
      biblicalSceneIds: ["genesis-light-seen"],
      connectionIds: ["or-raah", "seeing", "raah-tov", "goodness", "awareness"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo erkennst du etwas als gut, weil es Leben traegt?" },
    },
    {
      id: "light-on-the-way",
      navigationLabel: "Licht auf dem Weg",
      eyebrow: "Exodus 13,21",
      title: "Das Licht oeffnet eine Spur.",
      text: "Nach dem ersten Licht wird Sichtbarkeit zur Spur. Es nimmt den Weg nicht vorweg, aber es gibt Richtung.",
      inscription: "Saeule / Orientierung / Fuehrung",
      visual: {
        image: visualAssets.lichtOrderLine,
        backgroundImage: visualAssets.lichtDepth,
        alt: "Ruhige goldene Lichtachse weist durch einen dunklen nebligen Raum",
        atmosphere: { id: "guidance", mood: "gesammelt", motion: "weisend", light: "goldene Saeule", density: 0.5 },
        veilOpacity: 0.52,
      },
      hebrewLetterIds: ["vav"],
      hebrewCodexLetterIds: ["vav"],
      hebrewMeaningFieldIds: ["or-orientation"],
      hebrewSummary: "Vav wirkt wie eine verbindende Achse: Licht wird zum Weg durch die Nacht.",
      biblicalSceneIds: ["exodus-pillar"],
      connectionIds: ["guidance", "order", "presence"],
      reflection: { kicker: "Innere Erfahrung", question: "Woran orientierst du dich?" },
    },
    {
      id: "light-within",
      navigationLabel: "Licht in dir",
      eyebrow: "Johannes 1,4-5",
      title: "Das Licht rueckt ins Innere.",
      text: "Licht bleibt nicht nur vor dir. Es wird zu Bewusstsein, Gegenwart und lebendigem Leuchten im Inneren.",
      inscription: "Bewusstsein / Gegenwart / Leben",
      visual: {
        image: visualAssets.lichtReflection,
        backgroundImage: visualAssets.lichtMacro,
        alt: "Warmer goldener Lichtschein sammelt sich in einem ruhigen tiefen Raum",
        atmosphere: { id: "inner-light", mood: "gegenwaertig", motion: "sammelnd", light: "weichgold", density: 0.38 },
        veilOpacity: 0.48,
      },
      hebrewLetterIds: ["aleph", "vav", "resh"],
      hebrewCodexLetterIds: ["aleph", "vav", "resh"],
      hebrewMeaningFieldIds: ["or-awareness", "or-presence", "or-life"],
      hebrewSummary: "Aleph, Vav und Resh bilden eine Bewegung vom Ursprung ueber die Verbindung zur bewussten Sichtbarkeit.",
      biblicalSceneIds: ["john-light"],
      connectionIds: ["awareness", "presence", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo will etwas in dir leuchten?" },
    },
  ].slice(1, 3),
};
