import type { SymbolEngineData } from "@/types/engine";

export const lightEngineData: SymbolEngineData = {
  id: "light-engine",
  slug: "licht",
  title: "Lichtraum",
  symbolLabel: "Licht",
  hebrew: {
    hebrewWordId: "or",
    hebrewLetterIds: ["aleph", "vav", "resh"],
    hebrewMeaningFieldIds: ["or-light", "or-revelation", "or-awareness", "or-orientation", "or-presence", "or-visibility", "or-life"],
    word: "\u05d0\u05d5\u05e8",
    transliteration: "or",
    translation: "Licht",
    summary: "Or verbindet Sichtbarkeit, Erkenntnis und Orientierung: vom stillen Ursprung ueber die Verbindung bis zur sichtbaren Gegenwart.",
    letters: [
      {
        id: "aleph",
        hebrewLetterId: "aleph",
        letter: "\u05d0",
        name: "Aleph",
        position: "Anfang",
        meaning: "Ursprung, Stille, verborgene Gegenwart",
        detail: "Aleph steht am Anfang des Wortes: ein stiller Ursprung, bevor etwas sichtbar hervortritt.",
      },
      {
        id: "vav",
        hebrewLetterId: "vav",
        letter: "\u05d5",
        name: "Vav",
        position: "Mitte",
        meaning: "Verbindung, Achse, Weg",
        detail: "Vav verbindet Anfang und Sichtbarkeit. Im Licht wird aus dem Ursprung eine Richtung.",
      },
      {
        id: "resh",
        hebrewLetterId: "resh",
        letter: "\u05e8",
        name: "Resh",
        position: "Ende",
        meaning: "Haupt, Wahrnehmung, Sichtbarkeit",
        detail: "Resh schliesst das Wort mit einer sichtbaren Ausrichtung: Licht wird wahrnehmbar und lesbar.",
      },
    ],
  },
  scenes: [
    {
      id: "genesis-darkness",
      reference: "Genesis 1,2",
      title: "Vor dem Licht",
      text: "Finsternis liegt ueber der Tiefe. Noch ist keine Kontur sichtbar.",
      meaning: "Die Dunkelheit ist ein erwartender Raum vor der ersten Unterscheidung.",
    },
    {
      id: "genesis-light",
      reference: "Genesis 1,3",
      title: "Es werde Licht",
      text: "Gott spricht: Es werde Licht. Der erste Unterschied tritt hervor.",
      meaning: "Licht erscheint als Offenbarung und erster Durchbruch der Sichtbarkeit.",
    },
    {
      id: "exodus-pillar",
      reference: "Exodus 13,21",
      title: "Licht auf dem Weg",
      text: "Die Saeule begleitet Israel durch die Nacht und macht den Weg begehbar.",
      meaning: "Licht wird zur Orientierung: nicht als ganze Karte, sondern als leise Richtung im Dunkel.",
    },
    {
      id: "john-light",
      reference: "Johannes 1,4-5",
      title: "Licht in dir",
      text: "Das Leben ist das Licht der Menschen. Das Licht leuchtet in der Finsternis.",
      meaning: "Licht rueckt ins Innere: als Bewusstsein, Leben und Gegenwart.",
    },
  ],
  connections: [
    { id: "darkness", label: "Dunkelheit", relation: "Tiefe", detail: "Vor der Sichtbarkeit liegt ein Raum der Erwartung." },
    { id: "revelation", label: "Offenbarung", relation: "Durchbruch", detail: "Licht laesst hervortreten, was zuvor verborgen blieb." },
    { id: "awareness", label: "Erkenntnis", relation: "Bewusstsein", detail: "Sichtbarkeit kann zur inneren Wahrnehmung werden." },
    { id: "guidance", label: "Orientierung", relation: "Fuehrung", detail: "Licht zeigt genug Richtung fuer den Augenblick." },
    { id: "presence", label: "Gegenwart", relation: "Nahe", detail: "Licht macht eine tragende Gegenwart erfahrbar." },
    { id: "life", label: "Leben", relation: "Leuchten", detail: "Johannes verbindet Leben und Licht im Inneren." },
  ],
  states: [
    {
      id: "before-light",
      navigationLabel: "Vor dem Licht",
      eyebrow: "Genesis 1,2",
      title: "Noch liegt alles in der Tiefe.",
      text: "Dunkelheit liegt ueber dem Anfang. Der Raum ist still, tief und erwartend.",
      inscription: "Dunkelheit / Tiefe / Erwartung",
      visual: {
        image: "/Visuals/tiefenraum_backround.png",
        backgroundImage: "/Visuals/wasser_hero.png",
        alt: "Dunkler Raum aus Tiefe und Nebel vor dem ersten Licht",
        atmosphere: { id: "before-light", mood: "erwartend", motion: "schwebend", light: "verborgen", density: 0.82 },
        veilOpacity: 0.76,
      },
      hebrewLetterIds: ["aleph"],
      hebrewCodexLetterIds: ["aleph"],
      hebrewMeaningFieldIds: ["or-presence"],
      hebrewSummary: "Aleph steht am Anfang: still, verborgen und noch vor jeder sichtbaren Kontur.",
      biblicalSceneIds: ["genesis-darkness"],
      connectionIds: ["darkness", "presence"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo fehlt dir gerade Klarheit?" },
    },
    {
      id: "let-there-be-light",
      navigationLabel: "Es werde Licht",
      eyebrow: "Genesis 1,3",
      title: "Ein erster Durchbruch wird sichtbar.",
      text: "Licht tritt in den dunklen Raum. Es ueberstrahlt die Tiefe nicht, sondern macht den ersten Unterschied lesbar.",
      inscription: "Licht / Offenbarung / Durchbruch",
      visual: {
        image: "/Visuals/cinem_lichtraum_backround.png",
        backgroundImage: "/Visuals/hebr_archiv_waende_background.png",
        alt: "Goldene Lichtachsen brechen ruhig durch einen tiefen nebligen Raum",
        atmosphere: { id: "revelation", mood: "offen", motion: "durchbrechend", light: "goldene Achse", density: 0.58 },
        veilOpacity: 0.56,
      },
      hebrewLetterIds: ["aleph", "vav"],
      hebrewCodexLetterIds: ["aleph", "vav"],
      hebrewMeaningFieldIds: ["or-light", "or-revelation", "or-visibility"],
      hebrewSummary: "Aus dem stillen Aleph fuehrt Vav in die Sichtbarkeit: Licht wird zur Offenbarung.",
      biblicalSceneIds: ["genesis-light"],
      connectionIds: ["revelation", "awareness"],
      reflection: { kicker: "Innere Erfahrung", question: "Was beginnt sichtbar zu werden?" },
    },
    {
      id: "light-on-the-way",
      navigationLabel: "Licht auf dem Weg",
      eyebrow: "Exodus 13,21",
      title: "Das Licht oeffnet eine Spur.",
      text: "In der Nacht wird Licht zur Saeule. Es nimmt den Weg nicht vorweg, aber es gibt Richtung.",
      inscription: "Saeule / Orientierung / Fuehrung",
      visual: {
        image: "/Visuals/cinem_lichtraum_backround.png",
        backgroundImage: "/Visuals/symbolnetz_backround.png",
        alt: "Ruhige goldene Lichtachse weist durch einen dunklen nebligen Raum",
        atmosphere: { id: "guidance", mood: "gesammelt", motion: "weisend", light: "goldene Saeule", density: 0.5 },
        veilOpacity: 0.52,
      },
      hebrewLetterIds: ["vav"],
      hebrewCodexLetterIds: ["vav"],
      hebrewMeaningFieldIds: ["or-orientation"],
      hebrewSummary: "Vav wirkt wie eine verbindende Achse: Licht wird zum Weg durch die Nacht.",
      biblicalSceneIds: ["exodus-pillar"],
      connectionIds: ["guidance", "presence"],
      reflection: { kicker: "Innere Erfahrung", question: "Woran orientierst du dich?" },
    },
    {
      id: "light-within",
      navigationLabel: "Licht in dir",
      eyebrow: "Johannes 1,4-5",
      title: "Das Licht rueckt ins Innere.",
      text: "Licht bleibt nicht nur vor dir. Es wird zu Bewusstsein, Gegenwart und lebendigem Leuchten im Inneren.",
      inscription: "Bewusstsein / Gegenwart / Leben",
      visual: {
        image: "/Visuals/hebr_archiv_waende_background.png",
        backgroundImage: "/Visuals/cinem_lichtraum_backround.png",
        alt: "Warmer goldener Lichtschein sammelt sich in einem ruhigen tiefen Raum",
        atmosphere: { id: "inner-light", mood: "gegenwaertig", motion: "sammelnd", light: "weichgold", density: 0.38 },
        veilOpacity: 0.48,
      },
      hebrewLetterIds: ["aleph", "vav", "resh"],
      hebrewCodexLetterIds: ["aleph", "vav", "resh"],
      hebrewMeaningFieldIds: ["or-awareness", "or-presence", "or-life"],
      hebrewSummary: "Aleph, Vav und Resh bilden eine Bewegung vom Ursprung ueber die Verbindung zur bewussten Sichtbarkeit.",
      biblicalSceneIds: ["john-light"],
      connectionIds: ["awareness", "presence", "life"],
      reflection: { kicker: "Innere Erfahrung", question: "Wo will etwas in dir leuchten?" },
    },
  ],
};
