import type { SymbolRoomDefinition } from "@/components/rooms/types";
import type {
  ExperienceTraits,
  MeaningQuality,
  SymbolGraph,
  VisualTraits,
} from "@/lib/symbolism";
import { visualAssets } from "@/lib/visualAssets";

const lightVisuals: VisualTraits = {
  material: "gold-thread",
  accent: "gold",
  glow: 0.92,
  opacity: 0.92,
  motion: "spark",
};

const lightExperience: ExperienceTraits = {
  camera: "reveal",
  tone: "awakening",
  tempo: "slow",
  depth: 0.42,
};

const meaningQualityLabels: Record<MeaningQuality, string> = {
  origin: "Ursprung",
  depth: "Tiefe",
  chaos: "Dunkelheit",
  birth: "Anfang",
  transition: "\u00dcbergang",
  purification: "Kl\u00e4rung",
  "hidden-source": "verborgener Glanz",
  lack: "Mangel",
  revelation: "Offenbarung",
  life: "Leben",
  impulse: "Impuls",
  movement: "Bewegung",
  resistance: "Widerstand",
};

const lightSymbolGraph: SymbolGraph = {
  id: "light-symbol-engine",
  title: "Light Symbol Engine",
  centerId: "light",
  nodes: [
    {
      id: "light",
      type: "core-symbol",
      label: "Licht",
      hebrew: "\u05d0\u05d5\u05e8",
      transliteration: "Or",
      shortMeaning: "Licht macht sichtbar, richtet aus und \u00f6ffnet einen Weg.",
      importance: 1,
      depthLevel: 0,
      visuals: lightVisuals,
      experience: lightExperience,
      roomHref: "/raeume/licht",
    },
    {
      id: "darkness",
      type: "natural-symbol",
      label: "Dunkelheit",
      shortMeaning: "Der dunkle Raum, in dem Licht zuerst als Unterschied erfahrbar wird.",
      importance: 0.82,
      depthLevel: 1,
      visuals: { material: "deep-space", accent: "shadow", glow: 0.18, opacity: 0.84, motion: "stillness" },
      experience: { camera: "centered", tone: "still", tempo: "very-slow", depth: 0.72 },
    },
    {
      id: "first-gleam",
      type: "natural-symbol",
      label: "erster Glanz",
      shortMeaning: "Eine erste helle Spur unterbricht die Dunkelheit.",
      importance: 0.86,
      depthLevel: 1,
      visuals: { material: "gold-thread", accent: "gold", glow: 0.72, opacity: 0.82, motion: "spark" },
      experience: { camera: "draw-near", tone: "hope", tempo: "slow", depth: 0.52 },
    },
    {
      id: "revelation",
      type: "spiritual-symbol",
      label: "Offenbarung",
      shortMeaning: "Licht zeigt, was im Dunkel verborgen blieb.",
      importance: 0.9,
      depthLevel: 1,
      visuals: { material: "script-light", accent: "gold", glow: 0.9, opacity: 0.9, motion: "breathing" },
      experience: { camera: "reveal", tone: "awe", tempo: "slow", depth: 0.38 },
    },
    {
      id: "way",
      type: "spiritual-symbol",
      label: "Weg",
      shortMeaning: "Licht wird zur Orientierung im gegenwaertigen Dunkel.",
      importance: 0.84,
      depthLevel: 1,
      visuals: { material: "gold-thread", accent: "gold", glow: 0.76, opacity: 0.84, motion: "emerging" },
      experience: { camera: "wide-threshold", tone: "hope", tempo: "measured", depth: 0.46 },
    },
    {
      id: "clarity",
      type: "spiritual-symbol",
      label: "Klarheit",
      shortMeaning: "Was sichtbar wird, kann unterschieden und bewusst gegangen werden.",
      importance: 0.88,
      depthLevel: 1,
      visuals: { material: "script-light", accent: "gold", glow: 0.86, opacity: 0.88, motion: "stillness" },
      experience: { camera: "centered", tone: "release", tempo: "slow", depth: 0.32 },
    },
  ],
  edges: [
    {
      source: "light",
      target: "darkness",
      relation: "contrasts",
      weight: 0.86,
      layer: "existential",
      meaningQuality: "chaos",
      emotionalTone: "still",
      visualBehavior: "stillness",
      explanation: "Dunkelheit macht Licht als erste Unterscheidung sichtbar.",
    },
    {
      source: "light",
      target: "first-gleam",
      relation: "breaks-through",
      weight: 0.92,
      layer: "visual",
      meaningQuality: "origin",
      emotionalTone: "hope",
      visualBehavior: "spark",
      explanation: "Der erste Glanz ist noch keine Fl\u00e4che, sondern eine helle Spur.",
    },
    {
      source: "light",
      target: "revelation",
      relation: "reveals",
      weight: 0.96,
      layer: "spiritual",
      meaningQuality: "revelation",
      emotionalTone: "awe",
      visualBehavior: "breathing",
      explanation: "Offenbarung bedeutet: Verborgenes tritt in einen lesbaren Zusammenhang.",
    },
    {
      source: "light",
      target: "way",
      relation: "opens-path",
      weight: 0.88,
      layer: "existential",
      meaningQuality: "transition",
      emotionalTone: "hope",
      visualBehavior: "emerging",
      explanation: "Licht nimmt den Weg nicht vorweg, aber es laesst eine Spur sichtbar werden.",
    },
    {
      source: "light",
      target: "clarity",
      relation: "unfolds-into",
      weight: 0.9,
      layer: "existential",
      meaningQuality: "purification",
      emotionalTone: "release",
      visualBehavior: "stillness",
      explanation: "Klarheit ist Licht, das zur inneren Ausrichtung geworden ist.",
    },
  ],
  primaryPaths: {
    light: ["light", "darkness", "first-gleam", "revelation", "way", "clarity"],
    darkness: ["darkness", "light", "first-gleam"],
    "first-gleam": ["first-gleam", "light", "revelation"],
    revelation: ["revelation", "light", "clarity"],
    way: ["way", "light", "clarity"],
    clarity: ["clarity", "light", "way"],
  },
};

export const lightRoomDefinition: SymbolRoomDefinition = {
  id: "light-room",
  slug: "licht",
  graph: lightSymbolGraph,
  centerNodeId: "light",
  entrance: {
    symbolNodeId: "light",
    kickerPrefix: "Raum",
    statement: "Licht unterscheidet. Licht offenbart. Licht weist den Weg.",
    ctaLabel: "Dem Licht folgen",
    ctaHref: "#symbolreise",
    heroImage: {
      src: visualAssets.lichtHero,
      alt: "Dunkelblauer Raum mit warmen Lichtachsen",
    },
    backgroundImage: {
      src: visualAssets.lichtOrderLine,
      alt: "Atmosph\u00e4rischer Lichtraum",
    },
  },
  encounters: [
    {
      id: "darkness",
      symbolNodeId: "darkness",
      state: "darkness",
      impulse: "Noch ist nur der Unterschied sp\u00fcrbar.",
      experienceState: { mood: "still", motion: "waiting", light: "deep-blue", density: 0.7, transition: "hold" },
    },
    {
      id: "first-gleam",
      symbolNodeId: "first-gleam",
      state: "first-gleam",
      impulse: "Eine helle Spur beginnt.",
      experienceState: { mood: "hope", motion: "piercing", light: "first-gold", density: 0.52, transition: "open" },
    },
    {
      id: "revelation",
      symbolNodeId: "revelation",
      state: "revelation",
      impulse: "Was verborgen war, wird lesbar.",
      experienceState: { mood: "awe", motion: "radiating", light: "off-white-gold", density: 0.4, transition: "reveal" },
    },
    {
      id: "way",
      symbolNodeId: "way",
      state: "way",
      impulse: "Eine Spur tritt hervor.",
      experienceState: { mood: "hope", motion: "guiding", light: "gold-axis", density: 0.46, transition: "follow" },
    },
    {
      id: "clarity",
      symbolNodeId: "clarity",
      state: "clarity",
      impulse: "Klarheit wird zur Ausrichtung.",
      experienceState: { mood: "release", motion: "settling", light: "soft-off-white", density: 0.32, transition: "settle" },
    },
  ],
  decision: {
    kicker: "Reflexionsraum",
    reflectionQuestion: "Wo brauchst du gerade genug Licht fuer das, was sich zeigt?",
    textareaLabel: "Reflexion zum Lichtraum",
    placeholder: "Still notieren...",
    storageNotice: "Deine Reflexion bleibt nur auf diesem Ger\u00e4t gespeichert.",
    saveLabel: "Reflexion speichern",
    savedMessage: "Gespeichert. Du findest den Gedanken unter Mein Pfad.",
    emptyMessage: "Schreibe zuerst eine kurze Reflexion.",
  },
  transition: {
    symbolNodeId: "light",
  },
  theme: {
    id: "light",
    colors: {
      background: "#030712",
      accentRgb: "189, 160, 109",
      ambientRgb: "232, 220, 188",
      shadowRgb: "2, 4, 10",
      veilRgb: "16, 16, 18",
      depthRgb: "6, 10, 22",
    },
    atmosphereProfile: {
      id: "clear",
      motion: "radiant",
      particles: "dust",
      light: "beam",
      materiality: "luminous-air",
      rhythm: "still",
    },
    overlayStyle: {
      background:
        "linear-gradient(116deg, transparent 18%, rgba(var(--symbol-room-accent-rgb), 0.075) 18.2%, transparent 18.7%), linear-gradient(64deg, transparent 70%, rgba(245, 241, 232, 0.045) 70.2%, transparent 70.7%), radial-gradient(circle at 50% 18%, rgba(var(--symbol-room-accent-rgb), 0.12), transparent 30%), var(--symbol-room-background)",
    },
    encounterImage: {
      src: visualAssets.lichtReflection,
      alt: "Dunkelblauer Raum mit warmen Lichtachsen",
    },
    journeyKicker: "Symbolreise",
    journeyStatement: "F\u00fcnf Bewegungen des Lichts.",
    meaningQualityLabels,
    primaryMeaningQualities: ["revelation", "origin", "transition"],
    fallbackQualities: ["Offenbarung", "Ursprung", "Weg"],
  },
};
