import type { MeaningRelation } from "@/types/meaningGraph";

export const meaningRelations: MeaningRelation[] = [
  {
    id: "depth-birth",
    fromNodeId: "depth",
    toNodeId: "birth",
    description: "Aus der Tiefe kann ein neuer Anfang hervortreten.",
  },
  {
    id: "birth-life",
    fromNodeId: "birth",
    toNodeId: "life",
    description: "Geburt öffnet den Raum für Leben.",
  },
  {
    id: "chaos-transition",
    fromNodeId: "chaos",
    toNodeId: "transition",
    description: "Das Ungeordnete kann zur Schwelle einer neuen Ordnung werden.",
  },
  {
    id: "transition-purification",
    fromNodeId: "transition",
    toNodeId: "purification",
    description: "Der Übergang kann als Reinigung und Erneuerung erfahren werden.",
  },
  {
    id: "light-revelation",
    fromNodeId: "light",
    toNodeId: "revelation",
    description: "Licht macht Offenbarung als Hervortreten des Sichtbaren erfahrbar.",
  },
  {
    id: "revelation-awareness",
    fromNodeId: "revelation",
    toNodeId: "awareness",
    description: "Was sichtbar wird, kann zu innerem Bewusstsein werden.",
  },
  {
    id: "revelation-life",
    fromNodeId: "revelation",
    toNodeId: "life",
    description: "Offenbarung kann Leben als tragende Gegenwart sichtbar machen.",
  },
  {
    id: "light-guidance",
    fromNodeId: "light",
    toNodeId: "guidance",
    description: "Licht lässt eine Richtung im Dunkel sichtbar werden.",
  },
  {
    id: "fire-presence",
    fromNodeId: "fire",
    toNodeId: "presence",
    description: "Feuer kann Gegenwart als wirksame Nähe erfahrbar machen.",
  },
  {
    id: "presence-calling",
    fromNodeId: "presence",
    toNodeId: "calling",
    description: "Erfahrene Gegenwart kann als persönlicher Ruf in Bewegung setzen.",
  },
  {
    id: "fire-transformation",
    fromNodeId: "fire",
    toNodeId: "transformation",
    description: "Feuer macht Verwandlung als sichtbare Veränderung der Gestalt erfahrbar.",
  },
  {
    id: "transformation-purification",
    fromNodeId: "transformation",
    toNodeId: "purification",
    description: "Verwandlung kann als Läuterung und Reinigung erfahren werden.",
  },
  {
    id: "lack-dependence",
    fromNodeId: "lack",
    toNodeId: "dependence",
    description: "Mangel macht sichtbar, worauf Leben angewiesen ist.",
  },
  {
    id: "dependence-trust",
    fromNodeId: "dependence",
    toNodeId: "trust",
    description: "Erkannte Abhängigkeit kann zu Vertrauen werden.",
  },
  {
    id: "testing-revelation",
    fromNodeId: "testing",
    toNodeId: "revelation",
    description: "In der Prüfung kann sichtbar werden, was zuvor verborgen blieb.",
  },
  {
    id: "desert-guidance",
    fromNodeId: "desert",
    toNodeId: "guidance",
    description: "In der Wüste wird Führung als leise Spur sichtbar.",
  },
  {
    id: "hiddenness-voice",
    fromNodeId: "hiddenness",
    toNodeId: "voice",
    description: "In der Verborgenheit kann eine leise Stimme hörbar werden.",
  },
  {
    id: "voice-word",
    fromNodeId: "voice",
    toNodeId: "word",
    description: "Die gehörte Stimme kann als Wort Orientierung geben.",
  },
  {
    id: "guidance-path",
    fromNodeId: "guidance",
    toNodeId: "path",
    description: "Führung macht einen Weg im gegenwärtigen Augenblick begehbar.",
  },
  {
    id: "life-nourishment",
    fromNodeId: "life",
    toNodeId: "nourishment",
    description: "Lebendiges Wachstum kann zur Nahrung für den Weg reifen.",
  },
  {
    id: "revelation-nourishment",
    fromNodeId: "revelation",
    toNodeId: "nourishment",
    description: "Im Licht reift Nahrung; im Brot kann zugleich Verborgenes sichtbar werden.",
  },
  {
    id: "transformation-nourishment",
    fromNodeId: "transformation",
    toNodeId: "nourishment",
    description: "Im Feuer gewinnt das Gewachsene eine neue Gestalt und wird zu Brot.",
  },
  {
    id: "lack-gift",
    fromNodeId: "lack",
    toNodeId: "gift",
    description: "Im Mangel wird Versorgung als empfangene Gabe sichtbar.",
  },
  {
    id: "gift-nourishment",
    fromNodeId: "gift",
    toNodeId: "nourishment",
    description: "Die empfangene Gabe wird zur Nahrung für den heutigen Weg.",
  },
  {
    id: "nourishment-breaking",
    fromNodeId: "nourishment",
    toNodeId: "breaking",
    description: "Brot wird gebrochen, damit Nahrung geteilt werden kann.",
  },
  {
    id: "breaking-community",
    fromNodeId: "breaking",
    toNodeId: "community",
    description: "Im Brechen und Teilen des Brotes wird Gemeinschaft sichtbar.",
  },
  {
    id: "nourishment-word",
    fromNodeId: "nourishment",
    toNodeId: "word",
    description: "Brot verweist über äußere Nahrung hinaus auf das Wort, von dem der Mensch lebt.",
  },
];
