export type VisualAssetSlot = {
  current: string;
  future?: string;
};

export const visualAssetSlots = {
  startHero: {
    current: "/Visuals/start_symbolraum_hero.png",
    future: "/Visuals/start_symbolraum_hero.png",
  },
  wasserHero: { current: "/Visuals/wasser_tiefenbild.png" },
  wasserDepth: { current: "/Visuals/wasser_tiefenbild.png" },
  wasserInterface: { current: "/Visuals/wasser_interface_backround.png" },
  wasserMacro: { current: "/Visuals/wasser_makro.png" },
  wasserScene: { current: "/Visuals/wasser_szenenbild.png" },
  wasserHebrew: { current: "/Visuals/wasser_hebr_symbl.png" },
  lichtHero: {
    current: "/Visuals/licht_raum_hero.png",
    future: "/Visuals/licht_raum_hero.png",
  },
  lichtDepth: { current: "/Visuals/licht_raum_hero.png" },
  lichtHebrew: { current: "/Visuals/licht_raum_hero.png" },
  lichtMacro: { current: "/Visuals/licht_raum_hero.png" },
  feuerHero: {
    current: "/Visuals/feuer_glut_raum.png",
    future: "/Visuals/feuer_glut_raum.png",
  },
  feuerGlut: { current: "/Visuals/feuer_glut_raum.png" },
  feuerAsh: { current: "/Visuals/feuer_glut_raum.png" },
  feuerHebrew: { current: "/Visuals/feuer_glut_raum.png" },
  feuerMacro: { current: "/Visuals/feuer_glut_raum.png" },
  wuesteHero: {
    current: "/Visuals/wueste_nacht_raum.png",
    future: "/Visuals/wueste_nacht_raum.png",
  },
  wuestePath: { current: "/Visuals/wueste_nacht_raum.png" },
  wuesteDust: { current: "/Visuals/wueste_nacht_raum.png" },
  wuesteHebrew: { current: "/Visuals/wueste_nacht_raum.png" },
  wuesteMacro: { current: "/Visuals/wueste_nacht_raum.png" },
  brotHero: {
    current: "/Visuals/brot_manna_gabe.png",
    future: "/Visuals/brot_manna_gabe.png",
  },
  brotManna: { current: "/Visuals/brot_manna_gabe.png" },
  brotStone: { current: "/Visuals/brot_manna_gabe.png" },
  brotDew: { current: "/Visuals/brot_manna_gabe.png" },
  brotMacro: { current: "/Visuals/brot_manna_gabe.png" },
  archivHero: { current: "/Visuals/hebr_archiv_waende_background.png" },
  pfadHero: { current: "/Visuals/hebr_archiv_waende_background.png" },
  symbolnetzHero: { current: "/Visuals/symbolnetz_backround.png" },
  tiefenraum: { current: "/Visuals/tiefenraum_backround.png" },
} as const satisfies Record<string, VisualAssetSlot>;

export const visualAssets = {
  startHero: visualAssetSlots.startHero.current,
  wasserHero: visualAssetSlots.wasserHero.current,
  wasserDepth: visualAssetSlots.wasserDepth.current,
  wasserInterface: visualAssetSlots.wasserInterface.current,
  wasserMacro: visualAssetSlots.wasserMacro.current,
  wasserScene: visualAssetSlots.wasserScene.current,
  wasserHebrew: visualAssetSlots.wasserHebrew.current,
  lichtHero: visualAssetSlots.lichtHero.current,
  lichtDepth: visualAssetSlots.lichtDepth.current,
  lichtHebrew: visualAssetSlots.lichtHebrew.current,
  lichtMacro: visualAssetSlots.lichtMacro.current,
  feuerHero: visualAssetSlots.feuerHero.current,
  feuerGlut: visualAssetSlots.feuerGlut.current,
  feuerAsh: visualAssetSlots.feuerAsh.current,
  feuerHebrew: visualAssetSlots.feuerHebrew.current,
  feuerMacro: visualAssetSlots.feuerMacro.current,
  wuesteHero: visualAssetSlots.wuesteHero.current,
  wuestePath: visualAssetSlots.wuestePath.current,
  wuesteDust: visualAssetSlots.wuesteDust.current,
  wuesteHebrew: visualAssetSlots.wuesteHebrew.current,
  wuesteMacro: visualAssetSlots.wuesteMacro.current,
  brotHero: visualAssetSlots.brotHero.current,
  brotManna: visualAssetSlots.brotManna.current,
  brotStone: visualAssetSlots.brotStone.current,
  brotDew: visualAssetSlots.brotDew.current,
  brotMacro: visualAssetSlots.brotMacro.current,
  archivHero: visualAssetSlots.archivHero.current,
  pfadHero: visualAssetSlots.pfadHero.current,
  symbolnetzHero: visualAssetSlots.symbolnetzHero.current,
  tiefenraum: visualAssetSlots.tiefenraum.current,
} as const;
