import type { HebrewLetter, HebrewLetterSymbolism } from "@/types/hebrew";

const interpretive = (
  id: string,
  label: string,
  description: string,
): HebrewLetterSymbolism => ({
  id,
  label,
  description,
  provenance: "interpretive",
});

export const hebrewLetters: HebrewLetter[] = [
  {
    id: "aleph",
    glyph: "א",
    name: "Aleph",
    transcription: "ʾ",
    numericValue: 1,
    alphabetPosition: 1,
    symbolism: [
      interpretive("aleph-origin", "Ursprung", "Kann als Anfang und ungeteilter Ursprung gelesen werden."),
      interpretive("aleph-breath", "Atem", "Kann den stillen Atem vor dem gesprochenen Wort andeuten."),
    ],
    archetypalMeanings: ["Anfang", "Einheit", "verborgene Gegenwart"],
    relatedSymbolSlugs: ["licht", "feuer"],
    relatedWordIds: ["or", "esh"],
    biblicalReferences: [],
    experienceFields: ["Anfang", "Stille", "Ausrichtung"],
  },
  {
    id: "bet",
    glyph: "ב",
    name: "Bet",
    transcription: "b/v",
    numericValue: 2,
    alphabetPosition: 2,
    symbolism: [
      interpretive("bet-house", "Haus", "Kann als Haus, Innenraum und empfangende Form gelesen werden."),
      interpretive("bet-relation", "Beziehung", "Kann auf die Spannung zwischen Innen und Außen verweisen."),
    ],
    archetypalMeanings: ["Haus", "Innenraum", "Beziehung"],
    relatedSymbolSlugs: ["wueste"],
    relatedWordIds: ["midbar"],
    biblicalReferences: [],
    experienceFields: ["Geborgenheit", "Grenze", "Beziehung"],
  },
  {
    id: "gimel",
    glyph: "ג",
    name: "Gimel",
    transcription: "g",
    numericValue: 3,
    alphabetPosition: 3,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "dalet",
    glyph: "ד",
    name: "Dalet",
    transcription: "d",
    numericValue: 4,
    alphabetPosition: 4,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: ["wueste"],
    relatedWordIds: ["midbar"],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "he",
    glyph: "ה",
    name: "He",
    transcription: "h",
    numericValue: 5,
    alphabetPosition: 5,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "vav",
    glyph: "ו",
    name: "Vav",
    transcription: "v/w",
    numericValue: 6,
    alphabetPosition: 6,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: ["licht"],
    relatedWordIds: ["or"],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "zayin",
    glyph: "ז",
    name: "Zayin",
    transcription: "z",
    numericValue: 7,
    alphabetPosition: 7,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "chet",
    glyph: "ח",
    name: "Chet",
    transcription: "ch",
    numericValue: 8,
    alphabetPosition: 8,
    symbolism: [
      interpretive("chet-life", "Leben", "Kann als Hinweis auf Leben, Innenraum und tragende Gemeinschaft gelesen werden."),
    ],
    archetypalMeanings: ["Leben", "Innenraum", "Gemeinschaft"],
    relatedSymbolSlugs: ["brot"],
    relatedWordIds: ["lechem"],
    biblicalReferences: [],
    experienceFields: ["Leben", "Gemeinschaft"],
  },
  {
    id: "tet",
    glyph: "ט",
    name: "Tet",
    transcription: "t",
    numericValue: 9,
    alphabetPosition: 9,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "jod",
    glyph: "י",
    name: "Jod",
    transcription: "j",
    numericValue: 10,
    alphabetPosition: 10,
    symbolism: [
      interpretive("jod-point", "Punkt", "Kann als kleinster gesetzter Punkt und konzentrierter Anfang gelesen werden."),
      interpretive("jod-seed", "Same", "Kann einen Impuls lesen lassen, aus dem sich eine größere Form entfaltet."),
    ],
    archetypalMeanings: ["Punkt", "Same", "Impuls"],
    relatedSymbolSlugs: ["wasser"],
    relatedWordIds: ["majim"],
    biblicalReferences: [],
    experienceFields: ["Impuls", "Möglichkeit", "Beginn"],
  },
  {
    id: "kaf",
    glyph: "כ",
    finalForm: "ך",
    name: "Kaf",
    transcription: "k/ch",
    numericValue: 20,
    alphabetPosition: 11,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "lamed",
    glyph: "ל",
    name: "Lamed",
    transcription: "l",
    numericValue: 30,
    alphabetPosition: 12,
    symbolism: [
      interpretive("lamed-learning", "Lernen", "Kann als Bewegung des Lernens, Wachsens und Ausgerichtetwerdens gelesen werden."),
    ],
    archetypalMeanings: ["Lernen", "Wachstum", "Ausrichtung"],
    relatedSymbolSlugs: ["brot"],
    relatedWordIds: ["lechem"],
    biblicalReferences: [],
    experienceFields: ["Wachstum", "Ausrichtung"],
  },
  {
    id: "mem",
    glyph: "מ",
    openForm: "מ",
    closedForm: "ם",
    finalForm: "ם",
    name: "Mem",
    transcription: "m",
    numericValue: 40,
    alphabetPosition: 13,
    symbolism: [
      interpretive("mem-water", "Wasser", "Mem kann im Codex als Träger des Symbolfelds Wasser gelesen werden."),
      interpretive("mem-depth", "Tiefe", "Die offene und geschlossene Gestalt kann auf sichtbare und verborgene Tiefe verweisen."),
      interpretive("mem-womb", "Mutterleib", "Die umschließende Form kann als Mutterraum und Raum des Werdens gelesen werden."),
      interpretive("mem-origin", "Ursprung", "Wasser und Tiefe können Mem mit dem noch ungeformten Anfang verbinden."),
      interpretive("mem-sea", "Meer", "Mem kann in Beziehung zur Weite, Grenze und Unverfügbarkeit des Meeres stehen."),
      interpretive("mem-hiddenness", "Verborgenheit", "Das geschlossene finale Mem kann eine bewahrte, verborgene Innenseite andeuten."),
      interpretive("mem-birth", "Geburt", "Der Weg aus dem umschließenden Wasserraum kann als Geburt gelesen werden."),
      interpretive("mem-chaos", "Chaos vor der Ordnung", "Mem kann an das Wasser vor der ordnenden Scheidung erinnern."),
    ],
    archetypalMeanings: ["Wasser", "Tiefe", "Mutterleib", "Ursprung", "Meer", "Verborgenheit", "Geburt", "Chaos vor der Ordnung"],
    relatedSymbolSlugs: ["wasser", "meer", "tiefe", "taufe", "leben", "wueste", "brot"],
    relatedWordIds: ["majim", "lechem", "midbar"],
    biblicalReferences: [
      {
        id: "mem-genesis-1-2",
        reference: "Genesis 1,2",
        context: "Der Geist Gottes schwebt über den Wassern.",
        relation: "Mem wird über מים mit dem Wasser am Anfang der Schöpfung verbunden.",
        provenance: "canonical",
      },
      {
        id: "mem-exodus-14",
        reference: "Exodus 14",
        context: "Israel zieht durch das Meer.",
        relation: "Das Meer trägt die Motive Grenze, Durchgang und Befreiung.",
        provenance: "canonical",
      },
      {
        id: "mem-matthew-3",
        reference: "Matthäus 3,13-17",
        context: "Jesus wird im Jordan getauft.",
        relation: "Taufe verbindet Wasser mit Übergang und Neugeburt.",
        provenance: "canonical",
      },
    ],
    experienceFields: ["Unsicherheit", "Tiefe", "Übergang", "Neugeburt", "Verborgenheit"],
  },
  {
    id: "nun",
    glyph: "נ",
    finalForm: "ן",
    name: "Nun",
    transcription: "n",
    numericValue: 50,
    alphabetPosition: 14,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "samech",
    glyph: "ס",
    name: "Samech",
    transcription: "s",
    numericValue: 60,
    alphabetPosition: 15,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "ayin",
    glyph: "ע",
    name: "Ayin",
    transcription: "ʿ",
    numericValue: 70,
    alphabetPosition: 16,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "pe",
    glyph: "פ",
    finalForm: "ף",
    name: "Pe",
    transcription: "p/f",
    numericValue: 80,
    alphabetPosition: 17,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "tsadi",
    glyph: "צ",
    finalForm: "ץ",
    name: "Tsadi",
    transcription: "ts",
    numericValue: 90,
    alphabetPosition: 18,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "qof",
    glyph: "ק",
    name: "Qof",
    transcription: "q",
    numericValue: 100,
    alphabetPosition: 19,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "resh",
    glyph: "ר",
    name: "Resh",
    transcription: "r",
    numericValue: 200,
    alphabetPosition: 20,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: ["licht", "wueste"],
    relatedWordIds: ["or", "midbar"],
    biblicalReferences: [],
    experienceFields: [],
  },
  {
    id: "shin",
    glyph: "ש",
    name: "Shin",
    transcription: "sch/s",
    numericValue: 300,
    alphabetPosition: 21,
    symbolism: [
      interpretive("shin-fire", "Feuer", "Kann als bewegtes Feuer und verwandelnde Kraft gelesen werden."),
      interpretive("shin-transformation", "Verwandlung", "Kann für Läuterung, Energie und Veränderung stehen."),
    ],
    archetypalMeanings: ["Feuer", "Energie", "Verwandlung"],
    relatedSymbolSlugs: ["feuer"],
    relatedWordIds: ["esh"],
    biblicalReferences: [],
    experienceFields: ["Energie", "Läuterung", "Verwandlung"],
  },
  {
    id: "tav",
    glyph: "ת",
    name: "Tav",
    transcription: "t",
    numericValue: 400,
    alphabetPosition: 22,
    symbolism: [],
    archetypalMeanings: [],
    relatedSymbolSlugs: [],
    relatedWordIds: [],
    biblicalReferences: [],
    experienceFields: [],
  },
];
