import type {
  HebrewBiblicalReference,
  HebrewMeaningField,
  HebrewRoot,
  HebrewWord,
} from "@/types/hebrew";

import { phase36AHebrewWords } from "./phase36AHebrewWords";

const meaningField = (
  id: string,
  label: string,
  description: string,
  experienceFields: string[],
): HebrewMeaningField => ({
  id,
  label,
  description,
  provenance: "interpretive",
  experienceFields,
});

const reference = (
  id: string,
  biblicalReference: string,
  context: string,
  relation: string,
): HebrewBiblicalReference => ({
  id,
  reference: biblicalReference,
  context,
  relation,
  provenance: "canonical",
});

export const hebrewRoots: HebrewRoot[] = [
  {
    id: "root-or",
    radicals: ["א", "ו", "ר"],
    letterIds: ["aleph", "vav", "resh"],
    rootType: "triliteral",
    coreSemanticField: "Licht, hell werden und erleuchten",
    meaningFields: [],
    relatedRootIds: [],
    sources: [],
  },
  {
    id: "root-l-ch-m",
    radicals: ["ל", "ח", "ם"],
    letterIds: ["lamed", "chet", "mem"],
    rootType: "triliteral",
    coreSemanticField: "Brot und Nahrung",
    meaningFields: [],
    relatedRootIds: [],
    sources: [],
  },
  {
    id: "root-d-b-r",
    radicals: ["ד", "ב", "ר"],
    letterIds: ["dalet", "bet", "resh"],
    rootType: "triliteral",
    coreSemanticField: "Sprechen und Wort",
    meaningFields: [],
    relatedRootIds: [],
    notes: "Die Beziehung zwischen מדבר und דבר wird später philologisch genauer belegt.",
    sources: [],
  },
  {
    id: "root-r-a-h",
    radicals: ["\u05e8", "\u05d0", "\u05d4"],
    letterIds: ["resh", "aleph", "he"],
    rootType: "triliteral",
    coreSemanticField: "sehen, wahrnehmen und erkennen",
    meaningFields: [],
    relatedRootIds: [],
    sources: [],
  },
];

export const hebrewWords: HebrewWord[] = [
  {
    id: "bereschit",
    slug: "bereschit",
    hebrew: "\u05d1\u05e8\u05d0\u05e9\u05d9\u05ea",
    transliteration: "bereschit",
    germanMeaning: "im Anfang",
    meaningThreshold: "Bereschit oeffnet den Text als Innenraum des Anfangs: Ursprung, Schaffen und Ausrichtung liegen noch ineinander.",
    gematria: 913,
    category: "word",
    letterIds: ["bet", "resh", "aleph", "shin", "jod", "tav"],
    possibleRootIds: [],
    rootNote: "Bereschit wird hier als kanonischer Anfangsausdruck gelesen, nicht auf eine einzelne Verbalwurzel reduziert.",
    meaningFields: [
      meaningField("bereschit-origin", "Ursprung", "Der Anfang erscheint als Raum, aus dem Schöpfung lesbar wird.", ["Ursprung", "Anfang"]),
      meaningField("bereschit-hiddenness", "Verborgenheit", "Im Anfang ist die kommende Ordnung noch verborgen gegenwärtig.", ["Verborgenheit", "Potential"]),
      meaningField("bereschit-creation", "Schöpfung", "Bereschit markiert die Schwelle, an der Wirklichkeit in Gestalt tritt.", ["Schöpfung", "Werden"]),
    ],
    relatedSymbolSlugs: ["ursprung", "schoepfung", "licht"],
    biblicalReferences: [
      reference("bereschit-genesis-1-1", "Genesis 1,1", "Der erste Vers beginnt mit Bereschit.", "Anfang, Ursprung und Schöpfungsschwelle"),
    ],
  },
  {
    id: "majim",
    slug: "majim",
    hebrew: "מים",
    transliteration: "majim",
    germanMeaning: "Wasser",
    meaningThreshold: "Das Wasser steht im Codex für Ursprung, Übergang und verborgene Tiefe.",
    letterIds: ["mem", "jod", "mem"],
    possibleRootIds: [],
    rootNote: "מים wird nicht automatisch als gewöhnliche dreiradikalige Verbalwurzel behandelt.",
    meaningFields: [
      meaningField("majim-depth", "Tiefe", "Wasser kann als sichtbare und verborgene Tiefe gelesen werden.", ["Unsicherheit", "Verborgenheit"]),
      meaningField("majim-transition", "Übergang", "Wasser kann Grenze und Durchgang zugleich sein.", ["Schwelle", "Befreiung"]),
      meaningField("majim-new-birth", "Neugeburt", "Wasser kann Reinigung und neuen Anfang tragen.", ["Erneuerung", "Neuorientierung"]),
    ],
    relatedSymbolSlugs: ["wasser", "meer", "tiefe", "taufe", "leben"],
    biblicalReferences: [
      reference("majim-genesis-1-2", "Genesis 1,2", "Wasser steht am Anfang der Schöpfung.", "Urtiefe und Chaos vor der Ordnung"),
      reference("majim-exodus-14", "Exodus 14", "Das Meer wird zum Durchgang aus der Enge.", "Grenze, Übergang und Befreiung"),
      reference("majim-matthew-3", "Matthäus 3,13-17", "Jesus wird im Jordan getauft.", "Taufe, Übergang und Neugeburt"),
    ],
  },
  {
    id: "or",
    slug: "or",
    hebrew: "אור",
    transliteration: "or",
    germanMeaning: "Licht",
    meaningThreshold: "Or macht sichtbar, unterscheidbar und orientiert den Weg aus dem Verborgenen.",
    letterIds: ["aleph", "vav", "resh"],
    possibleRootIds: ["root-or"],
    meaningFields: [
      meaningField("or-light", "Licht", "Licht macht sichtbar und unterscheidbar.", ["Helligkeit", "Klarheit"]),
      meaningField("or-revelation", "Offenbarung", "Licht kann Verborgenes hervortreten lassen.", ["Offenheit", "Erkenntnis"]),
      meaningField("or-awareness", "Erkenntnis", "Licht kann Wahrnehmung und Bewusstsein öffnen.", ["Bewusstsein", "Klarheit"]),
      meaningField("or-orientation", "Orientierung", "Licht macht eine Spur sichtbar.", ["Klarheit", "Hoffnung"]),
      meaningField("or-presence", "Gegenwart", "Licht kann eine gegenwärtige Wirklichkeit erfahrbar machen.", ["Gegenwart", "Nahe"]),
      meaningField("or-visibility", "Sichtbarkeit", "Licht lässt Konturen und Unterschiede hervortreten.", ["Wahrnehmung", "Unterscheidung"]),
      meaningField("or-life", "Leben", "Licht kann mit Lebendigkeit und tragender Gegenwart verbunden werden.", ["Lebendigkeit", "Hoffnung"]),
    ],
    relatedSymbolSlugs: ["licht"],
    biblicalReferences: [
      reference("or-genesis-1-3", "Genesis 1,3", "Gott spricht: Es werde Licht.", "Schöpfung, Unterscheidung und Orientierung"),
      reference("or-exodus-13-21", "Exodus 13,21", "Die Feuersäule leuchtet Israel auf dem Weg.", "Orientierung und Führung"),
      reference("or-john-1-4-5", "Johannes 1,4-5", "Das Leben ist das Licht der Menschen.", "Licht, Leben und Gegenwart"),
    ],
  },
  {
    id: "esch",
    slug: "esch",
    hebrew: "אש",
    transliteration: "esch",
    germanMeaning: "Feuer",
    meaningThreshold: "Esch zeigt eine Gegenwart, die wärmt, ruft, reinigt und verwandelt.",
    letterIds: ["aleph", "shin"],
    possibleRootIds: [],
    rootNote: "Die lexikalische Einordnung wird in einer späteren Corpus-Phase ergänzt.",
    meaningFields: [
      meaningField("esh-fire", "Feuer", "Feuer kann als verborgene und sichtbare Energie gelesen werden.", ["Potential", "Energie"]),
      meaningField("esh-transformation", "Verwandlung", "Feuer kann Wärme, Läuterung und Veränderung sichtbar machen.", ["Energie", "Läuterung"]),
      meaningField("esh-presence", "Gegenwart", "Feuer kann eine wirksame und tragende Gegenwart sichtbar machen.", ["Nähe", "Offenbarung"]),
      meaningField("esh-purification", "Reinigung", "Feuer kann als Bild von Klärung und Läuterung gelesen werden.", ["Läuterung", "Erneuerung"]),
      meaningField("esh-calling", "Ruf", "Das Feuer des Dornbuschs verbindet Gegenwart mit persönlicher Ansprache.", ["Berufung", "Ausrichtung"]),
    ],
    relatedSymbolSlugs: ["feuer"],
    biblicalReferences: [
      reference("esh-exodus-3", "Exodus 3,2", "Der Dornbusch brennt und verbrennt nicht.", "Gegenwart, Ruf und Verwandlung"),
      reference("esh-exodus-13-21", "Exodus 13,21", "Die Feuersäule begleitet Israel durch die Nacht.", "Führung, Gegenwart und Weg"),
      reference("esh-malachi-3", "Maleachi 3,2-3", "Das Feuer des Schmelzers läutert.", "Reinigung und Verwandlung"),
    ],
  },
  {
    id: "lechem",
    slug: "lechem",
    hebrew: "לחם",
    transliteration: "lechem",
    germanMeaning: "Brot",
    meaningThreshold: "Lechem verbindet tägliche Nahrung mit Gabe, Gemeinschaft und tieferem Leben.",
    letterIds: ["lamed", "chet", "mem"],
    possibleRootIds: ["root-l-ch-m"],
    meaningFields: [
      meaningField("lechem-nourishment", "Nahrung", "Brot steht für alltägliche Versorgung und geteilte Gabe.", ["Versorgung", "Gemeinschaft"]),
      meaningField("lechem-gift", "Gabe", "Brot kann als empfangene Versorgung gelesen werden, die nicht allein aus eigener Verfügbarkeit kommt.", ["Gabe", "Vertrauen"]),
      meaningField("lechem-community", "Gemeinschaft", "Geteiltes Brot kann Gemeinschaft stiften und Beziehung sichtbar machen.", ["Gemeinschaft", "Teilen"]),
      meaningField("lechem-breaking", "Brechen", "Im Brechen wird Brot zur teilbaren Gabe und zum Zeichen gemeinsamer Nahrung.", ["Teilen", "Gemeinschaft"]),
      meaningField("lechem-life", "Leben", "Brot erhält Leben und kann auf eine innere Nahrung verweisen.", ["Leben", "Versorgung"]),
      meaningField("lechem-word", "Wort", "Brot und Wort stehen in einer Spannung von äußerer und innerer Nahrung.", ["Wort", "Ausrichtung"]),
    ],
    relatedSymbolSlugs: ["brot"],
    biblicalReferences: [
      reference("lechem-exodus-16", "Exodus 16,4", "Brot vom Himmel begleitet Israel durch die Wüste.", "Versorgung im Mangel"),
      reference("lechem-mark-4", "Markus 4,26-29", "Aus dem verborgenen Wachstum des Samens reift Korn.", "Verborgenes Leben und Reifung"),
      reference("lechem-deuteronomy-8", "Deuteronomium 8,3", "Der Mensch lebt nicht vom Brot allein.", "Brot und Wort als Nahrung"),
      reference("lechem-luke-24", "Lukas 24,30-31", "Beim Brechen des Brotes erkennen die Jünger Jesus.", "Teilen, Gemeinschaft und Offenbarung"),
      reference("lechem-john-6", "Johannes 6,35", "Jesus spricht vom Brot des Lebens.", "Christus-Bezug und innere Nahrung"),
    ],
  },
  {
    id: "elohim",
    slug: "elohim",
    hebrew: "\u05d0\u05dc\u05d4\u05d9\u05dd",
    transliteration: "elohim",
    germanMeaning: "Gott",
    meaningThreshold: "Elohim bleibt ehrfuerchtig als Gottesbezeichnung sichtbar: Ursprung, Gegenwart und Schöpfungshandeln werden nicht in ein Symbol aufgelöst.",
    gematria: 86,
    category: "word",
    letterIds: ["aleph", "lamed", "he", "jod", "mem"],
    possibleRootIds: [],
    rootNote: "Der Gottesname wird im Codex als kanonischer Schriftkörper sichtbar gehalten, nicht spekulativ etymologisiert.",
    meaningFields: [
      meaningField("elohim-presence", "Gegenwart", "Elohim steht am Anfang als wirksame Gegenwart.", ["Gegenwart", "Ehrfurcht"]),
      meaningField("elohim-origin", "Ursprung", "Der Name bindet den Anfang an Gottes Schöpfungshandeln.", ["Ursprung", "Schöpfung"]),
      meaningField("elohim-revelation", "Offenbarung", "Elohim wird durch Schaffen, Ruach und gesprochenes Licht erfahrbar.", ["Offenbarung", "Wort"]),
    ],
    relatedSymbolSlugs: ["ursprung", "offenbarung", "licht"],
    biblicalReferences: [
      reference("elohim-genesis-1-1", "Genesis 1,1", "Elohim schafft Himmel und Erde.", "Gott als Ursprung des Schöpfungsakts"),
      reference("elohim-genesis-1-2", "Genesis 1,2", "Die Ruach Elohim bewegt sich über den Wassern.", "Gottes Geist über der Tiefe"),
      reference("elohim-genesis-1-3", "Genesis 1,3", "Elohim spricht Licht.", "Gottes Sprechen führt in Sichtbarkeit"),
    ],
  },
  {
    id: "et",
    slug: "et",
    hebrew: "\u05d0\u05ea",
    transliteration: "et",
    germanMeaning: "Akkusativzeichen",
    meaningThreshold: "Et bleibt grammatisch zurueckhaltend und haelt zugleich Aleph und Tav, Anfang und Zeichen, in einem kleinen Schriftkoerper zusammen.",
    gematria: 401,
    category: "word",
    letterIds: ["aleph", "tav"],
    possibleRootIds: [],
    rootNote: "Et wird hier nicht spekulativ ueberhoeht, sondern als sichtbare Zeichenklammer im Vers gefuehrt.",
    meaningFields: [
      meaningField("et-sign", "Zeichen", "Et markiert im Satz eine Beziehung, ohne selbst Gegenstand der Handlung zu werden.", ["Zeichen", "Beziehung"]),
      meaningField("et-span", "Spannweite", "Aleph und Tav lassen Anfang und Markierung symbolisch nebeneinander stehen.", ["Anfang", "Gestalt"]),
    ],
    relatedSymbolSlugs: ["ursprung", "ordnung", "offenbarung"],
    biblicalReferences: [
      reference("et-genesis-1-1", "Genesis 1,1", "Et steht vor Himmel und Erde.", "Grammatische Beziehung und stille Zeichenklammer"),
    ],
  },
  {
    id: "tohu",
    slug: "tohu",
    hebrew: "\u05ea\u05d4\u05d5",
    transliteration: "tohu",
    germanMeaning: "Wüstheit · Formlosigkeit",
    meaningThreshold: "Tohu benennt den ungeformten Raum vor Ordnung: offen, unbewohnbar und noch nicht lesbar.",
    gematria: 411,
    category: "word",
    letterIds: ["tav", "he", "vav"],
    possibleRootIds: [],
    rootNote: "Tohu wird als Zustandswort von Genesis 1,2 gelesen und nicht als eigenständiger Raum erzwungen.",
    meaningFields: [
      meaningField("tohu-chaos", "Chaos", "Tohu steht für das Noch-nicht-Geordnete vor der ersten Unterscheidung.", ["Chaos", "Unordnung"]),
      meaningField("tohu-desert", "Wüstheit", "Das Wort berührt den Wüstenraum als Unbewohnbarkeit und Leere.", ["Wüste", "Leere"]),
      meaningField("tohu-hiddenness", "Verborgenheit", "Im Formlosen ist Gestalt noch verborgen.", ["Verborgenheit", "Potential"]),
    ],
    relatedSymbolSlugs: ["wueste", "tiefe", "ordnung"],
    biblicalReferences: [
      reference("tohu-genesis-1-2", "Genesis 1,2", "Die Erde ist tohu.", "Formlosigkeit vor Ordnung und Licht"),
    ],
  },
  {
    id: "bohu",
    slug: "bohu",
    hebrew: "\u05d1\u05d4\u05d5",
    transliteration: "bohu",
    germanMeaning: "Leere",
    meaningThreshold: "Bohu benennt die Leere des Anfangsraums: nicht fertiges Nichts, sondern noch unbewohnte Offenheit vor Gestalt.",
    gematria: 13,
    category: "word",
    letterIds: ["bet", "he", "vav"],
    possibleRootIds: [],
    rootNote: "Bohu wird als Grundform innerhalb der Versform vavohu sichtbar gehalten.",
    meaningFields: [
      meaningField("bohu-lack", "Leere", "Bohu macht den noch unbesetzten Anfangsraum sichtbar.", ["Leere", "Mangel"]),
      meaningField("bohu-receptivity", "Empfangsraum", "Die Leere kann Raum sein, in den Ordnung erst eintreten wird.", ["Empfang", "Werden"]),
      meaningField("bohu-hiddenness", "Verborgenheit", "Gestalt ist noch verborgen, aber nicht ausgeschlossen.", ["Verborgenheit", "Potential"]),
    ],
    relatedSymbolSlugs: ["wueste", "tiefe", "verborgenheit"],
    biblicalReferences: [
      reference("bohu-genesis-1-2", "Genesis 1,2", "Tohu wabohu beschreibt den ungeformten Zustand der Erde.", "Leere vor bewohnbarer Gestalt"),
    ],
  },
  {
    id: "vohu",
    slug: "vohu",
    hebrew: "\u05d5\u05d1\u05d4\u05d5",
    transliteration: "vohu",
    germanMeaning: "und Leere",
    meaningThreshold: "Vohu hält die Leere zusammen mit Tohu: kein fertiges Nichts, sondern ein unbesetzter Anfangsraum.",
    gematria: 19,
    category: "word",
    letterIds: ["vav", "bet", "he", "vav"],
    possibleRootIds: [],
    rootNote: "Die Form mit Vav wird als Versform aus Genesis 1,2 geführt; Bohu ohne Konjunktion bleibt darin enthalten.",
    meaningFields: [
      meaningField("vohu-lack", "Leere", "Vohu macht den unbesetzten Raum der Anfangsszene sichtbar.", ["Leere", "Mangel"]),
      meaningField("vohu-chaos", "Chaos", "Die Leere steht neben Tohu im Feld des Noch-nicht-Geordneten.", ["Chaos", "Unordnung"]),
      meaningField("vohu-receptivity", "Empfangsraum", "Die Leere kann als Raum gelesen werden, in den Ordnung erst eintreten wird.", ["Empfang", "Werden"]),
    ],
    relatedSymbolSlugs: ["wueste", "verborgenheit"],
    biblicalReferences: [
      reference("vohu-genesis-1-2", "Genesis 1,2", "Tohu vavohu beschreibt den ungeformten Zustand der Erde.", "Leere vor bewohnbarer Gestalt"),
    ],
  },
  {
    id: "choschech",
    slug: "choschech",
    hebrew: "\u05d7\u05e9\u05da",
    transliteration: "choschech",
    germanMeaning: "Finsternis",
    meaningThreshold: "Choschech ist die bedeckte Sichtbarkeit vor dem ersten Licht: nicht Ziel, sondern Schwelle zur Offenbarung.",
    gematria: 328,
    category: "word",
    letterIds: ["chet", "shin", "kaf"],
    possibleRootIds: [],
    rootNote: "Choschech wird im Codex als Dunkelheitsmotiv vor Genesis 1,3 geführt.",
    meaningFields: [
      meaningField("choschech-hiddenness", "Verborgenheit", "Finsternis verdeckt Konturen, ohne die Wirklichkeit aufzuheben.", ["Verborgenheit", "Nichtsehen"]),
      meaningField("choschech-chaos", "Dunkel vor Ordnung", "Das Dunkel steht vor der ersten lichten Unterscheidung.", ["Chaos", "Ordnung"]),
      meaningField("choschech-revelation", "Schwelle zum Licht", "Choschech bereitet die Frage nach Offenbarung und Sichtbarkeit vor.", ["Offenbarung", "Licht"]),
    ],
    relatedSymbolSlugs: ["verborgenheit", "licht", "tiefe"],
    biblicalReferences: [
      reference("choschech-genesis-1-2", "Genesis 1,2", "Finsternis liegt auf der Tiefe.", "Dunkelheit vor dem gesprochenen Licht"),
    ],
  },
  {
    id: "tehom",
    slug: "tehom",
    hebrew: "\u05ea\u05d4\u05d5\u05dd",
    transliteration: "tehom",
    germanMeaning: "Tiefe · Urflut · Urmeer",
    meaningThreshold: "Nicht einfach Wasser, sondern die ungeformte Tiefe vor der Schöpfungsordnung.",
    gematria: 451,
    category: "word",
    letterIds: ["tav", "he", "vav", "mem"],
    possibleRootIds: [],
    rootNote: "Tehom wird hier als uranfänglicher Tiefenraum gelesen, nicht als gewöhnliche Verbalwurzel.",
    meaningFields: [
      meaningField("tehom-origin", "Ursprung", "Tehom bezeichnet den verborgenen Ursprung vor Ordnung und Sichtbarkeit.", ["Ursprung", "Anfang"]),
      meaningField("tehom-depth", "Tiefe", "Tehom ist die Tiefe vor der Trennung und vor dem Licht.", ["Tiefe", "Verborgenheit"]),
      meaningField("tehom-hiddenness", "Verborgenheit", "Die Tiefe bewahrt Möglichkeit, bevor sie offenbar wird.", ["Verborgenheit", "Möglichkeit"]),
      meaningField("tehom-potential", "Potential", "Tehom trägt ungeformte Möglichkeit, ohne mit Chaos im modernen Sinn gleichgesetzt zu werden.", ["Potential", "Werden"]),
      meaningField("tehom-water", "Wasser", "Tehom steht im Anfangsraum nahe bei den Wassern, ist aber nicht einfach Wasser.", ["Wasser", "Tiefe"]),
      meaningField("tehom-birth", "Geburt", "Aus der Tiefe kann Gestalt hervortreten.", ["Geburt", "Hervorkommen"]),
      meaningField("tehom-revelation", "Offenbarung", "Aus der Tiefe erhebt sich das Wort und führt zur Offenbarung.", ["Offenbarung", "Sichtbarwerden"]),
    ],
    relatedSymbolSlugs: ["wasser", "tiefe", "licht", "wueste"],
    biblicalReferences: [
      reference("tehom-genesis-1-2", "Genesis 1,2", "Und Finsternis lag auf der Tiefe.", "Die Tiefe erscheint vor Ordnung, Trennung und Licht."),
    ],
  },
  {
    id: "ruach",
    slug: "ruach",
    hebrew: "\u05e8\u05d5\u05d7",
    transliteration: "ruach",
    germanMeaning: "Geist · Atem · Wind",
    meaningThreshold: "Ruach trägt Bewegung, Leben und Gottes Geist in einem einzigen hebräischen Wort.",
    gematria: 214,
    category: "word",
    letterIds: ["resh", "vav", "chet"],
    possibleRootIds: [],
    rootNote: "Ruach wird hier als Geist, Wind und Atem gelesen: unsichtbare Bewegung zwischen Ursprung und Offenbarung.",
    meaningFields: [
      meaningField("ruach-spirit", "Geist", "Ruach bezeichnet Geist als unsichtbare, wirksame Gegenwart.", ["Gegenwart", "Unsichtbarkeit"]),
      meaningField("ruach-breath", "Atem", "Ruach verbindet Leben mit Atem und innerer Bewegung.", ["Atem", "Leben"]),
      meaningField("ruach-wind", "Wind", "Ruach bewegt, ohne selbst sichtbar zu sein.", ["Bewegung", "Wirkung"]),
      meaningField("ruach-revelation", "Offenbarung", "Ruach trägt das Wort, bewegt die Stimme und öffnet zum Licht.", ["Offenbarung", "Stimme"]),
      meaningField("ruach-connection", "Verbindung", "Ruach verbindet Wasser, Tiefe, Wort, Stimme und Licht.", ["Verbindung", "Brücke"]),
    ],
    relatedSymbolSlugs: ["wasser", "tiefe", "licht", "leben"],
    biblicalReferences: [
      reference("ruach-genesis-1-2", "Genesis 1,2", "Die Ruach Gottes schwebt über den Wassern.", "Geist, Wind und Atem über der Anfangstiefe"),
    ],
  },
  {
    id: "merachefet",
    slug: "merachefet",
    hebrew: "\u05de\u05e8\u05d7\u05e4\u05ea",
    transliteration: "merachefet",
    germanMeaning: "schwebend · brütend",
    meaningThreshold: "Merachefet beschreibt die behutsame Bewegung der Ruach über den Wassern: Nähe ohne Zugriff, Gegenwart vor dem Wort.",
    gematria: 728,
    category: "word",
    letterIds: ["mem", "resh", "chet", "pe", "tav"],
    possibleRootIds: [],
    rootNote: "Die genaue Wurzelanalyse bleibt zurückhaltend; im Codex trägt das Wort die Bewegung von Genesis 1,2.",
    meaningFields: [
      meaningField("merachefet-movement", "Schweben", "Merachefet macht Bewegung sichtbar, ohne die Tiefe zu verdrängen.", ["Bewegung", "Nähe"]),
      meaningField("merachefet-presence", "Gegenwart", "Die Ruach ist gegenwärtig über den Wassern, bevor Licht gesprochen wird.", ["Gegenwart", "Atem"]),
      meaningField("merachefet-birth", "Brüten", "Das schwebende Verweilen kann als vorbereitender Raum des Werdens gelesen werden.", ["Geburt", "Werden"]),
    ],
    relatedSymbolSlugs: ["geist", "wasser", "tiefe"],
    biblicalReferences: [
      reference("merachefet-genesis-1-2", "Genesis 1,2", "Die Ruach Gottes schwebt über den Wassern.", "Bewegte Gegenwart über der Anfangstiefe"),
    ],
  },
  {
    id: "rachaf",
    slug: "rachaf",
    hebrew: "\u05e8\u05d7\u05e3",
    transliteration: "rachaf",
    germanMeaning: "schweben",
    meaningThreshold: "Rachaf benennt die leise Bewegung ueber den Wassern: Naehe ohne Zugriff, Gegenwart vor dem ersten Licht.",
    gematria: 288,
    category: "word",
    letterIds: ["resh", "chet", "pe"],
    possibleRootIds: [],
    rootNote: "Rachaf wird als Grundspur hinter merachefet gefuehrt, ohne die flektierte Versform zu ersetzen.",
    meaningFields: [
      meaningField("rachaf-movement", "Schweben", "Rachaf macht Bewegung sichtbar, die die Tiefe beruehrt, ohne sie zu verdraengen.", ["Bewegung", "Naehe"]),
      meaningField("rachaf-presence", "Gegenwart", "Das Schweben deutet eine wirksame Gegenwart vor dem Wort an.", ["Gegenwart", "Atem"]),
      meaningField("rachaf-birth", "Brueten", "Die Bewegung kann als vorbereitender Raum des Werdens gelesen werden.", ["Geburt", "Werden"]),
    ],
    relatedSymbolSlugs: ["geist", "wasser", "tiefe"],
    biblicalReferences: [
      reference("rachaf-genesis-1-2", "Genesis 1,2", "Die Ruach Gottes schwebt ueber den Wassern.", "Schweben als behutsame Bewegung ueber der Anfangstiefe"),
    ],
  },
  {
    id: "amar",
    slug: "amar",
    hebrew: "\u05d0\u05de\u05e8",
    transliteration: "amar",
    germanMeaning: "sprechen",
    meaningThreshold: "Amar ist das konkrete Sprechen in Genesis 1,3: Der Ruf lässt Licht in die Lesbarkeit treten.",
    gematria: 241,
    category: "word",
    letterIds: ["aleph", "mem", "resh"],
    possibleRootIds: [],
    rootNote: "Amar wird als Sprechverb neben Davar geführt: Es benennt den Akt des Sagens, während Davar das wirksame Wortfeld trägt.",
    meaningFields: [
      meaningField("amar-word", "Sprechen", "Amar markiert den Moment, in dem Sinn hörbar wird.", ["Wort", "Stimme"]),
      meaningField("amar-creation", "Schöpfungsruf", "Das Sprechen ruft Licht und öffnet Ordnung.", ["Schöpfung", "Licht"]),
      meaningField("amar-revelation", "Offenbarung", "Im Gesprochenen tritt das Verborgene in Sichtbarkeit.", ["Offenbarung", "Sichtbarkeit"]),
    ],
    relatedSymbolSlugs: ["wort", "licht", "offenbarung"],
    biblicalReferences: [
      reference("amar-genesis-1-3", "Genesis 1,3", "Gott spricht: Es werde Licht.", "Sprechen als Übergang von Tiefe zu Licht"),
    ],
  },
  {
    id: "jehi",
    slug: "jehi",
    hebrew: "\u05d9\u05d4\u05d9",
    transliteration: "jehi",
    germanMeaning: "es werde",
    meaningThreshold: "Jehi ist der knappe Ruf ins Werden: Ein Punkt des Wortes tritt aus der Tiefe in sichtbare Wirklichkeit.",
    gematria: 25,
    category: "word",
    letterIds: ["jod", "he", "jod"],
    possibleRootIds: [],
    rootNote: "Jehi wird als konkrete Genesis-1,3-Form von haja gefuehrt.",
    meaningFields: [
      meaningField("jehi-calling", "Ruf", "Jehi markiert den Moment, in dem das Wort Wirklichkeit anspricht.", ["Ruf", "Wort"]),
      meaningField("jehi-becoming", "Werden", "Das Gesagte tritt aus Moeglichkeit in Ereignis.", ["Werden", "Uebergang"]),
      meaningField("jehi-light", "Lichtwerdung", "Erste Lichtspur: Jehi richtet den Ruf auf Or.", ["Licht", "Offenbarung"]),
    ],
    relatedSymbolSlugs: ["licht", "wort", "offenbarung", "wandlung"],
    biblicalReferences: [
      reference("jehi-genesis-1-3", "Genesis 1,3", "Gott spricht: Es werde Licht.", "Werden als Ruf in Sichtbarkeit"),
    ],
  },
  {
    id: "haja",
    slug: "haja",
    hebrew: "\u05d4\u05d9\u05d4",
    transliteration: "haja",
    germanMeaning: "sein · werden",
    meaningThreshold: "Haja hält Sein und Werden zusammen: Der Anfang ist nicht statisch, sondern geht in Gestalt über.",
    gematria: 20,
    category: "word",
    letterIds: ["he", "jod", "he"],
    possibleRootIds: [],
    rootNote: "Haja wird in Genesis 1,2-3 über gebeugte Formen sichtbar und als Werden behutsam geführt.",
    meaningFields: [
      meaningField("haja-being", "Sein", "Haja benennt Gegenwart als Dasein.", ["Gegenwart", "Sein"]),
      meaningField("haja-becoming", "Werden", "Das Wort öffnet den Übergang von Zustand zu sichtbarer Wirklichkeit.", ["Werden", "Übergang"]),
      meaningField("haja-revelation", "Erscheinen", "Was wird, tritt aus Verborgenheit in Lesbarkeit.", ["Offenbarung", "Gestalt"]),
    ],
    relatedSymbolSlugs: ["wandlung", "ordnung", "licht"],
    biblicalReferences: [
      reference("haja-genesis-1-2", "Genesis 1,2", "Die Erde war in einem ungeformten Zustand.", "Sein als noch nicht geordnete Gegenwart"),
      reference("haja-genesis-1-3", "Genesis 1,3", "Licht werde.", "Werden als Ruf in Sichtbarkeit"),
    ],
  },
  {
    id: "wajehi",
    slug: "wajehi",
    hebrew: "\u05d5\u05d9\u05d4\u05d9",
    transliteration: "wajehi",
    germanMeaning: "und es wurde · und es geschah",
    meaningThreshold: "Wajehi bestätigt den Schöpfungsruf: Das gesprochene Licht geht in Ereignis und Wirklichkeit über.",
    gematria: 31,
    category: "word",
    letterIds: ["vav", "jod", "he", "jod"],
    possibleRootIds: [],
    rootNote: "Wajehi wird als Versform von Haja gelesen und mit dem Ereignischarakter des gesprochenen Lichts verbunden.",
    meaningFields: [
      meaningField("wajehi-event", "Ereignis", "Wajehi macht aus dem Ruf ein Geschehen.", ["Ereignis", "Wirklichkeit"]),
      meaningField("wajehi-transition", "Übergang", "Das Wort markiert den Übergang vom Gesagten zum Gewordenen.", ["Übergang", "Werden"]),
      meaningField("wajehi-light", "Lichtwerdung", "Erste Lichtspur: Wajehi bestätigt das Erscheinen des Lichts.", ["Licht", "Offenbarung"]),
    ],
    relatedSymbolSlugs: ["licht", "ordnung", "offenbarung"],
    biblicalReferences: [
      reference("wajehi-genesis-1-3", "Genesis 1,3", "Und es wurde Licht.", "Das gesprochene Licht wird Ereignis"),
    ],
  },
  {
    id: "tov",
    slug: "tov",
    hebrew: "\u05d8\u05d5\u05d1",
    transliteration: "tov",
    germanMeaning: "gut",
    meaningThreshold: "Tov benennt die Gutheit, die nach dem ersten Licht ausgesprochen wird: Sichtbarkeit wird als tragfaehige Ordnung erkannt.",
    gematria: 17,
    category: "word",
    letterIds: ["tet", "vav", "bet"],
    possibleRootIds: [],
    rootNote: "Tov wird als Anschlusswort von Genesis 1,4 gefuehrt: nicht flache Moral, sondern stimmige, lebensfaehige und von Gott erkannte Qualitaet.",
    meaningFields: [
      meaningField("tov-goodness", "Gutheit", "Tov bezeichnet eine stimmige Guete, die nicht nur behauptet, sondern erkannt wird.", ["Gutheit", "Bejahung", "Erkennen"]),
      meaningField("tov-order", "Tragfaehige Ordnung", "Das Gute wird sichtbar, nachdem Licht Wahrnehmung und Unterscheidung ermoeglicht.", ["Ordnung", "Licht", "Wahrnehmung"]),
      meaningField("tov-life", "Lebensdienlichkeit", "Gut ist, was Leben, Orientierung und Bestand traegt.", ["Leben", "Orientierung", "Bestand"]),
    ],
    relatedSymbolSlugs: ["licht", "ordnung", "offenbarung"],
    biblicalReferences: [
      reference("tov-genesis-1-4", "Genesis 1,4", "Gott sieht, dass das Licht gut ist.", "Gutheit als erste Antwort auf das Licht"),
    ],
  },
  {
    id: "raah",
    slug: "raah",
    hebrew: "\u05e8\u05d0\u05d4",
    transliteration: "raah",
    germanMeaning: "sehen",
    meaningThreshold: "Raah bereitet Genesis 1,4 vor: Licht wird nicht nur erschaffen, sondern gesehen und als traegende Guete erkannt.",
    category: "word",
    letterIds: ["resh", "aleph", "he"],
    possibleRootIds: ["root-r-a-h"],
    rootNote: "Raah wird als Folgeschwelle des Lichts gefuehrt; in Genesis 1,3 bleibt das Sehen vorbereitet und nicht dominant.",
    meaningFields: [
      meaningField("raah-seeing", "Sehen", "Raah benennt Wahrnehmung: Licht tritt vor einen Blick und wird lesbar.", ["Sehen", "Wahrnehmung", "Licht"]),
      meaningField("raah-recognition", "Erkenntnis", "Sehen wird zur Erkenntnis, wenn das Sichtbare als bedeutungsvoll erkannt wird.", ["Erkenntnis", "Deutung"]),
      meaningField("raah-revelation", "Offenbarung", "Was gesehen wird, ist nicht mehr nur verborgen, sondern erscheint im Raum der Offenbarung.", ["Offenbarung", "Sichtbarkeit"]),
    ],
    relatedSymbolSlugs: ["licht", "auge", "erkenntnis", "offenbarung"],
    biblicalReferences: [
      reference("raah-genesis-1-4", "Genesis 1,4", "Gott sah das Licht.", "Sehen als erste Pruefung des erschaffenen Lichts"),
    ],
  },
  {
    id: "al",
    slug: "al",
    hebrew: "\u05e2\u05dc",
    transliteration: "al",
    germanMeaning: "ueber / auf",
    meaningThreshold: "Al markiert die Lage an der Schwelle: Tiefe wird nicht verlassen, sondern von oben her beruehrt.",
    category: "word",
    letterIds: ["ayin", "lamed"],
    possibleRootIds: [],
    rootNote: "Al wird hier als kleine Praepositionsschwelle in Genesis 1,2 sichtbar gehalten.",
    meaningFields: [
      meaningField("al-surface", "Oberflaeche", "Al beschreibt die Lage auf oder ueber der Tiefe.", ["Oberflaeche", "Schwelle"]),
      meaningField("al-relation", "Beziehung", "Das Wort verbindet Finsternis, Ruach, Tiefe und Wasser in einer raeumlichen Beziehung.", ["Beziehung", "Verbindung"]),
    ],
    relatedSymbolSlugs: ["wasser", "tiefe", "offenbarung"],
    biblicalReferences: [
      reference("al-genesis-1-2", "Genesis 1,2", "Finsternis liegt auf der Tiefe; Ruach schwebt ueber den Wassern.", "Schwelle zwischen Tiefe und Oberflaeche"),
    ],
  },
  {
    id: "pnei",
    slug: "pnei",
    hebrew: "\u05e4\u05e0\u05d9",
    transliteration: "pnei",
    germanMeaning: "Angesicht / Oberflaeche",
    meaningThreshold: "Pnei macht die Tiefe als Angesicht lesbar: nicht flach, sondern beruehrbar.",
    category: "word",
    letterIds: ["pe", "nun", "jod"],
    possibleRootIds: [],
    rootNote: "Pnei wird als Versform der Oberflaechen- und Angesichtsspur in Genesis 1,2 gefuehrt.",
    meaningFields: [
      meaningField("pnei-face", "Angesicht", "Pnei benennt die Oberflaeche als Antlitz einer Tiefe.", ["Angesicht", "Wahrnehmung"]),
      meaningField("pnei-threshold", "Schwelle", "An Pnei beruehren sich Tiefe, Ruach und Blick.", ["Schwelle", "Beruehrung"]),
    ],
    relatedSymbolSlugs: ["wasser", "tiefe", "offenbarung"],
    biblicalReferences: [
      reference("pnei-genesis-1-2", "Genesis 1,2", "Finsternis und Ruach werden auf dem Angesicht der Tiefe und der Wasser verortet.", "Oberflaeche als beruehrbare Tiefe"),
    ],
  },
  {
    id: "davar",
    slug: "davar",
    hebrew: "דבר",
    transliteration: "davar",
    germanMeaning: "Wort · Sache · Ereignis",
    meaningThreshold: "Im Hebräischen ist ein Wort nie nur Sprache, sondern immer auch Wirklichkeit.",
    gematria: 206,
    category: "word",
    letterIds: ["dalet", "bet", "resh"],
    possibleRootIds: ["root-d-b-r"],
    meaningFields: [
      meaningField("davar-revelation", "Offenbarung", "Davar bringt Verborgenes hervor und macht Wirklichkeit lesbar.", ["Offenbarung", "Sichtbarwerden"]),
      meaningField("davar-creation", "Schöpfung", "Davar ruft, ordnet und bringt hervor.", ["Schöpfung", "Hervorbringen"]),
      meaningField("davar-reality", "Wirklichkeit", "Davar ist Wort, Sache, Ereignis und wirksame Wirklichkeit.", ["Wirklichkeit", "Ereignis"]),
      meaningField("davar-language", "Sprache", "Davar ist Sprache als geschehendes Wort, nicht nur Information.", ["Sprache", "Wort"]),
      meaningField("davar-order", "Ordnung", "Davar ordnet den offenen Raum und gibt Richtung.", ["Ordnung", "Ausrichtung"]),
      meaningField("davar-calling", "Ruf", "Davar kann als Ansprache gehört werden, die in Bewegung setzt.", ["Ruf", "Hören"]),
      meaningField("davar-encounter", "Begegnung", "Davar wird hörbar, wo Mensch und Gegenwart einander begegnen.", ["Begegnung", "Gegenwart"]),
    ],
    relatedSymbolSlugs: ["licht", "wueste", "brot"],
    biblicalReferences: [
      reference("davar-genesis-1-3", "Genesis 1,3", "Gott spricht: Es werde Licht.", "Licht entsteht durch das Wort"),
      reference("davar-deuteronomy-8-3", "Deuteronomium 8,3", "Der Mensch lebt nicht vom Brot allein.", "Der Mensch lebt vom Wort als tieferer Nahrung"),
    ],
  },
  {
    id: "qol",
    slug: "qol",
    hebrew: "קול",
    transliteration: "qol",
    germanMeaning: "Stimme · Klang",
    meaningThreshold: "Qol meint nicht nur hörbaren Schall, sondern das Wahrnehmbarwerden einer Gegenwart.",
    gematria: 136,
    category: "word",
    letterIds: ["qof", "vav", "lamed"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("qol-revelation", "Offenbarung", "Qol macht das Wort als hörbare Gegenwart erfahrbar.", ["Offenbarung", "Stimme"]),
      meaningField("qol-calling", "Ruf", "Qol ruft aus dem Verborgenen und setzt in Bewegung.", ["Ruf", "Ausrichtung"]),
      meaningField("qol-listening", "Hören", "Qol verlangt ein empfangendes Hören, bevor Verstehen Gestalt gewinnt.", ["Hören", "Empfang"]),
      meaningField("qol-guidance", "Führung", "Qol kann eine Richtung öffnen, ohne den ganzen Weg sichtbar zu machen.", ["Führung", "Weg"]),
      meaningField("qol-presence", "Gegenwart", "Qol lässt Gegenwart hörbar werden.", ["Gegenwart", "Nähe"]),
      meaningField("qol-encounter", "Begegnung", "Qol wird zum Ort, an dem Mensch und Ruf einander begegnen.", ["Begegnung", "Antwort"]),
      meaningField("qol-perception", "Wahrnehmung", "Qol schult die Wahrnehmung für das, was nicht zuerst sichtbar ist.", ["Wahrnehmung", "Achtsamkeit"]),
    ],
    relatedSymbolSlugs: ["wueste", "licht"],
    biblicalReferences: [],
  },
  {
    id: "midbar",
    slug: "midbar",
    hebrew: "מדבר",
    transliteration: "midbar",
    germanMeaning: "Wüste",
    meaningThreshold: "Midbar ist der leere Raum, in dem Mangel, Weg und hörbares Wort zusammenfinden.",
    letterIds: ["mem", "dalet", "bet", "resh"],
    possibleRootIds: ["root-d-b-r"],
    meaningFields: [
      meaningField("midbar-desert", "Wüste", "Midbar bezeichnet die Wüste und kann als Raum der Leere und des Weges gelesen werden.", ["Wüste", "Leere", "Weg"]),
      meaningField("midbar-testing", "Prüfung", "In der Wüste tritt hervor, worauf Vertrauen und Abhängigkeit gerichtet sind.", ["Prüfung", "Abhängigkeit", "Vertrauen"]),
      meaningField("midbar-guidance", "Führung", "Die Wüste kann zum Raum werden, in dem Führung als leise Spur sichtbar wird.", ["Führung", "Weg", "Übergang"]),
      meaningField("midbar-word", "Stimme und Wort", "Midbar kann in behutsamer Nähe zum Bedeutungsfeld von davar gelesen werden, ohne beide Wörter gleichzusetzen.", ["Stimme", "Wort", "Hören"]),
      meaningField("midbar-reduction", "Reduktion", "Die Wüste entzieht Gewohntes und macht Mangel erfahrbar.", ["Leere", "Prüfung"]),
      meaningField("midbar-listening", "Hören", "Die Wüste kann als Raum der Sammlung und des Hörens gelesen werden.", ["Stille", "Ausrichtung"]),
    ],
    relatedSymbolSlugs: ["wueste"],
    biblicalReferences: [
      reference("midbar-exodus-16", "Exodus 16", "Israel zieht durch die Wüste und erlebt Mangel und Versorgung.", "Leere, Abhängigkeit und Führung"),
      reference("midbar-deuteronomy-8", "Deuteronomium 8", "Der Weg durch die Wüste wird als Prüfung und Lernweg erinnert.", "Prüfung, Vertrauen und Übergang"),
      reference("midbar-matthew-4", "Matthaeus 4,1-11", "Jesus wird in der Wüste versucht.", "Prüfung und Vertrauen"),
      reference("midbar-exodus-3", "Exodus 3,1", "Mose hütet die Herde jenseits der Wüste.", "Stille, Schwelle und Ruf"),
    ],
  },
  ...phase36AHebrewWords,
];
