import type { HebrewLetter, HebrewLetterSymbolism } from "@/types/hebrew";

const interpretive = (
  id: string,
  label: string,
  description: string,
): HebrewLetterSymbolism => ({
  id,
  label,
  description,
  provenance: "interpretive",
});

const genesisReference = (id: string, relation: string) => ({
  id,
  reference: "Genesis 1,1-3",
  context: "Der biblische Anfangsanker zeigt Ursprung, Tiefe/Wasser/Ruach und Wort/Licht als erste gemeinsame Schriftbewegung.",
  relation,
  provenance: "canonical" as const,
});

export const hebrewLetters: HebrewLetter[] = [
  {
    id: "aleph",
    glyph: "\u05d0",
    name: "Aleph",
    transcription: "ʾ",
    numericValue: 1,
    alphabetPosition: 1,
    symbolism: [
      interpretive("aleph-origin", "Ursprung", "Aleph kann als stiller Anfang vor dem Klang gelesen werden."),
      interpretive("aleph-breath", "Atem", "Aleph deutet den unsichtbaren Atem an, aus dem Wort und Licht hervortreten."),
    ],
    archetypalMeanings: ["Ursprung", "Einheit", "Atem", "verborgene Gegenwart"],
    relatedSymbolSlugs: ["ursprung", "licht", "offenbarung", "wort", "erde"],
    relatedWordIds: ["bereschit", "bara", "elohim", "et", "erez", "amar", "or"],
    biblicalReferences: [genesisReference("aleph-genesis-1-1-3", "Aleph verbindet Elohim, et, eretz, amar und or: Ursprung, Gott, Erde, Wort und Licht.")],
    experienceFields: ["Anfang", "Stille", "Ausrichtung"],
  },
  {
    id: "bet",
    glyph: "\u05d1",
    name: "Bet",
    transcription: "b/v",
    numericValue: 2,
    alphabetPosition: 2,
    symbolism: [
      interpretive("bet-house", "Haus", "Bet kann als Haus, Innenraum und erste bergende Form gelesen werden."),
      interpretive("bet-beginning", "Anfangsraum", "Bet kann Anfang als bergenden Innenraum lesbar machen."),
    ],
    archetypalMeanings: ["Haus", "Innenraum", "Empfang", "Anfangsraum"],
    relatedSymbolSlugs: ["ursprung", "schoepfung", "wueste"],
    relatedWordIds: ["bereschit", "bara", "bohu", "vohu"],
    biblicalReferences: [genesisReference("bet-genesis-1-1-2", "Bet oeffnet Bereschit und Bara; in Bohu/Vohu beruehrt es den noch leeren Raum.")],
    experienceFields: ["Geborgenheit", "Grenze", "Beziehung"],
  },
  {
    id: "gimel",
    glyph: "\u05d2",
    name: "Gimel",
    transcription: "g",
    numericValue: 3,
    alphabetPosition: 3,
    symbolism: [
      interpretive("gimel-giving", "Gabe", "Gimel kann als Bewegung des Gebens und Hinwendens gelesen werden."),
    ],
    archetypalMeanings: ["Gabe", "Bewegung", "Hinwendung"],
    relatedSymbolSlugs: ["brot"],
    relatedWordIds: ["gan", "dagan"],
    biblicalReferences: [],
    experienceFields: ["Gabe", "Bewegung"],
  },
  {
    id: "dalet",
    glyph: "\u05d3",
    name: "Dalet",
    transcription: "d",
    numericValue: 4,
    alphabetPosition: 4,
    symbolism: [
      interpretive("dalet-threshold", "Schwelle", "Dalet kann als Tuer, Schwelle und Eintritt gelesen werden."),
    ],
    archetypalMeanings: ["Schwelle", "Tuer", "Eintritt"],
    relatedSymbolSlugs: ["wueste", "wort"],
    relatedWordIds: ["midbar", "davar", "derech"],
    biblicalReferences: [],
    experienceFields: ["Schwelle", "Eintritt"],
  },
  {
    id: "he",
    glyph: "\u05d4",
    name: "He",
    transcription: "h",
    numericValue: 5,
    alphabetPosition: 5,
    symbolism: [
      interpretive("he-breath-window", "Atemfenster", "He kann als offener Hauch und Fenster des Erscheinens gelesen werden."),
      interpretive("he-revelation", "Erscheinen", "He laesst Verborgenes nicht erzwingen, sondern hervortreten."),
    ],
    archetypalMeanings: ["Atem", "Fenster", "Erscheinen", "Offenheit"],
    relatedSymbolSlugs: ["licht", "offenbarung", "wandlung"],
    relatedWordIds: ["elohim", "tohu", "bohu", "vohu", "tehom", "jehi", "haja", "wajehi"],
    biblicalReferences: [genesisReference("he-genesis-1-1-3", "He steht in Elohim, Tohu, Bohu, Tehom und Jehi: Atem und Erscheinung zwischen Tiefe und Werden.")],
    experienceFields: ["Atem", "Offenheit", "Sichtbarwerden"],
  },
  {
    id: "vav",
    glyph: "\u05d5",
    name: "Vav",
    transcription: "v/w",
    numericValue: 6,
    alphabetPosition: 6,
    symbolism: [
      interpretive("vav-connection", "Verbindung", "Vav kann als verbindende Linie gelesen werden, die getrennte Felder zusammenhaelt."),
      interpretive("vav-and", "Und", "Vav traegt die Bewegung von Zustand zu Ereignis."),
    ],
    archetypalMeanings: ["Verbindung", "Linie", "Vermittlung", "Fortgang"],
    relatedSymbolSlugs: ["wasser", "licht", "uebergang"],
    relatedWordIds: ["schamajim", "tohu", "bohu", "vohu", "choschech", "tehom", "ruach", "or", "wajehi"],
    biblicalReferences: [genesisReference("vav-genesis-1-1-3", "Vav verbindet Himmel, ungeformten Zustand, Ruach und Lichtwerdung.")],
    experienceFields: ["Verbindung", "Vermittlung", "Fortgang"],
  },
  {
    id: "zayin",
    glyph: "\u05d6",
    name: "Zayin",
    transcription: "z",
    numericValue: 7,
    alphabetPosition: 7,
    symbolism: [
      interpretive("zayin-cut", "Unterscheidung", "Zayin kann als scharfe Markierung und Unterscheidung gelesen werden."),
    ],
    archetypalMeanings: ["Unterscheidung", "Markierung"],
    relatedSymbolSlugs: ["ordnung"],
    relatedWordIds: ["mizbeach"],
    biblicalReferences: [],
    experienceFields: ["Unterscheidung"],
  },
  {
    id: "chet",
    glyph: "\u05d7",
    name: "Chet",
    transcription: "ch",
    numericValue: 8,
    alphabetPosition: 8,
    symbolism: [
      interpretive("chet-life", "Leben", "Chet kann als eingehegter Lebensraum und tragende Lebendigkeit gelesen werden."),
      interpretive("chet-hidden-life", "Verborgenes Leben", "In Finsternis und Ruach bleibt Leben noch verborgen, aber nicht abwesend."),
    ],
    archetypalMeanings: ["Leben", "Innenraum", "Schutz", "verborgene Lebendigkeit"],
    relatedSymbolSlugs: ["leben", "wasser", "tiefe", "licht"],
    relatedWordIds: ["choschech", "ruach", "merachefet", "rachaf"],
    biblicalReferences: [genesisReference("chet-genesis-1-2", "Chet steht in Choschech, Ruach und Rachaf: Dunkel, Atem und schwebende Bewegung.")],
    experienceFields: ["Leben", "Gemeinschaft", "Atem"],
  },
  {
    id: "tet",
    glyph: "\u05d8",
    name: "Tet",
    transcription: "t",
    numericValue: 9,
    alphabetPosition: 9,
    symbolism: [
      interpretive("tet-good-hidden", "verborgenes Gut", "Tet kann als verborgene Guete gelesen werden, die noch nicht ausgesprochen ist."),
    ],
    archetypalMeanings: ["verborgene Guete", "Reifung"],
    relatedSymbolSlugs: ["licht"],
    relatedWordIds: ["tov"],
    biblicalReferences: [],
    experienceFields: ["Reifung"],
  },
  {
    id: "jod",
    glyph: "\u05d9",
    name: "Jod",
    transcription: "j/y",
    numericValue: 10,
    alphabetPosition: 10,
    symbolism: [
      interpretive("jod-point", "Punkt", "Jod ist der kleine gesetzte Punkt, aus dem Bewegung beginnen kann."),
      interpretive("jod-impulse", "Wirkimpuls", "Jod kann eine wirkende Spur bezeichnen, die ins Werden fuehrt."),
    ],
    archetypalMeanings: ["Punkt", "Impuls", "Hand", "wirkende Spur"],
    relatedSymbolSlugs: ["wasser", "licht", "wandlung"],
    relatedWordIds: ["bereschit", "elohim", "schamajim", "majim", "pnei", "jehi", "haja", "wajehi"],
    biblicalReferences: [genesisReference("jod-genesis-1-1-3", "Jod erscheint in Bereschit, Elohim, Schamajim, Majim und Jehi; in Jehi markiert es den Impuls des Werdens.")],
    experienceFields: ["Impuls", "Moeglichkeit", "Beginn"],
  },
  {
    id: "kaf",
    glyph: "\u05db",
    finalForm: "\u05da",
    name: "Kaf",
    transcription: "k/ch",
    numericValue: 20,
    alphabetPosition: 11,
    symbolism: [
      interpretive("kaf-palm", "Handflaeche", "Kaf kann als fassende, bergende und formende Hand gelesen werden."),
      interpretive("kaf-final-darkness", "Schlussform", "Die Schlussform in Choschech schliesst die Finsternis als bedeckte Schwelle."),
    ],
    archetypalMeanings: ["Hand", "Gefaess", "Fassen", "Form"],
    relatedSymbolSlugs: ["verborgenheit", "licht", "wueste"],
    relatedWordIds: ["choschech", "derech", "kavod", "chokma"],
    biblicalReferences: [genesisReference("kaf-genesis-1-2", "Kaf erscheint in Choschech als Schlussform: Finsternis wird als bedeckte Grenze vor dem Licht lesbar.")],
    experienceFields: ["Fassen", "Form", "Aufnahme"],
  },
  {
    id: "lamed",
    glyph: "\u05dc",
    name: "Lamed",
    transcription: "l",
    numericValue: 30,
    alphabetPosition: 12,
    symbolism: [
      interpretive("lamed-learning", "Lernen", "Lamed kann als Bewegung des Lernens und Ausgerichtetwerdens gelesen werden."),
      interpretive("lamed-lift", "Aufrichtung", "Der hohe Buchstabe hebt den Blick aus dem Schriftband."),
    ],
    archetypalMeanings: ["Lernen", "Aufrichtung", "Weisung", "Wachstum", "Empfangen"],
    relatedSymbolSlugs: ["offenbarung", "licht", "brot"],
    relatedWordIds: ["elohim", "al", "lechem", "qol"],
    biblicalReferences: [genesisReference("lamed-genesis-1-1-3", "Lamed steht in Elohim und haelt den Gottesnamen als ausrichtende Gegenwart sichtbar.")],
    experienceFields: ["Wachstum", "Ausrichtung", "Empfangen"],
  },
  {
    id: "mem",
    glyph: "\u05de",
    openForm: "\u05de",
    closedForm: "\u05dd",
    finalForm: "\u05dd",
    name: "Mem",
    transcription: "m",
    numericValue: 40,
    alphabetPosition: 13,
    symbolism: [
      interpretive("mem-water", "Wasser", "Mem ist die Wasserform des Codex: tragend, tief und beweglich."),
      interpretive("mem-depth", "Tiefe", "Offenes und finales Mem halten sichtbare und verborgene Tiefe zusammen."),
      interpretive("mem-womb", "Mutterraum", "Mem kann den umschliessenden Raum des Werdens andeuten."),
    ],
    archetypalMeanings: ["Wasser", "Tiefe", "Mutterraum", "Verborgenheit", "Geburt"],
    relatedSymbolSlugs: ["wasser", "tiefe", "leben", "verborgenheit", "wort"],
    relatedWordIds: ["elohim", "schamajim", "tehom", "majim", "merachefet", "amar", "midbar", "lechem"],
    biblicalReferences: [genesisReference("mem-genesis-1-1-3", "Mem erscheint in Elohim, Schamajim, Tehom, Majim und Amar; es verbindet Tiefe, Wasser und gesprochenes Licht.")],
    experienceFields: ["Unsicherheit", "Tiefe", "Uebergang", "Neugeburt", "Verborgenheit"],
  },
  {
    id: "nun",
    glyph: "\u05e0",
    finalForm: "\u05df",
    name: "Nun",
    transcription: "n",
    numericValue: 50,
    alphabetPosition: 14,
    symbolism: [
      interpretive("nun-seed-life", "Keimendes Leben", "Nun kann als verborgen wachsendes Leben gelesen werden."),
      interpretive("nun-face", "Zuwendung", "In Pnei beruehrt Nun die Oberflaeche, auf der Tiefe und Gegenwart erscheinen."),
    ],
    archetypalMeanings: ["Keim", "Fortgang", "Leben", "Werden"],
    relatedSymbolSlugs: ["wasser", "leben", "offenbarung"],
    relatedWordIds: ["panim", "pnei", "gan", "nahar", "jordan", "manna", "nes"],
    biblicalReferences: [genesisReference("nun-genesis-1-2", "Nun erscheint in Pnei, der Oberflaeche oder dem Angesicht ueber der Tiefe.")],
    experienceFields: ["Leben", "Fortgang", "Wachstum"],
  },
  {
    id: "samech",
    glyph: "\u05e1",
    name: "Samech",
    transcription: "s",
    numericValue: 60,
    alphabetPosition: 15,
    symbolism: [
      interpretive("samech-support", "Stuetzung", "Samech kann als tragender Kreis und Stuetzung gelesen werden."),
    ],
    archetypalMeanings: ["Stuetzung", "Umfassung"],
    relatedSymbolSlugs: ["brot"],
    relatedWordIds: ["nes", "sinai", "seudah"],
    biblicalReferences: [],
    experienceFields: ["Stuetzung"],
  },
  {
    id: "ayin",
    glyph: "\u05e2",
    name: "Ayin",
    transcription: "ʿ",
    numericValue: 70,
    alphabetPosition: 16,
    symbolism: [
      interpretive("ayin-eye", "Auge", "Ayin kann als Auge, Quelle und Wahrnehmung gelesen werden."),
      interpretive("ayin-surface", "Auf der Flaeche", "Ayin markiert das Auf-dem-Angesicht, an dem Tiefe als Oberflaeche wahrnehmbar wird."),
    ],
    archetypalMeanings: ["Auge", "Quelle", "Wahrnehmung", "Oberflaeche"],
    relatedSymbolSlugs: ["licht", "wasser", "offenbarung"],
    relatedWordIds: ["al", "panim"],
    biblicalReferences: [genesisReference("ayin-genesis-1-2", "Ayin erscheint in al, dem Ueber/auf der Tiefe: Wahrnehmung an der Grenze von Tiefe und Oberflaeche.")],
    experienceFields: ["Wahrnehmung", "Quelle", "Blick"],
  },
  {
    id: "pe",
    glyph: "\u05e4",
    finalForm: "\u05e3",
    name: "Pe",
    transcription: "p/f",
    numericValue: 80,
    alphabetPosition: 17,
    symbolism: [
      interpretive("pe-mouth", "Mund", "Pe kann als Mund, Oeffnung und Ort des Sprechens gelesen werden."),
      interpretive("pe-expression", "Ausdruck", "Pe macht Inneres hoerbar oder sichtbar."),
    ],
    archetypalMeanings: ["Mund", "Ausdruck", "Oeffnung", "Sprechen"],
    relatedSymbolSlugs: ["wort", "offenbarung", "wasser"],
    relatedWordIds: ["merachefet", "rachaf", "panim", "pnei"],
    biblicalReferences: [genesisReference("pe-genesis-1-2", "Pe steht in Rachaf/Merachefet und Pnei: Bewegung und Oberflaeche werden zur Schwelle des kommenden Wortes.")],
    experienceFields: ["Sprechen", "Ausdruck", "Oeffnung"],
  },
  {
    id: "tsadi",
    glyph: "\u05e6",
    finalForm: "\u05e5",
    name: "Tsade",
    transcription: "ts",
    numericValue: 90,
    alphabetPosition: 18,
    symbolism: [
      interpretive("tsade-earth", "Aufgerichtete Erde", "Tsade kann als gebeugte und zugleich aufgerichtete Gestalt gelesen werden."),
      interpretive("tsade-final-land", "Schlussform Erde", "In Erez schliesst Tsade die Erde als noch offene, aber genannte Wirklichkeit."),
    ],
    archetypalMeanings: ["Gerechtigkeit", "Aufrichtung", "Erde", "Gestalt"],
    relatedSymbolSlugs: ["erde", "wueste", "brot"],
    relatedWordIds: ["erez"],
    biblicalReferences: [genesisReference("tsade-genesis-1-1-2", "Tsade erscheint in Erez: Erde wird genannt, bevor sie bewohnbar geordnet ist.")],
    experienceFields: ["Aufrichtung", "Gestalt", "Boden"],
  },
  {
    id: "qof",
    glyph: "\u05e7",
    name: "Qof",
    transcription: "q",
    numericValue: 100,
    alphabetPosition: 19,
    symbolism: [
      interpretive("qof-horizon", "Horizont", "Qof kann als Horizont, Grenze und Ruf aus der Ferne gelesen werden."),
    ],
    archetypalMeanings: ["Horizont", "Grenze", "Ruf aus der Ferne"],
    relatedSymbolSlugs: ["wueste", "stimme"],
    relatedWordIds: ["qol", "mikwe", "korban"],
    biblicalReferences: [],
    experienceFields: ["Horizont", "Grenze", "Ruf"],
  },
  {
    id: "resh",
    glyph: "\u05e8",
    name: "Resh",
    transcription: "r",
    numericValue: 200,
    alphabetPosition: 20,
    symbolism: [
      interpretive("resh-head", "Haupt", "Resh kann als Haupt, Anfang und Ausrichtung gelesen werden."),
      interpretive("resh-turn", "Richtung", "Resh gibt der Bewegung eine erkennbare Richtung."),
    ],
    archetypalMeanings: ["Haupt", "Anfang", "Ausrichtung", "Richtung"],
    relatedSymbolSlugs: ["ursprung", "licht", "wasser", "wort"],
    relatedWordIds: ["bereschit", "bara", "erez", "ruach", "merachefet", "rachaf", "amar", "or", "davar", "midbar"],
    biblicalReferences: [genesisReference("resh-genesis-1-1-3", "Resh steht in Bereschit, Bara, Ruach, Amar und Or: Anfang, Atem, Wort und Licht bekommen Richtung.")],
    experienceFields: ["Anfang", "Ausrichtung", "Richtung"],
  },
  {
    id: "shin",
    glyph: "\u05e9",
    name: "Shin",
    transcription: "sch/s",
    numericValue: 300,
    alphabetPosition: 21,
    symbolism: [
      interpretive("shin-fire", "Feuer", "Shin kann als Feuer, göttliche Dynamik und verwandelnde Kraft gelesen werden."),
      interpretive("shin-heaven-darkness", "Spannung", "In Schamajim und Choschech verbindet Shin Weite und bedeckte Sichtbarkeit."),
    ],
    archetypalMeanings: ["Feuer", "Energie", "Verwandlung", "Spannung"],
    relatedSymbolSlugs: ["feuer", "himmel", "licht", "verborgenheit"],
    relatedWordIds: ["bereschit", "schamajim", "choschech", "esch"],
    biblicalReferences: [genesisReference("shin-genesis-1-1-2", "Shin erscheint in Bereschit, Schamajim und Choschech: Anfang, Himmel und Finsternis stehen in Spannung.")],
    experienceFields: ["Energie", "Laeuterung", "Verwandlung"],
  },
  {
    id: "tav",
    glyph: "\u05ea",
    name: "Tav",
    transcription: "t",
    numericValue: 400,
    alphabetPosition: 22,
    symbolism: [
      interpretive("tav-sign", "Zeichen", "Tav kann als Zeichen, Markierung und Vollendung einer Spur gelesen werden."),
      interpretive("tav-boundary", "Grenze", "Tav setzt eine Grenze, an der eine Bewegung lesbar wird."),
    ],
    archetypalMeanings: ["Zeichen", "Abschluss", "Markierung", "Gestalt"],
    relatedSymbolSlugs: ["ordnung", "offenbarung", "ursprung"],
    relatedWordIds: ["bereschit", "et", "tohu", "tehom", "merachefet", "rachaf"],
    biblicalReferences: [genesisReference("tav-genesis-1-1-2", "Tav steht in Bereschit, Et, Tohu und Tehom: Anfang, Zeichen und Tiefe werden markiert.")],
    experienceFields: ["Zeichen", "Gestalt", "Vollendung"],
  },
];
