import type {
  HebrewBiblicalReference,
  HebrewMeaningField,
  HebrewRoot,
  HebrewWord,
} from "@/types/hebrew";

const meaningField = (
  id: string,
  label: string,
  description: string,
  experienceFields: string[],
): HebrewMeaningField => ({
  id,
  label,
  description,
  provenance: "interpretive",
  experienceFields,
});

const reference = (
  id: string,
  biblicalReference: string,
  context: string,
  relation: string,
): HebrewBiblicalReference => ({
  id,
  reference: biblicalReference,
  context,
  relation,
  provenance: "canonical",
});

export const hebrewRoots: HebrewRoot[] = [
  {
    id: "root-or",
    radicals: ["א", "ו", "ר"],
    letterIds: ["aleph", "vav", "resh"],
    rootType: "triliteral",
    coreSemanticField: "Licht, hell werden und erleuchten",
    meaningFields: [],
    relatedRootIds: [],
    sources: [],
  },
  {
    id: "root-l-ch-m",
    radicals: ["ל", "ח", "ם"],
    letterIds: ["lamed", "chet", "mem"],
    rootType: "triliteral",
    coreSemanticField: "Brot und Nahrung",
    meaningFields: [],
    relatedRootIds: [],
    sources: [],
  },
  {
    id: "root-d-b-r",
    radicals: ["ד", "ב", "ר"],
    letterIds: ["dalet", "bet", "resh"],
    rootType: "triliteral",
    coreSemanticField: "Sprechen und Wort",
    meaningFields: [],
    relatedRootIds: [],
    notes: "Die Beziehung zwischen מדבר und דבר wird später philologisch genauer belegt.",
    sources: [],
  },
];

export const hebrewWords: HebrewWord[] = [
  {
    id: "majim",
    slug: "majim",
    hebrew: "מים",
    transliteration: "majim",
    germanMeaning: "Wasser",
    letterIds: ["mem", "jod", "mem"],
    possibleRootIds: [],
    rootNote: "מים wird nicht automatisch als gewöhnliche dreiradikalige Verbalwurzel behandelt.",
    meaningFields: [
      meaningField("majim-depth", "Tiefe", "Wasser kann als sichtbare und verborgene Tiefe gelesen werden.", ["Unsicherheit", "Verborgenheit"]),
      meaningField("majim-transition", "Übergang", "Wasser kann Grenze und Durchgang zugleich sein.", ["Schwelle", "Befreiung"]),
      meaningField("majim-new-birth", "Neugeburt", "Wasser kann Reinigung und neuen Anfang tragen.", ["Erneuerung", "Neuorientierung"]),
    ],
    relatedSymbolSlugs: ["wasser", "meer", "tiefe", "taufe", "leben"],
    biblicalReferences: [
      reference("majim-genesis-1-2", "Genesis 1,2", "Wasser steht am Anfang der Schöpfung.", "Urtiefe und Chaos vor der Ordnung"),
      reference("majim-exodus-14", "Exodus 14", "Das Meer wird zum Durchgang aus der Enge.", "Grenze, Übergang und Befreiung"),
      reference("majim-matthew-3", "Matthäus 3,13-17", "Jesus wird im Jordan getauft.", "Taufe, Übergang und Neugeburt"),
    ],
  },
  {
    id: "or",
    slug: "or",
    hebrew: "אור",
    transliteration: "or",
    germanMeaning: "Licht",
    letterIds: ["aleph", "vav", "resh"],
    possibleRootIds: ["root-or"],
    meaningFields: [
      meaningField("or-light", "Licht", "Licht macht sichtbar und unterscheidbar.", ["Helligkeit", "Klarheit"]),
      meaningField("or-revelation", "Offenbarung", "Licht kann Verborgenes hervortreten lassen.", ["Offenheit", "Erkenntnis"]),
      meaningField("or-awareness", "Erkenntnis", "Licht kann Wahrnehmung und Bewusstsein oeffnen.", ["Bewusstsein", "Klarheit"]),
      meaningField("or-orientation", "Orientierung", "Licht macht eine Spur sichtbar.", ["Klarheit", "Hoffnung"]),
      meaningField("or-presence", "Gegenwart", "Licht kann eine gegenwaertige Wirklichkeit erfahrbar machen.", ["Gegenwart", "Nahe"]),
      meaningField("or-visibility", "Sichtbarkeit", "Licht laesst Konturen und Unterschiede hervortreten.", ["Wahrnehmung", "Unterscheidung"]),
      meaningField("or-life", "Leben", "Licht kann mit Lebendigkeit und tragender Gegenwart verbunden werden.", ["Lebendigkeit", "Hoffnung"]),
    ],
    relatedSymbolSlugs: ["licht"],
    biblicalReferences: [
      reference("or-genesis-1-3", "Genesis 1,3", "Gott spricht: Es werde Licht.", "Schöpfung, Unterscheidung und Orientierung"),
      reference("or-exodus-13-21", "Exodus 13,21", "Die Feuersaeule leuchtet Israel auf dem Weg.", "Orientierung und Fuehrung"),
      reference("or-john-1-4-5", "Johannes 1,4-5", "Das Leben ist das Licht der Menschen.", "Licht, Leben und Gegenwart"),
    ],
  },
  {
    id: "esch",
    slug: "esch",
    hebrew: "אש",
    transliteration: "esch",
    germanMeaning: "Feuer",
    letterIds: ["aleph", "shin"],
    possibleRootIds: [],
    rootNote: "Die lexikalische Einordnung wird in einer späteren Corpus-Phase ergänzt.",
    meaningFields: [
      meaningField("esh-fire", "Feuer", "Feuer kann als verborgene und sichtbare Energie gelesen werden.", ["Potential", "Energie"]),
      meaningField("esh-transformation", "Verwandlung", "Feuer kann Wärme, Läuterung und Veränderung sichtbar machen.", ["Energie", "Läuterung"]),
      meaningField("esh-presence", "Gegenwart", "Feuer kann eine wirksame und tragende Gegenwart sichtbar machen.", ["Nähe", "Offenbarung"]),
      meaningField("esh-purification", "Reinigung", "Feuer kann als Bild von Klärung und Läuterung gelesen werden.", ["Läuterung", "Erneuerung"]),
      meaningField("esh-calling", "Ruf", "Das Feuer des Dornbuschs verbindet Gegenwart mit persönlicher Ansprache.", ["Berufung", "Ausrichtung"]),
    ],
    relatedSymbolSlugs: ["feuer"],
    biblicalReferences: [
      reference("esh-exodus-3", "Exodus 3,2", "Der Dornbusch brennt und verbrennt nicht.", "Gegenwart, Ruf und Verwandlung"),
      reference("esh-exodus-13-21", "Exodus 13,21", "Die Feuersaeule begleitet Israel durch die Nacht.", "Fuehrung, Gegenwart und Weg"),
      reference("esh-malachi-3", "Maleachi 3,2-3", "Das Feuer des Schmelzers laeutert.", "Reinigung und Verwandlung"),
    ],
  },
  {
    id: "lechem",
    slug: "lechem",
    hebrew: "לחם",
    transliteration: "lechem",
    germanMeaning: "Brot",
    letterIds: ["lamed", "chet", "mem"],
    possibleRootIds: ["root-l-ch-m"],
    meaningFields: [
      meaningField("lechem-nourishment", "Nahrung", "Brot steht für alltägliche Versorgung und geteilte Gabe.", ["Versorgung", "Gemeinschaft"]),
      meaningField("lechem-gift", "Gabe", "Brot kann als empfangene Versorgung gelesen werden, die nicht allein aus eigener Verfuegbarkeit kommt.", ["Gabe", "Vertrauen"]),
      meaningField("lechem-community", "Gemeinschaft", "Geteiltes Brot kann Gemeinschaft stiften und Beziehung sichtbar machen.", ["Gemeinschaft", "Teilen"]),
      meaningField("lechem-breaking", "Brechen", "Im Brechen wird Brot zur teilbaren Gabe und zum Zeichen gemeinsamer Nahrung.", ["Teilen", "Gemeinschaft"]),
      meaningField("lechem-life", "Leben", "Brot erhaelt Leben und kann auf eine innere Nahrung verweisen.", ["Leben", "Versorgung"]),
      meaningField("lechem-word", "Wort", "Brot und Wort stehen in einer Spannung von aeusserer und innerer Nahrung.", ["Wort", "Ausrichtung"]),
    ],
    relatedSymbolSlugs: ["brot"],
    biblicalReferences: [
      reference("lechem-exodus-16", "Exodus 16,4", "Brot vom Himmel begleitet Israel durch die Wüste.", "Versorgung im Mangel"),
      reference("lechem-mark-4", "Markus 4,26-29", "Aus dem verborgenen Wachstum des Samens reift Korn.", "Verborgenes Leben und Reifung"),
      reference("lechem-deuteronomy-8", "Deuteronomium 8,3", "Der Mensch lebt nicht vom Brot allein.", "Brot und Wort als Nahrung"),
      reference("lechem-luke-24", "Lukas 24,30-31", "Beim Brechen des Brotes erkennen die Juenger Jesus.", "Teilen, Gemeinschaft und Offenbarung"),
      reference("lechem-john-6", "Johannes 6,35", "Jesus spricht vom Brot des Lebens.", "Christus-Bezug und innere Nahrung"),
    ],
  },
  {
    id: "tehom",
    slug: "tehom",
    hebrew: "\u05ea\u05d4\u05d5\u05dd",
    transliteration: "tehom",
    germanMeaning: "Tiefe",
    gematria: 451,
    category: "word",
    letterIds: ["tav", "he", "vav", "mem"],
    possibleRootIds: [],
    rootNote: "Tehom wird hier als uranfaenglicher Tiefenraum gelesen, nicht als gewoehnliche Verbalwurzel.",
    meaningFields: [
      meaningField("tehom-origin", "Ursprung", "Tehom bezeichnet den verborgenen Ursprung vor Ordnung und Sichtbarkeit.", ["Ursprung", "Anfang"]),
      meaningField("tehom-depth", "Tiefe", "Tehom ist die Tiefe vor der Trennung und vor dem Licht.", ["Tiefe", "Verborgenheit"]),
      meaningField("tehom-hiddenness", "Verborgenheit", "Die Tiefe bewahrt Moeglichkeit, bevor sie offenbar wird.", ["Verborgenheit", "Moeglichkeit"]),
      meaningField("tehom-potential", "Potential", "Tehom traegt ungeformte Moeglichkeit, ohne mit Chaos im modernen Sinn gleichgesetzt zu werden.", ["Potential", "Werden"]),
      meaningField("tehom-water", "Wasser", "Tehom steht im Anfangsraum nahe bei den Wassern, ist aber nicht einfach Wasser.", ["Wasser", "Tiefe"]),
      meaningField("tehom-birth", "Geburt", "Aus der Tiefe kann Gestalt hervortreten.", ["Geburt", "Hervorkommen"]),
      meaningField("tehom-revelation", "Offenbarung", "Aus der Tiefe erhebt sich das Wort und fuehrt zur Offenbarung.", ["Offenbarung", "Sichtbarwerden"]),
    ],
    relatedSymbolSlugs: ["wasser", "tiefe", "licht", "wueste"],
    biblicalReferences: [
      reference("tehom-genesis-1-2", "Genesis 1,2", "Und Finsternis lag auf der Tiefe.", "Die Tiefe erscheint vor Ordnung, Trennung und Licht."),
    ],
  },
  {
    id: "ruach",
    slug: "ruach",
    hebrew: "\u05e8\u05d5\u05d7",
    transliteration: "ruach",
    germanMeaning: "Geist / Wind / Atem",
    gematria: 214,
    category: "word",
    letterIds: ["resh", "vav", "chet"],
    possibleRootIds: [],
    rootNote: "Ruach wird hier als Geist, Wind und Atem gelesen: unsichtbare Bewegung zwischen Ursprung und Offenbarung.",
    meaningFields: [
      meaningField("ruach-spirit", "Geist", "Ruach bezeichnet Geist als unsichtbare, wirksame Gegenwart.", ["Gegenwart", "Unsichtbarkeit"]),
      meaningField("ruach-breath", "Atem", "Ruach verbindet Leben mit Atem und innerer Bewegung.", ["Atem", "Leben"]),
      meaningField("ruach-wind", "Wind", "Ruach bewegt, ohne selbst sichtbar zu sein.", ["Bewegung", "Wirkung"]),
      meaningField("ruach-revelation", "Offenbarung", "Ruach traegt das Wort, bewegt die Stimme und oeffnet zum Licht.", ["Offenbarung", "Stimme"]),
      meaningField("ruach-connection", "Verbindung", "Ruach verbindet Wasser, Tiefe, Wort, Stimme und Licht.", ["Verbindung", "Bruecke"]),
    ],
    relatedSymbolSlugs: ["wasser", "tiefe", "licht", "leben"],
    biblicalReferences: [
      reference("ruach-genesis-1-2", "Genesis 1,2", "Die Ruach Gottes schwebt ueber den Wassern.", "Geist, Wind und Atem ueber der Anfangstiefe"),
    ],
  },
  {
    id: "davar",
    slug: "davar",
    hebrew: "דבר",
    transliteration: "davar",
    germanMeaning: "Wort",
    gematria: 206,
    category: "word",
    letterIds: ["dalet", "bet", "resh"],
    possibleRootIds: ["root-d-b-r"],
    meaningFields: [
      meaningField("davar-revelation", "Offenbarung", "Davar bringt Verborgenes hervor und macht Wirklichkeit lesbar.", ["Offenbarung", "Sichtbarwerden"]),
      meaningField("davar-creation", "Schoepfung", "Davar ruft, ordnet und bringt hervor.", ["Schoepfung", "Hervorbringen"]),
      meaningField("davar-reality", "Wirklichkeit", "Davar ist Wort, Sache, Ereignis und wirksame Wirklichkeit.", ["Wirklichkeit", "Ereignis"]),
      meaningField("davar-language", "Sprache", "Davar ist Sprache als geschehendes Wort, nicht nur Information.", ["Sprache", "Wort"]),
      meaningField("davar-order", "Ordnung", "Davar ordnet den offenen Raum und gibt Richtung.", ["Ordnung", "Ausrichtung"]),
      meaningField("davar-calling", "Ruf", "Davar kann als Ansprache gehoert werden, die in Bewegung setzt.", ["Ruf", "Hoeren"]),
      meaningField("davar-encounter", "Begegnung", "Davar wird hoerbar, wo Mensch und Gegenwart einander begegnen.", ["Begegnung", "Gegenwart"]),
    ],
    relatedSymbolSlugs: ["licht", "wueste", "brot"],
    biblicalReferences: [
      reference("davar-genesis-1-3", "Genesis 1,3", "Gott spricht: Es werde Licht.", "Licht entsteht durch das Wort"),
      reference("davar-deuteronomy-8-3", "Deuteronomium 8,3", "Der Mensch lebt nicht vom Brot allein.", "Der Mensch lebt vom Wort als tieferer Nahrung"),
    ],
  },
  {
    id: "qol",
    slug: "qol",
    hebrew: "קול",
    transliteration: "qol",
    germanMeaning: "Stimme",
    gematria: 136,
    category: "word",
    letterIds: ["qof", "vav", "lamed"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("qol-revelation", "Offenbarung", "Qol macht das Wort als hoerbare Gegenwart erfahrbar.", ["Offenbarung", "Stimme"]),
      meaningField("qol-calling", "Ruf", "Qol ruft aus dem Verborgenen und setzt in Bewegung.", ["Ruf", "Ausrichtung"]),
      meaningField("qol-listening", "Hoeren", "Qol verlangt ein empfangendes Hoeren, bevor Verstehen Gestalt gewinnt.", ["Hoeren", "Empfang"]),
      meaningField("qol-guidance", "Fuehrung", "Qol kann eine Richtung oeffnen, ohne den ganzen Weg sichtbar zu machen.", ["Fuehrung", "Weg"]),
      meaningField("qol-presence", "Gegenwart", "Qol laesst Gegenwart hoerbar werden.", ["Gegenwart", "Naehe"]),
      meaningField("qol-encounter", "Begegnung", "Qol wird zum Ort, an dem Mensch und Ruf einander begegnen.", ["Begegnung", "Antwort"]),
      meaningField("qol-perception", "Wahrnehmung", "Qol schult die Wahrnehmung fuer das, was nicht zuerst sichtbar ist.", ["Wahrnehmung", "Achtsamkeit"]),
    ],
    relatedSymbolSlugs: ["wueste", "licht"],
    biblicalReferences: [],
  },
  {
    id: "midbar",
    slug: "midbar",
    hebrew: "מדבר",
    transliteration: "midbar",
    germanMeaning: "Wüste",
    letterIds: ["mem", "dalet", "bet", "resh"],
    possibleRootIds: ["root-d-b-r"],
    meaningFields: [
      meaningField("midbar-desert", "Wueste", "Midbar bezeichnet die Wueste und kann als Raum der Leere und des Weges gelesen werden.", ["Wueste", "Leere", "Weg"]),
      meaningField("midbar-testing", "Pruefung", "In der Wueste tritt hervor, worauf Vertrauen und Abhaengigkeit gerichtet sind.", ["Pruefung", "Abhaengigkeit", "Vertrauen"]),
      meaningField("midbar-guidance", "Fuehrung", "Die Wueste kann zum Raum werden, in dem Fuehrung als leise Spur sichtbar wird.", ["Fuehrung", "Weg", "Uebergang"]),
      meaningField("midbar-word", "Stimme und Wort", "Midbar kann in behutsamer Naehe zum Bedeutungsfeld von davar gelesen werden, ohne beide Woerter gleichzusetzen.", ["Stimme", "Wort", "Hoeren"]),
      meaningField("midbar-reduction", "Reduktion", "Die Wüste entzieht Gewohntes und macht Mangel erfahrbar.", ["Leere", "Prüfung"]),
      meaningField("midbar-listening", "Hören", "Die Wüste kann als Raum der Sammlung und des Hörens gelesen werden.", ["Stille", "Ausrichtung"]),
    ],
    relatedSymbolSlugs: ["wueste"],
    biblicalReferences: [
      reference("midbar-exodus-16", "Exodus 16", "Israel zieht durch die Wueste und erlebt Mangel und Versorgung.", "Leere, Abhaengigkeit und Fuehrung"),
      reference("midbar-deuteronomy-8", "Deuteronomium 8", "Der Weg durch die Wueste wird als Pruefung und Lernweg erinnert.", "Pruefung, Vertrauen und Uebergang"),
      reference("midbar-matthew-4", "Matthaeus 4,1-11", "Jesus wird in der Wueste versucht.", "Pruefung und Vertrauen"),
      reference("midbar-exodus-3", "Exodus 3,1", "Mose hütet die Herde jenseits der Wüste.", "Stille, Schwelle und Ruf"),
    ],
  },
];
