import type {
  HebrewBiblicalReference,
  HebrewMeaningField,
  HebrewWord,
} from "@/types/hebrew";

const meaningField = (
  id: string,
  label: string,
  description: string,
  experienceFields: string[],
): HebrewMeaningField => ({
  id,
  label,
  description,
  provenance: "interpretive",
  experienceFields,
});

const reference = (
  id: string,
  biblicalReference: string,
  context: string,
  relation: string,
): HebrewBiblicalReference => ({
  id,
  reference: biblicalReference,
  context,
  relation,
  provenance: "canonical",
});

export const phase36AHebrewWords: HebrewWord[] = [
  {
    id: "bara",
    slug: "bara",
    hebrew: "\u05d1\u05e8\u05d0",
    transliteration: "bara",
    germanMeaning: "schaffen",
    meaningThreshold: "Bara markiert den Anfang, in dem Gottes Sprechen Wirklichkeit hervorruft.",
    gematria: 203,
    category: "word",
    letterIds: ["bet", "resh", "aleph"],
    possibleRootIds: [],
    rootNote: "Bara wird als Schöpfungsverb gelesen: Hervorbringen aus Gottes Ursprungshandeln.",
    meaningFields: [
      meaningField("bara-creation", "Schöpfung", "Bara markiert das Hervorrufen einer geordneten Wirklichkeit.", ["Schöpfung", "Anfang"]),
      meaningField("bara-origin", "Ursprung", "Das Wort bindet Anfang an wirksames Sprechen.", ["Ursprung", "Wort"]),
      meaningField("bara-order", "Ordnung", "Im Schaffen entsteht Unterscheidung aus dem Noch-nicht-Geformten.", ["Ordnung", "Klarheit"]),
    ],
    relatedSymbolSlugs: ["licht", "wasser"],
    biblicalReferences: [
      reference("bara-genesis-1-1", "Genesis 1,1", "Am Anfang schafft Gott Himmel und Erde.", "Schöpfung als erster Codex-Akt"),
    ],
  },
  {
    id: "schamajim",
    slug: "schamajim",
    hebrew: "\u05e9\u05de\u05d9\u05dd",
    transliteration: "schamajim",
    germanMeaning: "Himmel",
    meaningThreshold: "Schamajim öffnet die Weite über der Erde und den Raum der geordneten Schöpfung.",
    gematria: 390,
    category: "word",
    letterIds: ["shin", "mem", "jod", "mem"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("schamajim-heaven", "Himmel", "Schamajim öffnet den oberen Raum der Schöpfung.", ["Weite", "Oben"]),
      meaningField("schamajim-separation", "Scheidung", "Der Himmel entsteht im Raum der Trennung der Wasser.", ["Unterscheidung", "Ordnung"]),
      meaningField("schamajim-light", "Lichtträger", "Himmel wird zum Raum von Licht, Zeichen und Orientierung.", ["Licht", "Orientierung"]),
    ],
    relatedSymbolSlugs: ["wasser", "licht"],
    biblicalReferences: [
      reference("schamajim-genesis-1-1", "Genesis 1,1", "Himmel und Erde werden als Schöpfungsraum genannt.", "Kosmische Weite"),
      reference("schamajim-genesis-1-8", "Genesis 1,8", "Die Feste wird Himmel genannt.", "Ordnung durch Scheidung"),
    ],
  },
  {
    id: "erez",
    slug: "erez",
    hebrew: "\u05d0\u05e8\u05e5",
    transliteration: "erez",
    germanMeaning: "Erde · Land",
    meaningThreshold: "Erez ist Boden, Welt und verheissener Ort, auf dem Leben Gestalt gewinnt.",
    gematria: 291,
    category: "word",
    letterIds: ["aleph", "resh", "tsadi"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("erez-earth", "Erde", "Erez ist der tragende Boden der sichtbaren Welt.", ["Boden", "Gestalt"]),
      meaningField("erez-land", "Land", "Erez kann vom Weltboden zum verheißenen Land werden.", ["Ort", "Verheissung"]),
      meaningField("erez-habitation", "Bewohnbarkeit", "Die Erde wird Raum für Leben und Auftrag.", ["Leben", "Verantwortung"]),
    ],
    relatedSymbolSlugs: ["wueste", "brot"],
    biblicalReferences: [
      reference("erez-genesis-1-1", "Genesis 1,1", "Himmel und Erde bilden den ersten Schöpfungsbogen.", "Sichtbarer Raum"),
    ],
  },
  {
    id: "adam",
    slug: "adam",
    hebrew: "\u05d0\u05d3\u05dd",
    transliteration: "adam",
    germanMeaning: "Mensch",
    meaningThreshold: "Adam zeigt den Menschen als geformte Erde, die durch empfangenen Atem lebt.",
    gematria: 45,
    category: "word",
    letterIds: ["aleph", "dalet", "mem"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("adam-human", "Mensch", "Adam bezeichnet den Menschen als lebendige Gestalt vor Gott.", ["Leben", "Beziehung"]),
      meaningField("adam-earth", "Erdnähe", "Adam klingt mit Erde und geformtem Leib.", ["Erde", "Gestalt"]),
      meaningField("adam-breath", "Atem", "Der Mensch wird durch empfangenen Atem lebendig.", ["Atem", "Gegenwart"]),
    ],
    relatedSymbolSlugs: ["wasser", "brot"],
    biblicalReferences: [
      reference("adam-genesis-2-7", "Genesis 2,7", "Der Mensch wird aus Erde geformt und mit Atem belebt.", "Leib und Atem"),
    ],
  },
  {
    id: "chava",
    slug: "chava",
    hebrew: "\u05d7\u05d5\u05d4",
    transliteration: "chava",
    germanMeaning: "Eva · Leben",
    meaningThreshold: "Chava bindet den Namen Eva an Leben, Geburt und kommende Beziehung.",
    gematria: 19,
    category: "word",
    letterIds: ["chet", "vav", "he"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("chava-life", "Leben", "Chava trägt das Motiv der Mutter alles Lebendigen.", ["Leben", "Geburt"]),
      meaningField("chava-relation", "Beziehung", "Chava macht Menschsein als Beziehung sichtbar.", ["Beziehung", "Gegenwart"]),
      meaningField("chava-birth", "Geburt", "Der Name verbindet Anfang mit kommendem Leben.", ["Geburt", "Zukunft"]),
    ],
    relatedSymbolSlugs: ["wasser", "brot"],
    biblicalReferences: [
      reference("chava-genesis-3-20", "Genesis 3,20", "Eva wird Mutter alles Lebendigen genannt.", "Leben und Geburt"),
    ],
  },
  {
    id: "gan",
    slug: "gan",
    hebrew: "\u05d2\u05df",
    transliteration: "gan",
    germanMeaning: "Garten",
    meaningThreshold: "Gan ist geordneter Lebensraum, in dem Fülle, Grenze und Nähe zusammenstehen.",
    gematria: 53,
    category: "word",
    letterIds: ["gimel", "nun"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("gan-garden", "Garten", "Gan ist geordneter Lebensraum und geschützte Fülle.", ["Leben", "Fülle"]),
      meaningField("gan-presence", "Gegenwart", "Der Garten ist Ort der Nähe und des Gehens mit Gott.", ["Gegenwart", "Begegnung"]),
      meaningField("gan-boundary", "Grenze", "Der Garten trägt Fülle und Grenze zugleich.", ["Grenze", "Verantwortung"]),
    ],
    relatedSymbolSlugs: ["wasser", "brot", "licht"],
    biblicalReferences: [
      reference("gan-genesis-2-8", "Genesis 2,8", "Gott pflanzt einen Garten in Eden.", "Lebensraum und Gegenwart"),
    ],
  },
  {
    id: "nahar",
    slug: "nahar",
    hebrew: "\u05e0\u05d4\u05e8",
    transliteration: "nahar",
    germanMeaning: "Strom",
    meaningThreshold: "Nahar zeigt Wasser als Bewegung, Richtung und lebensnahe Versorgung.",
    gematria: 255,
    category: "word",
    letterIds: ["nun", "he", "resh"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("nahar-river", "Fluss", "Nahar zeigt Wasser als Bewegung, Strom und Richtung.", ["Bewegung", "Weg"]),
      meaningField("nahar-life", "Bewässerung", "Der Fluss nähert Garten, Land und Fruchtbarkeit.", ["Leben", "Nahrung"]),
      meaningField("nahar-threshold", "Schwelle", "Ein Fluss kann Grenze und Durchgang zugleich sein.", ["Übergang", "Grenze"]),
    ],
    relatedSymbolSlugs: ["wasser", "brot"],
    biblicalReferences: [
      reference("nahar-genesis-2-10", "Genesis 2,10", "Ein Strom geht von Eden aus, um den Garten zu bewässern.", "Lebensstrom"),
    ],
  },
  {
    id: "mikwe",
    slug: "mikwe",
    hebrew: "\u05de\u05e7\u05d5\u05d4",
    transliteration: "mikwe",
    germanMeaning: "Wasser-Sammlung · Reinigungsbad",
    meaningThreshold: "Mikwe sammelt Wasser zu einem Ort der Ordnung, Reinigung und Rückkehr.",
    gematria: 151,
    category: "word",
    letterIds: ["mem", "qof", "vav", "he"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("mikwe-gathering", "Sammlung", "Mikwe bezeichnet gesammeltes Wasser als geordneten Ort.", ["Sammlung", "Ordnung"]),
      meaningField("mikwe-purification", "Reinigung", "Die Mikwe wird zum Raum ritueller Klärung.", ["Reinigung", "Erneuerung"]),
      meaningField("mikwe-birth", "Neuwerden", "Das Eintauchen kann als Rückkehr in einen Wasserraum des Anfangs gelesen werden.", ["Geburt", "Übergang"]),
    ],
    relatedSymbolSlugs: ["wasser", "taufe"],
    biblicalReferences: [
      reference("mikwe-genesis-1-10", "Genesis 1,10", "Die Sammlung der Wasser wird Meer genannt.", "Wasser wird geordnet gesammelt"),
      reference("mikwe-leviticus-15", "Levitikus 15", "Wasser dient ritueller Reinigung.", "Reinigung und Rückkehr"),
    ],
  },
  {
    id: "jordan",
    slug: "jordan",
    hebrew: "\u05d9\u05e8\u05d3\u05df",
    transliteration: "jarden",
    germanMeaning: "Jordan",
    meaningThreshold: "Jarden ist Fluss, Grenze und Schwelle in neue Verheissung.",
    gematria: 264,
    category: "word",
    letterIds: ["jod", "resh", "dalet", "nun"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("jordan-river", "Jordan", "Der Jordan ist Fluss, Grenze und Durchgang.", ["Wasser", "Grenze"]),
      meaningField("jordan-transition", "Übergang", "Am Jordan wird Landnahme und Neubeginn erzählbar.", ["Übergang", "Verheissung"]),
      meaningField("jordan-baptism", "Taufe", "Der Jordan trägt die christliche Tauferzählung als Schwellenort.", ["Reinigung", "Geburt"]),
    ],
    relatedSymbolSlugs: ["wasser", "taufe"],
    biblicalReferences: [
      reference("jordan-joshua-3", "Josua 3", "Israel geht durch den Jordan ins Land.", "Übergang ins Land"),
      reference("jordan-matthew-3", "Matthaeus 3,13-17", "Jesus wird im Jordan getauft.", "Taufe und Offenbarung"),
    ],
  },
  {
    id: "jam",
    slug: "jam",
    hebrew: "\u05d9\u05dd",
    transliteration: "jam",
    germanMeaning: "Meer",
    meaningThreshold: "Jam steht für Wasserweite, Tiefe und die Grenze, die zum Durchgang werden kann.",
    gematria: 50,
    category: "word",
    letterIds: ["jod", "mem"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("jam-sea", "Meer", "Jam ist Wasserweite, Tiefe und unkontrollierbare Grenze.", ["Tiefe", "Grenze"]),
      meaningField("jam-chaos", "Chaos", "Das Meer kann als ungeordnete Macht vor dem Durchgang erscheinen.", ["Chaos", "Furcht"]),
      meaningField("jam-passage", "Durchgang", "Im Exodus wird das Meer zur Schwelle der Befreiung.", ["Übergang", "Befreiung"]),
    ],
    relatedSymbolSlugs: ["wasser", "meer"],
    biblicalReferences: [
      reference("jam-exodus-14", "Exodus 14", "Das Meer wird für Israel zum Weg.", "Grenze und Befreiung"),
    ],
  },
  {
    id: "panim",
    slug: "panim",
    hebrew: "\u05e4\u05e0\u05d9\u05dd",
    transliteration: "panim",
    germanMeaning: "Angesicht",
    meaningThreshold: "Panim macht Gegenwart persönlich wahrnehmbar, als zugewandtes Angesicht.",
    gematria: 180,
    category: "word",
    letterIds: ["pe", "nun", "jod", "mem"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("panim-face", "Angesicht", "Panim macht Gegenwart als zugewandtes Angesicht lesbar.", ["Gegenwart", "Beziehung"]),
      meaningField("panim-revelation", "Offenbarung", "Im Angesicht wird Verborgenes persönlich sichtbar.", ["Offenbarung", "Nahe"]),
      meaningField("panim-light", "Leuchten", "Das leuchtende Angesicht verbindet Licht mit Segen.", ["Licht", "Segen"]),
    ],
    relatedSymbolSlugs: ["licht"],
    biblicalReferences: [
      reference("panim-numbers-6", "Numeri 6,25", "Der HERR lasse sein Angesicht leuchten.", "Licht und Segen"),
    ],
  },
  {
    id: "kavod",
    slug: "kavod",
    hebrew: "\u05db\u05d1\u05d5\u05d3",
    transliteration: "kavod",
    germanMeaning: "Herrlichkeit · Gewicht",
    meaningThreshold: "Kavod ist nicht nur Glanz, sondern die gewichtige Gegenwart, die Raum einnimmt.",
    gematria: 32,
    category: "word",
    letterIds: ["kaf", "bet", "vav", "dalet"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("kavod-glory", "Herrlichkeit", "Kavod beschreibt sichtbare Würde und gewichtige Gegenwart.", ["Gegenwart", "Würde"]),
      meaningField("kavod-weight", "Gewicht", "Herrlichkeit ist nicht nur Glanz, sondern Schwere der Gegenwart.", ["Gewicht", "Ehrfurcht"]),
      meaningField("kavod-light", "Glanz", "Kavod kann als leuchtende Erscheinung der Gegenwart gelesen werden.", ["Licht", "Offenbarung"]),
    ],
    relatedSymbolSlugs: ["licht", "feuer"],
    biblicalReferences: [
      reference("kavod-exodus-24", "Exodus 24,16-17", "Die Herrlichkeit des HERRN erscheint am Sinai.", "Glanz, Wolke und Feuer"),
    ],
  },
  {
    id: "chokma",
    slug: "chokma",
    hebrew: "\u05d7\u05db\u05de\u05d4",
    transliteration: "chokma",
    germanMeaning: "Weisheit",
    meaningThreshold: "Chokma ist Weisheit, die Einsicht nicht sammelt, sondern Leben formen lässt.",
    gematria: 73,
    category: "word",
    letterIds: ["chet", "kaf", "mem", "he"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("chokma-wisdom", "Weisheit", "Chokma ist geordnete Einsicht, die Leben formen kann.", ["Erkenntnis", "Ordnung"]),
      meaningField("chokma-creation", "Schöpfungsweisheit", "Weisheit steht nahe am geordneten Bau der Welt.", ["Schöpfung", "Licht"]),
      meaningField("chokma-guidance", "Wegwissen", "Weisheit gibt Richtung im konkreten Handeln.", ["Orientierung", "Weg"]),
    ],
    relatedSymbolSlugs: ["licht", "brot"],
    biblicalReferences: [
      reference("chokma-proverbs-8", "Sprüche 8", "Weisheit steht am Anfang der Wege Gottes.", "Schöpfung und Einsicht"),
    ],
  },
  {
    id: "bina",
    slug: "bina",
    hebrew: "\u05d1\u05d9\u05e0\u05d4",
    transliteration: "bina",
    germanMeaning: "Einsicht · Verstehen",
    meaningThreshold: "Bina ist unterscheidendes Verstehen, das Gehörtes zu tragfähiger Gestalt ordnet.",
    gematria: 67,
    category: "word",
    letterIds: ["bet", "jod", "nun", "he"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("bina-understanding", "Verstehen", "Bina ist unterscheidende Einsicht, die Sinn gliedert.", ["Erkenntnis", "Unterscheidung"]),
      meaningField("bina-listening", "Hören", "Verstehen entsteht aus empfangendem Hören.", ["Hören", "Wort"]),
      meaningField("bina-order", "Ordnung", "Bina ordnet Wahrnehmung zu tragfähiger Gestalt.", ["Ordnung", "Klarheit"]),
    ],
    relatedSymbolSlugs: ["licht", "wueste"],
    biblicalReferences: [
      reference("bina-proverbs-2", "Sprüche 2,3-6", "Einsicht und Verstehen werden gesucht und empfangen.", "Weisheit und Erkenntnis"),
    ],
  },
  {
    id: "mizbeach",
    slug: "mizbeach",
    hebrew: "\u05de\u05d6\u05d1\u05d7",
    transliteration: "mizbeach",
    germanMeaning: "Altar",
    meaningThreshold: "Mizbeach ist der Ort, an dem Gabe, Feuer und Nähe sichtbar werden.",
    gematria: 57,
    category: "word",
    letterIds: ["mem", "zayin", "bet", "chet"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("mizbeach-altar", "Altar", "Mizbeach ist Ort der Gabe, Nähe und Hingabe.", ["Gabe", "Gegenwart"]),
      meaningField("mizbeach-fire", "Feuerort", "Der Altar bindet Feuer an Verwandlung und Begegnung.", ["Feuer", "Verwandlung"]),
      meaningField("mizbeach-threshold", "Schwelle", "Am Altar wird das Sichtbare zur dargebrachten Gabe.", ["Schwelle", "Hingabe"]),
    ],
    relatedSymbolSlugs: ["feuer", "brot"],
    biblicalReferences: [
      reference("mizbeach-exodus-27", "Exodus 27,1-8", "Der Altar wird für den Dienst am Heiligtum beschrieben.", "Gabe und Feuer"),
    ],
  },
  {
    id: "korban",
    slug: "korban",
    hebrew: "\u05e7\u05e8\u05d1\u05df",
    transliteration: "korban",
    germanMeaning: "Opfergabe · Darbringung",
    meaningThreshold: "Korban ist Gabe als Herantreten, nicht Verlust, sondern Beziehungsgeste zur Nähe.",
    gematria: 352,
    category: "word",
    letterIds: ["qof", "resh", "bet", "nun"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("korban-offering", "Gabe", "Korban ist Gabe, die Nähe sucht.", ["Gabe", "Nahe"]),
      meaningField("korban-nearness", "Nähe", "Das Wort klingt mit Herantreten und Beziehung.", ["Gegenwart", "Beziehung"]),
      meaningField("korban-transformation", "Verwandlung", "Die Gabe wird im Kult in eine Beziehungsgeste verwandelt.", ["Verwandlung", "Hingabe"]),
    ],
    relatedSymbolSlugs: ["feuer", "brot"],
    biblicalReferences: [
      reference("korban-leviticus-1", "Levitikus 1", "Die Opfergabe wird als Herantreten vor Gott geordnet.", "Gabe und Nähe"),
    ],
  },
  {
    id: "derech",
    slug: "derech",
    hebrew: "\u05d3\u05e8\u05da",
    transliteration: "derech",
    germanMeaning: "Weg",
    meaningThreshold: "Derech ist Richtung, Lebensweg und die Schwelle ins noch nicht Sichtbare.",
    gematria: 224,
    category: "word",
    letterIds: ["dalet", "resh", "kaf"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("derech-way", "Weg", "Derech ist begehbare Richtung und Lebensweg.", ["Weg", "Orientierung"]),
      meaningField("derech-threshold", "Schwelle", "Der Weg beginnt mit einem Durchgang ins Ungewisse.", ["Schwelle", "Vertrauen"]),
      meaningField("derech-testing", "Prüfung", "Auf dem Weg werden Vertrauen und Ausrichtung geformt.", ["Prüfung", "Reifung"]),
    ],
    relatedSymbolSlugs: ["wueste", "licht"],
    biblicalReferences: [
      reference("derech-deuteronomy-8", "Deuteronomium 8,2", "Der ganze Weg durch die Wüste wird erinnert.", "Weg, Prüfung und Vertrauen"),
    ],
  },
  {
    id: "nes",
    slug: "nes",
    hebrew: "\u05e0\u05e1",
    transliteration: "nes",
    germanMeaning: "Zeichen · Banner",
    meaningThreshold: "Nes richtet den Blick auf und sammelt Orientierung im offenen Raum.",
    gematria: 110,
    category: "word",
    letterIds: ["nun", "samech"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("nes-sign", "Zeichen", "Nes ist ein aufgerichtetes Zeichen im offenen Raum.", ["Zeichen", "Orientierung"]),
      meaningField("nes-banner", "Banner", "Das Banner sammelt Blick und Richtung.", ["Sammlung", "Weg"]),
      meaningField("nes-wonder", "Wunderzeichen", "Nes kann ein Ereignis markieren, das Vertrauen weckt.", ["Vertrauen", "Offenbarung"]),
    ],
    relatedSymbolSlugs: ["wueste", "licht"],
    biblicalReferences: [
      reference("nes-exodus-17", "Exodus 17,15", "Mose nennt den Altar: Der HERR ist mein Banner.", "Zeichen im Kampf und auf dem Weg"),
    ],
  },
  {
    id: "sinai",
    slug: "sinai",
    hebrew: "\u05e1\u05d9\u05e0\u05d9",
    transliteration: "sinai",
    germanMeaning: "Sinai",
    meaningThreshold: "Sinai verdichtet Wüste, Feuer, Stimme und Bund zu einem Ort der Offenbarung.",
    gematria: 130,
    category: "word",
    letterIds: ["samech", "jod", "nun", "jod"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("sinai-mountain", "Berg", "Sinai ist Berg der Offenbarung in der Wüste.", ["Offenbarung", "Ort"]),
      meaningField("sinai-covenant", "Bund", "Am Sinai wird Weg zu Bund und Weisung verdichtet.", ["Bund", "Wort"]),
      meaningField("sinai-fire", "Feuer", "Sinai verbindet Wolke, Feuer, Stimme und Furcht.", ["Feuer", "Stimme"]),
    ],
    relatedSymbolSlugs: ["wueste", "feuer", "licht"],
    biblicalReferences: [
      reference("sinai-exodus-19", "Exodus 19", "Israel steht am Sinai vor Stimme, Wolke und Feuer.", "Offenbarung in der Wüste"),
    ],
  },
  {
    id: "manna",
    slug: "manna",
    hebrew: "\u05de\u05df",
    transliteration: "man",
    germanMeaning: "Manna",
    meaningThreshold: "Man bleibt die Gabe im Mangel, die täglich empfangen und neu verstanden werden muss.",
    gematria: 90,
    category: "word",
    letterIds: ["mem", "nun"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("manna-gift", "Gabe", "Manna ist tägliche Gabe im Mangel.", ["Gabe", "Vertrauen"]),
      meaningField("manna-nourishment", "Nahrung", "Manna nähert den Weg, ohne Vorratssicherheit zu geben.", ["Nahrung", "Abhängigkeit"]),
      meaningField("manna-question", "Frage", "Manna bleibt als Was-ist-das eine Gabe, die Deutung verlangt.", ["Frage", "Hören"]),
    ],
    relatedSymbolSlugs: ["brot", "wueste"],
    biblicalReferences: [
      reference("manna-exodus-16", "Exodus 16", "Manna erscheint in der Wüste als tägliche Versorgung.", "Brot als Gabe"),
    ],
  },
  {
    id: "dagan",
    slug: "dagan",
    hebrew: "\u05d3\u05d2\u05df",
    transliteration: "dagan",
    germanMeaning: "Korn",
    meaningThreshold: "Dagan trägt Leben als verborgenes Potential, das zu Nahrung heranreift.",
    gematria: 57,
    category: "word",
    letterIds: ["dalet", "gimel", "nun"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("dagan-grain", "Korn", "Dagan ist Korn als verdichtetes Lebenspotential.", ["Nahrung", "Leben"]),
      meaningField("dagan-growth", "Wachstum", "Im Korn bleibt Leben verborgen, bis es aufgeht.", ["Verborgenheit", "Wachstum"]),
      meaningField("dagan-gift", "Erntegabe", "Korn verbindet Erde, Regen, Licht und menschliches Empfangen.", ["Gabe", "Ernte"]),
    ],
    relatedSymbolSlugs: ["brot", "wasser", "licht"],
    biblicalReferences: [
      reference("dagan-deuteronomy-8", "Deuteronomium 8,8", "Das gute Land wird mit Weizen und Gerste beschrieben.", "Korn und Versorgung"),
    ],
  },
  {
    id: "shever",
    slug: "shever",
    hebrew: "\u05e9\u05d1\u05e8",
    transliteration: "shever",
    germanMeaning: "Bruch · Getreidekauf",
    meaningThreshold: "Shever hält Bruch und Versorgung zusammen, wo Mangel nach Nahrung sucht.",
    gematria: 502,
    category: "word",
    letterIds: ["shin", "bet", "resh"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("shever-breaking", "Bruch", "Shever trägt Bruch und Brechen als Schwelle.", ["Brechen", "Schwelle"]),
      meaningField("shever-grain", "Getreide", "In Genesis wird Shever mit Nahrungssuche im Hunger verbunden.", ["Nahrung", "Mangel"]),
      meaningField("shever-restoration", "Wendung", "Der Bruch kann zum Ort von Versorgung und Versöhnung werden.", ["Verwandlung", "Gemeinschaft"]),
    ],
    relatedSymbolSlugs: ["brot"],
    biblicalReferences: [
      reference("shever-genesis-42", "Genesis 42", "Josefs Brüder ziehen nach Aegypten, um Getreide zu kaufen.", "Mangel, Nahrung und Versöhnung"),
    ],
  },
  {
    id: "seudah",
    slug: "seudah",
    hebrew: "\u05e1\u05e2\u05d5\u05d3\u05d4",
    transliteration: "seudah",
    germanMeaning: "Mahl",
    meaningThreshold: "Seudah macht Nahrung als geteilte Stärkung und geordnete Begegnung sichtbar.",
    gematria: 145,
    category: "word",
    letterIds: ["samech", "ayin", "vav", "dalet", "he"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("seudah-meal", "Mahl", "Seudah ist gemeinsames Essen als geordnete Begegnung.", ["Gemeinschaft", "Nahrung"]),
      meaningField("seudah-support", "Stärkung", "Das Mahl stärkt den Weg und die Beziehung.", ["Stärkung", "Weg"]),
      meaningField("seudah-table", "Tischgemeinschaft", "Am Mahl wird Gabe teilbar und sichtbar.", ["Teilen", "Gabe"]),
    ],
    relatedSymbolSlugs: ["brot"],
    biblicalReferences: [
      reference("seudah-genesis-18", "Genesis 18,1-8", "Abraham bereitet den Gästen ein Mahl.", "Gastfreundschaft und Gegenwart"),
    ],
  },
  {
    id: "noach",
    slug: "noach",
    hebrew: "\u05e0\u05d7",
    transliteration: "noach",
    germanMeaning: "Noah · Ruhe",
    meaningThreshold: "Noach klingt nach Ruhe, Bewahrung und Neubeginn nach den Wassern.",
    gematria: 58,
    category: "word",
    letterIds: ["nun", "chet"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("noach-rest", "Ruhe", "Noach klingt mit Ruhe nach Gericht und Wasser.", ["Ruhe", "Neuanfang"]),
      meaningField("noach-water", "Flut", "Noah steht im Wasserbogen von Gericht, Bewahrung und Neubeginn.", ["Wasser", "Übergang"]),
      meaningField("noach-covenant", "Bund", "Nach der Flut wird Bewahrung in Bund und Zeichen verdichtet.", ["Bund", "Zeichen"]),
    ],
    relatedSymbolSlugs: ["wasser", "licht"],
    biblicalReferences: [
      reference("noach-genesis-6-9", "Genesis 6-9", "Noah wird durch die Wasser der Flut bewahrt.", "Wasser, Bewahrung und Bund"),
    ],
  },
  {
    id: "tahor",
    slug: "tahor",
    hebrew: "\u05d8\u05d4\u05d5\u05e8",
    transliteration: "tahor",
    germanMeaning: "rein",
    meaningThreshold: "Tahor beschreibt geklärte Ordnung, die Rückkehr in Nähe und Gemeinschaft öffnet.",
    gematria: 220,
    category: "word",
    letterIds: ["tet", "he", "vav", "resh"],
    possibleRootIds: [],
    meaningFields: [
      meaningField("tahor-clean", "Reinheit", "Tahor beschreibt geklärte, kultisch geordnete Reinheit.", ["Reinigung", "Ordnung"]),
      meaningField("tahor-return", "Rückkehr", "Reinheit öffnet Rückkehr in Gemeinschaft und Nähe.", ["Gemeinschaft", "Nahe"]),
      meaningField("tahor-light", "Klarheit", "Reinheit kann als lichte Klarheit des Geordneten gelesen werden.", ["Klarheit", "Licht"]),
    ],
    relatedSymbolSlugs: ["wasser", "feuer", "licht"],
    biblicalReferences: [
      reference("tahor-leviticus-11", "Levitikus 11", "Rein und unrein ordnen kultische Nähe.", "Klärung und Ordnung"),
    ],
  },
];
