import type { HebrewSymbolMapping } from "@/types/hebrew";

export const symbolHebrewMappings: HebrewSymbolMapping[] = [
  {
    id: "symbol-wasser-majim",
    symbolSlug: "wasser",
    hebrewWordIds: [
      "majim",
      "tehom",
      "ruach",
      "merachefet",
      "schamajim",
      "nahar",
      "mikwe",
      "jordan",
      "jam",
      "noach",
      "tahor",
      "gan",
      "adam",
      "chava",
      "bara",
    ],
    primaryHebrewWordId: "majim",
  },
  {
    id: "symbol-licht-or",
    symbolSlug: "licht",
    hebrewWordIds: [
      "or",
      "bereschit",
      "elohim",
      "amar",
      "haja",
      "wajehi",
      "choschech",
      "panim",
      "kavod",
      "chokma",
      "bina",
      "schamajim",
      "bara",
      "ruach",
      "noach",
      "tahor",
    ],
    primaryHebrewWordId: "or",
  },
  {
    id: "symbol-feuer-esh",
    symbolSlug: "feuer",
    hebrewWordIds: [
      "esch",
      "mizbeach",
      "korban",
      "ruach",
      "kavod",
      "sinai",
      "tahor",
    ],
    primaryHebrewWordId: "esch",
  },
  {
    id: "symbol-brot-lechem",
    symbolSlug: "brot",
    hebrewWordIds: [
      "lechem",
      "manna",
      "dagan",
      "shever",
      "seudah",
      "erez",
      "gan",
      "nahar",
      "mizbeach",
      "korban",
      "chokma",
    ],
    primaryHebrewWordId: "lechem",
  },
  {
    id: "symbol-wueste-midbar",
    symbolSlug: "wueste",
    hebrewWordIds: [
      "midbar",
      "tohu",
      "vohu",
      "derech",
      "nes",
      "manna",
      "sinai",
      "erez",
      "bina",
      "qol",
      "davar",
      "jordan",
    ],
    primaryHebrewWordId: "midbar",
  },
];
