import type { MeaningNodeId } from "@/types/meaningGraph";
import type { CodexEntry, CodexRelation } from "./types";

type CompletionSeed = {
  title: string;
  summary: string;
  fields: MeaningNodeId[];
  anchor: [string, string];
  room?: string;
  related: [string, string];
  type?: CodexEntry["type"];
  aliases?: string[];
};

const seeds: Record<string, CompletionSeed> = {
  grenze: { title: "Grenze", summary: "Die Grenze unterscheidet, schützt und trennt. In der Schrift ist sie nicht nur Ende, sondern oft der Ort, an dem ein Übergang möglich wird: Wasser scheidet Räume, das Meer versperrt den Weg und öffnet ihn zugleich. Eine gute Grenze gibt Gestalt, ohne Beziehung unmöglich zu machen.", fields: ["order", "transition", "guidance"], anchor: ["genesis-1-6", "Genesis 1,6: Die Wasser werden geschieden und eine geordnete Welt wird möglich."], room: "wasser", related: ["uebergang", "Der Übergang zeigt, wie eine Grenze zur Schwelle werden kann."] },
  hunger: { title: "Hunger", summary: "Hunger macht Abhängigkeit leiblich spürbar. Er ist weder romantisch noch bloß ein Defizit, sondern die offene Stelle, an der sichtbar wird, wovon Leben zehrt. In der Wüste führt Hunger zur Frage nach dem täglichen Brot und nach dem Wort, das dem Empfangenen Richtung gibt.", fields: ["lack", "dependence", "nourishment"], anchor: ["deuteronomy-8-3", "Deuteronomium 8,3: Hunger, Manna und Wort öffnen gemeinsam die Frage nach dem Leben."], room: "brot", related: ["manna", "Manna antwortet auf Hunger als tägliche, nicht verfügbare Gabe."] },
  spiegel: { title: "Spiegel", summary: "Der Spiegel erzeugt kein eigenes Licht; er empfängt und gibt zurück. Darin wird er zum Bild der Erkenntnis: Sichtbarkeit kehrt zum Sehenden zurück und zeigt auch dessen Standort. Ein Spiegel kann klären, aber nicht festhalten — das Bild bleibt Beziehung zwischen Licht, Fläche und Blick.", fields: ["awareness", "knowledge", "light"], anchor: ["1-corinthians-13-12", "1 Korinther 13,12: Das gegenwärtige Erkennen bleibt wie ein Sehen im Spiegel."], room: "licht", related: ["glanz", "Glanz ist die sichtbare Spur des empfangenen und zurückgegebenen Lichts."] },
  vertrauen: { title: "Vertrauen", summary: "Vertrauen ist keine Sicherheit über den ganzen Weg, sondern die Bereitschaft, dem empfangenen nächsten Schritt zu folgen. In der Wüste gewinnt es Gestalt, weil Vorräte, Übersicht und gewohnte Ordnung fehlen. Vertrauen hält sich nicht am Ungewissen fest, sondern an einer Gabe, Stimme oder Führung, die für heute reicht.", fields: ["trust", "guidance", "path"], anchor: ["exodus-16-4", "Exodus 16,4: Das tägliche Manna lehrt Vertrauen ohne gehorteten Vorrat."], room: "wueste", related: ["weg", "Vertrauen macht einen Weg begehbar, bevor sein Ende sichtbar ist."] },
  altar: { title: "Altar", summary: "Der Altar ist der Ort, an dem Gabe und Nähe eine sichtbare Gestalt erhalten. Nicht Zerstörung steht im Mittelpunkt, sondern die Bewegung, in der etwas aus bloßem Besitz gelöst und vor Gott gebracht wird. So wird der Altar zur Schwelle: Das Endliche bleibt endlich und kann dennoch Träger einer Begegnung sein.", fields: ["gift", "presence", "transformation"], anchor: ["genesis-8-20", "Genesis 8,20: Noach antwortet auf die Bewahrung mit einer Gabe."], room: "feuer", related: ["feuer", "Die Gabe tritt ins Feuer und wird zur sichtbaren Antwort."] },
  auge: { title: "Auge", summary: "Das Auge steht für mehr als optisches Sehen. In der Schrift wird Wahrnehmung zur inneren Fähigkeit, eine gegebene Wirklichkeit zu erkennen und sie als gut, gefährdet oder wegweisend zu unterscheiden. Ein geöffnetes Auge sammelt Licht; doch erst Aufmerksamkeit macht aus Sichtbarkeit Erkenntnis.", fields: ["awareness", "knowledge", "light"], anchor: ["genesis-1-4", "Genesis 1,4: Gott sieht das Licht und erkennt es als gut."], room: "licht", related: ["raah", "Raah gibt dem Sehen seinen hebräischen Wortkörper."] },
  baum: { title: "Baum", summary: "Der Baum verbindet verborgene Tiefe und sichtbare Frucht. Seine Wurzeln empfangen, was dem Blick entzogen ist; Stamm, Zweige und Frucht tragen dieses Empfangen in die Welt. Darum kann der Baum zum Bild eines Lebens werden, das nicht aus sich selbst besteht, sondern an Quelle, Zeit und Gabe gebunden bleibt.", fields: ["life", "hiddenness", "nourishment"], anchor: ["genesis-2-9", "Genesis 2,9: Bäume erscheinen als schön, nahrhaft und mitten im Garten bedeutungsvoll."], room: "wasser", related: ["quelle", "Die Quelle nährt, was der Baum in Gestalt und Frucht verwandelt."] },
  "brennender-dornbusch": { title: "Brennender Dornbusch", summary: "Der brennende Dornbusch ist die Szene einer Nähe, die entzündet, ohne zu vernichten. Mose sieht das Gewöhnliche in einer unmöglichen Dauer brennen und wendet sich ihm zu. Erst in dieser Wendung wird das Feuer zum Ruf: Gegenwart unterbricht den gewohnten Weg und gibt ihm eine neue Richtung.", fields: ["fire", "presence", "calling"], anchor: ["exodus-3-2", "Exodus 3,2: Der Dornbusch brennt und wird nicht verzehrt."], room: "feuer", related: ["dornbusch", "Im unscheinbaren Dornbusch wird die tragende Gegenwart sichtbar."] },
  "brot-vom-himmel": { title: "Brot vom Himmel", summary: "Brot vom Himmel bezeichnet Versorgung, die nicht aus Vorrat und Kontrolle hervorgeht. Das Manna liegt am Morgen bereit und reicht für den Tag; wer es festhalten will, verliert seinen Sinn. Die Gabe lehrt darum ein Maß des Empfangens: Leben wird getragen, ohne vollständig verfügbar zu werden.", fields: ["gift", "nourishment", "trust"], anchor: ["exodus-16-4", "Exodus 16,4: Brot fällt vom Himmel und wird zum täglichen Maß."], room: "brot", related: ["manna", "Manna ist die konkrete Gestalt dieser unverfügbaren Tagesgabe."] },
  "deuteronomy-8": { title: "Deuteronomium 8", summary: "Deuteronomium 8 liest die Wüstenzeit rückblickend als Schule des Erinnerns. Hunger, Manna und Weg werden nicht verklärt; sie legen offen, wovon Leben tatsächlich getragen wird. Erinnerung bewahrt davor, die empfangene Gabe später für eigenen Besitz und eigene Kraft zu halten.", fields: ["desert", "testing", "trust", "word"], anchor: ["deuteronomy-8-3", "Deuteronomium 8,3: Hunger und Manna öffnen die Frage, wovon der Mensch lebt."], room: "wueste", related: ["manna", "Manna verbindet den erlittenen Mangel mit einer täglich empfangenen Gabe."], type: "scripture", aliases: ["Deuteronomium 8", "deuteronomium-8"] },
  "deuteronomy-8-2": { title: "Deuteronomium 8,2", summary: "Die Erinnerung an den ganzen Wüstenweg hält auch Umwege, Demütigung und Prüfung fest. Der Weg zeigt, was im Herzen Raum gewinnt, wenn vertraute Sicherheiten fehlen. Die Stelle macht Prüfung nicht zum Selbstzweck, sondern zum Offenbarwerden einer inneren Ausrichtung.", fields: ["path", "testing", "hiddenness"], anchor: ["deuteronomy-8-2", "Deuteronomium 8,2: Der zurückgelegte Weg soll erinnert werden."], room: "wueste", related: ["pruefung", "Prüfung bringt ans Licht, worauf Vertrauen sich wirklich richtet."], type: "scripture", aliases: ["Deuteronomium 8,2", "deuteronomium-8-2"] },
  "deuteronomy-8-3": { title: "Deuteronomium 8,3", summary: "Hunger und Manna führen zu einer Einsicht, die äußere Nahrung nicht abwertet, sondern vertieft: Der Mensch lebt nicht von Brot allein. Das gesprochene Wort ist ebenfalls Nahrung, weil es Richtung, Maß und Beziehung schenkt. Brot und Wort stehen deshalb nicht gegeneinander; das Sichtbare trägt eine unsichtbare Versorgung.", fields: ["lack", "nourishment", "word", "life"], anchor: ["deuteronomy-8-3", "Deuteronomium 8,3: Brot und Wort werden als zwei Seiten empfangenen Lebens lesbar."], room: "brot", related: ["wort", "Das Wort nährt, indem es dem empfangenen Leben Richtung gibt."], type: "scripture", aliases: ["Deuteronomium 8,3", "deuteronomium-8-3"] },
  dornbusch: { title: "Dornbusch", summary: "Der Dornbusch ist klein, widerspenstig und ohne den Glanz eines heiligen Gegenstands. Gerade er wird zum Träger des Feuers. Die Szene bewahrt damit eine einfache Wahrheit: Gegenwart ist nicht an Größe gebunden; sie kann im Übersehenen aufleuchten und den Menschen zum Innehalten und Hören rufen.", fields: ["hiddenness", "presence", "calling"], anchor: ["exodus-3-2", "Exodus 3,2: Ein gewöhnlicher Dornbusch wird zum Ort der Anrede."], room: "feuer", related: ["esch", "Esch macht im Dornbusch Nähe sichtbar, ohne ihn zu verzehren."] },
  erkenntnis: { title: "Erkenntnis", summary: "Erkenntnis ist in der Schrift kein bloßes Ansammeln von Wissen. Sie entsteht, wo Sehen, Unterscheiden und Beziehung zusammenfinden. Das Erkannte betrifft den Erkennenden: Licht wird zur inneren Orientierung, und eine sichtbare Ordnung verlangt eine Antwort im eigenen Weg.", fields: ["knowledge", "awareness", "order"], anchor: ["genesis-1-4", "Genesis 1,4: Das Licht wird gesehen und als gut unterschieden."], room: "licht", related: ["tov", "Tov benennt die erkannte Stimmigkeit des Geschaffenen."] },
  exodus: { title: "Exodus", summary: "Exodus ist die Bewegung aus der Enge in einen offenen, noch ungesicherten Weg. Befreiung endet nicht am Ausgang: Wasser, Wüste, Wort und Brot formen erst die Fähigkeit, Freiheit zu tragen. Die äußere Geschichte öffnet so einen inneren Weg, auf dem alte Bindung endet und Vertrauen Gestalt gewinnt.", fields: ["transition", "path", "trust"], anchor: ["exodus-14", "Exodus 14: Das Meer wird von der Grenze zum Durchgang."], related: ["uebergang", "Der Übergang löst aus der Enge und öffnet einen noch zu gehenden Weg."], type: "scripture" },
  "exodus-16": { title: "Exodus 16", summary: "Exodus 16 erzählt Hunger nicht als Nebensache, sondern als Wahrheitsmoment des Weges. In der Wüste erscheint Manna als tägliche Gabe, die weder Besitzdenken noch Vorratssicherheit bestätigt. Das Volk lernt ein neues Maß: empfangen, sammeln, ruhen und darauf vertrauen, dass auch morgen gegeben wird.", fields: ["lack", "gift", "nourishment", "trust"], anchor: ["exodus-16-4", "Exodus 16,4: Das tägliche Brot prüft und trägt zugleich."], room: "brot", related: ["manna", "Manna ist Nahrung und Lernweg des täglichen Empfangens."], type: "scripture" },
  "exodus-16-4": { title: "Exodus 16,4", summary: "Der angekündigte Regen von Brot verbindet Versorgung und Prüfung. Jeder sammelt ein Tagesmaß; die Gabe lässt sich empfangen, aber nicht in dauernde Verfügbarkeit verwandeln. Darin liegt ihre Tiefe: Was Leben trägt, kommt nahe genug für heute und entzieht sich doch dem Anspruch, es endgültig zu besitzen.", fields: ["gift", "testing", "trust"], anchor: ["exodus-16-4", "Exodus 16,4: Brot vom Himmel wird im Maß eines Tages gegeben."], room: "brot", related: ["gabe", "Die Gabe bleibt Geschenk, weil sie sich nicht in Besitz auflösen lässt."], type: "scripture" },
  "exodus-3": { title: "Exodus 3", summary: "Exodus 3 führt Mose aus dem gewohnten Weiden an eine Schwelle der Gegenwart. Feuer, Dornbusch, Name und Ruf treten zusammen: Gott sieht die Bedrängnis, hört das Schreien und sendet einen Menschen. Offenbarung bleibt deshalb nicht Schau; sie verwandelt Wahrnehmung in Verantwortung und Weg.", fields: ["presence", "calling", "revelation", "path"], anchor: ["exodus-3-2", "Exodus 3,2: Feuer im Dornbusch unterbricht den gewöhnlichen Weg."], room: "feuer", related: ["ruf", "Aus der wahrgenommenen Gegenwart wächst ein persönlicher Ruf."], type: "scripture" },
  "exodus-3-2": { title: "Exodus 3,2", summary: "Ein Engel erscheint in einer Feuerflamme mitten aus dem Dornbusch, doch der Busch wird nicht verzehrt. Die Szene hält Nähe und Grenze zusammen: Das Feuer ist wirklich, aber nicht zerstörerisch. Mose muss sich zuwenden; im aufmerksamen Sehen öffnet sich aus dem Zeichen eine Stimme.", fields: ["fire", "presence", "awareness"], anchor: ["exodus-3-2", "Exodus 3,2: Brennen ohne Verzehren wird zum Zeichen heiliger Gegenwart."], room: "feuer", related: ["stimme", "Aus dem gesehenen Zeichen wird eine hörbare Anrede."], type: "scripture" },
  felsen: { title: "Felsen", summary: "Der Felsen trägt Festigkeit, Grenze und Widerstand. In der Wüste wird gerade aus dem Harten Wasser gegeben; das scheinbar Verschlossene wird zum Ort unerwarteter Versorgung. Der Felsen erinnert daran, dass tragender Grund nicht immer weich erscheint und dass eine Quelle auch dort verborgen sein kann, wo nichts nach Leben aussieht.", fields: ["hiddenness", "life", "gift"], anchor: ["exodus-17-6", "Exodus 17,6: Aus dem Felsen tritt Wasser für das durstige Volk."], room: "wasser", related: ["quelle", "Im Felsen bleibt die Quelle verborgen, bis sie als Gabe hervortritt."] },
  flamme: { title: "Flamme", summary: "Die Flamme ist die sichtbare Bewegung des Feuers. Sie steigt auf, verändert sich in jedem Augenblick und bleibt doch an eine verborgene Glut gebunden. Als Zeichen spricht sie von Gegenwart, die nicht festgehalten werden kann: Sie leuchtet, wärmt und ruft zur Aufmerksamkeit, ohne sich in einer starren Form zu erschöpfen.", fields: ["fire", "presence", "revelation"], anchor: ["exodus-3-2", "Exodus 3,2: Die Flamme macht Gegenwart im Dornbusch sichtbar."], room: "feuer", related: ["glut", "Die Glut bewahrt, was in der Flamme sichtbar aufsteigt."] },
  gabe: { title: "Gabe", summary: "Eine Gabe ist mehr als ein Gegenstand, der den Besitzer wechselt. Sie stiftet Beziehung, weil in ihr Herkunft, Empfang und mögliche Weitergabe zusammenkommen. Im Manna wird diese Ordnung besonders klar: Was gegeben ist, trägt heute; wer es als Besitz sichern will, verfehlt sein Maß.", fields: ["gift", "nourishment", "community"], anchor: ["exodus-16-4", "Exodus 16,4: Das tägliche Brot wird empfangen, nicht hergestellt."], room: "brot", related: ["teilen", "Empfangene Gabe findet ihre Fortsetzung im Teilen."] },
  "gabe-im-mangel": { title: "Gabe im Mangel", summary: "Gabe im Mangel bezeichnet die biblische Bewegung, in der Versorgung nicht vor, sondern mitten in der Bedürftigkeit erscheint. Der Mangel wird dadurch nicht gutgeheißen; er verliert aber sein letztes Wort. Wo nichts verfügbar scheint, kann das Empfangene als Gabe erkannt werden und Vertrauen für den nächsten Schritt wecken.", fields: ["lack", "gift", "trust"], anchor: ["exodus-16-4", "Exodus 16,4: In der Wüste wird Hunger zum Ort täglicher Versorgung."], room: "brot", related: ["manna", "Manna trägt die Gabe nicht als Vorrat, sondern als tägliches Genug."] },
  gegenwart: { title: "Gegenwart", summary: "Gegenwart ist die Nähe, die einen Augenblick von innen her verändert. Sie muss nicht laut sein: Feuer, Stimme, Licht oder Brot können zu ihren Trägern werden. Der Mensch erkennt Gegenwart daran, dass das Gewöhnliche Tiefe gewinnt und aus Wahrnehmung eine Antwort, ein Halt oder ein neuer Weg entsteht.", fields: ["presence", "awareness", "calling"], anchor: ["exodus-3-2", "Exodus 3,2: Gegenwart zeigt sich im Feuer, das nicht verzehrt."], room: "feuer", related: ["offenbarung", "Offenbarung lässt verborgene Gegenwart lesbar hervortreten."] },
  glanz: { title: "Glanz", summary: "Glanz ist Licht, das an einer Gestalt zurückkehrt. Er ist nicht die Quelle selbst, sondern deren sichtbare Spur auf einer Fläche, einem Gesicht oder einem Weg. Darum bewahrt der Glanz eine heilsame Unterscheidung: Was leuchtet, empfängt Licht und verweist zugleich über sich hinaus.", fields: ["light", "revelation", "awareness"], anchor: ["exodus-34-29", "Exodus 34,29: Moses Gesicht trägt den Glanz einer empfangenen Begegnung."], room: "licht", related: ["spiegel", "Der Spiegel zeigt, wie empfangenes Licht als Glanz zurückkehrt."] },
  glut: { title: "Glut", summary: "Glut ist verborgenes Feuer: weniger sichtbar als die Flamme und doch voller gespeicherter Kraft. Sie steht für eine Gegenwart, die nicht erloschen ist, auch wenn das Leuchten klein geworden scheint. Ein Atemzug kann sie neu öffnen; so wird Glut zum Bild bewahrter Berufung und stiller Wandlung.", fields: ["fire", "hiddenness", "transformation"], anchor: ["isaiah-6-6", "Jesaja 6,6: Eine glühende Kohle berührt den Mund und öffnet einen Ruf."], room: "feuer", related: ["ruf", "Aus der Berührung mit der Glut wächst Bereitschaft zur Antwort."] },
  laeuterung: { title: "Läuterung", summary: "Läuterung ist die Bewegung, in der Feuer nicht vernichtet, sondern freilegt. Fremdes und Tragendes werden unterscheidbar; eine Gestalt verliert Schlacke und gewinnt Klarheit. Im inneren Weg bedeutet dies keine makellose Selbstherstellung, sondern das Aushalten einer Wahrheit, die reinigt und neu ausrichtet.", fields: ["purification", "fire", "transformation"], anchor: ["malachi-3-2-3", "Maleachi 3,2–3: Das Feuer des Schmelzers dient der Reinigung."], room: "feuer", related: ["reinigung", "Reinigung antwortet im Wasser auf dieselbe Bewegung der Klärung."] },
  leben: { title: "Leben", summary: "Leben ist in der Schrift empfangene Bewegung: Atem, Wasser, Licht und Nahrung wirken zusammen, ohne dass eines allein das Geheimnis erklärt. Lebendig ist, was Beziehung aufnehmen, wachsen und Frucht tragen kann. Darum bleibt Leben Gabe und Aufgabe zugleich — gegenwärtig, verletzlich und auf eine Quelle angewiesen.", fields: ["life", "breath", "nourishment"], anchor: ["genesis-2-7", "Genesis 2,7: Atem macht den geformten Menschen zu einem lebendigen Wesen."], related: ["ruach", "Ruach trägt Leben als Atem und unsichtbare Bewegung."] },
  leere: { title: "Leere", summary: "Leere ist nicht einfach Nichts. In der Wüste bezeichnet sie den entblößten Raum, in dem gewohnte Stimmen, Vorräte und Auswege verstummen. Gerade dadurch kann Leere hörfähig machen: Was sonst übertönt wird, tritt hervor, und eine neue Richtung kann empfangen werden.", fields: ["desert", "hiddenness", "voice"], anchor: ["deuteronomy-8-2", "Deuteronomium 8,2: Der lange Weg nimmt Sicherheiten und legt das Herz offen."], room: "wueste", related: ["stimme", "In der entleerten Weite kann eine leise Stimme unterscheidbar werden."] },
  "manna-in-der-wueste": { title: "Manna in der Wüste", summary: "Manna in der Wüste hält zwei Erfahrungen untrennbar zusammen: wirklichen Hunger und wirkliche Gabe. Die Nahrung erscheint klein, täglich und fragwürdig — ‚Was ist das?‘ bleibt in ihrem Namen hörbar. So wird Versorgung nicht selbstverständlich, sondern jeden Morgen neu als Geheimnis des Empfangens erkannt.", fields: ["desert", "lack", "gift", "nourishment"], anchor: ["exodus-16", "Exodus 16: In der Wüste liegt am Morgen das unbekannte Brot bereit."], room: "brot", related: ["midbar", "Midbar ist der entleerte Raum, in dem die Gabe neu erkannt wird."] },
  meer: { title: "Meer", summary: "Das Meer ist Wasser in seiner großen, unüberschaubaren Gestalt. Es kann Grenze, Tiefe und Bedrohung sein; im Exodus wird gerade diese Grenze zum geöffneten Weg. Das Meer verliert dabei nicht seine Macht, doch es wird in eine Ordnung gestellt, durch die Befreiung hindurchgehen kann.", fields: ["depth", "transition", "path"], anchor: ["exodus-14", "Exodus 14: Das Meer wird geteilt und aus der Grenze entsteht ein Durchgang."], room: "wasser", related: ["uebergang", "Im Übergang wird die Wassergrenze zur begehbaren Schwelle."] },
  nahrung: { title: "Nahrung", summary: "Nahrung ist das, was von außen empfangen und im Inneren zu Kraft verwandelt wird. Sie erinnert den Menschen daran, dass Leben nicht selbstgenügsam ist. Brot verdichtet diese Beziehung: Erde, Arbeit, Zeit und Gabe kommen zusammen und werden zu einem Maß, das den heutigen Weg trägt.", fields: ["nourishment", "life", "gift"], anchor: ["deuteronomy-8-3", "Deuteronomium 8,3: Nahrung wird über Brot hinaus als empfangenes Wort verstanden."], room: "brot", related: ["lechem", "Lechem gibt der alltäglichen Nahrung ihren hebräischen Wortkörper."] },
  "offenbarung-im-feuer": { title: "Offenbarung im Feuer", summary: "Offenbarung im Feuer ist Sichtbarwerden ohne vollständige Verfügbarkeit. Das Feuer zeigt Gegenwart, wahrt aber zugleich ihre Grenze; Mose kann sich nähern und muss doch die Heiligkeit des Ortes achten. Erkenntnis entsteht hier als Beziehung von Anziehung, Ehrfurcht, Hören und Antwort.", fields: ["revelation", "fire", "presence"], anchor: ["exodus-3-2", "Exodus 3,2: Die Flamme öffnet eine Gegenwart, die sich nicht verbraucht."], room: "feuer", related: ["brennender-dornbusch", "Der brennende Dornbusch ist die tragende Szene dieser Bewegung."] },
  pruefung: { title: "Prüfung", summary: "Prüfung ist der Augenblick, in dem eine verborgene Ausrichtung sichtbar wird. Die Wüste erzeugt nicht erst Mangel, Angst oder Vertrauen; sie legt offen, was den Menschen trägt, wenn Vorräte und vertraute Wege fehlen. Prüfung zielt darum auf Wahrheit und Reifung, nicht auf willkürliche Härte.", fields: ["testing", "hiddenness", "trust"], anchor: ["deuteronomy-8-2", "Deuteronomium 8,2: Der Wüstenweg legt offen, was im Herzen ist."], room: "wueste", related: ["vertrauen", "Vertrauen gewinnt in der Prüfung eine konkrete Gestalt."] },
  quelle: { title: "Quelle", summary: "Die Quelle ist Wasser im Augenblick seines Hervortretens. Was verborgen unter der Erde lag, wird zur Gabe, die fließt und Leben ermöglicht. Darum verbindet die Quelle Ursprung und Gegenwart: Sie verweist in die unsichtbare Tiefe und ist zugleich ganz für den Ort da, an dem Durst gestillt wird.", fields: ["origin", "hiddenness", "life"], anchor: ["genesis-2-10", "Genesis 2,10: Ein Strom geht von Eden aus und bewässert den Garten."], room: "wasser", related: ["wasser", "Wasser wird in der Quelle als hervortretendes Leben erfahrbar."] },
  ruf: { title: "Ruf", summary: "Der Ruf ist eine Stimme, die den Menschen nicht nur informiert, sondern meint. Er unterbricht den gewohnten Weg, nennt eine Wirklichkeit und öffnet Verantwortung. Im Dornbusch wird sichtbar, dass Berufung aus wahrgenommener Not und göttlicher Gegenwart zugleich hervorgeht.", fields: ["calling", "voice", "path"], anchor: ["exodus-3-4", "Exodus 3,4: Mose wird mit seinem Namen gerufen und antwortet."], room: "feuer", related: ["stimme", "Die Stimme macht den Ruf persönlich und hörbar."] },
  saettigung: { title: "Sättigung", summary: "Sättigung ist mehr als das Ende körperlichen Hungers. Sie bezeichnet ein empfangenes Genug, in dem Begehren für einen Augenblick zur Ruhe kommt. Die Schrift verbindet dieses Genug mit Maß und Dankbarkeit: Wer empfängt, erkennt die Gabe und wird frei, sie nicht grenzenlos festhalten zu müssen.", fields: ["nourishment", "gift", "life"], anchor: ["exodus-16-18", "Exodus 16,18: Wer viel oder wenig sammelt, hat das benötigte Maß."], room: "brot", related: ["teilen", "Aus dem erfahrenen Genug kann Raum für das Teilen entstehen."] },
  speise: { title: "Speise", summary: "Speise ist Nahrung, die bereitet und empfangen wird. In ihr wird das Natürliche zur menschlichen Beziehung: Korn wird Brot, Gabe wird Mahl, Einzelnes wird geteilt. Deshalb kann Speise äußeres Leben tragen und zugleich auf das Wort verweisen, das Sinn, Richtung und Gemeinschaft nährt.", fields: ["nourishment", "community", "word"], anchor: ["deuteronomy-8-3", "Deuteronomium 8,3: Der Mensch lebt von Brot und von dem Wort, das ihn erreicht."], room: "brot", related: ["wort", "Das Wort vertieft Speise zur Nahrung des inneren Weges."] },
  stimme: { title: "Stimme", summary: "Die Stimme ist Atem, der Richtung und Beziehung gewinnt. Sie bleibt unsichtbar und wird doch gehört; gerade darin verbindet sie Ruach und Wort. In der Wüste kann Stimme hervortreten, weil andere Sicherheiten leiser werden. Wer hört, empfängt nicht nur Klang, sondern eine mögliche Antwort.", fields: ["voice", "breath", "word"], anchor: ["exodus-3-4", "Exodus 3,4: Aus dem Feuer wird Mose beim Namen gerufen."], room: "wueste", related: ["qol", "Qol ist der hebräische Klangkörper der hörbaren Stimme."] },
  taufe: { title: "Taufe", summary: "Taufe führt durch Wasser in eine neue Zuordnung. Das Wasser ist Reinigung, Grenze und Grab des bisherigen Weges, zugleich aber Anfang und Geburt. Am Jordan treten Wasser, Ruach und Stimme zusammen: Der Übergang wird nicht nur vollzogen, sondern als Beziehung und Sendung hörbar.", fields: ["purification", "transition", "birth"], anchor: ["matthew-3-13-17", "Matthäus 3,13–17: Wasser, Geist und Stimme öffnen einen neuen Anfang."], room: "wasser", related: ["ruach", "Ruach verbindet den Wasserübergang mit Atem, Gegenwart und Sendung."] },
  teilen: { title: "Teilen", summary: "Teilen ist die Bewegung, in der eine Gabe ihre Beziehungskraft entfaltet. Brot wird gebrochen, ohne seinen Sinn zu verlieren; gerade im Geben wird sichtbar, dass Nahrung nicht nur den Einzelnen erhalten soll. Teilen verwandelt Besitz in Gemeinschaft und empfangenes Leben in eine offene Hand.", fields: ["breaking", "community", "gift"], anchor: ["luke-24-30-31", "Lukas 24,30–31: Im Brechen des Brotes werden die Augen geöffnet."], room: "brot", related: ["gabe", "Die Gabe kommt im Teilen zu ihrer gemeinschaftlichen Gestalt."] },
  weg: { title: "Weg", summary: "Der Weg ist eine Richtung, die erst im Gehen lesbar wird. Er verbindet Ausgang, Schwelle und Ziel, ohne den Zwischenraum abzukürzen. In Exodus und Wüste ist der Weg nicht bloße Strecke: Er formt Erinnerung, Vertrauen und die Fähigkeit, Führung für den heutigen Schritt zu empfangen.", fields: ["path", "guidance", "transition"], anchor: ["deuteronomy-8-2", "Deuteronomium 8,2: Der ganze zurückgelegte Weg soll erinnert werden."], room: "wueste", related: ["vertrauen", "Vertrauen macht den noch nicht überschaubaren Weg begehbar."] },
};

function completionEntry(id: string, seed: CompletionSeed): CodexEntry {
  const relations: CodexRelation[] = [
    { targetId: seed.related[0], type: "related", label: seed.related[1], source: "meaning-graph" },
    { targetId: seed.room ?? "leben", type: "shares-meaning", label: seed.room ? `Dieses Wort öffnet sich im Raum ${seed.room === "wueste" ? "Wüste" : seed.room[0].toUpperCase() + seed.room.slice(1)} weiter.` : "Dieses Wort führt in die lebendige Ordnung der Schrift.", source: "symbol-network" },
  ];
  return {
    id,
    type: seed.type ?? "meaning",
    title: seed.title,
    subtitle: seed.type === "scripture" ? "Schriftanker" : "Bedeutungsraum",
    hebrew: null,
    transliteration: null,
    aliases: [seed.title, ...(seed.aliases ?? [])],
    searchTerms: seed.fields,
    summary: seed.summary,
    meaningFields: seed.fields,
    relations,
    scriptureAnchors: [{ id: seed.anchor[0], reference: seed.anchor[1].split(":", 1)[0], label: seed.anchor[1].split(":", 1)[0], note: seed.anchor[1], source: "scripture-reference" }],
    symbolRoomSlug: seed.room ?? null,
    journeyIds: [],
    meta: { status: "stable", source: ["meaning-graph", "scripture-reference"], sourceIds: [id, seed.anchor[0]], tags: seed.fields },
  };
}

export const symbolNetCompletionEntries = Object.entries(seeds).map(([id, seed]) => completionEntry(id, seed));
